-- Mod-authored victory and defeat screen descriptions, es_ES overlay.
-- Baseline in CivVAccess_VictoryDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_MISSING"] = "No hay descripción para esta pantalla."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_CULTURAL"] =
    "Desde una cima herbosa a la sombra de un árbol oscuro, dos figuras se sientan en silueta y contemplan una ciudad dorada. Bajo ellas, una multitud cruza un puente de piedra de arcos flanqueado por estatuas clásicas sobre pedestales, con una sala abovedada que se alza detrás. Más allá de una franja de parque, el perfil urbano se eleva en esbeltas torres futuristas que se disuelven en una bruma ámbar. La gente puntea los céspedes: unos niños corren bajo una cometa que vuela alta en su hilo, una figura pasea bajo una sombrilla amarilla, y velas blancas asoman sobre aguas lejanas a través de la neblina. Toda la escena está impregnada de una cálida luz dorada, mitad atardecer y mitad sueño, con pájaros dispersos por el cielo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DIPLOMATIC"] =
    "Una ceremonia en un césped verde ante la alta losa blanca de la sede de las Naciones Unidas. En el primer plano, una multitud se halla de espaldas a ti, vestida con trajes, túnicas y pañuelos en la cabeza de muchas naciones, mientras un operador de televisión filma desde un trípode a la derecha. Mástiles rodean el césped portando docenas de banderas nacionales, reconocibles entre ellas las de los Estados Unidos y México. En el centro, un gran globo de piedra reposa sobre un pedestal cuadrado bajo árboles frondosos, con sus continentes en relieve. Ante él aguarda una hilera de niños con los trajes populares de distintos países; una mujer de azul se inclina para entregar algo a una niña pequeña con un vestido amarillo que se estira hacia arriba para alcanzarlo. Macizos de flores rojas y blancas bordean un estanque inmóvil al pie del encuadre, y una suave luz diurna gris lo iguala todo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DOMINATION"] =
    "Un desfile de la victoria pintado en colores de cartel, todo oro, oliva y rojo. En el primer plano derecho, un joven oficial con uniforme de gala blanco y galón dorado en el hombro empuña el asta de una enorme bandera roja que ondea desplegada por el cielo, con la gorra de plato ceñida de rojo y una insignia dorada. Tras él, filas de soldados con uniformes blancos a juego se mantienen firmes con los fusiles de bayoneta calada erguidos al hombro, y más banderas rojas se elevan de la columna. Sobre el desfile, una estatua de bronce de un comandante a lomos de un caballo al paso se alza en lo alto de un alto pedestal, con un gran capitolio abovedado detrás. Finos estandartes rojos fluyen en cintas por un resplandeciente cielo amarillo verdoso, con oscuros cipreses y montañas brumosas cerrando la lejanía."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_SPACE_RACE"] =
    "El espacio profundo, mirando hacia arriba a una vasta estación orbital desde abajo. Su oscuro casco se extiende por la parte superior del encuadre, con hileras de altas ventanas de luz cálida y bahías de resplandor verde a lo largo de su parte inferior. Jirones de vapor se desplazan por el metal. Planos paneles solares cuadriculados se extienden del casco sobre brazos reticulados, y una larga torre de armadura revestida de paneles cae desde su extremo opuesto por el costado derecho del encuadre. Abajo, el lado nocturno de un planeta se aleja en violeta y vino intensos, con su horizonte arqueándose por la parte inferior de la escena. El sol acaba de despuntar sobre ese horizonte en un destello blanco dorado que ilumina franjas de nubes rosa y crema a lo largo de la curva. En el primer plano, una solitaria nave alada cruza la oscuridad sobre una larga estela luminosa de color azul verdoso, y naves más pequeñas brillan en verde y naranja a lo lejos contra las estrellas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_TIME"] =
    "La propia ilustración de portada del juego ampliada para llenar la pantalla. Un globo terráqueo compuesto de antiguos mapas sepia domina el encuadre, con el título Sid Meier's Civilization atravesándolo en letras de metal pulido en relieve enhebradas en un gigantesco número romano cinco de latón. Un gastado sello postal finlandés está pegado en la parte superior izquierda, con un jinete sobre un caballo enjaezado que conmemora la epopeya del Kalevala. Tenues matasellos aparecen entintados a su alrededor. Tras el globo se extiende un collage de papel teñido de azul verdoso, un anillo meridiano de latón se arquea en torno al borde inferior del globo, y la luz cae desde la parte superior izquierda como sobre una curiosidad bajo una lámpara."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_DEFEAT"] =
    "Un imperio muerto bajo un cielo del desierto. La colosal cabeza de piedra de una estatua yace sobre la mejilla en la arena, con los ojos cerrados y el rostro sereno, mientras una mano de piedra rota emerge del suelo cerca de ella, con los dedos curvados hacia el cielo. Una excavación la rodea: zanjas abiertas en la tierra del primer plano, una línea de vallado de postes y alambre, y una solitaria figura con ropas pálidas de pie sobre una plataforma de escalera de madera, empequeñecida por el rostro que estudia. Un animal de carga aguarda a la izquierda. El valle vacío retrocede más allá de fragmentos erguidos dispersos hasta mesetas de cima plana en el horizonte. Todo es tostado y herrumbre bajo un fino cielo azul, las solitarias y llanas arenas del Ozymandias de Shelley extendiéndose en la lejanía."
