-- Mod-authored great work descriptions, es_ES overlay.
-- Baseline in CivVAccess_GreatWorkDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_MISSING"] = "No hay descripción de la pintura para esta gran obra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIRL_WITH_PEARL_EARRING"] =
    "Pintura al óleo del Siglo de Oro neerlandés, uno de los retratos más queridos del arte occidental. Una joven se vuelve por encima del hombro para encontrar tu mirada desde un fondo oscuro y liso, con los labios apenas entreabiertos como si fuera a hablar. Viste un turbante azul y dorado cuya tela le cae por la espalda, y una única perla grande en forma de lágrima atrapa la luz en su oreja."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HENRY_VIII"] =
    "Retrato de corte Tudor al óleo, la imagen que fijó cómo el mundo imagina a Enrique VIII. El rey está de pie de cuerpo entero frente a ti, los pies bien plantados y separados, de hombros anchos y figura corpulenta, con una mano apoyada en una daga a la cintura. Viste un jubón de plata con joyas bajo un abrigo carmesí forrado de piel, un sombrero plano con pluma y cadenas de oro, de pie sobre una alfombra de motivos entre columnas de mármol."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HUNTERS_IN_THE_SNOW"] =
    "Pintura al óleo del Renacimiento flamenco, un paisaje invernal visto desde lo alto de una colina. Tres cazadores agotados y su jauría de perros avanzan con esfuerzo por la nieve profunda en primer plano, cabizbajos, con un solo zorro como único fruto de la cacería. Más abajo, una aldea se extiende bajo un cielo gris verdoso, con diminutos patinadores jugando sobre estanques helados y picos dentados que se alzan en la distancia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LES_DEMOISELLES"] =
    "Pintura al óleo del primer modernismo, el lienzo que dio origen al cubismo. Cinco mujeres desnudas están de pie y sentadas en un espacio poco profundo de planos dentados rosas, blancos y azules, con los cuerpos descompuestos en formas angulosas y afiladas. Los dos rostros de la derecha están pintados como máscaras africanas, rayados y distorsionados, mientras que los demás miran de frente con grandes ojos almendrados; un pequeño frutero reposa en el borde inferior."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LUNCHEON"] =
    "Pintura al óleo del impresionismo francés de unos amigos que se demoran tras una comida. Un grupo animado en ropa de verano llena un balcón a la orilla del río bajo un toldo a rayas naranjas y blancas, conversando, coqueteando y apoyándose en la baranda; una joven en primer plano juega con un perrito. La mesa está cubierta de botellas de vino, copas y fruta, todo pintado en cálidas y sueltas pinceladas de color soleado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MONA_LISA"] =
    "Óleo sobre tabla de madera del Renacimiento italiano, probablemente el retrato más famoso del mundo. Una mujer está sentada con las manos cruzadas, vuelta ligeramente hacia ti contra un brumoso paisaje de ríos sinuosos y montañas azules lejanas. Sus ojos encuentran los tuyos directamente, la célebre mirada que parece seguirte allá donde te sitúes. Su tenue media sonrisa es el centro de la pintura, ejecutada en suaves tonos marrones y verdes sin contornos marcados, de modo que su expresión parece cambiar cuanto más la observas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUNDAY_AFTERNOON"] =
    "Pintura al óleo puntillista, construida por completo a partir de diminutos puntos de color puro. Los parisinos, con sus mejores galas dominicales, descansan en una soleada pradera a la orilla del río, paseando con sombrillas, tendidos sobre la hierba y sacando perritos, con veleros en el agua a su espalda. Todos están extrañamente quietos y solemnes, como figuras de un friso, y la luz se descompone en un titileo de motas verdes, naranjas y violetas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VIEW_OF_TOLEDO"] =
    "Pintura al óleo del Renacimiento español, uno de los primeros paisajes puros del arte occidental y uno insólitamente sombrío. La ciudad española de Toledo, sobre su cerro, se alza en la distancia bajo un cielo de tormenta violenta, con sus torres y murallas grises iluminadas por una inquietante luz plateada. Verdes colinas descienden hacia un río en primer plano, y toda la escena está pintada en verdes profundos y negros azulados que parecen más propios de un sueño que de la luz del día."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WATER_LILIES"] =
    "Pintura al óleo del impresionismo francés, de la famosa serie de Monet sobre el estanque de su jardín en Giverny. Todo el lienzo es la superficie del agua, sin horizonte ni orilla: balsas de verdes hojas de nenúfar se deslizan por un agua azul y lavanda salpicada de flores rosas y rojas. Las nubes y los árboles aparecen solo como suaves reflejos, con la pincelada lo bastante suelta como para que todo parezca flotar."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_STARRY_NIGHT"] =
    "Pintura al óleo postimpresionista, una de las imágenes más reconocidas del arte moderno. Un cielo nocturno henchido de movimiento llena la mayor parte del lienzo: las estrellas arden dentro de halos arremolinados, y la luna arde de naranja en la esquina mientras una gran corriente en espiral rueda por el centro del cielo. Abajo, una aldea tranquila con el campanario puntiagudo de una iglesia duerme entre colinas, y un oscuro ciprés se eleva en llamas por el borde izquierdo, todo en gruesas pinceladas visibles de azul y oro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BIRTH_OF_VENUS"] =
    "Pintura del Renacimiento italiano de la diosa del amor llegando del mar, una de las imágenes más famosas del mito clásico. Venus está de pie, desnuda, sobre una concha de vieira gigante, cubriéndose con las manos y con una larga melena de cabello dorado. A la izquierda, dos dioses alados del viento la empujan hacia la orilla a través de una lluvia de rosas rosadas, mientras que a la derecha una mujer con un vestido floreado se apresura a envolverla en un manto ondeante."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BINDO_ALTOVITI"] =
    "Retrato al óleo del Alto Renacimiento italiano de un joven y acaudalado banquero romano. Un apuesto joven de largo cabello dorado y gorra negra te mira por encima de su hombro desnudo, con una mano llevada al pecho. Viste un manto azul sobre una prenda negra, y su rostro pálido resplandece contra un fondo verde profundo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_DRAGON"] =
    "Pintura del primer Renacimiento italiano con el encanto rígido y de cuento de hadas de una fábula. A la derecha, un caballero con armadura sobre un caballo blanco encabritado hunde su lanza en las fauces abiertas de un dragón verde alado con manchadas alas de polilla. A la izquierda, una princesa serena con un largo vestido rosa sujeta a la bestia herida con una correa como a una mascota, ante su oscura cueva, mientras una extraña tormenta en espiral se reúne detrás del caballero."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CREATION_OF_ADAM"] =
    "Fresco del Renacimiento italiano de la bóveda de la Capilla Sixtina, origen de uno de los gestos más famosos del arte. Un Adán desnudo está recostado sobre una verde ladera a la izquierda, con un brazo extendido lánguidamente, mientras Dios, una figura de barba gris envuelta en un sudario ondeante de color rosa lleno de ángeles, irrumpe desde la derecha. Sus dedos índices extendidos se acercan uno al otro a través de un pequeño hueco, el instante anterior a la chispa de la vida."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GALLERY_OF_THE_LOUVRE"] =
    "Pintura al óleo estadounidense de una galería del interior del Louvre, obra del mismo Morse que más tarde inventaría el código del telégrafo. Un gran salón de paredes rojas está cubierto del suelo al techo con docenas de cuadros de viejos maestros en marcos dorados, entre ellos una diminuta Mona Lisa. En primer plano, unos estudiantes de arte están sentados copiando ante sus caballetes mientras su maestro se inclina sobre el hombro de una joven para corregir su trabajo, y un corredor abovedado de más galerías se abre en la distancia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WASHINGTON_CROSSING"] =
    "Heroica pintura de historia estadounidense al óleo, icono de la Guerra de Independencia. El general Washington va erguido en la proa de un bote de remos atestado mientras sus soldados impulsan y reman a través de un río obstruido por placas de hielo, y un oficial tras él sostiene en alto la bandera estadounidense. La luz del amanecer rompe entre la fría bruma, y más botes cargados de hombres y caballos siguen detrás."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ARRANGEMENT_IN_GREY"] =
    "Pintura al óleo estadounidense universalmente conocida como la madre de Whistler. Una anciana con un largo vestido negro y cofia de encaje blanco está sentada de estricto perfil, vuelta hacia la izquierda, las manos juntas en el regazo y los pies sobre un pequeño escabel. La habitación es austera y plana: una pared gris, una oscura cortina con dibujo y un único cuadro enmarcado, y toda la composición queda equilibrada como un estudio en gris y negro, exactamente como dice el título."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BREEZING_UP"] =
    "Pintura al óleo realista estadounidense sobre la navegación en botes pequeños frente a la costa de Nueva Inglaterra. Un hombre y tres muchachos se inclinan hacia atrás en un pequeño bote cangrejo llamado Gloucester mientras este escora con la brisa fuerte, la espuma rompiendo en la proa y la pesca del día amontonada a sus pies. El mar es de un verde picado bajo nubes rotas, con una goleta de dos palos en el horizonte."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_THOUSAND_LI"] =
    "Rollo de mano de paisaje chino en azul y verde, pintado sobre seda por un prodigio adolescente de la corte Song y de casi doce metros de largo. Montañas de vívido azul y verde mineral se alzan en cordillera tras cordillera desde un río dorado y sereno, con diminutas aldeas, puentes y árboles desnudos encajados entre las laderas. Columnas de caligrafía pincelada y rojos sellos de coleccionistas llenan el cielo sobre las cumbres."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DWELLING_IN_THE_FUCHUN"] =
    "Rollo de mano chino a tinta, obra maestra de la pintura de paisaje de los letrados de la dinastía Yuan, ejecutada por completo en tonos de tinta negra sobre papel. Montañas redondeadas construidas con pinceladas secas superpuestas se alzan sobre un río ancho y sereno, con pinos, cabañas dispersas y barcas de pesca a lo largo de las orillas. El ambiente es pausado y contemplativo, y el papel está salpicado de rojos sellos de coleccionistas acumulados a lo largo de siglos de admiradores."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ALONG_THE_RIVER"] =
    "Rollo de mano chino de la dinastía Song sobre seda, famoso panorama de la vida cotidiana de la ciudad de más de cinco metros de largo. La sección mostrada se centra en la gran puerta de la capital, una torre de madera maciza en lo alto de una rampa inclinada, con las calles de abajo rebosantes de vida: puestos de mercado, carros de bueyes, una caravana de camellos que cruza la puerta y mozos que cargan fardos en palos al hombro. Cada figura es diminuta pero está dibujada con precisión en fina línea de tinta y apagados tonos terrosos."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LEAF_2"] =
    "Hoja de álbum chino de la dinastía Qing, pintura de corte en fina línea y delicado color. Elegantes damas con largos ropajes flotantes de blanco, verde y azul se reúnen en un pabellón de jardín engalanado con tela de un azul vivo, y una de ellas quema incienso ante una mesa tras una baranda roja. A su alrededor hay rocas de jardín, bambú y una enredadera florida que trepa por el tejado del pabellón."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EMPEROR_TAIZONG"] =
    "Rollo de mano chino de la dinastía Tang sobre seda, registro cortesano de un encuentro diplomático. A la derecha, el emperador Taizong va sentado en una plataforma portada por damas de palacio que sostienen además dos grandes abanicos y un palio rojo sobre él. A la izquierda, tres figuras más pequeñas se acercan en actitud respetuosa: un ujier de la corte de rojo, el embajador del Tíbet con un ropaje estampado y un intérprete de blanco, todos contra una seda dorada y cálida cubierta de sellos rojos."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SPRING_MORNING"] =
    "Rollo de mano chino de la dinastía Ming sobre seda, largo panorama de las mujeres de palacio en su ocio una mañana de primavera. Docenas de elegantes damas llenan salas abiertas, galerías y patios: tocan música, pintan un retrato, juegan con niños y pasean entre sauces, rocas de jardín e incluso pavos reales. La arquitectura del palacio recorre todo el largo del rollo en cálidos rojos y verdes, y cada biombo, baranda y ropaje está plasmado con meticuloso detalle de fina línea."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_GREAT_WAVE"] =
    "Grabado japonés en madera del estilo ukiyo-e, la imagen más famosa de todo el arte japonés. Una enorme ola de azul profundo se encabrita a la izquierda y se enrosca sobre toda la escena, con la cresta rompiendo en dedos de espuma blanca semejantes a garras. Debajo, tres largos botes abiertos llenos de remeros cabalgan los senos de las olas, y a lo lejos, pequeño en el centro de todo, se alza el cono nevado del monte Fuji."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EVENING_SHOWER"] =
    "Grabado japonés en madera del estilo ukiyo-e, una de las escenas de lluvia más admiradas jamás creadas. Un aguacero repentino, dibujado como cortinas de finas líneas oblicuas, sorprende a la gente a mitad de un largo puente de madera; se apresuran en ambas direcciones bajo sombreros y paraguas, y una persona se cobija bajo una estera de paja. El río de abajo es una franja de color verde azulado con un solitario balsero que la cruza con su pértiga, y la orilla lejana se desvanece en un borrón oscuro bajo la tormenta."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_L_ABSINTHE"] =
    "Pintura impresionista francesa al óleo, escena despiadada de la vida de los cafés parisinos. Una mujer con vestido y sombrero pálidos está sentada desplomada ante una mesa de café de mármol, la mirada baja, un vaso de ajenjo de un verde lechoso ante ella; a su lado, un hombre barbudo con un abrigo arrugado mira a lo lejos hacia la derecha con una pipa en la boca. Los dos están juntos y sin embargo completamente apartados, pintados en grises y marrones apagados que cargan el cuadro de su aire de soledad."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_UPAUPA_SCHNEKLUD"] =
    "Retrato postimpresionista al óleo de un violonchelista en plena interpretación. El músico se inclina sobre su violonchelo de un naranja rojizo intenso, los ojos bajos en concentración, el brazo del arco recorriendo las cuerdas, y su traje azul oscuro enmarca el resplandor del instrumento. Detrás de él, el fondo se divide en zonas planas de marrón y verde musgo salpicadas de pálidas formas abstractas, en el estilo cromático audaz y simplificado de Gauguin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_BAR_AT_THE_FOLIES"] =
    "Pintura al óleo francesa de la vida moderna, la última gran obra de Manet. Una camarera con un corpiño de terciopelo negro y una flor en el pecho está de pie tras un mostrador de mármol abarrotado de botellas de champán, un cuenco de naranjas y un vaso con una rosa, mirando hacia fuera con una expresión cansada y ausente. Detrás de ella un enorme espejo refleja el resplandeciente salón de música, con sus arañas y su gentío, y, curiosamente desplazada hacia la derecha, su propia espalda mientras se inclina hacia un hombre con sombrero de copa."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BALL_AT_THE_MOULIN"] =
    "Pintura al óleo postimpresionista de la vida nocturna parisina en el famoso cabaret. Un grupo de hombres con sombrero de copa y mujeres con sombreros de plumas están sentados alrededor de una mesa con bebidas, mientras una mujer pelirroja se arregla el cabello en el salón de baile iluminado de verde a sus espaldas. El rostro de una mujer se asoma en el borde derecho, iluminado de un verde espectral desde abajo, y una larga baranda diagonal corta el primer plano al estilo de cartel de Lautrec."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS"] =
    "Pintura al óleo modernista vienesa recubierta de pan de oro auténtico, la obra más famosa de Klimt. Una pareja se arrodilla fundida en un abrazo sobre un prado florido, el hombre inclinándose para besar la mejilla de la mujer mientras ella alza el rostro con los ojos cerrados. Sus cuerpos se funden en un único manto dorado, estampado de rectángulos para él y de círculos brillantes para ella, resplandeciente contra un fondo plano de oro tornasolado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AMERICAN_GOTHIC"] =
    "Pintura al óleo del regionalismo estadounidense, parodiada sin fin y reconocible al instante. Un granjero severo y calvo, con gafas redondas y un peto vaquero, está de pie sosteniendo una horca de tres púas en vertical, con una mujer con un vestido delantal de estampado oscuro a su lado que mira a un lado con desaprobación en los labios apretados. Tras ellos está la casa de campo blanca que da nombre a la obra, con una ventana gótica de arco apuntado en su hastial."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SRI_SHANMUKAHA"] =
    "Pintura devocional india al estilo académico europeo que Ravi Varma hizo famoso por toda la India. El dios hindú Murugan cabalga sobre su pavo real con seis cabezas coronadas y muchos brazos que empuñan armas, flanqueado por sus dos consortes con saris de un rosa vivo. La cola del pavo real se despliega tras ellos como un abanico gigante de ojos verdes y dorados, mientras el ave sujeta una cobra bajo sus patas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DAUD_RECEIVES_A_ROBE"] =
    "Miniatura mogol de una crónica imperial ilustrada, en acuarela opaca y oro sobre papel. El detalle que se muestra se centra en un joven sirviente esbelto con una túnica pálida, un gorro rojo y una faja dorada, que porta la túnica de honor dorada y plegada para la ceremonia de entrega. Está de pie contra la pared de una tienda de un azul brillante cubierta de delicadas enredaderas en flor, cada pliegue y cada flor pintados con precisión miniaturista."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YUSEF_AND_ZULEYKHA"] =
    "Miniatura persa de un manuscrito ilustrado, la obra más celebrada del gran maestro de Herat, Behzad. La página la ocupa por completo un intrincado palacio visto en sección aplanada, un laberinto de escaleras, balcones y vanos revestidos de azulejos en azul, naranja y oro. En una cámara superior, el profeta Yusuf, con un halo de llamas, huye del brazo extendido de Zulaica, mientras paneles de caligrafía persa enmarcan la arquitectura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ASCENT_OF_MUHAMMAD"] =
    "Miniatura persa de un manuscrito real, que representa el viaje nocturno del Profeta a través de los cielos. Mahoma, con el rostro velado de blanco y rodeado de una llama dorada, cabalga sobre el corcel de cabeza humana Buraq por un cielo azul profundo sembrado de nubes ondulantes de bordes dorados. Ángeles con túnicas de rojo, verde y naranja giran en torno a él por todos lados portando regalos e incensarios, con versos persas que enmarcan la escena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LIBERTY_LEADING_THE_PEOPLE"] =
    "Pintura al óleo del romanticismo francés, la imagen por excelencia de la revolución. La propia Libertad, una mujer con el pecho desnudo, un vestido amarillo y un gorro rojo, avanza a grandes pasos sobre una barricada de escombros y cuerpos caídos, alzando la bandera tricolor francesa hacia el cielo cargado de humo. A su alrededor irrumpen ciudadanos armados de toda clase, entre ellos un caballero con sombrero de copa y un mosquete y un muchacho que agita dos pistolas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_JEROME_IN_HIS_STUDY"] =
    "Pintura al óleo del primer Renacimiento de una notable precisión miniaturista. Visto a través de un gran arco de piedra, San Jerónimo con túnica roja está sentado leyendo en un gabinete de madera construido como un escenario dentro de un espacio catedralicio abovedado, rodeado de estantes de libros y vasijas. La luz entra a raudales por ventanas a todos lados, un pavo real y una perdiz se posan en el umbral delante, y su león merodea entre las sombras a la derecha."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PARTHENON_FRIEZE"] =
    "Pintura al óleo victoriana que imagina la antigua Atenas; en el juego esta obra acompaña a la maravilla del Partenón. El escultor Fidias está de pie sobre un andamio de madera junto a su friso de mármol recién pintado de jinetes, todavía con los colores del taller, sujetando una cuerda mientras lo presenta. Un pequeño grupo de atenienses con túnicas drapeadas, Pericles entre ellos, se inclinan para admirar el tallado a la cálida luz del interior del templo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUE_DE_PARIS"] =
    "Pintura al óleo del realismo francés del París moderno en un día lluvioso, nítida y fotográfica allí donde sus amigos impresionistas eran sueltos. Una pareja bien vestida que comparte un paraguas pasea hacia ti sobre adoquines relucientes, el hombre con sombrero de copa y la mujer con un largo vestido oscuro y un pendiente que atrapa la luz. A su alrededor, otros caminantes con paraguas cruzan un ancho cruce flanqueado por edificios de viviendas grises en forma de cuña, con una farola verde que parte la escena por la mitad."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_NIGHT_WATCH"] =
    "Pintura al óleo del Siglo de Oro neerlandés a gran escala, el retrato de grupo más famoso jamás pintado. Una compañía de la milicia urbana irrumpe en movimiento desde una sombra profunda: el capitán vestido de negro con una faja roja avanza dando una orden a su teniente vestido de oro pálido, mientras tras ellos se cargan mosquetes, se alza un estandarte y un tambor marca el ritmo. Una niña pequeña con un vestido dorado resplandeciente brilla misteriosamente entre la multitud, iluminada como un foco en la penumbra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DEATH_OF_MARAT"] =
    'Pintura al óleo del neoclasicismo francés, la gran imagen mártir de la Revolución francesa. El periodista revolucionario Marat yace muerto en su bañera, desplomado como un santo caído, la cabeza envuelta en un turbante blanco y un brazo colgando hasta el suelo, sosteniendo aún su pluma. En la otra mano tiene la carta que su asesina usó para lograr entrar; la mitad superior del lienzo es pared oscura y desnuda, y la sencilla caja de madera junto a él lleva pintada la dedicatoria "A Marat, David".'
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ETIENNE_CHEVALIER"] =
    "Pintura francesa sobre tabla de finales de la Edad Media, una de las alas de un famoso díptico devocional. El tesorero real Étienne Chevalier se arrodilla con una rica túnica roja y las manos juntas en oración, presentado por su patrón san Esteban, que está de pie a su lado con una vestidura azul y oro. El santo lleva un libro coronado por una piedra dentada, el símbolo de su martirio, y ambos se hallan en una sala de mármol blanco con el nombre del donante grabado a lo largo del muro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_FRANCIS"] =
    "Pintura al óleo del barroco español, de austera devoción monástica. San Francisco está solo con un sencillo hábito con capucha del color de la arena, el rostro medio perdido en la profunda sombra de la capucha, los ojos bajos en oración. Sostiene en las manos una calavera humana como recordatorio de la muerte, iluminada por una única luz dura contra un fondo casi negro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HATAORI"] =
    "Estampa japonesa ukiyo-e grabada en madera de una tejedora trabajando. Una joven con un kimono índigo estampado se sienta descalza ante un gran telar de mano de madera, alzando la vista de su labor con una lanzadera en una mano, hilos de rojo, azul y blanco tendidos a lo largo de la máquina. Los colores son suaves cremas y azules apagados, con una columna de poesía a pincel que llena la parte superior izquierda de la hoja."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JANE_GREY"] =
    "Pintura francesa de historia académica, teatral y desgarradora. La reina adolescente, con los ojos vendados y vestida de raso blanco que resplandece contra la cámara de piedra oscura, se arrodilla y busca a ciegas el tajo de la ejecución mientras un anciano funcionario guía con suavidad sus manos hacia él. Sus damas se desploman de dolor contra una columna detrás de ella, y el verdugo aguarda a la derecha, apoyado en su hacha con los ojos vueltos hacia otro lado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WANDERER"] =
    "Pintura al óleo del romanticismo alemán, la imagen por excelencia del hombre a solas ante la naturaleza. Un joven con un abrigo verde oscuro está de pie de espaldas al espectador sobre una cumbre rocosa, apoyado en un bastón, el cabello agitado por el viento. Bajo él, un océano de niebla blanca engulle el valle, y solo crestas y peñascos asoman como islas, con pálidas montañas que se desvanecen en la distancia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BABEL"] =
    "Pintura al óleo del renacimiento flamenco de la torre condenada de la Biblia, hormigueante de detalle. Una colosal torre en espiral de arcos, en parte de piedra blanca y en parte de ladrillo rojo en bruto, se eleva torcida hacia las nubes, con la cima todavía en bruto y sin terminar. En torno a su base se extiende una ciudad portuaria con barcos anclados, y en primer plano un rey inspecciona a una cuadrilla de canteros que se arrodillan a sus pies entre los bloques."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YOUNG_LADY"] =
    "Retrato al óleo de los primeros maestros flamencos, pequeño, quieto y extrañamente moderno. Una pálida joven de rostro liso como la porcelana mira al espectador de soslayo desde debajo de un alto tocado de terciopelo negro ribeteado de oro. Viste un vestido azul con un cuello de piel blanca y un ceñido collar de bandas de oro y negro, sobre un sencillo muro tenue en lugar del habitual vacío oscuro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_KINDRED"] =
    "Pintura al óleo de la Escuela del río Hudson estadounidense, un homenaje a la amistad entre un pintor y un poeta. Dos hombres con abrigos conversan de pie sobre un saliente de roca que sobresale por encima de un barranco boscoso en los montes Catskill, uno señalando la vista con un pincel. Un arroyo cae sobre las rocas más abajo, enmarcado por un arco de árboles que cuelgan por encima, con cimas brumosas que se disuelven en una luz dorada al fondo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BLUE_BOY"] =
    "Retrato al óleo inglés al gran estilo, la obra más célebre del artista. Un muchacho de unos doce años está de pie de cuerpo entero con un reluciente traje de raso azul de calzón corto y cuello de encaje, una mano en la cadera y la otra sosteniendo a su lado un sombrero con plumas. Mira con tranquila seguridad desde un paisaje oscuro y tormentoso de tonos pardos que hace arder el traje azul."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SECOND_OF_MAY"] =
    "Pintura al óleo española, una de las primeras y mayores protestas contra la guerra en el arte. A la luz de un farol, un pelotón de fusilamiento francés forma una fila sin rostro, los fusiles apuntados a un grupo de cautivos españoles apiñados en una colina yerma a las afueras de Madrid. En el centro, un hombre con camisa blanca abre los brazos de par en par ante los fusiles, arrodillado entre los cuerpos de los ya fusilados, su postura evocando una crucifixión."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_CART"] =
    "Pintura militar al óleo francesa de la guerra franco-prusiana, una famosa imagen de la última resistencia desafiante. Un puñado de soldados franceses defiende la casa destrozada de un pueblo, disparando desde una ventana mientras los heridos están desplomados contra las paredes y un oficial cuenta sus últimos cartuchos. La habitación está arrasada, una puerta arrancada de sus goznes, el yeso cayendo del techo, la luz del día inundando el umbral donde los compañeros siguen luchando."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EARLY_AUTUMN"] =
    "Rollo de mano chino en tinta y color suave, un estudio en primer plano de la naturaleza de un estanque de lotos que se marchita. Libélulas en rojo, verde y azul revolotean sobre cañas secas y hojas de loto desgarradas, mientras saltamontes, una abeja y pequeñas ranas hacen su vida más abajo. El ambiente es de suave decadencia, la vida del verano que prosigue entre plantas que apenas empiezan a marchitarse, con sellos rojos de coleccionistas a lo largo de ambos bordes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_APPRECIATING_LOTUSES"] =
    "Rollo colgante japonés en tinta y color del fundador de la escuela Kano, pintado a la manera del paisaje letrado chino. Un letrado chino con túnica se deja llevar en una pequeña barca al borde de un estanque de lotos, contemplando las hojas flotantes bajo un sauce retorcido que se inclina desde la orilla rocosa. La mayor parte del alto rollo es bruma y aguas abiertas, con unas pocas copas de pino que se desvanecen en la calina."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EQUESTRIAN_PORTRAIT"] =
    "Pintura al óleo del renacimiento veneciano, el modelo de siglos de gobernantes a caballo. El emperador del Sacro Imperio Romano cabalga saliendo de un bosque oscuro con reluciente armadura completa y un yelmo de penacho rojo, lanza en mano, conmemorando su victoria en Mühlberg. Su caballo negro va cubierto de carmesí, y un bajo sol de atardecer rompe en oro y rosa bajo pesadas nubes de tormenta."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ARMADA"] =
    "Retrato de propaganda Tudor al óleo, pintado para celebrar la derrota de la Armada española. La reina Isabel está sentada con un inmenso vestido de perlas y lazos, el rostro enmarcado por una vasta gorguera blanca de encaje, una mano posada de forma posesiva sobre un globo terráqueo con los dedos sobre las Américas. A través de las ventanas a su espalda la historia se despliega dos veces: la flota inglesa en aguas en calma a un lado, los barcos españoles destrozados en una tormenta al otro. Su corona enjoyada reposa a su lado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRANCIS_I"] =
    "Retrato real renacentista francés al óleo. El rey te mira de frente de medio cuerpo con un espectacular atuendo de corte, mangas acuchilladas de raso blanco y dorado rayado de negro, una cadena de oro cruzándole el pecho y un gorro negro con una pluma blanca en la cabeza. Su rostro barbado, astuto y de nariz larga destaca contra un fondo de damasco carmesí con un motivo de coronas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SELF_PORTRAIT"] =
    "Autorretrato al óleo manierista nórdico del pintor de corte flamenco del emperador Rodolfo II. El artista te mira por encima del hombro, un hombre robusto y barbado de cabello rizado bajo un blando gorro negro, con un cuello blanco fruncido sobre un jubón gris azulado. El trazo es cálido y directo contra un fondo pardo liso, y su mirada de soslayo, evaluadora, retiene la tuya."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VERTUMNUS"] =
    "Pintura manierista al óleo, la más famosa de las fantasiosas cabezas compuestas de Arcimboldo. Es un retrato del emperador Rodolfo II como el dios romano de las estaciones, con todo el rostro y el pecho ensamblados a partir de frutas, verduras y flores: párpados de vaina de guisante, nariz de pera, labios de cereza, bigotes de espiga de trigo y cabello de uvas. De lejos es un gobernante digno; de cerca se disuelve en un puesto de mercado, todo ello contra un fondo negro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_SUPPER"] =
    "Pintura al óleo veneciana del Renacimiento tardío que reinventa la escena familiar. En lugar de presentarse de frente, la mesa del banquete se hunde en una pronunciada diagonal hacia el interior de una oscura sala de taberna, con Cristo resplandeciendo a media distancia mientras ofrece pan a los apóstoles. Unos sirvientes acarrean comida y un gato hocica en un cesto en primer plano, mientras una llameante lámpara de aceite llena de ángeles traslúcidos y arremolinados el aire humeante de lo alto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_A_MAN"] =
    "Pintura al óleo de los primitivos flamencos, posiblemente el propio rostro del artista y uno de los primeros autorretratos verdaderos. Un hombre de mediana edad, de rostro surcado y mirada penetrante, te mira directamente desde una sombra profunda, con un extravagante tocado rojo enrollado y anudado en pliegues escultóricos. El detalle es fino como una aguja, captada cada arruga y cada pelo de la barba incipiente, con la figura en un oscuro abrigo ribeteado de piel contra un fondo negro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRONT_OF_THE_MIRROR"] =
    "Pintura al óleo veneciana del Renacimiento, la serena obra maestra tardía del anciano Bellini. Una joven desnuda de cabello castaño rojizo está sentada sobre un paño rojo, peinándose con calma mientras sostiene un pequeño espejo de mano, y un segundo espejo redondo en la pared del fondo refleja la parte trasera de su tocado de motivos. Una ventana a su lado se abre a un verde campo con montañas azules a lo lejos bajo un cielo nublado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ADORATION"] =
    "Fresco italiano temprano de la capilla de los Scrovegni, del pintor al que se atribuye haber devuelto el sentimiento humano natural al arte occidental. Bajo un dosel de madera, María sostiene al niño Jesús mientras el mayor de los tres reyes se arrodilla para besar los pies del niño, con su corona dejada a un lado; los camellos esperan a la izquierda. Sobre el establo un cometa surca el cielo azul intenso en lugar de la habitual estrella, todo ello en las figuras sólidas y sencillas y los colores claros de Giotto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUBENS_AND_ISABELLA"] =
    "Pintura barroca flamenca al óleo, el retrato de boda del artista con su esposa. La joven pareja está sentada muy junta bajo un arbusto de madreselva, con la mano derecha de ella posada con ternura sobre la de él, el sereno centro del cuadro. Él está sentado por encima de ella con un jubón negro y una pierna cruzada, ella se arrodilla con una falda violeta, un corpiño bordado en oro, una amplia gorguera y un alto sombrero de paja, ambos mirando hacia fuera con tranquilo contento."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CHILDS_BATH"] =
    "Pintura al óleo impresionista estadounidense de ternura cotidiana, influida por las estampas japonesas en su punto de vista elevado y sus motivos planos. Una madre con un vestido de rayas marcadas sostiene en su regazo a un niño envuelto en una toalla, lavándole los pies al pequeño en una palangana de agua. Ambas cabezas se inclinan juntas sobre la tarea, y la habitación a su alrededor es una colcha de motivos: papel pintado floreado, un arcón pintado, una alfombra recargada y una jarra blanca."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_CARD_PLAYERS"] =
    "Pintura al óleo postimpresionista, una de una famosa serie sobre este tema. Dos campesinos con sombrero están sentados uno frente al otro a una pequeña mesa de madera, absortos en sus cartas, con una sola botella de vino en pie entre ellos como el centro inmóvil de la composición. Uno fuma en pipa; la pintura está construida en pacientes trazos macizos de pardo terroso, ocre y violeta apagado que hacen que las figuras parezcan talladas y permanentes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_SWING"] =
    "Pintura al óleo rococó francesa, frívola, secreta y la imagen más famosa de su época. En un frondoso jardín descuidado, una joven con un vaporoso vestido rosa se balancea en lo alto de un columpio de cuerda, lanzando una chinela al aire, mientras un anciano oculto tira de las cuerdas desde las sombras a su espalda. Su joven amante está tumbado entre los rosales de abajo, situado a la perfección para mirar bajo sus faldas, y una estatua de piedra de Cupido se lleva un dedo a los labios."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIANT_MAGNOLIAS"] =
    "Pintura de bodegón al óleo estadounidense, exuberante y de aire casi tropical. Dos enormes flores de magnolia de un blanco cremoso yacen cortadas sobre un paño de terciopelo azul intenso, rodeadas de sus brillantes hojas oscuras, con un tercer capullo aún cerrado. Los pétalos resplandecen contra el fondo casi negro, pintados con una precisión cerosa y sensual."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_KILLING"] =
    "Tabla gótica catalana al temple y oro. San Jorge, con armadura negra y una aureola dorada, se inclina desde su encabritado caballo blanco para clavar una larga lanza en las fauces abiertas de un dragón de alas de murciélago, con el suelo a su alrededor sembrado de huesos y calaveras. La princesa, con vestido rosa, reza sobre un saliente rocoso al fondo, y los espectadores se agolpan en las blancas murallas del castillo en lo alto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JACQUES_AND_BERTHE"] =
    "Doble retrato modernista al óleo del escultor Lipchitz y su esposa, pintado con el inconfundible estilo de Modigliani. El marido está de pie con un traje oscuro y la mano apoyada en el hombro de su mujer, sentada, cuyo rostro de mejillas sonrosadas emerge de un cuello de encaje blanco. Ambos tienen las caras alargadas, las narices largas y los ojos almendrados y vacíos característicos del artista, con sus nombres garabateados en lo alto del lienzo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DASH_FOR_TIMBER"] =
    "Pintura al óleo del Oeste americano, la clase de escena de acción a la carga que definió el Viejo Oeste en la imaginación popular. Ocho vaqueros galopan a pleno tendido directos hacia ti, con los cascos de los caballos en el aire, mientras dos jinetes se retuercen en la silla para disparar hacia atrás a la partida de apaches a caballo que los persigue entre el polvo a su espalda. Un hombre se desploma herido contra un compañero mientras corren hacia los árboles del borde izquierdo de la árida llanura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GEORGE_WASHINGTON_PORTRAIT"] =
    "Retrato oficial de Estado al óleo, la imagen oficial de la primera presidencia. Washington está de pie de cuerpo entero con un sencillo traje de terciopelo negro, un brazo extendido en un gesto de discurso y el otro sosteniendo una espada de gala, junto a una mesa con pluma y tintero. Lo que lo rodea es grandeza republicana: una silla dorada con el escudo de las barras y estrellas, columnas de mármol y un cortinaje carmesí, con un arcoíris que rompe entre nubes de tormenta al fondo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ATTACK_ON_BEIJING"] =
    "Estampa japonesa en color al estilo de la ilustración bélica de noticias, con leyendas en japonés y en inglés. Las tropas aliadas asaltan las murallas del palacio imperial de Pekín: soldados británicos de casaca roja con una bandera del Reino Unido cargan desde el primer plano mientras la infantería japonesa de uniforme blanco avanza por la derecha. Los estallidos de los proyectiles quedan suspendidos como bocanadas blancas sobre el verde campo de desfiles, con la puerta de tejado azul del palacio y las murallas humeantes al fondo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUMO_WRESTLER"] =
    "Estampa japonesa ukiyo-e en xilografía, el retrato de una celebridad, un luchador estrella fuera de servicio. El corpulento hombre está de pie en toda su estatura con un kimono negro sobre túnicas estampadas, las espadas al fajín, secándose la frente con un paño a cuadros mientras carga un manto plegado sobre un hombro. Su nombre baja por el lado derecho en vistosos paneles de caligrafía en rojo, la figura plana y monumental contra el papel desnudo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_TIGER_IN_TROPICAL_STORM"] =
    "Pintura al óleo de estilo naíf del autodidacta aduanero francés que nunca vio una selva. Un tigre de ojos muy abiertos se agazapa en la hierba alta sacudida por el viento, con los dientes al descubierto, sorprendido por una tormenta que dobla de lado toda la vegetación. La selva es un denso patrón de hojas estilizadas en verdes y rojos, con oblicuas vetas plateadas de lluvia trazadas sobre todo el lienzo como una gasa."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_HOME_GUARD"] =
    "Retrato húngaro al óleo de estilo Biedermeier de la revolución de 1848. Un ciudadano-soldado barbudo está sentado con una sencilla chaqueta de lino sin teñir, ambas manos enguantadas apoyadas en la empuñadura de su sable erguido, el brazalete nacional rojo, blanco y verde en la manga declarando su causa. Mira hacia un lado con calmada resolución, iluminado cálidamente contra una cortina de rojo oscuro, con su abrigo forrado de rojo echado sobre la silla."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CEREMONIAL_SITTING"] =
    "Pintura realista rusa al óleo de vasta escala, un retrato de grupo de todo el consejo de gobierno del imperio. Decenas de ancianos estadistas con uniformes oscuros cargados de galón dorado y fajines rojos están sentados en torno a una gran herradura de sillas rojas en una sala de columnas blancas adornada con arañas y retratos reales. Cada uno de los más de sesenta rostros es un retrato individual, pintado con el realismo rápido y seguro de Repin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUSSIAN_TSAR"] =
    "Pintura histórica rusa al óleo que recrea una procesión real del siglo XVI. Un zar con gorro de piel y un manto de brocado dorado cabalga sobre un caballo blanco por la nieve, precedido por guardias de brillantes casacas rojas que portan altas alabardas curvas. La multitud se arrodilla y se inclina hasta el suelo a ambos lados del camino nevado y pisoteado, con los edificios de troncos de una vieja ciudad rusa bajo un pálido cielo invernal."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CRUCIFIXION_OF_SAINT_PETER"] =
    "Pintura barroca italiana al óleo, brutal y física, con el estilo inconfundible de Caravaggio. Tres jornaleros se esfuerzan por izar una cruz de madera en la que el anciano San Pedro ha sido clavado boca abajo, uno tirando de una cuerda y otro agachado bajo el madero, con los rostros ocultos. El santo de barba blanca alza la cabeza para mirar su propia mano clavada, su musculoso cuerpo viejo refulgiendo desde una negrura absoluta bajo una única luz dura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LANDSCAPE_WITH_ANT_BEAR"] =
    "Paisaje colonial holandés al óleo, pintado por el primer artista de formación europea que trabajó en Brasil. Un amplio valle soleado con un río se abre bajo un gran cielo entre dos altas palmeras, con un asentamiento colonial de casas blancas en las colinas lejanas. Un grupo de figuras afrobrasileñas recorre un sendero en primer plano cargando fardos, y el oso hormiguero de hocico largo del título husmea entre la maleza en la parte inferior derecha."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DUTCH_MEN_O_WAR"] =
    "Pintura marina al óleo del Siglo de Oro holandés, obra del mayor pintor de barcos de la época. Altos buques de guerra de madera reposan anclados sobre un agua lisa como un cristal, con las velas colgando flojas y los cascos reflejados en el mar, cada cabo del aparejo exacto. Botes de remos trasladan pasajeros entre los navíos bajo un vasto cielo de cúmulos iluminados por el sol, toda la escena bañada en una calma dorada."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HARBOR_IN_BALAKLAVA"] =
    "Litografía coloreada de la guerra de Crimea, dibujada por uno de los primeros artistas de guerra que documentaron una campaña sobre el terreno. En una desolada orilla portuaria, soldados enfermos y heridos envueltos en mantas blancas son ayudados a bajar de literas a lomos de mula hasta un bote de remos que aguarda. Pelados cerros pardos se alzan tras el grupo de figuras, con barracones y tiendas del ejército salpicando la ladera, los colores apagados y documentales."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PEACEMAKERS"] =
    "Pintura histórica estadounidense al óleo de un auténtico consejo de la Guerra de Secesión en sus últimos días. El presidente Lincoln está sentado en el camarote de un barco de vapor escuchando con atención, la barbilla en la mano, mientras el general Sherman gesticula en plena discusión; el general Grant y el almirante Porter completan el círculo de cuatro figuras de traje oscuro. Por las ventanas del camarote a sus espaldas, un arcoíris rompe entre cielos que se despejan, la callada señal de la paz venidera que ofrece la pintura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_CHITASEI"] =
    "Estampa japonesa ukiyo-e en xilografía de la célebre serie de Kuniyoshi sobre los 108 héroes de la novela china A la orilla del agua. El erudito estratega Wu Yong está de pie con una fluida túnica oscura estampada con dragones, acariciándose la barba pensativo bajo un cielo nocturno tachonado de estrellas. A su lado descansa un gran globo celeste sobre un soporte ornamentado, y paneles de texto japonés enmarcan la figura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_LOUIS"] =
    "Retrato inglés al óleo del siglo XVIII de un escultor sorprendido durante su trabajo. Roubiliac, con un gorro blando y la camisa abierta de mangas remangadas, se detiene con la herramienta de modelar en alto y mira de reojo mientras trabaja en una estatuilla de arcilla de Shakespeare sobre un soporte. El escultor señala su propia creación con la mano libre, cálidamente iluminado contra el oscuro fondo del estudio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_NASSER"] =
    "Retrato cortesano persa de la dinastía qayar al óleo, con el esplendor regio aplicado a manos llenas. El joven shah de bigote se sienta rígidamente erguido con un uniforme escarlata cuajado de bordado dorado, sartas de perlas, charreteras enjoyadas y una banda azul, una mano sobre una espada incrustada de gemas. Lleva un alto gorro negro con un ramillete de diamantes, los ojos de contorno oscuro mirando al frente contra un fondo verde oliva intenso estampado con una inscripción real."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FIELD_WITH_SHEAFS"] =
    "Paisaje al óleo de inclinación expresionista alemana, pintado con pinceladas amplias y enérgicas. Un campo de trigo segado llena el primer plano con hileras de gavillas doradas apiladas en haces inclinados, el amarillo aplicado espeso y brillante. Una línea de árboles verde oscuro cierra el campo, con un cielo de un pálido azul violáceo de nubes movidas por el viento encima."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AT_THE_EDGE_OF_THE_BROOK"] =
    "Pintura académica francesa al óleo, pulida hasta la perfección vidriada por la que Bouguereau fue famoso. Dos niños campesinos descalzos se sientan sobre una piedra en la orilla de un arroyo, la niña más pequeña quitándose una media mientras su compañera de cabello oscuro se recoge la falda para vadear. Intercambian una mirada en mitad de la conversación, la piel y el pelo revuelto pintados con una suavidad fotográfica contra un suave paisaje rural."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS_ALT"] =
    "Pintura romántica italiana al óleo, el beso más famoso del arte italiano y un emblema patriótico oculto de la unificación. En un pasillo medieval de piedra, un joven con un sombrero emplumado y una capa parda inclina hacia atrás a una mujer en un beso apasionado, un pie ya sobre el escalón como si se detuviera en plena huida. El vestido de raso azul pálido de ella derrama luz sobre la escena, mientras una figura sombría se acerca a través del arco del fondo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MOVING_HOUSE"] =
    "Pintura realista rusa al óleo de la callada pobreza urbana. Una pareja anciana cruza con paso fatigado el hielo del río helado de San Petersburgo cargando cuanto poseen en un hatillo de tela, el hombre apoyado en un bastón, ambos arrebujados en abrigos y pañuelos gastados contra el frío. Un perro pequeño trota delante de ellos, y la dorada aguja de la fortaleza de Pedro y Pablo se eleva entre la bruma invernal al fondo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MEXICAN_EXPEDITION"] =
    "Pintura francesa de historia naval al óleo, de estilo reporteril y abarrotada de acción. Un buque de guerra francés con la bandera tricolor domina el primer plano izquierdo, con sus oficiales en cubierta dirigiendo un bombardeo de la fortaleza mexicana de San Juan de Ulúa, el humo elevándose sobre el agua. Los proyectiles caen al agua cerca de los botes de remos que transportan hombres entre los barcos, con un volcán de cima nevada en el horizonte brumoso."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_DAY_OF_POMPEII"] =
    "Pintura romántica rusa al óleo sobre un lienzo enorme, la epopeya del desastre de su siglo. El cielo sobre Pompeya arde en rojo y negro al erupcionar el Vesubio, las estatuas se desploman desde un tejado y un rayo hiende la nube de ceniza. Multitudes de habitantes con atuendo romano huyen entre los escombros que caen, resguardando a niños y ancianos bajo las capas, mientras una mujer caída yace tendida junto a un carro volcado en el centro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ACCOLADE"] =
    "Pintura al óleo de estilo prerrafaelita inglés, una visión de cuento de la caballería. Una reina de cabello dorado con un vaporoso vestido blanco posa una espada sobre el hombro de un caballero arrodillado, armándolo ante un pequeño público cortesano. Él inclina la cabeza con cota de malla y una sobreveste roja, el yelmo en el suelo a su lado, la sala de piedra y el estrado rojo pintados con resplandeciente detalle romántico."
