-- Mod-authored world wonder splash painting descriptions, it_IT overlay.
-- Baseline in CivVAccess_WonderDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_MISSING"] = "Nessuna descrizione per questa meraviglia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOTHERLAND_STATUE"] =
    "Il gioco è stato distribuito senza un dipinto per questa meraviglia; non c'è alcuna immagine da descrivere."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ALHAMBRA"] =
    "Da sotto l'ombra di una snella colonna di pietra, un cortile di palazzo si apre attorno a una lunga vasca riflettente, il Cortile dei Mirti dell'Alhambra. La vasca corre via verso un portico ad arcate in pietra color rosa, i cui archi si specchiano nell'acqua immobile. Una torre quadrata di fortezza si erge calda contro il cielo azzurro alle spalle. Basse siepi potate orlano il bordo dell'acqua, una pianta in vaso sta in primo piano, e piccoli gruppi in lunghe vesti conversano lungo i camminamenti illuminati dal sole. Il sole vivido del pomeriggio riempie il cortile, bianco dove colpisce la pavimentazione. Un'ombra profonda giace sotto il colonnato."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ANGKOR_WAT"] =
    "Un gruppo di torri di pietra grigia a piani digradanti, modellate come boccioli di loto chiusi, si erge sullo sfondo, in parte schermato da palme sotto un cielo caldo e pallido. Il primo piano è una processione festiva: un elefante grigio avanza a grandi passi tra una folla fitta, con un conducente sul collo e un seggio a baldacchino sul dorso, ombreggiato da un alto parasole rosso-arancio. La folla preme da ogni lato in vesti bianche, zafferano e prugna; le teste sono avvolte, le spalle nude, e ogni volto si volge verso l'elefante che passa. La scena è battuta dal sole e polverosa, e la pietra è di un verde-grigio fresco contro la pelle calda e i tessuti sottostanti."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BIG_BEN"] =
    "Una torre dell'orologio in stile gotico si erge di notte all'estremità del ponte di Westminster, con il suo orologio a quattro facce che brilla d'ambra vicino alla cima. Sopra l'orologio, la guglia svanisce in un cielo azzurro intenso. La lunga facciata delle Case del Parlamento di Londra si estende via verso sinistra, finestre e pietra illuminate di un caldo oro dai riflettori. Torri merlate si ergono alla sua estremità lontana. Il ponte attraversa il primo piano con una fila di lampioni luminosi. Alcune carrozze e figure appaiono piccole e scure sulla carreggiata. L'intera scena è dipinta in azzurri notturni contro l'oro dei lampioni e della pietra illuminata."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BOROBUDUR"] =
    "Una piramide a gradoni di pietra vulcanica grigia si erge dalla giungla come una collina terrazzata, i suoi piani superiori cinti da piccoli stupa a forma di campana. Uno stupa più grande corona la sommità. Palme crescono dalle terrazze inferiori e la foresta preme vicina attorno alla sua base. In primo piano una fila di monaci in vesti arancioni e rosse sale verso il tempio lungo un sentiero ombroso nella giungla, e uccelli si sparpagliano nel cielo velato sopra. La tavolozza è di un grigio-verde nebbioso, e le vesti sono l'unica forte nota di colore."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BRANDENBURG_GATE"] =
    "Un ampio portale classico di arenaria consumata si erge in fondo a una piazza cittadina animata, sollevato su file appaiate di pesanti colonne e coronato dalla quadriga, la statua bronzea del carro a quattro cavalli, che spicca scura contro un cielo coperto e pallido. Un'ala colonnata più bassa si dirama verso destra in direzione degli edifici di pietra circostanti. La piazza davanti è la Berlino dell'Ottocento: carrozze trainate da cavalli che rotolano sui ciottoli, cavalieri, e folle in lunghi cappotti scuri e cilindri, con un lampione che si erge a sinistra. I colori sono grigi e marroni sobri, e la luce è piatta e uniforme."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BROADWAY"] =
    "Un quartiere dei teatri di notte all'inizio del Novecento, la strada bagnata di pioggia e splendente di luce riflessa. Pensiline e insegne luminose affollano entrambi i lati del viale, lampadine bianche e rosse che compitano i nomi degli spettacoli. Una lunga facciata luminosa di teatro brilla al centro dell'isolato. Folle in cappotti e cappelli scuri riempiono i marciapiedi e si riversano nella strada tra alcune vecchie automobili, tutti piccoli contro gli alti palazzi di uffici scuri che si innalzano nel cielo notturno. La tavolozza è di un azzurro-nero profondo, spezzato da pozze di calda luce elettrica bianca, rossa e gialla."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CN_TOWER"] =
    "Uno snello ago di cemento si erge al centro dello skyline di Toronto, gonfiandosi in un'arrotondata capsula panoramica vicino alla cima e assottigliandosi poi in una guglia d'antenna. Le nubi temporalesche si stanno aprendo attorno ad esso, e fasci di luce solare si riversano dietro la torre attraverso lo squarcio, velando i palazzi di uffici su entrambi i lati. Il primo piano è una superstrada infossata percorsa da un flusso di traffico, fari e fanali rossi posteriori che brillano nella foschia tra terrapieni di cemento. L'intera scena è grigio acciaio e oro. La città è per metà nell'ombra del temporale, per metà nella luce che si fa strada."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CHICHEN_ITZA"] =
    "Una piramide a gradoni, El Castillo, si erge al centro sotto un cielo arancione ardente, nove piani quadrati che salgono fino a un piccolo tempio sulla sommità. Una larga scalinata corre dritta su per la sua facciata. Un secondo tempio a gradoni si erge sul margine sinistro, e il fumo si disperde attraverso il sole dove esso pende basso e rosso. Una piazza sottostante è gremita di una folla di Maya, la maggior parte rivolti di spalle: spalle nude, copricapi piumati, bastoni e lance alzati. Un gruppo di guerrieri sta su una piattaforma di pietra a destra. Tutto è immerso nella luce ruggine e ambra del crepuscolo. La folla cade in scura sagoma controluce contro la pietra che riluce."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CRISTO_REDENTOR"] =
    "Un colossale Cristo di pietra pallida, visto da dietro e dall'alto, si erge sul suo piedistallo in cima al monte con le braccia spalancate sopra la baia sottostante. La sua schiena in veste e le braccia protese riempiono l'inquadratura vicina, il capo lievemente chinato in avanti. Oltre e molto più in basso, Rio de Janeiro si estende attorno all'acqua in candide distese di edifici, con la gobba arrotondata del Pan di Zucchero che si erge dalla baia tra isole verdi e navi all'ancora. La foschia ammorbidisce la distanza, lasciando la città e il mare in pallidi azzurri e grigi, mentre le spalle della statua catturano la luce del giorno."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_COLOSSUS"] =
    "Un gigante di bronzo si erge in lontananza sull'imbocco roccioso del porto, un braccio alzato, mezzo dissolto in una foschia dorata. Contro un cielo color ottone è più una sagoma che una statua. Il primo piano appartiene al mare: una piccola barca a vela si inclina verso l'osservatore sotto un'unica ampia vela, con due o tre uomini d'equipaggio visibili a poppa. Altre vele sono sparse per il porto. Basse rocce corrono lungo la battigia a destra, e l'acqua porta lo stesso oro caldo del cielo. L'intero dipinto è un solo colore, luce e foschia d'ambra. Il Colosso vi splende attraverso come una figura in un sogno."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOSQUE_OF_DJENNE"] =
    "Un lungo muro di terra fatto di torri e pinnacoli si estende sullo sfondo, mattoni di fango in un rosso-bruno intenso. Le sue facce sono irte di toron, file di travi di legno che sporgono dalle pareti come spine. Il cielo dietro di esso è denso di polvere e fumo arancioni, il sole perduto nella foschia. Tutto il primo piano è un giorno di mercato: tendoni e baldacchini in rosso e bianco, animali tra le bancarelle, e una folla fitta in vesti vivaci che si muove tra esse. Calore e polvere unificano la scena, e tutto è dipinto in arance, ruggini e marroni."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_EIFFEL_TOWER"] =
    "Un oscuro traliccio di ferro fatto di piedi e piattaforme a travature riempie la parte superiore sinistra dell'inquadratura, così vicino che la cima è tagliata via dal bordo del quadro. Sotto di esso la scena è un pomeriggio di belle epoque sull'erba: gruppi in lunghi abiti bianchi e completi scuri fanno un picnic su un ampio prato verde, con parasoli, cappelli da sole e cesti sparsi intorno a loro. Una donna in bianco sta al centro. Dietro il prato scorre la Senna, e la pietra chiara di Parigi si estende lungo la riva opposta sotto un morbido cielo grigio. La tavolozza è di verdi e grigi freddi. Gli abiti bianchi catturano quel poco di luce che c'è."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_FORBIDDEN_PALACE"] =
    "Le sale di palazzo, con ampi tetti di tegole dorate e pareti rosso intenso, si ergono al di là di un vasto cortile lastricato, viste da una terrazza di marmo rialzata in primo piano. Una scura statua di leone guardiano è accovacciata sulla balaustra della terrazza a sinistra, e figure in veste stanno lungo le scale. Giù nel cortile, schiere di soldati sono schierate in serrata formazione davanti alla sala centrale, rese minuscole dall'architettura intorno a loro. Un pallido sole pende in un cielo d'ambra velato di foschia, e l'intera scena è inondata di un oro polveroso contro il rosso delle pareti."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GLOBE_THEATER"] =
    "Un teatro circolare di legno visto dal suo stesso palco a metà di una rappresentazione. Tre ordini di gallerie a balconata curvano attorno al cortile centrale, ogni ringhiera gremita di spettatori. Sul pavimento aperto in basso, gli spettatori in piedi si accalcano, un pallido mare di volti. Sul palco un attore in farsetto scuro recita una scena rivolto a due donne in lunghe vesti, una delle quali gesticola con un braccio teso. Il tetto a baldacchino dipinto sporge in alto a destra su un palo intagliato. Una morbida luce diurna scende dal cielo aperto sopra il cortile. Il legno è di un caldo crema e marrone, e la folla è abbozzata in toni pallidi attorno alle figure più nitide sul palco."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_FIREWALL"] =
    "Una scena digitale astratta senza alcun edificio, un cyberspazio oscuro reso in verdi e nero. Ampie superfici curve attraversano l'inquadratura come bastioni di dati, le loro facce rivestite di luminose cifre binarie verdi, e tracce luminose le sfrecciano lungo come traffico su un'autostrada di notte. Schermi e griglie spettrali aleggiano nell'oscurità sopra, alludendo a circuiti e sorveglianza. L'intera immagine ha l'aspetto del mondo interiore di un computer, luce verde fosforo su nero."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIBRARY"] =
    "Una monumentale sala classica fa fronte a una piazza assolata, con alti stendardi rossi appesi tra le colonne del suo lungo colonnato. Un fregio scolpito corre sopra le colonne, e ampi gradini si aprono verso il selciato. La piazza è vista da un portico in ombra in primo piano: una colonna si innalza a sinistra, una sfinge di pietra siede su un plinto a destra, e una cupola bianca si mostra in lontananza oltre. Studiosi e cittadini in toghe e vesti colorate si radunano sui gradini e per la piazza, la maggior parte in piedi a due a due o a tre a tre in conversazione mentre una figura siede sola con un rotolo. La pietra è di un caldo crema nella luce del sole sotto un cielo azzurro striato di nuvole, e gli stendardi sono il rosso più forte della scena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIGHTHOUSE"] =
    "Un'alta torre pallida a ripiani sovrapposti si erge in lontananza a destra, illuminata da uno squarcio nella tempesta, il suo faro splendente in cima. Il resto del quadro è mare agitato: una fila di antiche galee sotto vele quadre a righe rosse e bianche fatica tra pesanti onde grigio-verdi verso la luce, le prore curvate in alto. Gli spruzzi esplodono bianchi contro gli scafi. Oscure nubi di tempesta premono su tutta la scena, e il cielo si apre solo intorno alla torre, come se le navi stessero correndo verso di essa. Le vele portano l'unico colore caldo in un dipinto di ardesia, schiuma e pioggia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_WALL"] =
    "Un ampio bastione di pietra corre dal fondo dell'inquadratura diritto su e oltre le montagne, i suoi parapetti merlati che salgono lungo i crinali finché il muro si riduce a un filo sulle vette più lontane. Una torre di guardia quadrata a due piani con finestre ad arco e un piccolo padiglione coperto in cima si erge sul primo rialzo. Il tracciato del muro si piega attraverso di essa. Le montagne sono piegate e verdi, pendii cespugliosi che precipitano nella foschia, valle dopo valle. Nessuna figura si mostra in alcun punto del muro. La luce è fredda e limpida, pietra grigia contro verde profondo sotto un cielo pallido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HAGIA_SOPHIA"] =
    "Una grande basilica a cupola domina il panorama di una città all'ora dorata, la sua ampia cupola centrale che si eleva da un cumulo di mura contraffortate e semicupole. Quattro minareti slanciati si ergono agli angoli, l'edificio raffigurato come la moschea che divenne in seguito. Tutt'intorno i tetti di Istanbul digradano lungo la collina in toni di sabbia e grigio, interrotti da alberi, cupole minori e torri lontane che si dissolvono nella foschia. Un bagliore d'acqua e basse colline chiudono la distanza a sinistra. Tutto giace sotto un caldo cielo ambrato, e la sagoma della cupola è oro scuro contro la luce."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HANGING_GARDEN"] =
    "Una corte giardino si apre dentro mura di archi in calda arenaria. Le palme si elevano sopra i camminamenti, e il verde trabocca da ogni arco e cornicione. Figure in veste passeggiano e conversano a due e a tre lungo i sentieri ombrosi tra aiuole e piccoli alberi. Attraverso l'arcata centrale e oltre il muro, una bianca città-palazzo sale una collina in terrazze sovrapposte, splendendo in lontananza come la corona del giardino. Tutto si erge in piena luce, verde fogliame intenso contro la pietra dorata e un cielo pallido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HIMEJI_CASTLE"] =
    "Un bianco mastio di castello si eleva da una collina boscosa in cima all'inquadratura, livello su livello di pareti chiare sotto curvi tetti grigi. Più in basso, torrette bianche più piccole si raggruppano tra gli alberi. La strada che vi sale attraversa un villaggio di scuri tetti di tegole, e una porta dalla cornice rossa scavalca il percorso nella media distanza. Samurai a cavallo cavalcano verso di esso attraverso il primo piano, alti stendardi rossi che si ergono dalle loro schiene. Fanti in armatura attendono presso le case a destra. La giornata è tenue e coperta, e la scena è tutta verdi e grigi attorno al bianco mastio. Gli stendardi sono il rosso più acceso della scena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HUBBLE"] =
    "Un lungo cilindro argenteo avvolto in pannelli di lamina fluttua in orbita, il suo sportello apribile aperto all'estremità vicina per esporre la scura bocca dell'ottica. Piatti pannelli solari in telai oro ramato si dispiegano dai suoi fianchi, e un astronauta in tuta spaziale lavora al suo lato, piccolo accanto allo strumento. Parte di una navetta agganciata entra nell'angolo in basso a destra dell'inquadratura. Dietro ogni cosa la Terra riempie il quadro, una curva di oceano blu e nubi bianche che si perde nel nero dello spazio. La tavolozza è argento e oro contro il blu della Terra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_KREMLIN"] =
    "La neve cade sulla Piazza Rossa, dove un muro di fortezza in mattoni rosso scuro corre lungo il lato destro sotto un pesante cielo grigio d'inverno. Una bandiera rossa sventola dal tozzo blocco a gradoni del Mausoleo di Lenin addossato al muro, e più lontano un'alta torre si erge nella caligine, la sua guglia a forma di ripida tenda. Folle in lunghi cappotti scuri e colbacchi di pelliccia attraversano la piazza innevata in una lenta fila, singole figure che arrancano nel primo piano dando le spalle a chi guarda. Il dipinto è quasi monocromo, neve bianca e grigio carbone, con i mattoni e la bandiera come unici rossi."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LEANING_TOWER"] =
    "Un rotondo campanile bianco si eleva da un prato verde, cinto piano dopo piano da aperte arcate in marmo e inclinato inconfondibilmente a destra. Si staglia luminoso contro un cupo cielo di tempesta. Il pallido fianco della Cattedrale di Pisa sta al bordo destro dell'inquadratura, e più bassi edifici cittadini in ocra chiudono il verde sulla sinistra. Popolani e monaci in lunghe vesti marroni e rosse attraversano il prato in radi cortei, piccoli sotto la torre. La luce è teatrale: uno squarcio tra le nubi illumina il marmo bianco mentre il cielo dietro di esso resta quasi nero."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LOUVRE"] =
    "Un palazzo in pietra grigia si estende attraverso lo sfondo, un alto padiglione centrale con ornamenti scolpiti e ripidi tetti mansardati in ardesia, con ali che si protendono ai due lati. Gli artisti lo mostrano nei suoi giorni di palazzo reale, molto prima della piramide di vetro del museo moderno. Davanti si stendono giardini formali: prati piatti attraversati da vialetti di ghiaia, giovani alberi e una piccola fontana che spruzza acqua a sinistra. Passeggiatori in abiti dell'Ottocento punteggiano i camminamenti, donne in lunghe vesti bianche e uomini in cappotti scuri e cilindri. Una coppia si attarda insieme a destra. La giornata è tenue e perlacea. Tutto è pietra grigia e verde smorzato sotto un cielo pallido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MACHU_PICHU"] =
    "Una città di pietra sorge in un'alta sella montana, terrazze agricole che salgono a gradoni lungo il pendio verso gruppi di edifici a timpano sotto tetti di paglia. Dietro di essa, la ripida vetta di Huayna Picchu si arrampica nelle nubi. La foschia indugia sulle catene circostanti, e la valle precipita nell'ombra più in basso. Sul sentiero in primo piano un piccolo gruppo con lama da soma si fa strada in salita verso le porte della città, minuscolo a confronto delle terrazze. La luce filtra in pallidi fasci attraverso il maltempo, facendo emergere la calda pietra color sabbia dal verde e dal grigio delle Ande."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MAUSOLEUM_HALICARNASSUS"] =
    "Un massiccio podio quadrato in marmo bianco, fasciato da fregi scolpiti, si eleva verso una corona di colonne in cima all'inquadratura. Sovrasta una piazza dove statue si ergono su alti pilastri, tra esse una figura in armatura e un cavaliere. Scuri cipressi sono piantati tra le pavimentazioni. Figure in vesti bianche e rosse si raccolgono in basso, rese minuscole dal monumento. La giornata è limpida e luminosa. Marmo bianco e ammassi di candide nubi si stagliano contro un cielo blu intenso."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NEUSCHWANSTEIN"] =
    "Una pallida apparizione di castello sorge su un crinale boscoso, mura bianche e torri raggruppate per metà dissolte nella neve che cade in alto a sinistra dell'inquadratura. Il primo piano è la strada che vi sale: una scura carrozza chiusa attende alla curva mentre cavalieri sfilano in salita lungo il pendio, smuovendo la neve sul tracciato. Abeti spolverati di neve fiancheggiano il percorso e si chiudono sopra la valle sottostante. Il dipinto è grigio e bianco invernale dappertutto. I cavalieri e la carrozza sono le uniche forme scure che vi spiccano contro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NOTRE_DAME"] =
    "Una cattedrale gotica si innalza dalla Parigi medievale, vista dall'alto, con le sue due torri quadrate gemelle, la guglia centrale e la lunga navata sostenuta da contrafforti che svettano ben oltre ogni tetto intorno. La città si stringe alle sue mura in un fitto intreccio di case con abbaini e comignoli fumanti, e la Senna si snoda in primo piano oltre le banchine e piccole imbarcazioni. Il cielo è greve e grigio, ma fasci di luce solare squarciano le nuvole e cadono dritti sulla cattedrale, accendendone d'oro la pietra mentre la città resta in un'ombra ardesia. L'orizzonte sfuma piatto e pallido oltre i tetti."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ORACLE"] =
    "Un tempio rotondo a colonnato sotto una cupola di pietra, una tholos, si erge su uno scoglio in riva al mare all'estremità di un promontorio roccioso, e un arco naturale si apre nella scogliera sottostante. Gli artisti hanno collocato il santuario sulla costa anziché sul fianco della montagna di Delfi. Un sentiero si snoda verso di esso oltre pozze di marea e rocce affioranti. In primo piano, pellegrini in vesti rosse, blu e bianche avanzano lungo il sentiero in piccoli gruppi, incorniciati da pini scuri che si protendono da entrambi i lati. È sera presto e l'aria è fresca, con un cielo pallido illuminato dalla luna e un mare grigio-verde intorno alla pietra calda del santuario."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PARTHENON"] =
    "Un lungo tempio dorico si staglia intero in cima all'inquadratura, il suo colonnato che regge un frontone scolpito e dipinto. Il marmo è di un oro caldo sotto un cielo di nuvole grigie in movimento. Ampi gradini scendono da esso attraverso fasce di bassi arbusti verdi, con statue di bronzo erette su plinti a sinistra. Lungo i gradini avanza una processione di Greci in mantelli cremisi, e al centro un solo oplita guarda verso l'osservatore, con un elmo crestato e uno scudo rotondo al braccio. Il rosso dei mantelli arde contro la pietra, e la luce ha la pesante intensità di un giorno prossimo al temporale."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PENTAGON"] =
    "Una veduta aerea dell'edificio a cinque lati del quartier generale, i suoi anelli pentagonali concentrici di cemento chiaro e tetto scuro che digradano verso l'interno fino a un cortile verde al centro. Strade e parcheggi avvolgono l'edificio, con prati e alberi dalle tinte autunnali oltre. Il Potomac scorre alle sue spalle, attraversato da ponti. Sulla riva opposta la capitale giace nella foschia, l'obelisco bianco del Washington Monument e la cupola del Campidoglio piccoli all'orizzonte. La giornata è semplice e grigia; nulla nella scena risalta tranne la forma dell'edificio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PETRA"] =
    "L'osservatore si trova dentro il Siq, lo stretto canyon d'accesso, tra pareti di roccia rosso-rosa che torreggiano nell'ombra su entrambi i lati dell'inquadratura. Attraverso la fenditura, illuminato dal pieno sole, si erge Al-Khazneh, il Tesoro, una facciata scolpita direttamente nella scogliera. I suoi due ordini di colonne e frontoni classici si innalzano in arenaria rosa, con un padiglione rotondo al centro del livello superiore. Viaggiatori si dirigono verso di esso lungo il fondo sabbioso del canyon: due cavalieri ondeggiano su cammelli in primo piano, e figure in veste camminano dietro. Il dipinto è tutto rossi caldi e bruni in ombra, la facciata scolpita che risplende in fondo al passaggio buio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PORCELAIN_TOWER"] =
    "Un'alta pagoda si innalza sopra il giardino di un tempio, piano dopo piano di scure gronde slanciate su un corpo affusolato. Si erge sopra i tetti di tegole delle sale alla sua base. Il giardino si stende in primo piano attorno a uno stagno immobile: pini potati, salici, lanterne di pietra e una statua di leone scolpita su un piedistallo all'estremità sinistra. Figure in veste passeggiano lungo i sentieri di ghiaia a due a due e a tre a tre, e colline boscose si elevano sfumate dietro la torre. La scena è calma e verde, una morbida luce diurna sull'acqua, la pagoda scura contro un cielo pallido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PRORA_RESORT"] =
    "Un blocco monolitico di villeggiatura corre lungo la riva apparentemente senza fine. La sua facciata chiara ripete le stesse file di finestre più e più volte, estendendosi lungo la spiaggia finché svanisce verso l'orizzonte. Il tratto più lontano è ancora coperto di impalcature. All'estremità vicina si erge un grande tamburo rotondo di un edificio cinto di colonne su una base rosso scuro, con una bandiera rossa che sventola dal tetto. Sotto, la spiaggia è animata: bagnanti e passeggiatori sparsi minuti sulla sabbia, con il mare grigio-verde che rotola sulla destra. Nuvole torreggianti illuminate dal sole riempiono il cielo su un luminoso pomeriggio di mare, cemento color crema contro l'acqua blu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PYRAMID"] =
    "Due grandi piramidi si ergono pallide nella foschia del deserto, la più vicina che riempie la parte superiore destra dell'inquadratura. Una terza si erge piccola all'orizzonte. La Sfinge si accuccia tra di esse a media distanza. Palme si allineano in una sottile fila lungo la sabbia, e basse mura in rovina e blocchi orlano un avvallamento in primo piano. Un cavaliere in rosso siede su un cammello in basso a destra, e una piccola carovana di cammelli attraversa la sabbia a sinistra con figure che camminano accanto. Tutto è color sabbia, fulvo e osso sotto un cielo bianco e velato. Il cavaliere rosso è l'unico colore netto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_RED_FORT"] =
    "Una fortezza di arenaria rosso intenso sotto attacco: alte mura e bastioni rotondi riempiono l'inquadratura, padiglioni bianchi a cupola si ergono lungo i bastioni, l'erba cresce dalle cornici, e colonne di fumo nero si levano dagli incendi all'interno. I difensori affollano i merli sopra la porta. In primo piano, soldati corazzati con elmi arrotondati premono verso le mura, oltre una catapulta di legno e la sua guarnigione all'estremità sinistra. Il dipinto è greve di pietra rossa e fumo, e i padiglioni bianchi e una striscia di cielo pallido sono l'unico sollievo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SISTINE_CHAPEL"] =
    "Una cerimonia all'interno della cappella, vista in mezzo ai fedeli. La parete di fondo dietro l'altare è coperta dal pavimento al soffitto dall'affresco del Giudizio Universale, un vortice di figure su sfondo blu, e scene dipinte e drappeggi rivestono le pareti laterali sotto alte finestre ad arco. La volta affrescata sfiora appena il margine superiore dell'inquadratura. Il clero in bianco celebra all'altare illuminato dalle candele mentre cardinali in scarlatto riempiono il primo piano e i banchi lungo le pareti. Il loro rosso è il colore più forte nell'interno fioco. La poca luce diurna cade grigia dalle finestre sulle pareti dipinte."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_INTERNATIONAL_SPACE_STATION"] =
    "Una stazione a traliccio è sospesa in orbita contro il nero dello spazio: un lungo traliccio centrale attraversato da coppie di grandi ali solari grigio-azzurre, con la fila di moduli cilindrici bianchi e nodi di attracco raggruppati al centro. Una capsula è ormeggiata all'estremità vicina della fila di moduli, e pannelli radiatori si dispiegano piatti sotto il traliccio. Dietro di essa la Terra si incurva in un azzurro intenso, con vortici di nuvole luminosi sul suo lato notturno. Le stelle sono sparse nel nero in alto. L'immagine è nitida e fotografica: metallo bianco, un pianeta azzurro, e nessuna figura in nessun punto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_OF_LIBERTY"] =
    "Una figura di rame drappeggiata, scolorita in un verde pallido dal tempo, si erge sul suo piedistallo di pietra a sinistra di un porto affollato, il braccio con la torcia levato alto contro un cielo di nuvole spezzate. Oltre di lei avanza a vapore un transatlantico dei primi del Novecento, dallo scafo nero e con due fumaioli rossi e neri che lasciano una scia di fumo di carbone, mentre dei rimorchiatori solcano accanto le acque mosse. Lo skyline di New York si stende basso e velato dalla foschia attraverso l'acqua, sulla destra. La scena è dipinta in grigi e verdi marini, con fumo e nuvole che si mescolano. La statua verde pallido è la forma più nitida in tutto quel fumo e quelle nuvole."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STONEHENGE"] =
    "Un cerchio di grandi pietre erette, sormontate da architravi, si erge su una brughiera scura nella notte, illuminato da un caldo bagliore di fuochi accesi da qualche parte all'interno, come se fosse in corso una cerimonia. Una cometa attraversa il cielo stellato sopra di esso. Pietre isolate sparse si levano dall'erica nel primo piano in ombra, con pochi piccoli fuochi e figure indistinte disseminate per la piana. Tutto è di un blu notte profondo tranne la luce ambrata raccolta presso il monumento."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SYDNEY_OPERA_HOUSE"] =
    "Grandi gusci di tetto bianchi a forma di vela riempiono da vicino la destra dell'inquadratura, sovrapponendosi contro un cielo azzurro brillante. Il vetro e la scura muratura della base dell'edificio si scorgono sotto di essi. Una grande nave da crociera bianca è ormeggiata poco oltre, e uno yacht a motore slanciato fende le acque mosse in primo piano. Attraverso il porto scintillante, le torri di Sydney si ergono lontane sulla sinistra. La giornata è luminosa e limpida. I tetti bianchi e le navi bianche risaltano sull'acqua di un verde-azzurro intenso."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TAJ_MAHAL"] =
    "Un mausoleo di marmo bianco si erge frontalmente in fondo al suo lungo giardino, con la grande cupola centrale che si gonfia sopra il recesso di un portale ad arco. Chioschi minori a cupola siedono ai lati della grande cupola, e una torre di minareto si innalza a ciascun angolo della piattaforma. Il giardino corre dritto verso di esso: uno stretto canale che riflette al centro, fiancheggiato da camminamenti lastricati, file di scuri cipressi e basse aiuole verdi. Poche piccole figure in vesti percorrono i sentieri. Il cielo dietro è un morbido tramonto di pesca e oro, e il marmo prende quel colore, il bianco che sfuma nel crema e nel rosa."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TEMPLE_ARTEMIS"] =
    "Un lungo colonnato di marmo sotto un frontone scolpito corona un'altura sul fondo della scena, con la statua di un cavaliere innalzata davanti ai gradini e cipressi scuri lungo la via d'accesso. Una vasta terrazza davanti è piena di vita: figure in bianche toghe e vesti colorate passeggiano e commerciano, dei venditori sono accovacciati presso ceste sulla sinistra, e donne velate passano vicine nel primo piano a destra. Una colonna rossa incornicia la vista sul margine sinistro, con verdi campagne di valle e un fiume che precipitano in basso lontano. Il sole di mezzogiorno arde sul marmo bianco e sulle stoffe vivaci sotto un cielo azzurro carico di nuvole."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_ZEUS"] =
    "All'interno della sala di un tempio, il dio in trono si eleva fino al soffitto in oro e avorio, barbuto e a torso nudo, con una veste in grembo. Una mano tiene una piccola figura alata della Vittoria protesa sopra la sala, e l'altra impugna un alto scettro. Il suo trono è lavorato in oro contro una parete di un rosso caldo, e file di colonne si succedono lungo entrambi i lati della camera, lasciando le navate laterali nell'ombra. Adoratori in vesti pallide si raccolgono ai piedi della statua, nessuno di loro arriva ai suoi stinchi. Piccole fiamme ardono lungo le pareti. La luce cade da qualche punto in alto, raccogliendosi dorata sulla statua mentre la sala attorno resta in penombra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TERRACOTTA_ARMY"] =
    "File di soldati d'argilla riempiono l'inquadratura da parete a parete, fila dopo fila di guerrieri a grandezza naturale in corazze a giubba sull'attenti. Si allontanano in lunghi corridoi tra muri divisori di terra. Ogni fila sfuma più in profondità nella fossa finché i più lontani non sono che sagome contro un bagliore dorato che irrompe sul fondo della camera. Le figure sono di un grigio e di un bruno terra, le spalle e gli elmi orlati dalla luce calda. L'atmosfera è silenziosa e vasta, un esercito di morti schierato nel buio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UNITED_NATIONS"] =
    "Una veduta a livello stradale della piazza delle Nazioni Unite. La piatta lastra di vetro della torre del Segretariato si innalza a sinistra, sopra la lunga e bassa distesa dell'edificio dell'assemblea. Una fila di pennoni porta le bandiere di molte nazioni lungo l'isolato. La piazza è piena di delegati: uomini e donne in abito da lavoro mescolati ad abiti nazionali, una figura in bianche vesti e copricapo del Golfo al centro della folla, gruppi che si fermano a conversare mentre entrano. Un taxi giallo attende sul bordo del marciapiede a destra, e lo skyline di New York si erge dietro le bandiere. È tardo pomeriggio, con lunghe ombre sul selciato e il sole basso che si riflette sul vetro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UFFIZI"] =
    "Due lunghe ali di galleria si fronteggiano attraverso uno stretto cortile, alte facciate rinascimentali di pietra grigia e intonaco crema con statue erette in nicchie sopra la loggia del piano terra. Il cortile corre in profondità nel quadro verso un'apertura ad arco all'estremità in fondo, e una torre si staglia contro il cielo oltre di essa. Sotto, il cortile è animato da fiorentini in lunghi abiti e cappotti scuri, sculture esposte su piedistalli lungo il centro, e una bancarella con baldacchino rosso allestita nel primo piano a sinistra. Il sole pomeridiano entra obliquo da un lato, illuminando di luce calda i piani superiori mentre la loggia sotto trattiene un'ombra fredda."
