-- Mod-authored world wonder splash painting descriptions, es_ES overlay.
-- Baseline in CivVAccess_WonderDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_MISSING"] = "No hay descripción para esta maravilla."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOTHERLAND_STATUE"] =
    "El juego salió sin una pintura para esta maravilla; no hay imagen que describir."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ALHAMBRA"] =
    "Desde la sombra de una esbelta columna de piedra, un patio de palacio se abre en torno a una larga alberca, el Patio de los Arrayanes de la Alhambra. La alberca se aleja hacia un pórtico con arcadas de piedra de color rosado cuyos arcos se reflejan en el agua quieta. Una torre cuadrada de fortaleza se alza cálida contra el cielo azul al fondo. Bajos setos recortados bordean la orilla del agua, una planta en maceta reposa en el primer plano, y pequeños grupos en largas túnicas conversan de pie a lo largo de los paseos soleados. El sol brillante de la tarde llena el patio, blanco allí donde da sobre el pavimento. Una sombra profunda yace bajo la columnata."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ANGKOR_WAT"] =
    "Un grupo de torres escalonadas de piedra gris con forma de capullos de loto cerrados se eleva al fondo, medio veladas por palmeras bajo un cielo cálido y pálido. El primer plano es una procesión festiva: un elefante gris avanza a grandes pasos entre una densa multitud, con un jinete en el cuello y un asiento con dosel sobre el lomo, resguardado por un alto parasol de color rojo anaranjado. La multitud se agolpa por todos lados en túnicas blancas, azafrán y ciruela; las cabezas van envueltas, los hombros desnudos, y todos los rostros se vuelven hacia el elefante cuando pasa. La escena está bañada de sol y polvo, y la piedra es de un verde grisáceo frío frente a la piel y las telas cálidas de abajo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BIG_BEN"] =
    "Una torre del reloj gótica se alza de noche al final del puente de Westminster, con su reloj de cuatro caras brillando en ámbar cerca de lo alto. Por encima del reloj, la aguja se difumina en un cielo azul profundo. La larga fachada de las Casas del Parlamento de Londres se extiende hacia la izquierda, con sus ventanas y su cantería iluminadas de un cálido dorado por los focos. Torres con pináculos se elevan en su extremo más lejano. El puente cruza el primer plano con una hilera de farolas encendidas. Unos pocos carruajes y figuras se ven pequeños y oscuros sobre la calzada. Toda la escena está pintada en azules nocturnos frente al dorado de las farolas y la piedra iluminada."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BOROBUDUR"] =
    "Una pirámide escalonada de piedra volcánica gris se eleva de la selva como una colina aterrazada, con sus niveles superiores rodeados de pequeñas estupas en forma de campana. Una estupa mayor corona la cima. Palmeras crecen en las terrazas inferiores y el bosque se aprieta en torno a su base. En el primer plano, una fila de monjes con túnicas naranjas y rojas asciende hacia el templo por un sendero umbrío de la selva, y unos pájaros se dispersan por el cielo brumoso de lo alto. La paleta es de un verde grisáceo neblinoso, y las túnicas son la única nota fuerte de color."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BRANDENBURG_GATE"] =
    "Una ancha puerta clásica de arenisca curtida se alza al fondo de una concurrida plaza urbana, montada sobre dobles hileras de pesadas columnas y coronada por la cuadriga, la estatua de bronce del carro de cuatro caballos, que se recorta oscura contra un cielo pálido y nublado. Un ala porticada más baja se prolonga hacia la derecha en dirección a los edificios de piedra que la rodean. La plaza de delante es el Berlín del siglo XIX: carruajes tirados por caballos que ruedan sobre los adoquines, jinetes, y multitudes con largos abrigos oscuros y sombreros de copa, con una farola que se alza a la izquierda. Los colores son grises y marrones sobrios, y la luz es plana y uniforme."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BROADWAY"] =
    "Un distrito de teatros de noche a principios del siglo XX, con la calle mojada de lluvia y reluciente con la luz reflejada. Marquesinas y letreros iluminados se apiñan a ambos lados de la avenida, bombillas blancas y rojas que deletrean los nombres de los espectáculos. Una larga y luminosa fachada de teatro brilla en el centro de la manzana. Multitudes con abrigos y sombreros oscuros llenan las aceras y se derraman a la calle entre unos pocos automóviles antiguos, todos pequeños frente a los altos y oscuros bloques de oficinas que se elevan hacia el cielo nocturno. La paleta es de un azul negruzco profundo quebrado por charcos de cálida luz eléctrica blanca, roja y amarilla."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CN_TOWER"] =
    "Una esbelta aguja de hormigón se eleva en el centro del horizonte de Toronto, ensanchándose en una redondeada cápsula de observación cerca de lo alto y afinándose luego en una aguja de antena. Las nubes de tormenta se abren a su alrededor, y haces de luz solar se vierten por detrás de la torre a través del claro, velando los bloques de oficinas a ambos lados. El primer plano es una autopista hundida que fluye de tráfico, con faros y luces traseras rojas brillando en la penumbra entre terraplenes de hormigón. Toda la escena es de un gris acero y oro. La ciudad está medio sumida en la sombra de la tormenta, medio bañada en la luz que se abre paso."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CHICHEN_ITZA"] =
    "Una pirámide escalonada, El Castillo, se alza en el centro bajo un ardiente cielo anaranjado, con nueve niveles cuadrados que ascienden hacia un pequeño templo en la cima. Una ancha escalinata sube en línea recta por su cara. Un segundo templo escalonado se eleva en el borde izquierdo, y el humo se desplaza ante el sol, que cuelga bajo y rojo. Una plaza abajo está llena de una multitud de mayas, la mayoría de espaldas: hombros desnudos, tocados de plumas, varas y lanzas en alto. Un grupo de guerreros está de pie sobre una plataforma de piedra a la derecha. Todo está impregnado de la luz óxido y ámbar del crepúsculo. La multitud queda en oscura silueta contra la piedra resplandeciente."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CRISTO_REDENTOR"] =
    "Un colosal Cristo de piedra pálida, visto desde atrás y desde arriba, se alza sobre su pedestal en la cima de la montaña con los brazos abiertos de par en par sobre la bahía de abajo. Su espalda con túnica y sus brazos extendidos llenan el plano cercano, la cabeza ligeramente inclinada hacia delante. Más allá y muy abajo, Río de Janeiro se extiende en torno al agua en blancos cúmulos de edificios, con la redondeada joroba del Pan de Azúcar alzándose de la bahía entre islas verdes y barcos anclados. La bruma suaviza la distancia, dejando la ciudad y el mar en pálidos azules y grises, mientras los hombros de la estatua reciben la luz del día."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_COLOSSUS"] =
    "Un gigante de bronce se alza a lo lejos, en la rocosa bocana del puerto, con un brazo en alto, medio disuelto en una bruma dorada. Es más silueta que estatua contra un cielo del color del latón. El primer plano pertenece al mar: una pequeña barca de vela se inclina hacia el espectador bajo una única vela ancha, con dos o tres tripulantes visibles en la popa. Otras velas se dispersan por el puerto. Rocas bajas recorren la orilla del agua a la derecha, y el agua lleva el mismo oro cálido que el cielo. Toda la pintura es de un solo color, luz y bruma de ámbar. El Coloso brilla a través de ella como una figura en un sueño."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOSQUE_OF_DJENNE"] =
    "Un largo muro de tierra de torres y pináculos se extiende por el fondo, de adobe en un rojo pardo intenso. Sus caras se erizan de toron, hileras de vigas de madera que sobresalen de las paredes como espinas. El cielo tras él está cargado de polvo y humo anaranjados, con el sol perdido en la bruma. Todo el primer plano es un día de mercado: toldos y lonas en rojo y blanco, animales entre los puestos, y una densa multitud de túnicas vivas que se mueve entre ellos. El calor y el polvo unifican la escena, y todo está pintado en naranjas, óxidos y pardos."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_EIFFEL_TOWER"] =
    "Un oscuro entramado de hierro de patas y plataformas de vigas llena la parte superior izquierda del encuadre, tan cerca que el borde de la imagen corta su cima. Debajo, la escena es una tarde de la belle epoque sobre la hierba: grupos en largos vestidos blancos y trajes oscuros hacen un picnic sobre un amplio césped verde, con sombrillas, pamelas y cestas repartidas a su alrededor. Una mujer de blanco está de pie en el centro. Tras el césped se desliza el Sena, y la piedra pálida de París se extiende a lo largo de la orilla lejana bajo un suave cielo gris. La paleta es de verdes y grises fríos. Los vestidos blancos atrapan la poca luz que hay."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_FORBIDDEN_PALACE"] =
    "Salones de palacio con tejados de teja dorada que se curvan y paredes de un rojo intenso se alzan al otro lado de un vasto patio empedrado, vistos desde una elevada terraza de mármol en el primer plano. Una oscura estatua de león guardián se agazapa sobre la balaustrada de la terraza a la izquierda, y figuras en túnica están de pie a lo largo de las escaleras. Abajo, en el patio, hileras de soldados están formadas en apretada formación ante el salón central, empequeñecidos por la arquitectura que los rodea. Un sol pálido cuelga en un brumoso cielo de ámbar, y toda la escena está bañada en un oro polvoriento contra el rojo de las paredes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GLOBE_THEATER"] =
    "Un redondo teatro de madera visto desde su propio escenario en plena función. Tres pisos de balconadas con galerías se curvan alrededor del patio central, con cada baranda repleta de espectadores. En el suelo abierto de abajo, los groundlings, el público de pie del patio, se apretujan, un pálido mar de rostros. En el escenario, un actor con un oscuro jubón representa una escena ante dos mujeres en largos vestidos, una de ellas gesticulando con el brazo extendido. El techo de lona pintada se proyecta hacia dentro en la parte superior derecha sobre un poste tallado. Una suave luz diurna cae desde el cielo abierto sobre el patio. La madera es de un cálido crema y pardo, y la multitud está esbozada en tonos pálidos en torno a las figuras más nítidas del escenario."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_FIREWALL"] =
    "Una escena digital abstracta sin edificio alguno, un oscuro ciberespacio representado en verdes y negro. Anchas superficies curvas barren el encuadre como murallas de datos, con sus caras alicatadas de relucientes dígitos binarios verdes, y trazos luminosos las recorren como el tráfico en una autopista de noche. Pantallas y rejillas espectrales flotan en la penumbra de arriba, sugiriendo circuitos y vigilancia. Toda la imagen tiene el aspecto del mundo interior de un ordenador, luz verde de fósforo sobre negro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIBRARY"] =
    "Un monumental salón clásico da a una plaza soleada, con altos estandartes rojos colgados entre las columnas de su larga columnata. Un friso tallado discurre por encima de las columnas, y amplios escalones bajan hasta el pavimento. La plaza se ve desde un pórtico en sombra en el primer plano: una columna se eleva a la izquierda, una esfinge de piedra reposa sobre un plinto a la derecha, y una cúpula blanca asoma a lo lejos más allá. Eruditos y ciudadanos en togas y túnicas de colores se reúnen en los escalones y por la plaza, la mayoría de pie en grupos de dos y tres conversando, mientras una figura se sienta sola con un pergamino. La piedra es de un cálido crema bajo la luz del sol, bajo un cielo azul vetado de nubes, y los estandartes son el rojo más intenso de la escena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIGHTHOUSE"] =
    "Una alta torre pálida de pisos escalonados se alza a lo lejos a la derecha, iluminada por un claro en la tormenta, con su faro brillando en lo alto. El resto de la imagen es mar embravecido: una hilera de antiguas galeras bajo velas cuadradas a rayas rojas y blancas avanza penosamente entre pesadas marejadas de un gris verdoso hacia la luz, con las proas curvadas en alto. La espuma estalla blanca contra los cascos. Oscuros nubarrones de tormenta presionan sobre toda la escena, y el cielo solo se abre en torno a la torre, como si los barcos corrieran hacia ella. Las velas portan el único color cálido en una pintura de pizarra, espuma y lluvia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_WALL"] =
    "Una ancha muralla de piedra corre desde el fondo del encuadre recto hacia arriba y por encima de las montañas, con sus parapetos almenados trepando por las crestas hasta que la muralla se reduce a un hilo en los picos más lejanos. Una torre de vigilancia cuadrada de dos pisos, con ventanas en arco y un pequeño pabellón techado en lo alto, se alza en la primera elevación. El trazado de la muralla se curva a través de ella. Las montañas son plegadas y verdes, con laderas de maleza que caen en la bruma, valle tras valle. No se ve figura alguna en parte alguna de la muralla. La luz es fría y clara, piedra gris contra un verde intenso bajo un cielo pálido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HAGIA_SOPHIA"] =
    "Una gran basílica abovedada corona un panorama urbano a la hora dorada, con su ancha cúpula central elevándose desde un cúmulo de muros con contrafuertes y medias cúpulas. Cuatro esbeltos minaretes se alzan en las esquinas, y el edificio aparece dibujado como la mezquita en que más tarde se convirtió. A su alrededor, los tejados de Estambul descienden ladera abajo en tonos pardos y grises, salpicados de árboles, cúpulas menores y torres lejanas que se diluyen en la bruma. Un destello de agua y unas colinas bajas cierran la distancia a la izquierda. Todo se extiende bajo un cálido cielo ámbar, y la silueta de la cúpula se recorta en oro oscuro contra la luz."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HANGING_GARDEN"] =
    "Un patio ajardinado se abre dentro de unos muros de arcos de cálida arenisca. Las palmeras se alzan sobre los paseos, y la vegetación se derrama sobre cada arco y repisa. Figuras con túnicas pasean y conversan en grupos de dos y tres a lo largo de los senderos sombreados, entre parterres y arbolillos. A través del arco central y por encima del muro, una ciudad palaciega blanca trepa por una colina en gradas escalonadas, reluciendo en la distancia como la corona del jardín. Todo queda bajo un sol brillante, con el follaje verde intenso recortado contra la piedra dorada y un cielo pálido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HIMEJI_CASTLE"] =
    "Una torre del homenaje blanca se alza sobre una colina boscosa en lo alto del encuadre, grada tras grada de muros pálidos bajo tejados grises curvados. Torretas blancas más pequeñas se agrupan más abajo entre los árboles. El camino que sube hasta ella atraviesa una aldea de oscuros tejados de teja, y una puerta de marco rojo cruza la vía en el plano medio. Samuráis a caballo cabalgan hacia ella por el primer plano, con altos estandartes rojos erguidos a sus espaldas. Soldados de a pie armados aguardan junto a las casas a la derecha. El día es suave y nublado, y la escena se compone toda de verdes y grises en torno a la torre blanca. Los estandartes son el rojo más nítido de la escena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HUBBLE"] =
    "Un largo cilindro plateado envuelto en paneles de lámina flota en órbita, con la puerta abatible de su abertura abierta en el extremo cercano para dejar al descubierto la boca oscura de la óptica. Planos paneles solares en marcos de oro cobrizo se extienden a sus costados, y un astronauta con traje espacial trabaja en su flanco, pequeño junto al instrumento. Parte de una nave acoplada asoma por el extremo inferior derecho del encuadre. Detrás de todo, la Tierra llena la imagen, una curva de océano azul y nube blanca que se desvanece hacia el negro del espacio. La paleta es plata y oro contra el azul de la Tierra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_KREMLIN"] =
    "Cae la nieve sobre la Plaza Roja, donde un muro de fortaleza de ladrillo rojo oscuro recorre la derecha bajo un pesado cielo gris de invierno. Una bandera roja ondea sobre el rechoncho bloque escalonado del Mausoleo de Lenin, adosado al muro, y más allá una torre alta se eleva hacia la bruma, con su aguja en forma de tienda empinada. Multitudes con largos abrigos oscuros y gorros de piel cruzan la plaza nevada en una lenta cola, figuras solitarias avanzando con esfuerzo por el primer plano, de espaldas al espectador. La pintura es casi monocroma, blanco de nieve y gris carbón, con el ladrillo y la bandera como sus únicos rojos."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LEANING_TOWER"] =
    "Un campanario redondo de mármol blanco se alza desde un césped verde, anillado piso tras piso de arquerías de mármol abiertas e inclinándose de forma inconfundible hacia la derecha. Se recorta brillante contra un oscuro cielo de tormenta. El pálido costado de la catedral de Pisa queda en el borde derecho del encuadre, y edificios más bajos de la ciudad en ocre cierran el césped por la izquierda. Vecinos y monjes con largas túnicas pardas y rojas cruzan el césped en sueltas procesiones, pequeños bajo la torre. La luz es teatral: un claro entre las nubes ilumina como un foco el mármol blanco mientras el cielo del fondo permanece casi negro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LOUVRE"] =
    "Un palacio de piedra gris se extiende a lo largo del fondo, con un alto pabellón central de ornamento tallado y empinados tejados de pizarra a la mansarda, y alas que se prolongan a ambos lados. Los artistas lo muestran en sus días de palacio real, mucho antes de la pirámide de vidrio del museo moderno. Delante se extienden jardines formales: llanos céspedes cruzados por senderos de grava, árboles jóvenes y una pequeña fuente que arroja agua a la izquierda. Paseantes con vestimenta del siglo XIX salpican las avenidas, mujeres con largos vestidos blancos y hombres con abrigos oscuros y sombreros de copa. Una pareja se detiene junta a la derecha. El día es suave y aperlado. Todo es piedra gris y verde apagado bajo un cielo pálido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MACHU_PICHU"] =
    "Una ciudad de piedra se asienta en una alta ensilladura de montaña, con terrazas de cultivo que escalonan la ladera hasta grupos de edificios a dos aguas bajo tejados de paja. Detrás, el escarpado pico del Huayna Picchu se eleva hacia las nubes. La niebla cuelga sobre las cordilleras circundantes, y el valle cae en sombra abajo. Por el sendero del primer plano, una pequeña comitiva con llamas de carga asciende con esfuerzo hacia las puertas de la ciudad, diminuta frente a las terrazas. La luz entra en pálidos haces a través del temporal, recortando la cálida piedra parda del verde y el gris de los Andes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MAUSOLEUM_HALICARNASSUS"] =
    "Un macizo podio cuadrado de mármol blanco, ceñido con frisos esculpidos, se eleva hacia un anillo de columnas en lo alto del encuadre. Domina una plaza donde se alzan estatuas sobre altos pilares, entre ellas una figura armada y un jinete. Oscuros cipreses están plantados entre los pavimentos. Figuras con túnicas blancas y rojas se congregan abajo, empequeñecidas por el monumento. El día es luminoso y despejado. El mármol blanco y los amontonados nubarrones blancos se recortan contra un cielo azul intenso."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NEUSCHWANSTEIN"] =
    "Una pálida aparición de castillo se alza sobre una cresta boscosa, con muros blancos y torres agrupadas medio disueltos en la nieve que cae, en el extremo superior izquierdo del encuadre. El primer plano es el camino que sube hasta él: un oscuro carruaje cerrado aguarda en la curva mientras los jinetes desfilan ladera arriba, revolviendo la nieve de la senda. Abetos espolvoreados de nieve bordean el camino y se cierran sobre el valle de abajo. La pintura es gris y blanca de invierno en toda su extensión. Los jinetes y el carruaje son las únicas formas oscuras sobre ella."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NOTRE_DAME"] =
    "Una catedral gótica se eleva sobre el París medieval, vista desde lo alto, con sus dos torres cuadradas gemelas, su aguja central y su larga nave reforzada por arbotantes alzándose muy por encima de todos los tejados de alrededor. La ciudad se apretuja hasta sus muros en un denso entramado de casas de tejado a dos aguas y chimeneas humeantes, y el Sena describe una curva por el primer plano pasando junto a muelles y pequeñas barcas. El cielo es pesado y gris, pero haces de luz solar rompen entre las nubes y caen directamente sobre la catedral, iluminando su piedra de dorado mientras la ciudad permanece en sombra pizarra. El horizonte se desvanece plano y pálido más allá de los tejados."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ORACLE"] =
    "Un templo circular de columnas bajo una cúpula de piedra, un tholos, se alza sobre un peñasco marino al final de un promontorio rocoso, y un arco natural se abre a través del acantilado bajo él. Los artistas situaron el santuario en la costa en lugar de en la ladera de la montaña de Delfos. Un sendero serpentea hacia él pasando junto a charcas de marea y rocas erguidas. En el primer plano, peregrinos con túnicas rojas, azules y blancas avanzan por el camino en pequeños grupos, enmarcados por oscuros pinos que se inclinan desde ambos lados. Es una fresca caída de la tarde, con un cielo pálido a la luz de la luna y un mar de un verde grisáceo en torno a la cálida piedra del santuario."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PARTHENON"] =
    "Un largo templo dórico se alza entero a lo ancho de la parte superior del encuadre, con su columnata sosteniendo un frontón esculpido y pintado. El mármol es de un cálido dorado bajo un cielo de nubes grises que ruedan. Anchos escalones descienden desde él entre macizos de bajos arbustos verdes, con estatuas de bronce alzadas sobre plintos a la izquierda. Por los escalones baja una procesión de griegos con capas carmesí, y en el centro un único hoplita encara al espectador con un yelmo de cresta y un escudo redondo en el brazo. Los rojos de las capas arden contra la piedra, y la luz tiene el brillo pesado de un día a punto de tormenta."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PENTAGON"] =
    "Una vista aérea del edificio sede de cinco lados, con sus anillos pentagonales concéntricos de hormigón pálido y techo oscuro escalonándose hacia dentro hasta un patio verde en el centro. Carreteras y aparcamientos rodean el edificio, con céspedes y árboles teñidos de otoño más allá. El Potomac discurre por detrás de él, cruzado por puentes. En la orilla opuesta la ciudad capital yace entre la bruma, con el blanco obelisco del Monumento a Washington y la cúpula del Capitolio pequeños en el horizonte. El día es apagado y gris; nada en la escena destaca salvo la forma del edificio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PETRA"] =
    "El espectador se encuentra dentro del Siq, el estrecho desfiladero de acceso, entre paredes de roca de un rojo rosado que se alzan en sombra a ambos lados del encuadre. A través de la brecha, iluminada por el sol pleno, se alza Al-Khazneh, el Tesoro, una fachada tallada directamente en el acantilado. Sus dos pisos de columnas y frontones clásicos se elevan en arenisca rosa, con un pabellón circular en el centro del nivel superior. Viajeros se dirigen hacia él por el suelo arenoso del desfiladero: dos jinetes se balancean sobre camellos en el primer plano cercano, y figuras con túnica caminan detrás. La pintura es toda de cálidos rojos y pardos en sombra, con el frente tallado resplandeciendo al final del pasaje oscuro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PORCELAIN_TOWER"] =
    "Una alta pagoda se eleva sobre un jardín de templo, piso tras piso de oscuros aleros curvos sobre un cuerpo esbelto. Se alza por encima de los tejados de tejas de los pabellones en su base. El jardín se extiende en el primer plano en torno a un estanque inmóvil: pinos recortados, sauces, faroles de piedra y la estatua tallada de un león sobre un pedestal en el borde izquierdo. Figuras con túnica pasean por los senderos de grava en grupos de dos y de tres, y colinas boscosas se alzan brumosas detrás de la Torre de Porcelana. La escena es serena y verde, con una suave luz diurna sobre el agua y la pagoda recortándose oscura contra un cielo pálido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PRORA_RESORT"] =
    "Un bloque monolítico de complejo turístico se prolonga a lo largo de la costa aparentemente sin fin. Su pálida fachada repite una y otra vez las mismas hileras de ventanas, extendiéndose playa abajo hasta desvanecerse hacia el horizonte. El tramo más lejano sigue cubierto de andamios. En el extremo cercano se alza un gran tambor de un edificio circular ceñido de columnas sobre una base de rojo oscuro, con una bandera roja ondeando en su techo. Abajo, la playa está animada: bañistas y paseantes pequeños y dispersos sobre la arena, con el mar de un verde grisáceo rompiendo a la derecha. Imponentes nubes iluminadas por el sol llenan el cielo sobre una luminosa tarde de costa, hormigón color crema contra agua azul."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PYRAMID"] =
    "Dos grandes pirámides se alzan pálidas en la bruma del desierto, la más cercana llenando la parte superior derecha del encuadre. Una tercera se yergue pequeña en el horizonte. La Esfinge se agazapa entre ellas en la distancia media. Unas palmeras forman una fina hilera a lo largo de la arena, y bajos muros en ruinas y bloques bordean una hondonada en el primer plano. Un jinete de rojo va sentado sobre un camello en la parte inferior derecha, y una pequeña caravana de camellos cruza la arena a la izquierda con figuras caminando junto a ella. Todo es de color arena, tostado y hueso bajo un brumoso cielo blanco. El jinete de rojo es el único color nítido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_RED_FORT"] =
    "Una fortaleza de arenisca de un rojo intenso bajo ataque: altos muros y bastiones redondos llenan el encuadre, blancos pabellones abovedados se alzan a lo largo de las almenas, hierba crece en las repisas, y columnas de humo negro suben de los incendios en su interior. Los defensores se apiñan en las almenas sobre la puerta. En el primer plano, soldados acorazados con yelmos redondeados avanzan hacia los muros, pasando junto a una catapulta de madera y su dotación en el borde izquierdo. La pintura es densa en piedra roja y humo, y los blancos pabellones y una franja de cielo pálido son el único alivio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SISTINE_CHAPEL"] =
    "Una ceremonia dentro de la capilla, vista desde entre la congregación. El muro del fondo tras el altar está cubierto del suelo al techo por el fresco del Juicio Final, un remolino de figuras sobre azul, y escenas pintadas y colgaduras recubren los muros laterales bajo altos ventanales de arco. La bóveda al fresco apenas asoma en la parte superior del encuadre. El clero de blanco oficia ante el altar iluminado por velas mientras cardenales de escarlata llenan el primer plano y los bancos a lo largo de los muros. Su rojo es el color más intenso del penumbroso interior. La poca luz diurna que hay cae gris desde los ventanales sobre los muros pintados."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_INTERNATIONAL_SPACE_STATION"] =
    "Una estación reticulada pende en órbita contra el negro del espacio: una larga viga central cruzada por pares de grandes alas solares de azul grisáceo, con la hilera de módulos cilíndricos blancos y nodos de acoplamiento agrupados en su centro. Una cápsula está amarrada en el extremo cercano de la cadena de módulos, y unos paneles radiadores se despliegan planos bajo la viga. Detrás, la Tierra se curva hacia la lejanía en azul profundo, con remolinos de nube brillando en su cara nocturna. Las estrellas se dispersan en el negro de arriba. La imagen es limpia y fotográfica: metal blanco, un planeta azul y ninguna figura en parte alguna."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_OF_LIBERTY"] =
    "Una figura de cobre envuelta en una túnica, desgastada hasta un verde pálido, se alza sobre su pedestal de piedra a la izquierda de un puerto bullicioso, con el brazo de la antorcha alzado en alto contra un cielo de nubes rotas. Más allá de ella navega un transatlántico de principios del siglo XX, de casco negro y dos chimeneas rojas y negras que dejan una estela de humo de carbón, mientras los remolcadores baten el oleaje a su lado. La línea de rascacielos de Nueva York se extiende baja y brumosa al otro lado del agua, a la derecha. La escena está pintada en grises y verdes marinos, con el humo y la nube mezclándose. La estatua verde pálido es la forma más nítida en todo el humo y la nube."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STONEHENGE"] =
    "Un círculo de grandes piedras erguidas, coronadas por dinteles, se alza sobre un páramo oscuro de noche, resplandeciendo cálido por las hogueras encendidas en algún lugar de su interior, como si una ceremonia estuviera en curso. Un cometa cruza fugaz el cielo estrellado por encima. Piedras dispersas más alejadas surgen del brezal en el primer plano sombrío, con unas pocas hogueras pequeñas y figuras tenues salpicadas por la llanura. Todo es de un azul de noche profunda salvo la luz ámbar acumulada en el monumento."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SYDNEY_OPERA_HOUSE"] =
    "Grandes conchas blancas de tejado en forma de vela llenan la parte derecha del encuadre vistas de cerca, solapándose contra un cielo de azul intenso. El vidrio y la oscura cantería de la base del edificio se ven por debajo de ellas. Un gran crucero blanco yace atracado justo más allá, y un esbelto yate a motor surca el oleaje del primer plano. Al otro lado del puerto resplandeciente, las torres de Sídney se alzan a lo lejos a la izquierda. El día es luminoso y despejado. Los tejados blancos y los barcos blancos destacan sobre el agua de un verde azulado profundo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TAJ_MAHAL"] =
    "Un mausoleo de mármol blanco se alza de frente al fondo de su largo jardín, con su gran cúpula central hinchándose sobre un nicho de portal en arco. Quioscos menores abovedados se asientan a uno y otro lado de la gran cúpula, y una torre de minarete se eleva en cada esquina de la plataforma. El jardín discurre recto hacia él: un estrecho canal reflectante por el centro flanqueado de paseos pavimentados, hileras de cipreses oscuros y bajos parterres verdes. Unas pocas figuras pequeñas en túnicas recorren los senderos. El cielo al fondo es un suave atardecer de melocotón y oro, y el mármol toma el color, con el blanco virando a crema y rosa."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TEMPLE_ARTEMIS"] =
    "Una larga columnata de mármol bajo un frontón esculpido corona una elevación al fondo de la escena, con la estatua de un jinete alzada ante las escaleras y cipreses erguidos oscuros a lo largo del acceso. Una amplia terraza al frente rebosa de vida: figuras en togas blancas y túnicas de colores pasean y comercian, vendedores se acuclillan junto a cestas a la izquierda, y mujeres con velo pasan cerca en el primer plano derecho. Una columna roja enmarca la vista en el borde izquierdo, con verde campiña de valle y un río que cae a lo lejos por debajo. El sol del mediodía abrasa sobre el mármol blanco y la tela brillante bajo un cielo azul cargado de nubes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_ZEUS"] =
    "Dentro de la sala de un templo, el dios entronizado se eleva hasta el techo en oro y marfil, barbudo y con el pecho desnudo, con una túnica sobre el regazo. Una mano sostiene una pequeña figura alada de la Victoria extendida sobre la sala, y la otra empuña un alto cetro. Su trono está labrado en oro contra un muro de rojo cálido, e hileras de columnas avanzan por ambos lados de la cámara, dejando las naves laterales en sombra. Fieles en túnicas pálidas se congregan a los pies de la estatua, sin que ninguno alcance sus espinillas. Pequeñas llamas arden a lo largo de los muros. La luz cae desde algún punto en lo alto, acumulándose dorada sobre la estatua mientras la sala que la rodea permanece en penumbra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TERRACOTTA_ARMY"] =
    "Filas de soldados de arcilla llenan el encuadre de pared a pared, hilera tras hilera de guerreros de tamaño natural con cotas acorazadas firmes en posición de atención. Se alejan en largos corredores entre muros divisorios de tierra. Cada fila se desvanece más adentro en el foso hasta que las más lejanas no son más que siluetas contra un resplandor dorado que entra al fondo de la cámara. Las figuras son de pardo terroso y gris, con los hombros y los cascos perfilados por la luz cálida. El ambiente es silencioso y vasto, un ejército de los muertos formado en la oscuridad."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UNITED_NATIONS"] =
    "Una vista a pie de calle de la Plaza de las Naciones Unidas. La plana losa de vidrio de la torre de la Secretaría se alza a la izquierda, por encima del largo y bajo trazado del edificio de la asamblea. Una hilera de astas porta las banderas de muchas naciones a lo largo de la manzana. La plaza está llena de delegados: hombres y mujeres en trajes de negocios mezclados con atuendos nacionales, una figura con túnica y tocado blancos del Golfo en el centro de la multitud, grupos que se detienen a conversar de camino al interior. Un taxi amarillo espera junto al bordillo a la derecha, y la línea de rascacielos de Nueva York se alza tras las banderas. Es media tarde, con largas sombras sobre el pavimento y el sol bajo prendiendo en el vidrio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UFFIZI"] =
    "Dos largas alas de galería se enfrentan a través de un patio estrecho, altas fachadas renacentistas de piedra gris y enlucido crema con estatuas erguidas en nichos sobre la logia de la planta baja. El patio se adentra en profundidad en el cuadro hacia una abertura en arco al fondo, y una torre se recorta contra el cielo más allá. Abajo, el patio bulle de florentinos en largos vestidos y oscuros abrigos, esculturas expuestas sobre pedestales por el centro, y un puesto con toldo rojo montado en el primer plano izquierdo. El sol de la tarde entra oblicuo por un lado, iluminando cálidos los pisos superiores mientras la logia de abajo guarda una sombra fría."
