-- Mod-authored world wonder splash painting descriptions, pt_BR overlay.
-- Baseline in CivVAccess_WonderDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_MISSING"] = "Nenhuma descrição para esta maravilha."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOTHERLAND_STATUE"] =
    "O jogo foi distribuído sem uma pintura para esta maravilha; não há imagem para descrever."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ALHAMBRA"] =
    "Sob a sombra de uma esguia coluna de pedra, um pátio de palácio se abre em torno de um longo espelho d'água, o Pátio dos Arrayanes da Alhambra. O espelho d'água corre ao fundo até um pórtico arcado de pedra cor-de-rosa cujos arcos se refletem na água parada. Uma torre quadrada de fortaleza se ergue aquecida contra o céu azul atrás. Baixas sebes aparadas margeiam a beira da água, uma planta envasada fica no primeiro plano, e pequenos grupos em longas túnicas conversam ao longo das passagens ensolaradas. O sol vívido da tarde enche o pátio, branco onde incide sobre o piso. Sombra profunda repousa sob a colunata."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ANGKOR_WAT"] =
    "Um agrupamento de torres escalonadas de pedra cinza em forma de botões de lótus fechados se ergue ao fundo, meio encoberto por palmeiras sob um céu quente e pálido. O primeiro plano é uma procissão festiva: um elefante cinza avança por uma densa multidão, com um condutor em seu pescoço e um assento sob dossel em suas costas sombreado por um alto guarda-sol vermelho-alaranjado. A multidão se comprime de todos os lados em túnicas brancas, açafrão e ameixa; as cabeças estão enroladas, os ombros nus, e cada rosto se volta para o elefante ao passar. A cena está banhada de sol e poeirenta, e a pedra é de um cinza-esverdeado frio contra a pele e os tecidos quentes abaixo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BIG_BEN"] =
    "Uma torre de relógio gótica se ergue à noite no extremo da Ponte de Westminster, seu relógio de quatro faces brilhando em âmbar perto do topo. Acima do relógio, a flecha se esvai em um céu de azul intenso. A longa fachada do Parlamento de Londres se estende ao longe para a esquerda, janelas e cantaria iluminadas em um dourado quente pelos holofotes. Torres com pináculos se erguem na extremidade distante. A ponte cruza o primeiro plano com uma fileira de postes de luz acesos. Algumas carruagens e figuras aparecem pequenas e escuras na pista. Toda a cena é pintada em azuis noturnos contra o dourado dos lampiões e da pedra iluminada."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BOROBUDUR"] =
    "Uma pirâmide escalonada de pedra vulcânica cinza se ergue da selva como uma colina em terraços, suas fileiras superiores cingidas por pequenas estupas em forma de sino. Uma estupa maior coroa o cume. Palmeiras crescem dos terraços inferiores e a floresta se comprime ao redor da sua base. No primeiro plano, uma fila de monges em túnicas alaranjadas e vermelhas sobe rumo ao templo por um caminho sombreado da selva, e aves se dispersam pelo céu enevoado acima. A paleta é de um cinza-esverdeado nebuloso, e as túnicas são a única nota forte de cor."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BRANDENBURG_GATE"] =
    "Um amplo portal clássico de arenito intemperizado se estende ao fundo de uma movimentada praça da cidade, erguido sobre fileiras emparelhadas de colunas pesadas e coroado pela quadriga, a estátua de bronze da carruagem de quatro cavalos, que se recorta escura contra um céu pálido e encoberto. Uma ala mais baixa com colunata corre para a direita rumo aos edifícios de pedra ao redor. A praça à frente é a Berlim do século XIX: carruagens puxadas a cavalo rolando sobre o calçamento, cavaleiros, e multidões em longos casacos escuros e cartolas, com um poste de luz se erguendo à esquerda. As cores são cinzas e marrons sóbrios, e a luz é plana e uniforme."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BROADWAY"] =
    "Um distrito teatral à noite no início do século XX, a rua molhada de chuva e reluzente de luz refletida. Marquises e letreiros iluminados se aglomeram dos dois lados da avenida, lâmpadas brancas e vermelhas soletrando nomes de espetáculos. Uma longa fachada de teatro vívida brilha no centro do quarteirão. Multidões em casacos e chapéus escuros enchem as calçadas e transbordam para a rua entre alguns automóveis antigos, todos pequenos diante dos altos blocos escuros de escritórios que se erguem ao céu noturno. A paleta é de um azul-preto profundo rompido por poças de luz elétrica quente, branca, vermelha e amarela."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CN_TOWER"] =
    "Uma esguia agulha de concreto se ergue ao centro do horizonte de Toronto, alargando-se em um arredondado mirante de observação perto do topo e afilando-se em uma flecha de antena. Nuvens de tempestade se rompem ao seu redor, e feixes de luz solar despencam atrás da torre pela fresta, embaçando os blocos de escritórios de cada lado. O primeiro plano é uma via expressa rebaixada repleta de tráfego, faróis e lanternas vermelhas brilhando na penumbra entre taludes de concreto. Toda a cena é de um cinza de aço e dourado. A cidade está metade na sombra da tempestade, metade na luz que rompe."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CHICHEN_ITZA"] =
    "Uma pirâmide escalonada, El Castillo, ergue-se ao centro sob um céu laranja em brasa, nove patamares quadrados subindo até um pequeno templo no cume. Uma larga escadaria sobe reta por sua face. Um segundo templo escalonado se ergue na borda esquerda, e a fumaça vagueia diante do sol onde ele pende baixo e vermelho. Uma praça abaixo está repleta de uma multidão de maias, a maioria deles de costas: ombros nus, cocares de penas, cajados e lanças erguidos. Um grupo de guerreiros está sobre uma plataforma de pedra à direita. Tudo está imerso na luz de ferrugem e âmbar do entardecer. A multidão cai em silhueta escura contra a pedra reluzente."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CRISTO_REDENTOR"] =
    "Um colossal Cristo de pedra pálida, visto de trás e de cima, está sobre seu pedestal no alto da montanha com os braços estendidos sobre a baía abaixo. Suas costas cobertas por uma túnica e seus braços abertos enchem o quadro próximo, a cabeça curvada ligeiramente para a frente. Além e bem abaixo, o Rio de Janeiro se espalha em torno da água em alvas manchas de edifícios, com o arredondado dorso do Pão de Açúcar erguendo-se da baía entre ilhas verdes e navios ancorados. A névoa suaviza a distância, deixando a cidade e o mar em pálidos azuis e cinzas, enquanto os ombros da estátua captam a luz do dia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_COLOSSUS"] =
    "Um gigante de bronze se ergue ao longe na rochosa boca do porto, um braço levantado, meio dissolvido em uma bruma dourada. Contra um céu da cor do latão, ele é mais silhueta do que estátua. O primeiro plano pertence ao mar: um pequeno barco a vela inclina-se em direção ao observador sob uma única vela larga, dois ou três tripulantes visíveis na popa. Outras velas estão espalhadas pelo porto. Rochas baixas correm ao longo da linha d'água à direita, e a água carrega o mesmo ouro quente do céu. Toda a pintura é de uma só cor, luz e bruma de âmbar. O Colosso reluz através dela como uma figura em um sonho."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOSQUE_OF_DJENNE"] =
    "Um longo muro de terra de torres e pináculos se estende pelo fundo, em tijolo de barro de um vermelho-marrom profundo. Suas faces eriçam-se de toron, fileiras de vigas de madeira saindo das paredes como espinhos. O céu atrás dele está denso de poeira e fumaça alaranjadas, o sol perdido na bruma. Todo o primeiro plano é um dia de mercado: toldos e coberturas em vermelho e branco, animais entre as bancas, e uma densa multidão em vestes vivas movendo-se entre elas. O calor e a poeira unificam a cena, e tudo é pintado em laranjas, ferrugens e marrons."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_EIFFEL_TOWER"] =
    "Uma escura treliça de ferro de pés e plataformas em vigamento preenche o canto superior esquerdo do quadro, tão perto que o topo é cortado pela borda da imagem. Abaixo dela a cena é uma tarde da belle epoque sobre a relva: grupos em longos vestidos brancos e ternos escuros fazem piquenique em um amplo gramado verde, com sombrinhas, chapéus de sol e cestas espalhados ao redor. Uma mulher de branco está no centro. Atrás do gramado o Sena desliza, e a pedra pálida de Paris se estende ao longo da margem distante sob um suave céu cinzento. A paleta é de verdes e cinzas frios. Os vestidos brancos captam a pouca luz que há."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_FORBIDDEN_PALACE"] =
    "Salões de palácio com amplos telhados de telhas douradas e paredes de um vermelho profundo erguem-se ao longo de um vasto pátio pavimentado, vistos de um terraço de mármore elevado no primeiro plano. Uma escura estátua de leão guardião agacha-se sobre a balaustrada do terraço à esquerda, e figuras em vestes longas estão ao longo das escadarias. Lá embaixo no pátio, fileiras de soldados estão dispostas em formação cerrada diante do salão central, diminuídas pela arquitetura ao redor. Um sol pálido paira em um céu de âmbar enevoado, e toda a cena é banhada em ouro empoeirado contra o vermelho das paredes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GLOBE_THEATER"] =
    "Um teatro circular de madeira visto de seu próprio palco em plena apresentação. Três níveis de balcões em galeria curvam-se ao redor do pátio central, cada parapeito apinhado de espectadores. No piso aberto abaixo, os espectadores de pé comprimem-se uns contra os outros, um pálido mar de rostos. No palco, um ator em um gibão escuro representa uma cena diante de duas mulheres em longos vestidos, uma delas gesticulando com o braço estendido. O teto de lona pintado projeta-se para dentro no canto superior direito sobre um poste entalhado. Uma suave luz do dia cai do céu aberto acima do pátio. A madeira é de um creme e marrom quentes, e a multidão está esboçada em tons pálidos ao redor das figuras mais nítidas no palco."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_FIREWALL"] =
    "Uma cena digital abstrata sem nenhum edifício, um ciberespaço escuro renderizado em verdes e preto. Amplas superfícies curvas varrem o quadro como muralhas de dados, suas faces revestidas de dígitos binários verdes luminosos, e traços luminosos riscam ao longo delas como o tráfego em uma rodovia à noite. Telas e grades fantasmagóricas pairam na penumbra acima, sugerindo circuitos e vigilância. Toda a imagem tem o aspecto do mundo interior de um computador, luz verde de fósforo sobre o preto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIBRARY"] =
    "Um monumental salão clássico dá frente para uma praça iluminada pelo sol, com altos estandartes vermelhos pendurados entre as colunas de sua longa colunata. Um friso entalhado corre acima das colunas, e largos degraus descem até o calçamento. A praça é vista de um pórtico sombreado no primeiro plano: uma coluna se ergue à esquerda, uma esfinge de pedra repousa sobre um plinto à direita, e uma cúpula branca surge ao longe além. Eruditos e cidadãos em togas e vestes coloridas reúnem-se nos degraus e por toda a praça, a maioria de pé em duplas e trios em conversa, enquanto uma figura está sentada sozinha com um rolo de pergaminho. A pedra é de um creme quente sob a luz do sol em um céu azul riscado de nuvens, e os estandartes são o vermelho mais forte da cena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIGHTHOUSE"] =
    "Uma alta torre pálida em níveis sobrepostos ergue-se ao longe à direita, iluminada por uma brecha na tempestade, seu farol brilhando no topo. O resto da imagem é mar revolto: uma fila de antigas galés sob velas quadradas listradas de vermelho e branco labuta através de pesadas vagas cinza-esverdeadas em direção à luz, as proas curvadas para o alto. A espuma estoura branca contra os cascos. Escuras nuvens de tempestade pressionam sobre toda a cena, e o céu se abre apenas em torno da torre, como se os navios estivessem correndo para ela. As velas carregam a única cor quente em uma pintura de ardósia, espuma e chuva."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_WALL"] =
    "Uma larga muralha de pedra corre da base do quadro reto para cima e por sobre as montanhas, seus parapeitos ameiados subindo pelas cristas até a muralha encolher a um fio nos picos mais distantes. Uma torre de vigia quadrada de dois andares, com janelas em arco e um pequeno pavilhão coberto no topo, ergue-se na primeira elevação. O traçado da muralha dobra-se através dela. As montanhas são dobradas e verdes, encostas cobertas de mato caindo em vale após vale na bruma. Nenhuma figura aparece em ponto algum da muralha. A luz é fria e clara, pedra cinzenta contra um verde profundo sob um céu pálido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HAGIA_SOPHIA"] =
    "Uma grande basílica em cúpula coroa o panorama de uma cidade na hora dourada, sua ampla cúpula central erguendo-se de um amontoado de paredes contrafortadas e meias-cúpulas. Quatro minaretes esguios se postam nos cantos, o edifício retratado como a mesquita em que mais tarde se converteu. Ao seu redor, os telhados de Istambul descem pela encosta em tons de bege e cinza, interrompidos por árvores, cúpulas menores e torres distantes que se dissolvem na bruma. Um reflexo de água e colinas baixas fecham a distância à esquerda. Tudo repousa sob um céu de âmbar quente, e a silhueta da cúpula é de ouro escuro contra a luz."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HANGING_GARDEN"] =
    "Um pátio ajardinado se estende dentro de paredes de arcos de arenito quente. Palmeiras se erguem sobre as passagens, e a vegetação transborda por cada arco e saliência. Figuras em túnicas passeiam e conversam em duplas e trios pelos caminhos sombreados, entre canteiros e pequenas árvores. Através do arco central e acima do muro, uma cidade-palácio branca trepa por uma colina em terraços empilhados, reluzindo à distância como a coroa do jardim. Tudo está sob sol intenso, folhagem de verde profundo contra a pedra dourada e um céu pálido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HIMEJI_CASTLE"] =
    "Uma torre de menagem branca se ergue de uma colina arborizada no alto do quadro, camada sobre camada de paredes pálidas sob telhados cinza curvos. Torres brancas menores se agrupam abaixo dela entre as árvores. A estrada que sobe até ela atravessa uma aldeia de telhados escuros de telha, e um portão de moldura vermelha cruza o caminho no plano médio. Samurais montados cavalgam em sua direção pelo primeiro plano, altas bandeiras vermelhas erguendo-se de suas costas. Soldados de infantaria de armadura aguardam junto às casas à direita. O dia está ameno e encoberto, e a cena é toda de verdes e cinzas em torno da torre branca. As bandeiras são o vermelho mais nítido da cena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HUBBLE"] =
    "Um longo cilindro prateado envolto em painéis de folha metálica flutua em órbita, sua porta articulada de abertura escancarada na extremidade próxima para expor a boca escura da óptica. Painéis solares planos em armações de cobre-dourado se abrem de suas laterais, e um astronauta em traje espacial trabalha em seu flanco, pequeno diante do instrumento. Parte de uma nave espacial acoplada surge no canto inferior direito do quadro. Atrás de tudo, a Terra preenche a imagem, uma curva de oceano azul e nuvem branca caindo para o espaço negro. A paleta é prata e ouro contra o azul da Terra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_KREMLIN"] =
    "A neve cai sobre a Praça Vermelha, onde uma muralha de fortaleza de tijolo vermelho escuro corre ao longo da direita sob um pesado céu cinza de inverno. Uma bandeira vermelha tremula do bloco baixo e escalonado do Mausoléu de Lenin assentado contra a muralha, e mais ao longe uma alta torre se ergue na penumbra, seu pináculo em forma de tenda íngreme. Multidões em longos sobretudos escuros e gorros de pele cruzam a praça coberta de neve em uma fila lenta, figuras solitárias arrastando-se pelo primeiro plano de costas para o observador. A pintura é quase monocromática, neve branca e cinza-carvão, com o tijolo e a bandeira como seus únicos vermelhos."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LEANING_TOWER"] =
    "Um campanário branco e redondo se ergue de um gramado verde, cercado andar após andar por arcadas de mármore abertas e inclinando-se inconfundivelmente para a direita. Ele se destaca, claro, contra um céu escuro de tempestade. O flanco pálido da Catedral de Pisa fica na borda direita do quadro, e edifícios mais baixos da cidade em ocre fecham o verde à esquerda. Habitantes e monges em longas túnicas marrons e vermelhas cruzam o gramado em procissões soltas, pequenos sob a torre. A luz é teatral: uma fresta nas nuvens ilumina o mármore branco enquanto o céu atrás dele permanece quase negro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LOUVRE"] =
    "Um palácio de pedra cinza se estende pelo fundo, um alto pavilhão central com ornamentos entalhados e íngremes telhados de mansarda de ardósia, com alas correndo para ambos os lados. Os artistas o mostram em seus dias como palácio real, muito antes da moderna pirâmide de vidro do museu. À frente estendem-se jardins formais: gramados planos cortados por caminhos de cascalho, árvores jovens e uma pequena fonte lançando água à esquerda. Passeantes em trajes do século XIX pontilham as alamedas, mulheres em longos vestidos brancos e homens em casacos escuros e cartolas. Um casal se detém junto à direita. O dia está ameno e perolado. Tudo é pedra cinza e verde suave sob um céu pálido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MACHU_PICHU"] =
    "Uma cidade de pedra repousa em uma alta sela montanhosa, terraços agrícolas escalando a encosta até grupos de edifícios com empenas sob telhados de palha. Atrás dela, o pico íngreme de Huayna Picchu sobe até as nuvens. A névoa paira sobre as serras circundantes, e o vale despenca na sombra abaixo. Na trilha em primeiro plano, um pequeno grupo com lhamas de carga abre caminho subindo em direção aos portões da cidade, minúsculo diante dos terraços. A luz chega em pálidos feixes através do tempo, destacando a pedra de tom bege quente do verde e do cinza dos Andes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MAUSOLEUM_HALICARNASSUS"] =
    "Um massivo pódio quadrado de mármore branco, faixado por frisos esculpidos, eleva-se em direção a um anel de colunas no alto do quadro. Ele domina uma praça onde estátuas se postam sobre altos pilares, uma figura blindada e um cavaleiro entre elas. Ciprestes escuros estão plantados entre os pavimentos. Figuras em túnicas brancas e vermelhas se reúnem abaixo, diminuídas pelo monumento. O dia está claro e límpido. Mármore branco e nuvens brancas amontoadas se destacam contra um céu azul profundo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NEUSCHWANSTEIN"] =
    "Uma pálida aparição de castelo se ergue sobre uma crista florestada, paredes brancas e torres agrupadas meio dissolvidas na neve que cai no canto superior esquerdo do quadro. O primeiro plano é a estrada que sobe até ele: uma carruagem escura e fechada espera na curva enquanto cavaleiros desfilam em fila encosta acima, revolvendo a neve da trilha. Abetos polvilhados de neve margeiam o caminho e se fecham sobre o vale abaixo. A pintura é cinza e branca de inverno por toda parte. Os cavaleiros e a carruagem são as únicas formas escuras contra ela."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NOTRE_DAME"] =
    "Uma catedral gótica se ergue da Paris medieval, vista de cima, suas duas torres quadradas geminadas, a flecha central e a longa nave com arcobotantes erguendo-se bem acima de todos os telhados ao redor. A cidade se aperta contra suas muralhas em um denso entrelaçado de casas de empena e chaminés fumegantes, e o Sena dobra pelo primeiro plano passando por cais e pequenos barcos. O céu é pesado e cinzento, mas feixes de luz solar rompem pelas nuvens e caem diretamente sobre a catedral, dourando sua pedra enquanto a cidade permanece em sombra ardósia. O horizonte se esvai plano e pálido além dos telhados."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ORACLE"] =
    "Um templo redondo com colunata sob uma cúpula de pedra, um tholos, ergue-se sobre um rochedo marinho na ponta de um promontório rochoso, e um arco natural se abre pela falésia abaixo dele. Os artistas dispuseram o santuário na costa, e não na encosta da montanha de Delfos. Um caminho serpenteia em sua direção passando por poças de maré e rochas erguidas. No primeiro plano, peregrinos em vestes vermelhas, azuis e brancas seguem pela trilha em pequenos grupos, emoldurados por pinheiros escuros que se inclinam dos dois lados. É o início frio da noite, com um céu pálido enluarado e um mar cinza-esverdeado em torno da pedra quente do santuário."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PARTHENON"] =
    "Um longo templo dórico ergue-se inteiro ao longo do topo do quadro, sua colunata sustentando um frontão esculpido e pintado. O mármore é de um dourado quente sob um céu de nuvens cinzentas revoltas. Largos degraus descem dele por entre maciços de arbustos verdes baixos, com estátuas de bronze erguidas sobre plintos à esquerda. Pelos degraus desce uma procissão de gregos em mantos carmesim, e ao centro um único hoplita encara o observador com um elmo de crista, um escudo redondo no braço. Os vermelhos dos mantos ardem contra a pedra, e a luz tem o brilho pesado de um dia prestes a desabar em tempestade."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PENTAGON"] =
    "Uma vista aérea do edifício-sede de cinco lados, seus anéis pentagonais concêntricos de concreto pálido e teto escuro escalonando-se para dentro até um pátio verde no centro. Vias e estacionamentos contornam o edifício, com gramados e árvores tingidas de outono além. O Potomac corre atrás dele, atravessado por pontes. Na margem oposta, a cidade capital jaz na bruma, o obelisco branco do Monumento a Washington e a cúpula do Capitólio pequenos no horizonte. O dia é simples e cinzento; nada na cena se destaca exceto a forma do edifício."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PETRA"] =
    "O observador está dentro do Siq, o estreito desfiladeiro de acesso, entre paredes de rocha vermelho-rosadas que se elevam na sombra dos dois lados do quadro. Pela fenda, iluminado pelo sol pleno, ergue-se Al-Khazneh, o Tesouro, uma fachada esculpida diretamente na falésia. Seus dois andares de colunas e frontões clássicos sobem em arenito rosa, com um pavilhão redondo ao centro do nível superior. Viajantes avançam em sua direção pelo chão arenoso do desfiladeiro: dois cavaleiros balançam sobre camelos no primeiro plano próximo, e figuras de túnica caminham atrás. A pintura é toda de vermelhos quentes e marrons sombreados, a fachada esculpida resplandecendo ao fim da passagem escura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PORCELAIN_TOWER"] =
    "Um alto pagode ergue-se acima de um jardim de templo, andar sobre andar de beirais escuros e arqueados sobre um corpo esguio. Ele se ergue acima dos telhados de telha dos salões em sua base. O jardim se espalha no primeiro plano em torno de um lago tranquilo: pinheiros aparados, salgueiros, lanternas de pedra e uma estátua de leão esculpida sobre um pedestal na borda esquerda. Figuras de túnica passeiam pelos caminhos de cascalho em duplas e trios, e colinas arborizadas se elevam enevoadas atrás da torre. A cena é calma e verde, luz suave do dia sobre a água, o pagode erguendo-se escuro contra um céu pálido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PRORA_RESORT"] =
    "Um bloco monolítico de resort corre ao longo da costa aparentemente sem fim. Sua fachada pálida repete as mesmas fileiras de janelas vez após vez, estendendo-se praia abaixo até desaparecer rumo ao horizonte. O trecho mais distante ainda está coberto de andaimes. Na extremidade próxima ergue-se um grande tambor circular de edifício cercado de colunas sobre uma base vermelho-escura, uma bandeira vermelha tremulando de seu teto. Abaixo, a praia está movimentada: banhistas e passeantes espalhados em pequenas figuras pela areia, com o mar cinza-esverdeado rolando à direita. Nuvens altas iluminadas pelo sol preenchem o céu sobre uma tarde luminosa à beira-mar, concreto creme contra água azul."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PYRAMID"] =
    "Duas grandes pirâmides erguem-se pálidas na bruma do deserto, a mais próxima preenchendo o canto superior direito do quadro. Uma terceira ergue-se pequena no horizonte. A Esfinge agacha-se entre elas no plano médio. Palmeiras estão dispostas em uma linha fina ao longo da areia, e muros baixos em ruína e blocos bordejam uma depressão no primeiro plano. Um cavaleiro de vermelho está sentado sobre um camelo no canto inferior direito, e uma pequena caravana de camelos cruza a areia à esquerda com figuras caminhando ao lado. Tudo tem cor de areia, em tons de bege e osso sob um céu branco enevoado. O cavaleiro vermelho é a única cor nítida."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_RED_FORT"] =
    "Uma fortaleza de arenito vermelho intenso sob ataque: altas muralhas e baluartes redondos preenchem o quadro, pavilhões brancos de cúpula erguem-se ao longo das ameias, capim cresce das saliências, e colunas de fumaça preta sobem de incêndios no interior. Defensores se aglomeram nas ameias acima do portão. No primeiro plano, soldados de armadura em elmos arredondados avançam rumo às muralhas, passando por uma catapulta de madeira e sua tripulação na borda esquerda. A pintura é pesada de pedra vermelha e fumaça, e os pavilhões brancos e uma faixa de céu pálido são o único alívio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SISTINE_CHAPEL"] =
    "Uma cerimônia dentro da capela, vista do meio da congregação. A parede do fundo atrás do altar é coberta do chão ao teto pelo afresco do Juízo Final, um turbilhão de figuras sobre azul, e cenas pintadas e tapeçarias revestem as paredes laterais abaixo de altas janelas em arco. A abóbada afrescada apenas aflora no topo do quadro. Clérigos de branco celebram no altar iluminado por velas enquanto cardeais em escarlate preenchem o primeiro plano e os bancos ao longo das paredes. Seu vermelho é a cor mais forte no interior penumbroso. A pouca luz do dia que há cai cinzenta das janelas sobre as paredes pintadas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_INTERNATIONAL_SPACE_STATION"] =
    "Uma estação em treliça paira em órbita contra o negro do espaço: uma longa viga central cruzada por pares de grandes asas solares em azul-acinzentado, com a fileira de módulos cilíndricos brancos e nós de acoplamento agrupados em seu centro. Uma cápsula está atracada na extremidade próxima da fileira de módulos, e painéis radiadores se abrem em leque planos abaixo da viga. Atrás dela a Terra se curva para longe em azul profundo, com volutas de nuvem brilhando em seu lado noturno. Estrelas se espalham pelo negro acima. A imagem é limpa e fotográfica: metal branco, um planeta azul, e nenhuma figura em parte alguma."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_OF_LIBERTY"] =
    "Uma figura de cobre em túnica, envelhecida em verde pálido, está de pé sobre seu pedestal de pedra à esquerda de um porto movimentado, o braço da tocha erguido bem alto contra um céu de nuvens esparsas. Por ela passa a vapor um transatlântico do início do século XX, de casco preto com duas chaminés vermelhas e pretas soltando fumaça de carvão, enquanto rebocadores agitam a água revolta ao seu lado. O perfil de Nova York se estende baixo e enevoado do outro lado da água, à direita. A cena é pintada em cinzas e verdes marítimos, fumaça e nuvem se mesclando. A estátua verde pálido é a forma mais nítida em toda a fumaça e a nuvem."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STONEHENGE"] =
    "Um círculo de grandes pedras eretas, encimadas por dintéis, ergue-se em uma charneca escura à noite, brilhando em tom quente por fogueiras acesas em algum ponto interno, como se uma cerimônia estivesse em curso. Um cometa risca o céu estrelado acima dele. Pedras isoladas esparsas se erguem da urze no primeiro plano sombreado, com algumas pequenas fogueiras e figuras tênues pontilhadas pela planície. Tudo é de um azul profundo de noite, exceto a luz âmbar acumulada junto ao monumento."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SYDNEY_OPERA_HOUSE"] =
    "Grandes conchas de telhado brancas em forma de vela preenchem o lado direito do quadro vistas de perto, sobrepondo-se contra um céu azul vivo. O vidro e a cantaria escura da base do edifício aparecem por baixo delas. Um grande navio de cruzeiro branco está atracado logo além delas, e um iate a motor elegante corta a água revolta no primeiro plano. Do outro lado do porto cintilante, as torres de Sydney se erguem ao longe, à esquerda. O dia está claro e luminoso. Telhados brancos e navios brancos se destacam sobre a água em azul-esverdeado profundo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TAJ_MAHAL"] =
    "Um mausoléu de mármore branco se ergue de frente ao fim de seu longo jardim, sua grande cúpula central avultando acima de um nicho de portal em arco. Quiosques menores com cúpula ficam de cada lado da grande cúpula, e uma torre de minarete se eleva em cada canto da plataforma. O jardim corre reto em direção a ele: um estreito canal de reflexo ao centro ladeado por passeios pavimentados, fileiras de ciprestes escuros e baixos canteiros verdes. Algumas pequenas figuras em túnicas caminham pelos caminhos. O céu atrás é um suave pôr do sol em pêssego e ouro, e o mármore toma a cor, o branco passando a creme e rosa."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TEMPLE_ARTEMIS"] =
    "Uma longa colunata de mármore sob um frontão esculpido coroa uma elevação ao fundo da cena, com a estátua de um cavaleiro erguida diante dos degraus e ciprestes escuros postados ao longo do acesso. Um amplo terraço à frente está cheio de vida: figuras em togas brancas e túnicas coloridas passeiam e comerciam, vendedores se agacham junto a cestos à esquerda, e mulheres veladas passam de perto no primeiro plano à direita. Uma coluna vermelha emoldura a vista na borda esquerda, com um vale verde campestre e um rio caindo para longe bem abaixo. O sol do meio-dia resplandece sobre o mármore branco e o tecido vivo sob um céu azul carregado de nuvens."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_ZEUS"] =
    "Dentro de um salão de templo, o deus entronizado se ergue até o teto em ouro e marfim, barbado e de peito nu, com um manto sobre o colo. Uma das mãos sustenta uma pequena figura alada da Vitória estendida sobre o salão, e a outra empunha um alto cetro. Seu trono é trabalhado em ouro contra uma parede de vermelho quente, e fileiras de colunas avançam por ambos os lados da câmara, deixando as naves laterais na sombra. Adoradores em túnicas pálidas se reúnem aos pés da estátua, nenhum deles alcançando suas canelas. Pequenas chamas ardem ao longo das paredes. A luz desce de algum ponto alto, acumulando-se em ouro sobre a estátua enquanto o salão ao seu redor permanece sombrio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TERRACOTTA_ARMY"] =
    "Fileiras de soldados de argila preenchem o quadro de parede a parede, fila após fila de guerreiros em tamanho natural em casacos de armadura postados em sentido. Eles recuam por longos corredores entre paredes divisórias de terra. Cada fileira se esvanece mais fundo na fossa até que os mais distantes são apenas silhuetas contra um brilho dourado que irrompe no fundo da câmara. As figuras são de marrom-terra e cinza, com ombros e elmos contornados pela luz quente. O clima é silencioso e vasto, um exército de mortos perfilado na escuridão."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UNITED_NATIONS"] =
    "Uma vista ao nível da rua da Praça das Nações Unidas. A laje plana de vidro da torre do Secretariado se ergue à esquerda, acima do longo e baixo arco do edifício da assembleia. Uma fileira de mastros carrega as bandeiras de muitas nações ao longo do quarteirão. A praça está cheia de delegados: homens e mulheres em ternos sociais misturados a trajes nacionais, uma figura em vestes e toucado brancos do Golfo no centro da multidão, grupos pausando em conversa a caminho da entrada. Um táxi amarelo aguarda no meio-fio à direita, e o perfil de Nova York se ergue atrás das bandeiras. É fim de tarde, com longas sombras sobre o calçamento e o sol baixo refletindo no vidro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UFFIZI"] =
    "Duas longas alas de galeria se voltam uma para a outra através de um pátio estreito, altas fachadas renascentistas de pedra cinza e reboco creme com estátuas postadas em nichos acima da loggia do pavimento térreo. O pátio se aprofunda na imagem em direção a uma abertura em arco na extremidade oposta, e uma torre aparece contra o céu além dela. Abaixo, o pátio está movimentado com florentinos em longos vestidos e casacos escuros, esculturas expostas sobre pedestais ao centro, e uma barraca de toldo vermelho montada no primeiro plano à esquerda. O sol da tarde incide de soslaio de um dos lados, iluminando os andares superiores em tom quente enquanto a loggia abaixo retém uma sombra fria."
