-- Mod-authored great work descriptions, pl_PL overlay.
-- Baseline in CivVAccess_GreatWorkDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_MISSING"] = "Brak opisu obrazu dla tego dzieła sztuki."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIRL_WITH_PEARL_EARRING"] =
    "Obraz olejny z holenderskiego złotego wieku, jeden z najbardziej ukochanych portretów w sztuce Zachodu. Młoda kobieta odwraca się przez ramię, by spojrzeć ci w oczy z jednolitego ciemnego tła, usta lekko rozchylone, jakby miała coś powiedzieć. Nosi niebiesko-złoty turban, którego tkanina opada jej na plecy, a duża perła w kształcie łzy chwyta światło przy jej uchu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HENRY_VIII"] =
    "Tudorowski portret dworski w oleju, obraz, który utrwalił wyobrażenie świata o Henryku VIII. Król stoi zwrócony ku tobie w pełnej postaci, stopy rozstawione szeroko, barczysty i masywny, jedną dłoń trzyma na sztylecie przy pasie. Nosi wysadzany klejnotami srebrny dublet pod szkarłatnym płaszczem podbitym futrem, płaski pierzasty kapelusz i złote łańcuchy, stojąc na wzorzystym dywanie między marmurowymi kolumnami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HUNTERS_IN_THE_SNOW"] =
    "Flamandzki renesansowy obraz olejny, zimowy pejzaż oglądany ze szczytu wzgórza. Trzej zmęczeni myśliwi i ich sfora psów brną przez głęboki śnieg na pierwszym planie, z pochylonymi głowami, z całego polowania mając tylko jednego lisa. Poniżej nich rozciąga się wioska pod szaro-zielonym niebem, z maleńkimi łyżwiarzami na zamarzniętych stawach i poszarpanymi szczytami wznoszącymi się w oddali."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LES_DEMOISELLES"] =
    "Wczesnomodernistyczny obraz olejny, płótno, które dało początek kubizmowi. Pięć nagich kobiet stoi i siedzi w płytkiej przestrzeni poszarpanych różowych, białych i niebieskich płaszczyzn, a ich ciała są rozbite na ostre, kanciaste kształty. Dwie twarze po prawej stronie namalowano jak afrykańskie maski, pasiaste i zniekształcone, podczas gdy pozostałe patrzą prosto przed siebie szerokimi migdałowymi oczami; przy dolnej krawędzi stoi mała misa z owocami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LUNCHEON"] =
    "Francuski impresjonistyczny obraz olejny przedstawiający przyjaciół zwlekających po posiłku. Ożywione towarzystwo w letnich strojach tłoczy się na nadrzecznym balkonie pod pasiastą pomarańczowo-białą markizą, rozmawiając, flirtując i opierając się o barierkę; młoda kobieta z przodu bawi się z małym psem. Stół zastawiony jest butelkami wina, kieliszkami i owocami, wszystko namalowane ciepłymi, luźnymi dotknięciami nasłonecznionego koloru."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MONA_LISA"] =
    "Włoski renesansowy obraz olejny na desce, prawdopodobnie najsłynniejszy portret na świecie. Kobieta siedzi ze splecionymi dłońmi, zwrócona lekko ku tobie na tle zamglonego pejzażu z krętymi rzekami i dalekimi niebieskimi górami. Jej oczy spotykają się bezpośrednio z twoimi, słynne spojrzenie, które zdaje się podążać za tobą, gdziekolwiek staniesz. Jej ledwie widoczny półuśmiech jest punktem skupienia obrazu, namalowany w miękkich brązach i zieleniach bez ostrych konturów, tak że jej wyraz twarzy zdaje się zmieniać, im dłużej patrzysz."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUNDAY_AFTERNOON"] =
    "Puentylistyczny obraz olejny, zbudowany w całości z drobnych kropek czystego koloru. Paryżanie w odświętnych niedzielnych strojach wypoczywają na słonecznym nadrzecznym trawniku, spacerując z parasolkami, wylegując się na trawie i prowadząc małe pieski, a za nimi na wodzie żaglówki. Wszyscy są dziwnie nieruchomi i sztywni, jak postacie z fryzu, a światło rozbite jest na migotanie zielonych, pomarańczowych i fioletowych drobinek."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VIEW_OF_TOLEDO"] =
    "Hiszpański renesansowy obraz olejny, jeden z najwcześniejszych czystych pejzaży w sztuce Zachodu i niezwykle mroczny. Hiszpańskie wzgórzowe miasto Toledo wznosi się w oddali pod gwałtownym, burzowym niebem, jego szare iglice i mury oświetlone niesamowitym srebrnym światłem. Zielone wzgórza opadają ku rzece na pierwszym planie, a cała scena namalowana jest w głębokich zieleniach i niebieskich czerniach, które bardziej przypominają sen niż dzień."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WATER_LILIES"] =
    "Francuski impresjonistyczny obraz olejny ze słynnej serii Moneta przedstawiającej jego ogrodowy staw w Giverny. Całe płótno to powierzchnia wody, bez horyzontu i brzegu: kępy zielonych liści lilii dryfują po niebiesko-lawendowej wodzie usianej różowymi i czerwonymi kwiatami. Chmury i drzewa pojawiają się jedynie jako miękkie odbicia, a pędzel jest na tyle luźny, że wszystko zdaje się unosić."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_STARRY_NIGHT"] =
    "Postimpresjonistyczny obraz olejny, jeden z najbardziej rozpoznawalnych obrazów sztuki nowoczesnej. Nocne niebo pełne ruchu wypełnia większą część płótna: gwiazdy płoną wewnątrz wirujących aureoli, a księżyc pali się na pomarańczowo w rogu, podczas gdy wielki spiralny prąd toczy się przez środek nieba. Poniżej cicha wioska ze spiczastą wieżą kościoła śpi wśród wzgórz, a ciemny cyprys strzela płomieniem w górę przy lewej krawędzi, wszystko w grubych, widocznych pociągnięciach błękitu i złota."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BIRTH_OF_VENUS"] =
    "Włoski renesansowy obraz przedstawiający boginię miłości przybywającą z morza, jeden z najsłynniejszych obrazów klasycznego mitu. Wenus stoi naga na olbrzymiej muszli przegrzebka, zakrywając się dłońmi i kaskadą długich złotych włosów. Po lewej dwa skrzydlate bóstwa wiatru wieją ku brzegowi przez deszcz różowych róż, podczas gdy po prawej kobieta w kwiecistej sukni spieszy, by owinąć ją powiewającym płaszczem."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BINDO_ALTOVITI"] =
    "Włoski portret olejny z okresu pełnego renesansu, przedstawiający bogatego młodego rzymskiego bankiera. Przystojny młody mężczyzna o długich złotych włosach i w czarnej czapce ogląda się ku tobie przez nagie ramię, jedną dłoń ma przyciągniętą do piersi. Nosi niebieski płaszcz na czarnej szacie, a jego blada twarz jaśnieje na tle głębokiej zieleni."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_DRAGON"] =
    "Wczesnorenesansowy włoski obraz o sztywnym, baśniowym uroku rodem z bajki. Po prawej stronie opancerzony rycerz na stającym dęba białym koniu wbija lancę w rozwartą paszczę skrzydlatego zielonego smoka o nakrapianych skrzydłach jak u ćmy. Po lewej spokojna księżniczka w długiej różowej sukni trzyma rannego stwora na smyczy niczym zwierzaka, przed jego ciemną jaskinią, podczas gdy za rycerzem zbiera się dziwna spiralna burza."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CREATION_OF_ADAM"] =
    "Włoski renesansowy fresk z sufitu Kaplicy Sykstyńskiej, źródło jednego z najsłynniejszych gestów w sztuce. Nagi Adam spoczywa na zielonym zboczu po lewej stronie, jedno ramię wyciągnięte bezwładnie, podczas gdy Bóg, siwobroda postać w powiewającym różowym całunie pełnym aniołów, nadciąga z prawej. Ich wyciągnięte palce wskazujące sięgają ku sobie przez niewielką szczelinę, w chwili tuż przed iskrą życia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GALLERY_OF_THE_LOUVRE"] =
    "Amerykański obraz olejny przedstawiający galerię wewnątrz Luwru, namalowany przez tego samego Morse'a, który później wynalazł alfabet telegraficzny. Okazały salon o czerwonych ścianach pokryty jest od podłogi po sufit dziesiątkami obrazów dawnych mistrzów w złotych ramach, wśród nich maleńka Mona Lisa. Na pierwszym planie studenci sztuki kopiują dzieła przy sztalugach, a ich nauczyciel pochyla się nad ramieniem młodej kobiety, by poprawić jej pracę; w głębi otwiera się łukowy korytarz prowadzący do dalszych galerii."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WASHINGTON_CROSSING"] =
    "Heroiczny amerykański obraz historyczny olejny, ikona wojny o niepodległość. Generał Waszyngton stoi wyprostowany na dziobie przepełnionej łodzi wiosłowej, podczas gdy jego żołnierze odpychają się drągami i wiosłują przez rzekę zatłoczoną krami lodu, a oficer za jego plecami unosi w górę amerykańską flagę. Światło świtu przebija się przez zimną mgłę, a z tyłu podążają kolejne łodzie pełne ludzi i koni."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ARRANGEMENT_IN_GREY"] =
    "Amerykański obraz olejny, powszechnie znany jako Matka Whistlera. Starsza kobieta w długiej czarnej sukni i białym koronkowym czepku siedzi ściśle z profilu, zwrócona w lewo, z dłońmi złożonymi na podołku i stopami na małym podnóżku. Wnętrze jest surowe i płaskie: szara ściana, ciemna wzorzysta kotara i pojedynczy obraz w ramie, a cała kompozycja wyważona jest niczym studium szarości i czerni, dokładnie tak, jak głosi tytuł."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BREEZING_UP"] =
    "Amerykański realistyczny obraz olejny przedstawiający żeglugę małą łodzią u wybrzeży Nowej Anglii. Mężczyzna i trzej chłopcy odchylają się do tyłu w małej żaglówce o nazwie Gloucester, gdy ta przechyla się na mocnym wietrze; piana rozbryzguje się od dziobu, a u ich stóp piętrzy się dzienny połów. Morze jest wzburzone i zielone pod poszarpanymi chmurami, a na horyzoncie widnieje dwumasztowy szkuner."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_THOUSAND_LI"] =
    "Chiński niebiesko-zielony pejzaż w formie zwoju ręcznego, namalowany na jedwabiu przez nastoletniego geniusza dworu Song i liczący blisko dwanaście metrów długości. Góry w żywej mineralnej niebieskości i zieleni wznoszą się grzbiet za grzbietem nad spokojną złotą rzeką, a między zboczami ukryte są maleńkie wioski, mosty i nagie drzewa. Kolumny kaligrafii pisanej pędzlem oraz czerwone pieczęcie kolekcjonerów wypełniają niebo nad szczytami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DWELLING_IN_THE_FUCHUN"] =
    "Chiński zwój ręczny tuszem, arcydzieło pejzażu literackiego epoki Yuan, wykonany w całości w odcieniach czarnego tuszu na papierze. Zaokrąglone góry zbudowane z warstwowych, suchych pociągnięć pędzla wznoszą się nad szeroką spokojną rzeką, a wzdłuż brzegów rosną sosny i stoją rozproszone chaty oraz łodzie rybackie. Nastrój jest spokojny i kontemplacyjny, papier usiany czerwonymi pieczęciami kolekcjonerów gromadzonymi przez stulecia wielbicieli."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ALONG_THE_RIVER"] =
    "Chiński zwój ręczny na jedwabiu z epoki Song, słynna panorama codziennego życia miasta o długości ponad pięciu metrów. Pokazany fragment skupia się na wielkiej bramie miejskiej stolicy, masywnej drewnianej wieży na pochyłym wale, pod którą ulice tętnią życiem: stragany targowe, wozy zaprzężone w woły, karawana wielbłądów przechodząca przez bramę i tragarze niosący ładunki na drągach przewieszonych przez ramiona. Każda postać jest maleńka, lecz precyzyjnie nakreślona cienką kreską tuszu w stłumionych ziemistych barwach."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LEAF_2"] =
    "Chiński liść albumowy z epoki Qing, malarstwo dworskie w cienkiej kresce i delikatnym kolorze. Eleganckie damy w długich powłóczystych szatach w bieli, zieleni i błękicie gromadzą się w ogrodowym pawilonie udrapowanym jaskrawoniebieską tkaniną, a jedna z nich pali kadzidło przy stole za czerwoną balustradą. Wokół nich znajdują się ogrodowe skały, bambus i kwitnące pnącze wspinające się po dachu pawilonu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EMPEROR_TAIZONG"] =
    "Chiński zwój ręczny na jedwabiu z epoki Tang, dworski zapis spotkania dyplomatycznego. Po prawej cesarz Taizong siedzi na platformie niesionej przez damy dworu, które trzymają także dwa wielkie wachlarze i czerwony baldachim nad jego głową. Po lewej zbliżają się w pełnych szacunku pozach trzy mniejsze postacie: dworski herold w czerwieni, tybetański poseł we wzorzystej szacie i tłumacz w bieli, wszyscy na tle ciepłego złotego jedwabiu pokrytego czerwonymi pieczęciami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SPRING_MORNING"] =
    "Chiński zwój ręczny na jedwabiu z epoki Ming, długa panorama pałacowych kobiet spędzających czas na wiosennym poranku. Dziesiątki eleganckich dam wypełniają otwarte sale, werandy i dziedzińce: muzykują, malują portret, bawią się z dziećmi i przechadzają wśród wierzb, ogrodowych skał, a nawet pawi. Pałacowa architektura ciągnie się przez całą długość zwoju w ciepłych czerwieniach i zieleniach, a każdy parawan, balustrada i szata oddane są z drobiazgową, cienką kreską."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_GREAT_WAVE"] =
    "Japoński drzeworyt ukiyo-e, najsłynniejszy pojedynczy obraz w sztuce japońskiej. Ogromna ciemnoniebieska fala wzbija się po lewej i zawija nad całą sceną, a jej grzebień rozbija się na szponiaste palce białej piany. Pod nią trzy długie otwarte łodzie pełne wioślarzy przemierzają doliny fal, a daleko w głębi, maleńki pośrodku tego wszystkiego, wznosi się ośnieżony stożek góry Fudżi."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EVENING_SHOWER"] =
    "Japoński drzeworyt ukiyo-e, jedna z najbardziej podziwianych scen deszczowych, jakie kiedykolwiek powstały. Nagła ulewa, narysowana jako pasma cienkich ukośnych linii, zaskakuje ludzi w połowie długiego drewnianego mostu; spieszą oni w obu kierunkach pod kapeluszami i parasolami, a jeden chroni się pod słomianą matą. Rzeka w dole jest pasmem zieleni morskiej, którym przepływa samotny flisak odpychający się drągiem, a przeciwny brzeg rozmywa się w ciemną plamę pod burzą."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_L_ABSINTHE"] =
    "Francuski obraz olejny w stylu impresjonistycznym, bezlitosna scena z życia paryskiej kawiarni. Kobieta w bladej sukni i kapeluszu siedzi przygarbiona przy marmurowym stoliku kawiarnianym, ze spuszczonym wzrokiem, przed nią kieliszek mlecznozielonego absyntu; obok niej brodaty mężczyzna w pomiętym płaszczu wpatruje się w prawo z fajką w ustach. Oboje siedzą razem, a jednak zupełnie osobno, namalowani w szarawych i brunatnych barwach niosących przenikającą obraz atmosferę samotności."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_UPAUPA_SCHNEKLUD"] =
    "Postimpresjonistyczny portret olejny wiolonczelisty w trakcie występu. Muzyk pochyla się nad jaskrawą pomarańczowoczerwoną wiolonczelą, oczy spuszczone w skupieniu, ramię ze smyczkiem przesuwa się po strunach, a jego ciemnoniebieski garnitur otacza rozjarzony instrument. Za nim tło rozpada się na płaskie strefy brązu i mszystej zieleni, usiane bladymi abstrakcyjnymi kształtami, w śmiałym, uproszczonym stylu kolorystycznym Gauguina."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_BAR_AT_THE_FOLIES"] =
    "Francuski olejny obraz życia współczesnego, ostatnie wielkie dzieło Maneta. Barmanka w gorsecie z czarnego aksamitu z kwiatem przy piersi stoi za marmurowym kontuarem zastawionym butelkami szampana, misą pomarańczy i kieliszkiem z różą, patrząc przed siebie ze znużonym, nieobecnym wyrazem twarzy. Za jej plecami ogromne lustro odbija rozświetloną salę koncertową, jej żyrandole i tłum, a także, dziwnie przesunięte w prawo, jej własne plecy, gdy pochyla się ku mężczyźnie w cylindrze."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BALL_AT_THE_MOULIN"] =
    "Postimpresjonistyczny olejny obraz paryskiego życia nocnego w słynnym kabarecie. Grupa mężczyzn w cylindrach i kobiet w kapeluszach z piórami siedzi wokół stołu z napojami, a w oświetlonej na zielono sali tanecznej za nimi rudowłosa kobieta poprawia włosy. Twarz kobiety wyłania się przy prawej krawędzi, oświetlona od dołu upiorną zielenią, a długa ukośna barierka przecina pierwszy plan w plakatowym stylu Lautreca."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS"] =
    "Wiedeński olejny obraz w stylu secesji, pokryty warstwami prawdziwego złotego listka, najsłynniejsze dzieło Klimta. Para klęczy złączona w uścisku na ukwieconej łące, mężczyzna pochyla się, by pocałować policzek kobiety, a ona unosi twarz z zamkniętymi oczami. Ich ciała zlewają się w jeden złoty płaszcz, wzorzysty w prostokąty po jego stronie i w jasne koła po jej, lśniący na płaskim, migoczącym złotym tle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AMERICAN_GOTHIC"] =
    "Amerykański olejny obraz regionalistyczny, bez końca parodiowany i rozpoznawalny od pierwszego spojrzenia. Surowy, łysiejący farmer w okrągłych okularach i dżinsowych ogrodniczkach stoi, trzymając pionowo trójzębne widły, a u jego boku kobieta w ciemnej wzorzystej sukni fartuchowej patrzy w bok z dezaprobatą zaciśniętych ust. Za nimi stoi biały dom wiejski, od którego pochodzi tytuł obrazu, z ostrołukowym gotyckim oknem w szczycie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SRI_SHANMUKAHA"] =
    "Indyjski obraz dewocyjny w europejskim stylu akademickim, który Ravi Varma rozsławił w całych Indiach. Hinduski bóg Murugan jedzie na swoim wierzchowcu pawiu, ma sześć ukoronowanych głów i wiele rąk dzierżących broń, a po bokach towarzyszą mu dwie małżonki w jaskrawo różowych sari. Pawi ogon rozpościera się za nimi niczym olbrzymi wachlarz zielono-złotych oczek, podczas gdy ptak przyciska kobrę stopami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DAUD_RECEIVES_A_ROBE"] =
    "Mogolska miniatura z ilustrowanej cesarskiej kroniki, malowana kryjącą akwarelą i złotem na papierze. Pokazany fragment skupia się na smukłym młodym słudze w bladej szacie, czerwonej czapce i złotej szarfie, niosącym złożoną złotą szatę honorową na ceremonię wręczenia. Stoi on na tle olśniewająco błękitnej ściany namiotu pokrytej delikatnymi kwitnącymi pnączami, każdy fałd i kwiat namalowane z miniaturową precyzją."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YUSEF_AND_ZULEYKHA"] =
    "Perska miniatura z ilustrowanego rękopisu, najsłynniejsze dzieło wielkiego mistrza z Heratu, Behzada. Stronę wypełnia misterny pałac ukazany w spłaszczonym przekroju, labirynt schodów, balkonów i drzwi wyłożonych płytkami w błękicie, pomarańczu i złocie. W górnej komnacie prorok Józef, w aureoli płomieni, ucieka przed wyciągniętymi po niego dłońmi Zulejki, a panele perskiej kaligrafii oprawiają architekturę."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ASCENT_OF_MUHAMMAD"] =
    "Perska miniatura z królewskiego rękopisu, ukazująca nocną podróż Proroka przez niebiosa. Mahomet, twarz zasłoniętą bielą i otoczoną złotym płomieniem, jedzie na ludzkogłowym rumaku Buraku przez głęboko niebieskie niebo usiane skręconymi obłokami obrysowanymi złotem. Aniołowie w szatach czerwonych, zielonych i pomarańczowych wirują wokół niego ze wszystkich stron, niosąc dary i kadzielnice, a wersy perskiej poezji oprawiają scenę."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LIBERTY_LEADING_THE_PEOPLE"] =
    "Francuski olejny obraz romantyczny, definiujący obraz rewolucji. Sama Wolność, kobieta z odsłoniętą piersią w żółtej sukni i czerwonej czapce, kroczy po barykadzie z gruzu i poległych ciał, wznosząc francuską trójkolorową flagę ku zadymionemu niebu. Wokół niej napierają uzbrojeni obywatele wszystkich stanów, wśród nich dżentelmen w cylindrze z muszkietem i chłopiec wymachujący dwoma pistoletami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_JEROME_IN_HIS_STUDY"] =
    "Wczesnorenesansowy olejny obraz o niezwykłej miniaturowej precyzji. Widziany przez okazałą kamienną arkadę, święty Hieronim w czerwonych szatach siedzi czytając w drewnianej pracowni zbudowanej niczym scena wewnątrz sklepionej przestrzeni katedralnej, otoczony półkami pełnymi ksiąg i naczyń. Światło wpada przez okna ze wszystkich stron, paw i kuropatwa przysiadły z przodu na progu, a jego lew krąży w cieniu po prawej stronie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PARTHENON_FRIEZE"] =
    "Wiktoriański olejny obraz wyobrażający starożytne Ateny; w grze dzieło to towarzyszy cudowi Partenon. Rzeźbiarz Fidiasz stoi na drewnianym rusztowaniu obok świeżo pomalowanego marmurowego fryzu z jeźdźcami, wciąż w pracownianych barwach, i przytrzymując linę prezentuje go. Niewielka grupa Ateńczyków w drapowanych szatach, wśród nich Perykles, pochyla się, by podziwiać rzeźbę w ciepłym świetle wnętrza świątyni."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUE_DE_PARIS"] =
    "Francuski olejny obraz realistyczny ukazujący nowoczesny Paryż w mżysty dzień, ostry i fotograficzny tam, gdzie jego impresjonistyczni przyjaciele malowali swobodnie. Dobrze ubrana para pod wspólnym parasolem idzie ku tobie po lśniącym bruku, mężczyzna w cylindrze, a kobieta w długiej ciemnej sukni z kolczykiem chwytającym światło. Wokół nich inni przechodnie z parasolami przecinają szerokie skrzyżowanie obrzeżone klinowatymi szarymi kamienicami, a zielona latarnia dzieli scenę pośrodku."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_NIGHT_WATCH"] =
    "Olejny obraz holenderskiego złotego wieku na ogromną skalę, najsłynniejszy portret zbiorowy, jaki kiedykolwiek powstał. Kompania straży miejskiej zrywa się do ruchu z głębokiego cienia: kapitan w czerni z czerwoną szarfą kroczy naprzód, wydając rozkaz porucznikowi w bladym złocie, a za nimi nabija się muszkiety, wznosi sztandar i dobosz wybija takt. Mała dziewczynka w jarzącej się złotej sukni lśni tajemniczo w tłumie, oświetlona niczym reflektorem w mroku."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DEATH_OF_MARAT"] =
    'Francuski olejny obraz neoklasycystyczny, wielki obraz męczennika rewolucji francuskiej. Rewolucyjny dziennikarz Marat leży martwy w swojej wannie, osunięty niczym poległy święty, głowę owija mu biały turban, a jedno ramię zwisa do podłogi, wciąż trzymając pióro. W drugiej dłoni trzyma list, którym jego zabójczyni posłużyła się, by uzyskać wstęp; górna połowa płótna to naga ciemna ściana, a prosta drewniana skrzynia obok niego nosi malowaną dedykację "A Marat, David."'
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ETIENNE_CHEVALIER"] =
    "Francuskie późnośredniowieczne malarstwo tablicowe, jedno skrzydło słynnego dewocyjnego dyptyku. Skarbnik królewski Etienne Chevalier klęczy w bogatej czerwonej szacie ze złożonymi do modlitwy dłońmi, przedstawiany przez swojego patrona świętego Stefana, który stoi obok niego w niebiesko-złotym ornacie. Święty trzyma księgę zwieńczoną postrzępionym kamieniem, symbolem swojego męczeństwa, a obaj stoją w sali z białego marmuru, na której ścianie wyryto imię fundatora."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_FRANCIS"] =
    "Hiszpańskie barokowe malarstwo olejne surowej zakonnej pobożności. Święty Franciszek stoi samotnie w prostym habicie z kapturem w kolorze piasku, twarz na wpół skryta w głębokim cieniu kaptura, oczy spuszczone w modlitwie. W dłoniach trzyma ludzką czaszkę jako przypomnienie o śmierci, oświetloną pojedynczym ostrym światłem na niemal czarnym tle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HATAORI"] =
    "Japoński drzeworyt ukiyo-e przedstawiający tkaczkę przy pracy. Młoda kobieta we wzorzystym kimonie w kolorze indygo siedzi boso przy dużym drewnianym krośnie ręcznym, podnosząc wzrok znad pracy z czółenkiem w jednej dłoni, a nici w czerwieni, błękicie i bieli rozciągają się na całą długość maszyny. Barwy są miękkimi kremami i stonowanymi błękitami, a kolumna pisanej pędzlem poezji wypełnia lewy górny róg arkusza."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JANE_GREY"] =
    "Francuskie akademickie malarstwo historyczne, teatralne i wstrząsające. Nastoletnia królowa, z zawiązanymi oczami i ubrana w biały atłas jaśniejący na tle ciemnej kamiennej komnaty, klęczy i po omacku szuka pieńka katowskiego, podczas gdy starszy dostojnik delikatnie kieruje ku niemu jej dłonie. Jej damy dworu osuwają się z rozpaczy o filar za jej plecami, a kat czeka po prawej, wsparty o swój topór z odwróconym wzrokiem."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WANDERER"] =
    "Niemieckie romantyczne malarstwo olejne, sztandarowy obraz człowieka samotnego wobec natury. Młody mężczyzna w ciemnozielonym płaszczu stoi tyłem do patrzącego na skalistym szczycie, wsparty na lasce, włosy targane wiatrem. Poniżej niego ocean białej mgły pochłania dolinę, z której tylko grzbiety i turnie przebijają się jak wyspy, a blade góry rozpływają się w oddali."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BABEL"] =
    "Flamandzkie renesansowe malarstwo olejne przedstawiające skazaną na zagładę biblijną Wieżę Babel, kipiące od szczegółów. Kolosalna spiralna wieża z łuków, częściowo z białego kamienia, a częściowo z surowej czerwonej cegły, wznosi się krzywo ku chmurom, a jej szczyt wciąż jest surowy i nieukończony. U jej podnóża rozpościera się miasto portowe z zakotwiczonymi statkami, a na pierwszym planie król dokonuje przeglądu drużyny kamieniarzy, którzy klęczą u jego stóp pośród swoich bloków."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YOUNG_LADY"] =
    "Wczesnoniderlandzki portret olejny, mały, spokojny i dziwnie nowoczesny. Blada młoda kobieta o gładkiej jak porcelana twarzy spogląda na patrzącego z ukosa spod wysokiego nakrycia głowy z czarnego aksamitu obszytego złotem. Nosi niebieską suknię z białym futrzanym kołnierzem i ciasny naszyjnik ze złotych i czarnych pasków, ukazana na tle gładkiej, przyćmionej ściany zamiast zwyczajowej ciemnej pustki."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_KINDRED"] =
    "Amerykańskie malarstwo olejne szkoły rzeki Hudson, hołd dla przyjaźni między malarzem a poetą. Dwaj mężczyźni w płaszczach stoją rozmawiając na skalnym występie wystającym nad zalesionym wąwozem w górach Catskill, jeden z nich wskazuje pędzlem na widok. Strumień spływa po skałach w dole, ujęty w łuk zwisających drzew, a za nim mgliste szczyty roztapiają się w złotym świetle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BLUE_BOY"] =
    "Angielski portret olejny w stylu wielkiej maniery, najsłynniejsze dzieło artysty. Chłopiec około dwunastoletni stoi w pełnej postaci w mieniącym się stroju z niebieskiego atłasu, w spodniach do kolan i koronkowym kołnierzu, jedną dłoń wsparł na biodrze, w drugiej trzyma u boku kapelusz z piórem. Spogląda z lekką pewnością siebie na tle ciemnego, burzowego brązowego pejzażu, który sprawia, że niebieski strój płonie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SECOND_OF_MAY"] =
    "Hiszpańskie malarstwo olejne, jeden z pierwszych i najwspanialszych protestów przeciw wojnie w sztuce. W świetle latarni francuski pluton egzekucyjny stoi w bezosobowym szeregu z karabinami wycelowanymi w zbitą gromadę hiszpańskich jeńców na gołym wzgórzu pod Madrytem. W centrum mężczyzna w białej koszuli rozkłada szeroko ramiona przed lufami, klęcząc pośród ciał już rozstrzelanych, a jego poza przywołuje ukrzyżowanie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_CART"] =
    "Francuskie malarstwo olejne o tematyce wojskowej z wojny francusko-pruskiej, słynny obraz nieugiętego ostatniego oporu. Garstka francuskich żołnierzy broni zrujnowanego wiejskiego domu, strzelając z okna, podczas gdy ranni siedzą osunięci pod ścianami, a oficer liczy ich ostatnie naboje. Pomieszczenie jest zdemolowane, drzwi wyrwane z zawiasów, tynk sypie się z sufitu, a światło dnia wlewa się przez otwór drzwiowy, w którym towarzysze walczą dalej."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EARLY_AUTUMN"] =
    "Chiński zwój ręczny w tuszu i miękkim kolorze, studium natury z bliska przedstawiające więdnący staw lotosowy. Ważki w czerwieni, zieleni i błękicie unoszą się nad usychającymi trzcinami i postrzępionymi liśćmi lotosu, podczas gdy w dole zajęte są swoimi sprawami koniki polne, pszczoła i małe żaby. Nastrój to łagodne więdnięcie, życie lata trwające wśród roślin dopiero zaczynających usychać, a wzdłuż obu krawędzi widnieją czerwone pieczęcie kolekcjonerów."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_APPRECIATING_LOTUSES"] =
    "Japoński wiszący zwój w tuszu i kolorze pędzla założyciela szkoły Kano, namalowany w chińskiej manierze pejzażu uczonych. Odziany w szatę chiński uczony dryfuje w małej łodzi na skraju stawu lotosowego, wpatrując się w pływające liście pod sękatą wierzbą, która wychyla się ze skalistego brzegu. Większość wysokiego zwoju to mgła i otwarta woda, z kilkoma wierzchołkami sosen rozpływającymi się w oparach."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EQUESTRIAN_PORTRAIT"] =
    "Weneckie renesansowe malarstwo olejne, wzór dla wieków wizerunków władców na koniu. Cesarz Świętego Cesarstwa Rzymskiego wyjeżdża z ciemnego lasu w pełnej lśniącej zbroi, w hełmie z czerwonym pióropuszem, z kopią w dłoni, upamiętniając swoje zwycięstwo pod Mühlbergiem. Jego czarny koń okryty jest karmazynem, a niskie wieczorne słońce przebija się złotem i różem spod ciężkich burzowych chmur."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ARMADA"] =
    "Tudorowski portret propagandowy olejny, namalowany dla uczczenia klęski hiszpańskiej Armady. Królowa Elżbieta siedzi w przeogromnej sukni z pereł i kokard, twarz oprawioną w rozległą białą koronkową kryzę, jedną dłoń kładzie zaborczo na globusie, palcami spoczywając na obu Amerykach. Przez okna za jej plecami opowieść rozgrywa się dwukrotnie: po jednej stronie flota angielska na spokojnym morzu, po drugiej hiszpańskie okręty roztrzaskane w sztormie. Wysadzana klejnotami korona stoi obok niej."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRANCIS_I"] =
    "Francuski renesansowy portret królewski olejny. Franciszek I patrzy na ciebie ujęty od pasa w górę, w okazałym stroju dworskim: rozcinane rękawy z białego i złotego atłasu w czarne pasy, złoty łańcuch na piersi, na głowie czarny biret z białym piórem. Jego chytra, długonosa, brodata twarz odcina się od karmazynowego adamaszkowego tła wzorzystego w korony."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SELF_PORTRAIT"] =
    "Olejny autoportret w stylu północnego manieryzmu, pędzla flamandzkiego nadwornego malarza cesarza Rudolfa II. Artysta ogląda się ku tobie przez ramię, krzepki brodaty mężczyzna o kręconych włosach pod miękką czarną czapką, w białym karbowanym kołnierzu na szaroniebieskim kaftanie. Sposób malowania jest ciepły i bezpośredni na tle gładkiego brązu, a jego oceniające spojrzenie z ukosa przykuwa wzrok."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VERTUMNUS"] =
    "Olejny obraz manierystyczny, najsłynniejsza z fantazyjnych głów złożonych Arcimbolda. To portret cesarza Rudolfa II jako rzymskiego boga pór roku, którego cała twarz i pierś złożone są z owoców, warzyw i kwiatów: powieki z łupin grochu, nos z gruszki, wargi z wiśni, wąsy z kłosów pszenicy i włosy z winogron. Z daleka jest dostojnym władcą, z bliska rozpada się w stragan, a wszystko na czarnym tle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_SUPPER"] =
    "Wenecki obraz olejny późnego renesansu, który na nowo wymyśla znaną scenę. Zamiast stać wprost ku tobie, stół wieczerzy ucieka stromo na ukos w głąb mrocznej tawerny, a Chrystus jaśnieje w połowie jego długości, podając chleb apostołom. Słudzy dźwigają jedzenie, a kot wtyka pysk do kosza na pierwszym planie, podczas gdy płonąca oliwna lampa wypełnia zadymione powietrze nad nimi przezroczystymi, wirującymi aniołami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_A_MAN"] =
    "Wczesnoniderlandzki obraz olejny, być może własna twarz artysty i jeden z pierwszych prawdziwych autoportretów. Mężczyzna w średnim wieku, o pomarszczonej twarzy i bystrym spojrzeniu, patrzy wprost na ciebie z głębokiego cienia, w wystawnym czerwonym nakryciu głowy zwiniętym i zawiązanym w rzeźbiarskie fałdy. Szczegół jest cienki jak igła, każda zmarszczka i każdy włos zarostu uchwycone, a postać w ciemnym płaszczu obszytym futrem widnieje na czarnym tle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRONT_OF_THE_MIRROR"] =
    "Wenecki obraz olejny renesansu, pogodne późne arcydzieło sędziwego Belliniego. Naga młoda kobieta o kasztanowych włosach siedzi na czerwonej tkaninie, spokojnie układając włosy i trzymając małe lusterko, a drugie okrągłe lustro na ścianie za nią odbija tył jej wzorzystego nakrycia głowy. Okno obok niej otwiera się na zieloną wieś z odległymi błękitnymi górami pod zachmurzonym niebem."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ADORATION"] =
    "Wczesnowłoski fresk z kaplicy Scrovegnich, pędzla malarza, któremu przypisuje się przywrócenie sztuce zachodniej naturalnego ludzkiego uczucia. Pod drewnianym baldachimem Maria trzyma Dzieciątko Jezus, a najstarszy z trzech króli klęka, by ucałować stopy dziecka, odłożywszy koronę; po lewej czekają wielbłądy. Nad stajnią kometa przecina głębokie błękitne niebo zamiast zwykłej gwiazdy, a wszystko oddane jest w solidnych, prostych postaciach i czystych barwach Giotta."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUBENS_AND_ISABELLA"] =
    "Flamandzki obraz olejny baroku, ślubny portret artysty z jego oblubienicą. Młoda para siedzi blisko siebie pod krzewem wiciokrzewu, jej prawa dłoń spoczywa czule na jego dłoni, co jest cichym środkiem obrazu. On siedzi nad nią w czarnym kaftanie z założoną nogą, ona klęczy w fioletowej spódnicy, gorsecie haftowanym złotem, szerokiej kryzie i wysokim słomkowym kapeluszu, oboje spoglądając ku tobie ze spokojnym zadowoleniem."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CHILDS_BATH"] =
    "Amerykański obraz olejny impresjonizmu o codziennej czułości, inspirowany rycinami japońskimi w wysokim punkcie widzenia i płaskich wzorach. Matka w sukni w wyraziste pasy trzyma na kolanach dziecko owinięte w ręcznik, myjąc malcowi stopy w misce z wodą. Obie głowy pochylają się razem nad tym zajęciem, a pokój wokół nich jest patchworkiem wzorów: kwiecista tapeta, malowana skrzynia, ozdobny dywan i biały dzban."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_CARD_PLAYERS"] =
    "Obraz olejny postimpresjonizmu, jeden ze słynnej serii o tym temacie. Dwóch chłopów w kapeluszach siedzi naprzeciw siebie przy małym drewnianym stole, pochłoniętych grą w karty, a pojedyncza butelka wina stoi między nimi jako nieruchomy środek kompozycji. Jeden pali fajkę; farba jest nakładana cierpliwymi, blokowymi pociągnięciami ziemistego brązu, ochry i przygaszonego fioletu, które sprawiają, że postacie zdają się wyrzeźbione i trwałe."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_SWING"] =
    "Francuski obraz olejny rokoka, frywolny, pełen sekretu i najsłynniejszy obraz tej epoki. W bujnym, zarośniętym ogrodzie młoda kobieta w zwiewnej różowej sukni wzlatuje wysoko na huśtawce, zrzucając jeden pantofelek w powietrze, podczas gdy ukryty starszy mężczyzna ciągnie liny z cienia za nią. Jej młody kochanek rozparł się w krzewach róż poniżej, idealnie umieszczony, by zaglądać jej pod spódnice, a kamienny posąg kupidyna przykłada palec do ust."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIANT_MAGNOLIAS"] =
    "Amerykański obraz olejny martwej natury, bujny i niemal tropikalny w nastroju. Dwa ogromne kremowobiałe kwiaty magnolii leżą ścięte na fałdzie głębokoniebieskiego aksamitu, otoczone błyszczącymi ciemnymi liśćmi, z trzecim pąkiem jeszcze zamkniętym. Płatki jaśnieją na niemal czarnym tle, namalowane z woskową, zmysłową precyzją."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_KILLING"] =
    "Kataloński gotycki obraz tablicowy w technice tempery i złota. Święty Jerzy, w czarnej zbroi ze złotą aureolą, wychyla się ze swojego stającego dęba białego rumaka, by wbić długą włócznię w rozwartą paszczę nietoperzoskrzydłego smoka, a ziemia wokół nich zasłana jest kośćmi i czaszkami. Księżniczka w różowej sukni modli się na skalnym występie za nimi, a widzowie tłoczą się na białych murach zamku powyżej."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JACQUES_AND_BERTHE"] =
    "Modernistyczny olejny podwójny portret rzeźbiarza Lipchitza i jego żony, namalowany w niewątpliwie rozpoznawalnym stylu Modiglianiego. Mąż stoi w ciemnym garniturze, dłoń wsparta na ramieniu siedzącej żony, której rumiana twarz wyrasta z białego koronkowego kołnierza. Oboje mają charakterystyczne dla artysty wydłużone twarze, długie nosy i puste migdałowe oczy, a ich imiona naskrobane są u góry płótna."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DASH_FOR_TIMBER"] =
    "Amerykański obraz olejny z Dzikiego Zachodu, ten rodzaj pełnej akcji sceny pościgu, który ukształtował obraz Starego Zachodu w powszechnej wyobraźni. Ośmiu kowbojów galopuje wprost na patrzącego w pełnym pędzie, kopyta koni oderwane od ziemi, dwóch jeźdźców skręca się w siodle, by odstrzeliwać się gromadzie konnych Apaczów ścigających ich w tumanie kurzu z tyłu. Jeden z mężczyzn osuwa się ranny na towarzysza, gdy gnają ku drzewom przy lewej krawędzi suchej równiny."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GEORGE_WASHINGTON_PORTRAIT"] =
    "Amerykański portret państwowy w oleju, oficjalny wizerunek pierwszej prezydentury. Waszyngton stoi w całej postaci w prostym czarnym aksamitnym stroju, jedno ramię wyciągnięte w geście przemowy, w drugiej dłoni ceremonialny miecz, obok stolik z piórem i kałamarzem. Otaczające go akcesoria to republikańska wspaniałość: złocone krzesło z tarczą w gwiazdy i pasy, marmurowe kolumny oraz zwój szkarłatnej kotary z tęczą przebijającą się przez burzowe chmury w głębi."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ATTACK_ON_BEIJING"] =
    "Japoński barwny drzeworyt w stylu wojennej ilustracji prasowej, z podpisami po japońsku i angielsku. Wojska sprzymierzone szturmują mury pałacu cesarskiego w Pekinie: czerwono umundurowani brytyjscy żołnierze z flagą Union Jack nacierają z pierwszego planu, a biało umundurowana japońska piechota posuwa się po prawej stronie. Wybuchy pocisków wiszą jak białe kłęby nad zielonym placem apelowym, w głębi widać bramę pałacu o niebieskim dachu i dymiące mury."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUMO_WRESTLER"] =
    "Japoński drzeworyt ukiyo-e, portret gwiazdorskiego zapaśnika poza służbą. Potężny mężczyzna stoi w całej okazałości w czarnym kimonie narzuconym na wzorzyste szaty, miecze u pasa, ocierając czoło chustą w kratę, gdy niesie zwinięty płaszcz przerzucony przez ramię. Jego imię biegnie wzdłuż prawej krawędzi w grubych czerwonych panelach kaligrafii, a postać jest płaska i monumentalna na tle czystego papieru."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_TIGER_IN_TROPICAL_STORM"] =
    "Obraz olejny w stylu naiwnym pędzla samouka, francuskiego celnika, który nigdy nie widział dżungli. Tygrys o szeroko otwartych oczach przyczaja się nisko w długiej, smaganej wiatrem trawie, z obnażonymi zębami, schwytany w burzę, która kładzie na bok każdą roślinę. Dżungla to gęsty wzór stylizowanych liści w zieleniach i czerwieniach, ze skośnymi srebrnymi smugami deszczu przeciągniętymi przez całe płótno niczym gaza."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_HOME_GUARD"] =
    "Węgierski portret olejny w stylu biedermeier z czasów rewolucji 1848 roku. Brodaty żołnierz-obywatel siedzi w prostej kurtce z niefarbowanego lnu, obie dłonie w rękawiczkach spoczywają na rękojeści wzniesionej pionowo szabli, a czerwono-biało-zielona opaska narodowa na rękawie głosi jego sprawę. Patrzy w bok ze spokojną determinacją, oświetlony ciepło na tle ciemnoczerwonej kotary, czerwono podszyty płaszcz przerzucony przez krzesło."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CEREMONIAL_SITTING"] =
    "Rosyjski obraz olejny w nurcie realizmu, na ogromną skalę, zbiorowy portret całej rady rządzącej imperium. Dziesiątki sędziwych mężów stanu w ciemnych mundurach ciężkich od złotych galonów i czerwonych szarf siedzą wokół wielkiej podkowy z czerwonych krzeseł w białej kolumnowej sali obwieszonej żyrandolami i portretami królewskimi. Każda z ponad sześćdziesięciu twarzy jest indywidualnym portretem, namalowanym szybkim, pewnym realizmem Riepina."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUSSIAN_TSAR"] =
    "Rosyjski obraz historyczny w oleju, odtwarzający szesnastowieczną procesję królewską. Car w futrzanej czapie i szacie ze złotego brokatu jedzie na białym koniu przez śnieg, poprzedzany przez gwardzistów w jaskrawoczerwonych kaftanach niosących wysokie zakrzywione berdysze. Tłum klęka i bije pokłony do ziemi po obu stronach stratowanej, ośnieżonej drogi, a w tle drewniane zabudowania starego ruskiego miasta pod bladym zimowym niebem."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CRUCIFIXION_OF_SAINT_PETER"] =
    "Włoski obraz olejny w stylu barokowym, brutalny i cielesny w charakterystycznym stylu Caravaggia. Trzej robotnicy z wysiłkiem dźwigają drewniany krzyż, na którym sędziwy święty Piotr został przybity głową w dół, jeden ciągnie za linę, drugi przykuca pod belką, ich twarze są ukryte. Białobrody święty unosi głowę, by spojrzeć na własną przybitą dłoń, a jego umięśnione, stare ciało wyłania się z czarnego mroku w jednym twardym świetle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LANDSCAPE_WITH_ANT_BEAR"] =
    "Holenderski pejzaż kolonialny w oleju, namalowany przez pierwszego wykształconego w Europie artystę, który pracował w Brazylii. Szeroka, nasłoneczniona dolina z rzeką otwiera się pod wielkim niebem między dwiema wysokimi palmami, a na dalekich wzgórzach widać kolonialną osadę z białych domów. Grupa afrobrazylijskich postaci idzie ścieżką na pierwszym planie, niosąc tobołki, a tytułowy długonosy mrówkojad węszy w zaroślach w prawym dolnym rogu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DUTCH_MEN_O_WAR"] =
    "Holenderski obraz marynistyczny w oleju ze złotego wieku, pędzla najwybitniejszego ówczesnego malarza okrętów. Wysokie drewniane okręty wojenne stoją na kotwicy na wodzie gładkiej jak szkło, ich żagle zwisają luźno, a kadłuby odbijają się w morzu, każda lina takielunku oddana dokładnie. Łodzie wiosłowe przewożą pasażerów między jednostkami pod rozległym niebem nasłonecznionych cumulusów, a cała scena skąpana jest w złotym spokoju."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HARBOR_IN_BALAKLAVA"] =
    "Kolorowana litografia z wojny krymskiej, narysowana przez jednego z pierwszych artystów wojennych, którzy dokumentowali kampanię na miejscu. Na ponurym brzegu przystani chorych i rannych żołnierzy owiniętych w białe koce wsadza się z noszy niesionych przez muły do czekającej łodzi wiosłowej. Nagie brązowe wzgórza wznoszą się za skupiskiem postaci, a po zboczu rozsiane są wojskowe baraki i namioty, barwy stłumione i dokumentalne."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PEACEMAKERS"] =
    "Amerykański obraz historyczny w oleju, przedstawiający prawdziwą naradę z ostatnich dni wojny secesyjnej. Prezydent Lincoln siedzi w kabinie parowca, słuchając uważnie, podbródek wsparty na dłoni, podczas gdy generał Sherman gestykuluje w trakcie sporu; generał Grant i admirał Porter dopełniają krąg czterech postaci w ciemnych garniturach. Przez okna kabiny za nimi tęcza przebija się przez przejaśniające się niebo, cichy znak nadchodzącego pokoju."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_CHITASEI"] =
    "Japoński drzeworyt ukiyo-e ze słynnego cyklu Kuniyoshiego przedstawiającego 108 bohaterów chińskiej powieści Opowieści znad brzegów rzek. Uczony-strateg Wu Yong stoi w powłóczystej ciemnej szacie wzorzystej w smoki, gładząc brodę w zamyśleniu pod nocnym niebem usianym gwiazdami. Obok niego na zdobnej podstawie stoi wielki globus niebieski, a postać oprawiają panele z japońskim tekstem."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_LOUIS"] =
    "Angielski osiemnastowieczny portret olejny rzeźbiarza uchwyconego przy pracy. Roubiliac, w miękkiej czapce i rozpiętej koszuli z podwiniętymi rękawami, zatrzymuje się z uniesionym narzędziem modelarskim i zerka w bok, pracując nad glinianą figurką Szekspira ustawioną na stojaku. Wolną ręką wskazuje na własne dzieło, ciepło oświetlony na tle ciemnego wnętrza pracowni."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_NASSER"] =
    "Perski dworski portret Kadżarów, olejny, królewski przepych nałożony grubą warstwą. Młody wąsaty szach siedzi sztywno wyprostowany w szkarłatnym mundurze pokrytym złotym haftem, sznurami pereł, klejnotami zdobionymi epoletami i niebieską szarfą, z jedną dłonią na wysadzanej kamieniami szabli. Nosi wysoką czarną czapkę z pióropuszem z diamentów, a jego ciemno obwiedzione oczy spoglądają wprost przed siebie na tle głębokiej oliwkowej barwy odbitej królewską inskrypcją."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FIELD_WITH_SHEAFS"] =
    "Niemiecki pejzaż o ekspresjonistycznym zacięciu, olejny, malowany szerokimi, energicznymi pociągnięciami. Zżęte pole pszenicy wypełnia pierwszy plan rzędami złotych snopów ułożonych w pochylone wiązki, żółć nałożona grubo i jaskrawo. Linia ciemnozielonych drzew zamyka pole, a powyżej rozciąga się blade fioletowoniebieskie niebo z wietrznymi chmurami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AT_THE_EDGE_OF_THE_BROOK"] =
    "Francuski akademicki obraz olejny, wygładzony do szklistej doskonałości, z której Bouguereau słynął. Dwoje bosych wiejskich dzieci siedzi na kamieniu nad brzegiem strumienia; młodsza dziewczynka ściąga pończochę, a jej ciemnowłosa towarzyszka podkasuje spódnicę, by wejść do wody. Wymieniają spojrzenie w trakcie rozmowy, ich skóra i potargane włosy oddane z fotograficzną gładkością na tle łagodnego wiejskiego pejzażu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS_ALT"] =
    "Włoski romantyczny obraz olejny, najsłynniejszy pocałunek we włoskim malarstwie i ukryty patriotyczny emblemat zjednoczenia. W średniowiecznym kamiennym korytarzu młody mężczyzna w kapeluszu z pióropuszem i brązowym płaszczu odgina kobietę do tyłu w namiętnym pocałunku, jedną stopę już stawiając na schodach, jakby zatrzymał się w ucieczce. Jej sukienka z bladoniebieskiego atłasu wlewa do sceny światło, podczas gdy cienista postać zbliża się przez łuk w głębi."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MOVING_HOUSE"] =
    "Rosyjski realistyczny obraz olejny cichej miejskiej biedy. Starsze małżeństwo brnie przez zamarznięty lód rzeki w Petersburgu, niosąc cały swój dobytek w płóciennym tobołku; mężczyzna wspiera się na lasce, oboje opatuleni w znoszone płaszcze i chusty przed chłodem. Mały pies biegnie truchtem przed nimi, a złocona iglica twierdzy Pietropawłowskiej wznosi się przez zimową mgłę za ich plecami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MEXICAN_EXPEDITION"] =
    "Francuski historyczny obraz olejny o tematyce morskiej, w stylu reportażu, gęsty od akcji. Francuski okręt wojenny pod trójkolorową banderą dominuje na pierwszym planie po lewej, oficerowie na jego pokładzie kierują bombardowaniem meksykańskiej twierdzy San Juan de Ulua, dym unosi się nad wodą. Pociski wzbijają wodę przy łodziach wiosłowych przewożących ludzi między statkami, a na zamglonym horyzoncie widać ośnieżony wulkan."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_DAY_OF_POMPEII"] =
    "Rosyjski romantyczny obraz olejny na ogromnym płótnie, epos o katastrofie swojego stulecia. Niebo nad Pompejami płonie czerwienią i czernią, gdy Wezuwiusz wybucha, posągi spadają z dachu, a błyskawica rozłupuje chmurę popiołu. Tłumy mieszkańców w rzymskich strojach uciekają przez spadające szczątki, osłaniając pod płaszczami dzieci i starców, podczas gdy w samym środku powalona kobieta leży rozciągnięta obok przewróconego rydwanu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ACCOLADE"] =
    "Angielski obraz olejny w stylu prerafaelickim, baśniowa wizja rycerskości. Złotowłosa królowa w powłóczystej białej sukni dotyka mieczem ramienia klęczącego rycerza, pasując go na rycerza przed niewielkim dworskim audytorium. On pochyla głowę w kolczudze i czerwonym kaftanie narzutowym, jego hełm leży na podłodze obok niego, a kamienna sala i czerwone podwyższenie są oddane w rozjarzonych romantycznych detalach."
