-- Mod-authored world wonder splash painting descriptions, pl_PL overlay.
-- Baseline in CivVAccess_WonderDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_MISSING"] = "Brak opisu tego cudu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOTHERLAND_STATUE"] =
    "Gra ukazała się bez obrazu dla tego cudu; nie ma ilustracji do opisania."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ALHAMBRA"] =
    "Spod cienia smukłej kamiennej kolumny dziedziniec pałacowy otwiera się wokół długiej sadzawki, to Dziedziniec Mirtów w Alhambrze. Sadzawka biegnie w dal ku arkadowemu portykowi z różowego kamienia, którego łuki odbijają się w nieruchomej wodzie. Za nim na tle błękitnego nieba wznosi się ciepła w barwie kwadratowa wieża obronna. Niskie strzyżone żywopłoty obrzeżają brzeg wody, na pierwszym planie stoi roślina w doniczce, a wzdłuż nasłonecznionych chodników rozmawiają niewielkie grupki w długich szatach. Jasne popołudniowe słońce wypełnia dziedziniec, bielejąc tam, gdzie pada na bruk. Pod kolumnadą leży głęboki cień."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ANGKOR_WAT"] =
    "W tle wznosi się skupisko piętrowych szarych kamiennych wież w kształcie zamkniętych pąków lotosu, na wpół przesłoniętych palmami pod gorącym, bladym niebem. Na pierwszym planie trwa świąteczny pochód: szary słoń kroczy przez gęsty tłum, z jeźdźcem na karku i osłoniętym baldachimem siedziskiem na grzbiecie, ocienionym wysokim czerwono-pomarańczowym parasolem. Tłum napiera ze wszystkich stron w białych, szafranowych i śliwkowych szatach; głowy owinięte, ramiona obnażone, a każda twarz zwraca się ku przechodzącemu słoniowi. Scena tonie w słońcu i kurzu, a kamień jest chłodny, zielonkawoszary na tle ciepłej skóry i tkanin poniżej."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BIG_BEN"] =
    "Gotycka wieża zegarowa stoi nocą u wylotu mostu Westminster, jej czterotarczowy zegar jarzy się bursztynowo blisko szczytu. Nad zegarem iglica zanika w głębokim błękicie nieba. Długa fasada londyńskiego Pałacu Westminsterskiego ciągnie się w lewo, jej okna i kamieniarka rozświetlone ciepłym złotem reflektorów. Na dalekim krańcu wznoszą się wieże o spiczastych zwieńczeniach. Most przecina pierwszy plan z rzędem świecących latarni. Kilka powozów i postaci rysuje się małych i ciemnych na jezdni. Cała scena utrzymana jest w nocnych błękitach na tle złota lamp i rozświetlonego kamienia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BOROBUDUR"] =
    "Schodkowa piramida z szarego kamienia wulkanicznego wyrasta z dżungli niczym tarasowate wzgórze, jej górne kondygnacje opasane wieńcem małych stup w kształcie dzwonów. Większa stupa wieńczy szczyt. Z niższych tarasów wyrastają palmy, a las ciśnie się ciasno wokół podstawy. Na pierwszym planie szereg mnichów w pomarańczowych i czerwonych szatach wspina się ku świątyni zacienioną ścieżką w dżungli, a po zamglonym niebie nad nimi rozpierzchają się ptaki. Paleta jest mglista, zielonoszara, a szaty są jedyną mocną nutą koloru."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BRANDENBURG_GATE"] =
    "Szeroka klasycystyczna brama z wietrzejącego piaskowca stoi w głębi gwarnego miejskiego placu, wsparta na sparowanych rzędach ciężkich kolumn i zwieńczona kwadrygą, brązowym posągiem czterokonnego rydwanu, który rysuje się ciemno na tle bladego, zachmurzonego nieba. Niższe skrzydło z kolumnadą odbiega w prawo ku otaczającym kamiennym budynkom. Plac przed nią to dziewiętnastowieczny Berlin: konne powozy toczące się po bruku, jeźdźcy i tłumy w długich ciemnych płaszczach i cylindrach, a po lewej wznosi się latarnia. Barwy są stonowane, szare i brązowe, a światło płaskie i równomierne."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BROADWAY"] =
    "Dzielnica teatralna nocą na początku dwudziestego wieku, ulica mokra od deszczu i lśniąca odbitym światłem. Rozświetlone markizy i szyldy tłoczą się po obu stronach alei, białe i czerwone żarówki układają się w nazwy spektakli. Pośrodku przecznicy jarzy się jedna długa, jasna fasada teatru. Tłumy w ciemnych płaszczach i kapeluszach wypełniają chodniki i wylewają się na ulicę między nieliczne stare samochody, wszyscy mali na tle wysokich, ciemnych biurowców wznoszących się w nocne niebo. Paleta jest głęboko granatowoczarna, przełamana plamami ciepłego białego, czerwonego i żółtego elektrycznego światła."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CN_TOWER"] =
    "Smukła betonowa igła wznosi się pośrodku panoramy Toronto, rozszerzając się w zaokrągloną kapsułę widokową blisko szczytu i przechodząc dalej w iglicę anteny. Wokół niej rozstępują się burzowe chmury, a snopy słonecznego światła przelewają się za wieżą przez szczelinę, zamglając biurowce po obu stronach. Na pierwszym planie wgłębiona arteria szybkiego ruchu płynie potokiem aut, reflektory i czerwone tylne światła jarzą się w mroku między betonowymi nasypami. Cała scena jest stalowoszara i złota. Miasto na poły tonie w cieniu burzy, na poły w przebijającym się świetle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CHICHEN_ITZA"] =
    "Schodkowa piramida, El Castillo, stoi pośrodku pod płonącym pomarańczowym niebem, dziewięć kwadratowych kondygnacji wspina się ku małej świątyni na szczycie. Szerokie schody biegną prosto w górę po jej licu. Przy lewym brzegu wznosi się druga piętrowa świątynia, a dym snuje się po słońcu, gdy zawisa ono nisko i czerwone. Plac poniżej wypełnia tłum Majów, większość zwrócona tyłem: obnażone ramiona, pióropusze, uniesione laski i włócznie. Po prawej na kamiennej platformie stoi grupka wojowników. Wszystko przesycone jest rdzawym, bursztynowym światłem zmierzchu. Tłum zapada się w ciemną sylwetkę na tle rozjarzonego kamienia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CRISTO_REDENTOR"] =
    "Kolosalny Chrystus z bladego kamienia, widziany od tyłu i z góry, stoi na szczytowym cokole swojej góry z ramionami rozpostartymi szeroko nad zatoką w dole. Jego odziane plecy i wyciągnięte ramiona wypełniają bliski kadr, głowa lekko pochylona do przodu. Daleko poniżej i w głębi Rio de Janeiro rozlewa się wokół wody białymi smugami zabudowy, z zaokrąglonym garbem Głowy Cukru wyrastającym z zatoki pośród zielonych wysp i zakotwiczonych statków. Mgła łagodzi dal, pozostawiając miasto i morze w bladych błękitach i szarościach, podczas gdy ramiona posągu chwytają dzienne światło."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_COLOSSUS"] =
    "Daleko, u skalistego wejścia do portu, stoi spiżowy olbrzym z jednym ramieniem uniesionym, na poły rozpłynięty w złotej mgle. Na tle nieba w barwie mosiądzu jest bardziej sylwetką niż posągiem. Pierwszy plan należy do morza: niewielka żaglówka przechyla się ku patrzącemu pod pojedynczym szerokim żaglem, na rufie widać dwóch lub trzech marynarzy. Inne żagle rozrzucone są po całym porcie. Niskie skały ciągną się wzdłuż linii wody po prawej, a woda niesie tę samą ciepłą złocistość co niebo. Cały obraz utrzymany jest w jednej barwie, w bursztynowym świetle i mgle. Kolos jarzy się przez nią jak postać ze snu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOSQUE_OF_DJENNE"] =
    "Długi gliniany mur wież i szczytów ciągnie się przez całe tło, z cegły mułowej w głębokiej czerwono-brązowej barwie. Jego lica najeżone są toronami, rzędami drewnianych belek sterczących ze ścian niczym ciernie. Niebo za nim gęste jest od pomarańczowego pyłu i dymu, słońce ginie w mgle. Cały pierwszy plan to dzień targowy: markizy i baldachimy w czerwieni i bieli, zwierzęta między straganami i gęsty tłum w jaskrawych szatach przesuwający się między nimi. Upał i pył spajają scenę, a wszystko namalowane jest w pomarańczach, rdzach i brązach."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_EIFFEL_TOWER"] =
    "Ciemna żelazna kratownica nóg i kratowych platform wypełnia lewą górną część kadru, tak blisko, że szczyt obcięty jest krawędzią obrazu. Pod nią scena to popołudnie belle epoque na trawie: grupy w długich białych sukniach i ciemnych garniturach piknikują na rozległym zielonym trawniku, a wokół nich rozłożone są parasolki, słomkowe kapelusze i kosze. Pośrodku stoi kobieta w bieli. Za trawnikiem przesuwa się Sekwana, a jasny kamień Paryża ciągnie się wzdłuż dalekiego brzegu pod miękkim szarym niebem. Paleta to chłodne zielenie i szarości. Białe suknie chwytają to skąpe światło, jakie jest."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_FORBIDDEN_PALACE"] =
    "Pałacowe sale z rozłożystymi dachami krytymi złotą dachówką i o głęboko czerwonych ścianach stoją po drugiej stronie rozległego brukowanego dziedzińca, oglądane z wyniesionego marmurowego tarasu na pierwszym planie. Po lewej, na balustradzie tarasu, przyczaił się ciemny posąg lwa strażniczego, a wzdłuż schodów stoją odziane w szaty postacie. W dole na dziedzińcu, przed centralną salą, ustawiły się w ciasnym szyku szeregi żołnierzy, przytłoczone otaczającą je architekturą. Blade słońce wisi na zamglonym bursztynowym niebie, a cała scena skąpana jest w zakurzonym złocie odcinającym się od czerwieni ścian."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GLOBE_THEATER"] =
    "Okrągły drewniany teatr oglądany z jego własnej sceny w trakcie przedstawienia. Trzy kondygnacje galeriowych balkonów wyginają się wokół centralnego dziedzińca, każda balustrada obsadzona widzami. Na otwartej posadzce w dole tłoczą się stojący widzowie, blade morze twarzy. Na scenie aktor w ciemnym kaftanie gra scenę zwróconą ku dwóm kobietom w długich sukniach, z których jedna gestykuluje wyciągniętym ramieniem. Malowany baldachim dachu wcina się w prawym górnym rogu na rzeźbionym słupie. Miękkie dzienne światło pada z otwartego nieba nad dziedzińcem. Drewno jest w ciepłej kremowej i brązowej barwie, a tłum naszkicowano blado wokół ostrzejszych postaci na scenie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_FIREWALL"] =
    "Abstrakcyjna cyfrowa scena bez żadnego budynku, mroczna cyberprzestrzeń oddana w zieleniach i czerni. Szerokie wygięte powierzchnie przecinają kadr niczym wały danych, ich lica wyłożone świecącymi zielonymi cyframi binarnymi, a wzdłuż nich smugują się świetliste ślady jak ruch na autostradzie nocą. Widmowe ekrany i siatki unoszą się w mroku powyżej, sugerując obwody i inwigilację. Cały obraz wygląda jak wewnętrzny świat komputera, fosforowo zielone światło na czerni."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIBRARY"] =
    "Monumentalna klasyczna sala wznosi się przed zalanym słońcem placem, z wysokimi czerwonymi sztandarami zawieszonymi między kolumnami jej długiej kolumnady. Nad kolumnami biegnie rzeźbiony fryz, a szerokie schody schodzą ku bruku. Plac oglądany jest z zacienionego portyku na pierwszym planie: po lewej wznosi się kolumna, po prawej na cokole siedzi kamienny sfinks, a w oddali za nimi widać białą kopułę. Uczeni i mieszczanie w togach i kolorowych szatach gromadzą się na schodach i po całym placu, większość stoi po dwie i po trzy osoby pogrążone w rozmowie, podczas gdy jedna postać siedzi samotnie ze zwojem. Kamień jest w ciepłej kremowej barwie w słońcu pod błękitnym niebem pasmowanym chmurami, a sztandary są najmocniejszą czerwienią w scenie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIGHTHOUSE"] =
    "Wysoka blada wieża z piętrzących się kondygnacji stoi daleko po prawej, oświetlona przez przerwę w burzy, z latarnią jarzącą się na szczycie. Reszta obrazu to wzburzone morze: szereg starożytnych galer pod czerwono-białymi pasiastymi żaglami rejowymi mozoli się przez ciężkie szaro-zielone fale ku światłu, z dziobami wygiętymi wysoko. Bryzgi rozpryskują się biało o kadłuby. Ciemne burzowe chmury napierają na całą scenę, a niebo otwiera się tylko wokół wieży, jakby okręty zmierzały ku niej. Żagle niosą jedyną ciepłą barwę w obrazie z łupku, piany i deszczu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_WALL"] =
    "Szeroki kamienny wał biegnie od dołu kadru prosto w górę i przez góry, jego blankowane przedpiersia wspinają się po grzbietach, aż mur kurczy się do nitki na najdalszych szczytach. Przy pierwszym wzniesieniu stoi kwadratowa dwukondygnacyjna wieża strażnicza z łukowymi oknami i niewielkim krytym pawilonem na szczycie. Bieg muru zakręca przez nią. Góry są pofałdowane i zielone, porośnięte krzewami zbocza opadają w mgłę dolina za doliną. Nigdzie na murze nie widać żadnej postaci. Światło jest chłodne i czyste, szary kamień na tle głębokiej zieleni pod bladym niebem."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HAGIA_SOPHIA"] =
    "Wielka kopułowa bazylika wieńczy panoramę miasta o złotej godzinie, jej szeroka centralna kopuła wznosi się ze wzniesienia oszkarpowanych murów i półkopuł. Cztery smukłe minarety stoją po rogach, budowla przedstawiona jest jako meczet, którym później się stała. Wokół niej dachy Stambułu spadają w dół zbocza w barwach piaskowej i szarej, poprzecinane drzewami, mniejszymi kopułami i odległymi wieżami rozmywającymi się we mgle. Po lewej stronie odległość zamykają błysk wody i niskie wzgórza. Wszystko leży pod ciepłym bursztynowym niebem, a sylwetka kopuły rysuje się ciemnym złotem na tle światła."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HANGING_GARDEN"] =
    "Ogrodowy dziedziniec leży wewnątrz murów z ciepłych piaskowcowych arkad. Palmy wznoszą się nad alejkami, a zieleń przelewa się przez każdą arkadę i półkę. Postacie w szatach przechadzają się i rozmawiają po dwoje i troje wzdłuż zacienionych ścieżek wśród rabat i niewielkich drzew. Przez centralną arkadę i ponad murem białe pałacowe miasto pnie się na wzgórze piętrzącymi się tarasami, lśniąc w oddali niczym korona ogrodu. Wszystko stoi w jasnym słońcu, głęboka zieleń listowia na tle złocistego kamienia i bladego nieba."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HIMEJI_CASTLE"] =
    "Biały zamkowy donżon wznosi się z zalesionego wzgórza u góry kadru, kondygnacja po kondygnacji bladych murów pod wygiętymi szarymi dachami. Mniejsze białe wieżyczki skupiają się poniżej niego wśród drzew. Droga prowadząca w górę przechodzi przez wioskę o ciemnych dachach krytych dachówką, a w środkowym planie nad przejściem rozpina się brama o czerwonej ramie. Konni samuraje jadą ku niemu przez pierwszy plan, wysokie czerwone chorągwie sterczą im z pleców. Pancerni piechurzy czekają przy domach po prawej stronie. Dzień jest łagodny i pochmurny, a cała scena utrzymana jest w zieleniach i szarościach wokół białego donżonu. Chorągwie są najostrzejszą czerwienią w scenie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HUBBLE"] =
    "Długi srebrny walec owinięty foliowymi panelami unosi się na orbicie, jego uchylna klapa przesłony jest otwarta od strony bliższego końca, odsłaniając ciemny otwór optyki. Płaskie panele słoneczne w miedziano-złotych ramach rozkładają się po jego bokach, a astronauta w skafandrze pracuje przy jego boku, mały na tle instrumentu. Część zadokowanego statku kosmicznego wsuwa się w prawy dolny róg kadru. Za wszystkim Ziemia wypełnia obraz, łuk błękitnego oceanu i białej chmury opadający w czarną przestrzeń. Paleta jest srebrno-złota na tle błękitu Ziemi."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_KREMLIN"] =
    "Śnieg pada nad placem Czerwonym, gdzie mur twierdzy z ciemnoczerwonej cegły biegnie wzdłuż prawej strony pod ciężkim szarym zimowym niebem. Czerwona flaga powiewa nad przysadzistym, schodkowym blokiem mauzoleum Lenina ustawionym przy murze, a dalej wysoka wieża wznosi się w mrok, jej iglica ma kształt stromego namiotu. Tłumy w długich ciemnych płaszczach i futrzanych czapach przesuwają się przez ośnieżony plac w powolnej kolejce, pojedyncze postacie brną przez pierwszy plan tyłem do patrzącego. Obraz jest niemal monochromatyczny, biały śnieg i grafitowa szarość, a cegła i flaga są jego jedynymi czerwieniami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LEANING_TOWER"] =
    "Okrągła biała dzwonnica wznosi się z zielonego trawnika, opasana piętro po piętrze otwartymi marmurowymi arkadami i przechylona niewątpliwie w prawo. Stoi jasno na tle ciemnego burzowego nieba. Blady bok katedry w Pizie stoi przy prawej krawędzi kadru, a niższe miejskie budynki w barwie ochry zamykają zieleń po lewej. Mieszczanie i mnisi w długich brązowych i czerwonych szatach przecinają trawnik luźnymi procesjami, mali pod wieżą. Światło jest teatralne: prześwit w chmurach oświetla biały marmur niczym reflektorem, podczas gdy niebo za nim pozostaje niemal czarne."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LOUVRE"] =
    "Szary kamienny pałac rozciąga się w tle, wysoki centralny pawilon z rzeźbionym ornamentem i stromymi łupkowymi dachami mansardowymi, ze skrzydłami odchodzącymi na obie strony. Artyści ukazują Luwr w czasach, gdy był pałacem królewskim, na długo przed szklaną piramidą współczesnego muzeum. Z przodu leżą ogrody w stylu francuskim: płaskie trawniki przecięte żwirowymi ścieżkami, młode drzewa i niewielka fontanna tryskająca wodą po lewej. Spacerowicze w strojach z dziewiętnastego wieku rozsiani są po alejkach, kobiety w długich białych sukniach i mężczyźni w ciemnych surdutach i cylindrach. Para zatrzymuje się razem po prawej. Dzień jest łagodny i perłowy. Wszystko jest szarym kamieniem i stłumioną zielenią pod bladym niebem."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MACHU_PICHU"] =
    "Kamienne miasto leży w wysokim górskim siodle, rolnicze tarasy wstępują po zboczu ku skupiskom budynków o spadzistych dachach krytych strzechą. Za nim stromy szczyt Huayna Picchu pnie się w chmury. Mgła wisi nad otaczającymi pasmami, a dolina opada w cień poniżej. Na ścieżce na pierwszym planie niewielka grupa z jucznymi lamami mozolnie wspina się ku bramom miasta, drobna na tle tarasów. Światło wpada bladymi snopami przez pogodę, wydobywając ciepły piaskowy kamień z zieleni i szarości Andów."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MAUSOLEUM_HALICARNASSUS"] =
    "Masywny kwadratowy cokół z białego marmuru, opasany rzeźbionymi fryzami, wznosi się ku wieńcowi kolumn u góry kadru. Mauzoleum w Halikarnasie góruje nad placem, gdzie na wysokich filarach stoją posągi, wśród nich pancerna postać i jeździec. Między brukami zasadzono ciemne cyprysy. Postacie w białych i czerwonych szatach gromadzą się poniżej, przyćmione przez pomnik. Dzień jest jasny i bezchmurny. Biały marmur i spiętrzone białe chmury rysują się na tle głębokiego błękitu nieba."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NEUSCHWANSTEIN"] =
    "Blada zjawa zamku stoi na zalesionym grzbiecie, białe mury i skupione wieże na poły rozpływają się w padającym śniegu w lewym górnym rogu kadru. Pierwszy plan to droga prowadząca w górę: ciemny zamknięty powóz czeka na zakręcie, podczas gdy jeźdźcy przesuwają się obok w górę zbocza, rozdeptując śnieg na trakcie. Przyprószone śniegiem jodły obrastają drogę i zamykają się nad doliną poniżej. Obraz jest w całości zimowo szary i biały. Jeźdźcy i powóz są jedynymi ciemnymi kształtami na jego tle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NOTRE_DAME"] =
    "Gotycka katedra wznosi się nad średniowiecznym Paryżem, widziana z góry; jej bliźniacze kwadratowe wieże, środkowa iglica i długa nawa wsparta przyporami górują daleko nad wszystkimi dachami wokół. Miasto ciśnie się do jej murów gęstą plątaniną domów z dwuspadowymi szczytami i dymiących kominów, a Sekwana zakręca przez pierwszy plan obok nabrzeży i małych łodzi. Niebo jest ciężkie i szare, ale smugi słonecznego światła przebijają przez chmury i padają wprost na katedrę, rozświetlając jej kamień na złoto, podczas gdy miasto pozostaje w łupkowym cieniu. Horyzont gaśnie płaski i blady za dachami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ORACLE"] =
    "Okrągła kolumnowa świątynia pod kamienną kopułą, tolos, stoi na nadmorskiej skale na końcu skalistego cypla, a u jej stóp w urwisku otwiera się naturalny łuk. Artyści umieścili sanktuarium na wybrzeżu, nie na zboczu delfickiej góry. Ścieżka wije się ku niej obok przybrzeżnych sadzawek i sterczących skał. Na pierwszym planie pielgrzymi w czerwonych, niebieskich i białych szatach idą szlakiem małymi grupami, ujęci z obu stron przez ciemne sosny pochylone do wnętrza kadru. Jest chłodny wczesny wieczór, blade rozświetlone księżycem niebo i szarozielone morze wokół ciepłego kamienia świątyni."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PARTHENON"] =
    "Długa dorycka świątynia stoi w całości w górnej części kadru, a jej kolumnada dźwiga rzeźbiony i malowany przyczółek. Marmur jest ciepło złoty pod niebem kłębiących się szarych chmur. Szerokie stopnie schodzą od niej przez kępy niskich zielonych krzewów, z brązowymi posągami uniesionymi na cokołach po lewej. Stopniami schodzi procesja Greków w karmazynowych płaszczach, a pośrodku pojedynczy hoplita zwraca się ku patrzącemu w hełmie z grzebieniem, z okrągłą tarczą na ramieniu. Czerwienie płaszczy płoną na tle kamienia, a światło ma ciężki blask dnia, który zaraz przejdzie w burzę."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PENTAGON"] =
    "Widok z lotu ptaka na pięcioboczny gmach dowództwa, którego koncentryczne pięciokątne pierścienie z bladego betonu i ciemnych dachów schodzą tarasowo ku zielonemu dziedzińcowi pośrodku. Drogi i parkingi otaczają budynek, a za nimi trawniki i drzewa o jesiennych barwach. Z tyłu płynie Potomak, przecięty mostami. Na drugim brzegu stolica leży w mgle, biały obelisk pomnika Waszyngtona i kopuła Kapitolu drobne na horyzoncie. Dzień jest zwykły i szary; nic w scenie się nie wyróżnia poza kształtem budynku."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PETRA"] =
    "Patrzący stoi wewnątrz Siku, wąskiego kanionu, którym wiedzie dojście, między różowoczerwonymi skalnymi ścianami, które piętrzą się w cieniu po obu stronach kadru. Przez szczelinę, oświetlony pełnym słońcem, stoi Al-Chazna, Skarbiec, fasada wykuta wprost w urwisku. Jej dwie kondygnacje klasycznych kolumn i przyczółków wznoszą się w różowym piaskowcu, z okrągłym pawilonem pośrodku górnego poziomu. Podróżni zmierzają ku niej po piaszczystym dnie kanionu: dwaj jeźdźcy kołyszą się na wielbłądach na bliskim pierwszym planie, a postacie w szatach idą za nimi. Obraz jest cały w ciepłych czerwieniach i zacienionych brązach, a wykuta fasada jarzy się na końcu ciemnego przejścia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PORCELAIN_TOWER"] =
    "Wysoka pagoda wznosi się nad świątynnym ogrodem, kondygnacja po kondygnacji ciemnych, rozłożystych okapów na smukłym trzonie. Góruje nad dachówkowymi dachami stojących u jej podstawy hal. Ogród rozciąga się na pierwszym planie wokół spokojnego stawu: przycięte sosny, wierzby, kamienne latarnie i rzeźbiony posąg lwa na cokole przy lewej krawędzi. Postacie w szatach przechadzają się żwirowymi ścieżkami po dwie i po trzy, a za wieżą piętrzą się zamglone zalesione wzgórza. Scena jest spokojna i zielona, miękkie światło dnia na wodzie, pagoda stoi ciemna na tle bladego nieba."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PRORA_RESORT"] =
    "Monolityczny blok kurortu ciągnie się wzdłuż brzegu, jakby bez końca. Jego blada fasada powtarza w kółko te same rzędy okien, biegnąc wzdłuż plaży, aż znika ku horyzontowi. Najdalszy odcinek wciąż pokryty jest rusztowaniami. Na bliższym końcu stoi wielki okrągły bęben budynku obwiedziony kolumnami na ciemnoczerwonej podstawie, z czerwoną flagą powiewającą z dachu. Niżej plaża tętni życiem: kąpiący się i spacerujący rozsiani drobno po piasku, a szarozielone morze nadciąga z prawej. Górujące rozświetlone słońcem chmury wypełniają niebo nad jasnym nadmorskim popołudniem, kremowy beton na tle błękitnej wody."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PYRAMID"] =
    "Dwie wielkie piramidy stoją blade w pustynnej mgle, bliższa wypełnia górną prawą część kadru. Trzecia stoi mała na horyzoncie. Między nimi w średnim planie przyczaił się Sfinks. Palmy stoją cienką linią wzdłuż piasku, a niskie zburzone mury i bloki obrzeżają zagłębienie na pierwszym planie. Jeździec w czerwieni siedzi na wielbłądzie w prawym dolnym rogu, a po lewej mała karawana wielbłądów przecina piasek, z postaciami idącymi obok. Wszystko jest barwy piasku, płowe i kościanobiałe pod zamglonym białym niebem. Czerwony jeździec to jedyna ostra barwa."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_RED_FORT"] =
    "Forteca z ciemnoczerwonego piaskowca pod atakiem: wysokie mury i okrągłe bastiony wypełniają kadr, białe kopułowe pawilony stoją wzdłuż wałów, z występów wyrasta trawa, a kolumny czarnego dymu wznoszą się od pożarów wewnątrz. Obrońcy tłoczą się na blankach nad bramą. Na pierwszym planie zbrojni żołnierze w zaokrąglonych hełmach prą ku murom, mijając drewnianą katapultę i jej obsługę przy lewej krawędzi. Obraz jest ciężki od czerwonego kamienia i dymu, a białe pawilony i pas bladego nieba to jedyna ulga dla oka."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SISTINE_CHAPEL"] =
    "Ceremonia we wnętrzu kaplicy, oglądana spośród zgromadzonych. Ścianę za ołtarzem od posadzki po sufit pokrywa fresk Sąd Ostateczny, wir postaci na błękicie, a malowane sceny i tkaniny ciągną się wzdłuż ścian bocznych pod wysokimi łukowymi oknami. Freskowane sklepienie ledwie wchodzi w górny skraj kadru. Duchowni w bieli odprawiają nabożeństwo przy oświetlonym świecami ołtarzu, podczas gdy kardynałowie w szkarłacie wypełniają pierwszy plan i ławki wzdłuż ścian. Ich czerwień to najmocniejsza barwa w przyćmionym wnętrzu. Tyle światła dnia, ile jest, pada szare z okien na malowane ściany."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_INTERNATIONAL_SPACE_STATION"] =
    "Kratownicowa stacja zawisa na orbicie na tle czerni kosmosu: długi centralny dźwigar przecięty parami wielkich niebieskoszarych skrzydeł słonecznych, z łańcuchem białych walcowatych modułów i węzłów dokujących skupionych w jego środku. Przy bliższym końcu łańcucha modułów zacumowana jest kapsuła, a panele radiatorów rozkładają się płasko pod dźwigarem. Za nią Ziemia odgina się w głębokim błękicie, jasne smugi chmur na jej nocnej stronie. W czerni ponad nią rozsypane są gwiazdy. Obraz jest czysty i fotograficzny: biały metal, błękitna planeta i nigdzie żadnej postaci."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_OF_LIBERTY"] =
    "Odziana miedziana postać, spatynowana na bladą zieleń, stoi na kamiennym cokole po lewej stronie ruchliwego portu, ramię z pochodnią wzniesione wysoko na tle nieba przerywanego chmurami. Mija ją parowy transatlantyk z początku dwudziestego wieku, czarnokadłubowy, z dwoma czerwono-czarnymi kominami snującymi węglowy dym, a holowniki spieniają wodę u jego boku, prując falę. Niska i zamglona panorama Nowego Jorku leży po prawej, za wodą. Scena jest namalowana w morskich szarościach i zieleniach, dym miesza się z chmurami. Bladozielony posąg jest najwyraźniejszym kształtem w całym tym dymie i chmurach."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STONEHENGE"] =
    "Krąg wielkich stojących głazów zwieńczonych nadprożami wznosi się nocą na ciemnym wrzosowisku, jarząc się ciepło od ognisk rozpalonych gdzieś wewnątrz, jakby trwała ceremonia. Po rozgwieżdżonym niebie nad nim przemyka kometa. W zacienionym pierwszym planie z wrzosowiska sterczą rozrzucone głazy poboczne, a po równinie rozsiane są nieliczne małe ogniska i ledwie widoczne postacie. Wszystko tonie w głębokim nocnym błękicie poza bursztynowym światłem zebranym przy zabytku."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SYDNEY_OPERA_HOUSE"] =
    "Wielkie białe muszle dachu w kształcie żagli wypełniają z bliska prawą część kadru, nachodząc na siebie na tle jasnobłękitnego nieba. Pod nimi widać szkło i ciemną kamieniarkę podstawy budynku. Tuż za nimi stoi przycumowany duży biały statek wycieczkowy, a smukły jacht motorowy tnie falę na pierwszym planie. Po drugiej stronie skrzącego się portu, daleko po lewej, wznoszą się wieżowce Sydney. Dzień jest jasny i pogodny. Białe dachy i białe statki odcinają się na głębokiej niebieskozielonej wodzie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TAJ_MAHAL"] =
    "Białe marmurowe mauzoleum stoi na wprost, u końca swojego długiego ogrodu, jego wielka centralna kopuła wzbiera nad wnęką łukowatej bramy. Po obu stronach wielkiej kopuły siedzą mniejsze zwieńczone kopułkami kioski, a na każdym narożniku platformy wznosi się wieża minaretu. Ogród biegnie prosto ku niemu: wąski kanał lustrzanej wody pośrodku, oflankowany brukowanymi alejkami, rzędami ciemnych cyprysów i niskimi zielonymi rabatami. Po ścieżkach przechadza się kilka małych postaci w szatach. Niebo za nim to łagodny zachód słońca w barwach brzoskwini i złota, a marmur przejmuje ten kolor, biel przechodzi w kremowość i róż."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TEMPLE_ARTEMIS"] =
    "Długa marmurowa kolumnada pod rzeźbionym frontonem wieńczy wzniesienie w głębi sceny, przed schodami wzniesiono posąg jeźdźca, a wzdłuż podejścia ciemnieją cyprysy. Szeroki taras przed nią tętni życiem: postacie w białych togach i barwnych szatach przechadzają się i handlują, sprzedawcy kucają przy koszach po lewej, a zawoalowane kobiety przechodzą blisko na pierwszym planie po prawej. Czerwona kolumna oprawia widok przy lewej krawędzi, a daleko w dole opada zielona dolina z rzeką. Południowe słońce rozpala biały marmur i jaskrawe tkaniny pod błękitnym niebem spiętrzonym chmurami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_ZEUS"] =
    "We wnętrzu świątynnej sali tronujący bóg wznosi się ku sufitowi w złocie i kości słoniowej, brodaty i z obnażonym torsem, z szatą na kolanach. Jedna dłoń wyciąga nad salą małą uskrzydloną postać Wiktorii, druga ściska wysokie berło. Jego tron jest kuty w złocie na tle ściany ciepłej czerwieni, a rzędy kolumn maszerują po obu bokach komnaty, pozostawiając boczne nawy w cieniu. U stóp posągu gromadzą się wyznawcy w bladych szatach, żaden z nich nie sięga jego goleni. Wzdłuż ścian płoną małe płomienie. Światło pada skądś z góry, zbierając się złotem na posągu, podczas gdy sala wokół niego pozostaje przyćmiona."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TERRACOTTA_ARMY"] =
    "Szeregi glinianych żołnierzy wypełniają kadr od ściany do ściany, rząd za rzędem naturalnej wielkości wojowników w zbrojnych kaftanach stojących na baczność. Cofają się w długich korytarzach między ziemnymi ścianami działowymi. Każdy rząd ginie głębiej w jamie, aż najdalsze są już tylko sylwetkami na tle złocistej łuny wpadającej w głębi komnaty. Postacie są ziemistobrązowe i szare, ich ramiona i hełmy obwiedzione ciepłym światłem. Nastrój jest cichy i ogromny, armia umarłych ustawiona w szyku w mroku."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UNITED_NATIONS"] =
    "Widok z poziomu ulicy na plac Organizacji Narodów Zjednoczonych. Płaska szklana płyta wieży Sekretariatu wznosi się po lewej, nad długim, niskim łukiem budynku zgromadzenia. Rząd masztów niesie wzdłuż przecznicy flagi wielu narodów. Plac wypełniają delegaci: mężczyźni i kobiety w garniturach pomieszani ze strojami narodowymi, postać w białych szatach i nakryciu głowy znad Zatoki w środku tłumu, grupy zatrzymujące się na rozmowę w drodze do środka. Przy krawężniku po prawej czeka żółta taksówka, a za flagami wznosi się panorama Nowego Jorku. Jest późne popołudnie, długie cienie kładą się na bruku, a niskie słońce chwyta się szkła."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UFFIZI"] =
    "Dwa długie skrzydła Galerii Uffizi stoją naprzeciw siebie przez wąski dziedziniec, wysokie renesansowe fasady z szarego kamienia i kremowego tynku z posągami stojącymi we wnękach nad parterową loggią. Dziedziniec biegnie głęboko w głąb obrazu ku łukowatemu prześwitowi w dali, a za nim na tle nieba rysuje się wieża. Niżej dziedziniec tętni florentyńczykami w długich sukniach i ciemnych płaszczach, rzeźby wystawione są na cokołach pośrodku, a w pierwszym planie po lewej rozstawiono stragan pod czerwonym baldachimem. Popołudniowe słońce wpada ukośnie z jednej strony, oświetlając ciepło górne kondygnacje, podczas gdy loggia niżej trzyma chłodny cień."
