-- Mod-authored victory and defeat screen descriptions, pl_PL overlay.
-- Baseline in CivVAccess_VictoryDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_MISSING"] = "Brak opisu tego ekranu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_CULTURAL"] =
    "Na trawiastym wzgórzu w cieniu ciemnego drzewa dwie postacie siedzą w sylwecie i spoglądają na złote miasto. Pod nimi tłum przechodzi przez łukowy kamienny most flankowany klasycznymi posągami na cokołach, a za nim wznosi się sala z kopułą. Za pasem parku panorama wspina się ku smukłym futurystycznym wieżom, które rozpływają się w bursztynowej mgiełce. Trawniki upstrzone są ludźmi: dzieci biegną pod latawcem szybującym wysoko na sznurku, jakaś postać spaceruje pod żółtą parasolką, a na odległej wodzie przez mgłę widać białe żagle. Cała scena skąpana jest w ciepłym złotym świetle, na poły późnopopołudniowym, na poły sennym, z ptakami rozsianymi po niebie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DIPLOMATIC"] =
    "Ceremonia na zielonym trawniku przed wysoką białą płytą siedziby Organizacji Narodów Zjednoczonych. Na pierwszym planie tłum stoi tyłem do patrzącego, ubrany w garnitury, szaty i chusty na głowę z wielu narodów, a po prawej operator telewizyjny filmuje ze statywu. Maszty wokół trawnika niosą dziesiątki flag narodowych, wśród nich rozpoznawalne Stany Zjednoczone i Meksyk. Pośrodku, pod rozłożystymi drzewami, wielki kamienny globus spoczywa na kwadratowym cokole, a jego kontynenty wystają reliefem. Przed nim czeka rząd dzieci w strojach ludowych różnych krajów; kobieta w błękicie pochyla się, by coś podać małej dziewczynce w żółtej sukience, która sięga po to w górę. Rabaty kwiatowe w czerwieni i bieli obrzeżają nieruchomy staw u dołu kadru, a miękkie szare światło dnia wyrównuje wszystko."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DOMINATION"] =
    "Parada zwycięstwa malowana w plakatowych barwach, samo złoto, oliwka i czerwień. Na pierwszym planie po prawej młody oficer w białym mundurze galowym ze złotym galonem na ramieniu ściska drzewce ogromnej czerwonej flagi, która faluje przez całe niebo; jego czapka z daszkiem ma czerwoną opaskę i złotą odznakę. Za nim szeregi żołnierzy w pasujących białych mundurach stoją z karabinami z bagnetami wzniesionymi pionowo przy ramionach, a z kolumny wznosi się więcej czerwonych flag. Nad paradą, na wysokim cokole, stoi brązowy posąg dowódcy na kroczącym koniu, a za nim wielki gmach kapitolu z kopułą. Cienkie czerwone proporce wiją się wstęgami przez rozjarzone żółtozielone niebo, a ciemne cyprysy i zamglone góry zamykają oddal."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_SPACE_RACE"] =
    "Głęboki kosmos, spojrzenie w górę na ogromną stację orbitalną z dołu. Jej ciemny kadłub rozciąga się przez górę kadru, a wzdłuż jego spodu ciągną się rzędy wysokich, ciepło oświetlonych okien i zielono jarzących się luków. Smugi pary dryfują po metalu. Płaskie, kratowe panele słoneczne rozchodzą się z kadłuba na kratownicowych wysięgnikach, a z jego dalszego końca w dół prawej strony kadru opada długa, oblicowana panelami wieża kratownicowa. Poniżej nocna strona planety oddala się w głębokim fiolecie i winnej czerwieni, a jej horyzont łukiem przecina dół sceny. Słońce właśnie przebija się nad tym horyzontem białozłotym rozbłyskiem, który rozświetla pasma różowych i kremowych chmur wzdłuż krzywizny. Na pierwszym planie samotny uskrzydlony statek przecina ciemność na długim, świetlistym, morsko zielonym śladzie, a w oddali na tle gwiazd mniejsze pojazdy lśnią zielenią i pomarańczą."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_TIME"] =
    "Własna grafika z okładki gry powiększona tak, by wypełnić ekran. W kadrze dominuje globus złożony z antycznych sepiowych map, a tytuł Sid Meier's Civilization biegnie przez niego literami z wypolerowanego metalu w reliefie, przeplecionymi przez gigantyczną mosiężną rzymską cyfrę pięć. W lewym górnym rogu naklejony jest zniszczony fiński znaczek pocztowy, na którym jeździec na ozdobionym koniu upamiętnia epos Kalevala. Wokół niego odbite są blade stemple pocztowe. Za globusem leży kolaż z papieru zabarwionego na morsko zielono, mosiężny pierścień południka łukiem otacza dolną krawędź globusa, a światło pada z lewego górnego rogu, jak na osobliwości pod lampą."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_DEFEAT"] =
    "Martwe imperium pod pustynnym niebem. Kolosalna kamienna głowa posągu leży policzkiem na piasku, z zamkniętymi oczami i pogodną twarzą, a nieopodal z ziemi wyłania się złamana kamienna dłoń, z palcami zagiętymi ku niebu. Otacza ją wykopalisko: rowy wcięte w ziemię na pierwszym planie, linia ogrodzenia ze słupków i drutu oraz samotna postać w jasnym odzieniu, stojąca na drewnianym podeście ze schodkami, przyćmiona przez twarz, którą bada. Po lewej czeka zwierzę juczne. Pusta dolina cofa się za rozrzuconymi stojącymi fragmentami ku płaskoszczytowym mesom na horyzoncie. Wszystko jest piaskowe i rdzawe pod cienkim błękitnym niebem, a samotne i równe piaski Ozymandiasa Shelleya ciągną się daleko."
