-- Mod-authored great work descriptions, pt_BR overlay.
-- Baseline in CivVAccess_GreatWorkDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_MISSING"] = "Nenhuma descrição de pintura para esta grande obra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIRL_WITH_PEARL_EARRING"] =
    "Pintura a óleo do Século de Ouro holandês, um dos retratos mais amados da arte ocidental. Uma jovem volta o rosto sobre o ombro para encontrar seu olhar, surgindo de um fundo escuro e liso, os lábios apenas entreabertos como se fosse falar. Ela usa um turbante azul e dourado cujo tecido escorre pelas costas, e uma única pérola grande em forma de lágrima capta a luz em sua orelha."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HENRY_VIII"] =
    "Retrato de corte Tudor a óleo, a imagem que fixou o modo como o mundo imagina Henrique VIII. O rei está de pé diante de você de corpo inteiro, com os pés firmemente afastados, ombros largos e porte pesado, uma das mãos repousando em um punhal na cintura. Ele veste um gibão de prata cravejado de joias sob um casaco carmesim forrado de pele, um chapéu chato com plumas e correntes de ouro, de pé sobre um tapete com padrões entre colunas de mármore."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HUNTERS_IN_THE_SNOW"] =
    "Pintura a óleo do Renascimento flamengo, uma paisagem de inverno vista do alto de uma colina. Três caçadores exaustos e sua matilha de cães caminham penosamente pela neve funda em primeiro plano, de cabeça baixa, com apenas uma raposa solitária a mostrar pela caçada. Abaixo deles, uma aldeia se estende sob um céu verde-acinzentado, com minúsculos patinadores brincando sobre lagoas congeladas e picos recortados erguendo-se ao longe."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LES_DEMOISELLES"] =
    "Pintura a óleo do início do modernismo, a tela que lançou o Cubismo. Cinco mulheres nuas estão de pé e sentadas em um espaço raso de planos recortados em rosa, branco e azul, seus corpos decompostos em formas angulares e afiadas. Os dois rostos à direita são pintados como máscaras africanas, listrados e distorcidos, enquanto os outros olham direto para fora com largos olhos amendoados; uma pequena tigela de frutas repousa na borda inferior."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LUNCHEON"] =
    "Pintura a óleo do Impressionismo francês de amigos demorando-se após uma refeição. Um grupo animado em traje de verão se aglomera em uma sacada à beira-rio sob um toldo listrado de laranja e branco, conversando, flertando e debruçando-se sobre a balaustrada; uma jovem à frente brinca com um cachorrinho. A mesa está coberta de garrafas de vinho, taças e frutas, tudo pintado em pinceladas quentes e soltas de cor ensolarada."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MONA_LISA"] =
    "Óleo sobre painel de madeira do Renascimento italiano, provavelmente o retrato mais famoso do mundo. Uma mulher está sentada com as mãos cruzadas, ligeiramente voltada para você diante de uma paisagem enevoada de rios sinuosos e montanhas azuis ao longe. Seus olhos encontram os seus diretamente, o célebre olhar que parece seguir você onde quer que esteja. Seu tênue meio sorriso é o foco da pintura, pintado em suaves marrons e verdes sem contornos rígidos, de modo que sua expressão parece mudar quanto mais você a observa."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUNDAY_AFTERNOON"] =
    "Pintura a óleo pontilhista, construída inteiramente a partir de minúsculos pontos de cor pura. Parisienses em seu traje de domingo descansam em um gramado ensolarado à beira-rio, passeando com sombrinhas, deitando-se na grama e levando cachorrinhos, com veleiros sobre a água ao fundo. Todos estão estranhamente imóveis e formais, como figuras de um friso, a luz decomposta em um cintilar de pontinhos verdes, laranjas e violetas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VIEW_OF_TOLEDO"] =
    "Pintura a óleo do Renascimento espanhol, uma das primeiras paisagens puras da arte ocidental e uma de incomum escuridão. A cidade espanhola de Toledo, sobre uma colina, ergue-se ao longe sob um céu de tempestade violenta, suas torres e muralhas cinzentas iluminadas por uma estranha luz prateada. Colinas verdes descem até um rio em primeiro plano, toda a cena pintada em verdes profundos e negros azulados que parecem mais sonho do que luz do dia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WATER_LILIES"] =
    "Pintura a óleo do Impressionismo francês, da famosa série de Monet sobre o lago de seu jardim em Giverny. Toda a tela é a superfície da água, sem horizonte nem margem: ilhas de folhas verdes de nenúfar flutuam sobre uma água azul e lavanda salpicada de flores rosa e vermelhas. Nuvens e árvores aparecem apenas como reflexos suaves, a pincelada solta o bastante para que tudo pareça boiar."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_STARRY_NIGHT"] =
    "Pintura a óleo pós-impressionista, uma das imagens mais reconhecidas da arte moderna. Um céu noturno vivo de movimento preenche a maior parte da tela: as estrelas ardem dentro de halos rodopiantes, e a lua queima em laranja no canto enquanto uma grande corrente em espiral rola pelo meio do céu. Abaixo, uma aldeia tranquila com uma pontiaguda torre de igreja dorme entre colinas, e um escuro cipreste se eleva em chamas pela borda esquerda, tudo em pinceladas grossas e visíveis de azul e dourado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BIRTH_OF_VENUS"] =
    "Pintura do Renascimento italiano da deusa do amor chegando do mar, entre as imagens mais famosas do mito clássico. Vênus está de pé, nua, sobre uma concha de vieira gigante, cobrindo-se com as mãos e com uma onda de longos cabelos dourados. À esquerda, dois deuses do vento alados a sopram em direção à praia através de uma chuva de rosas cor-de-rosa, enquanto à direita uma mulher em um vestido florido se apressa para envolvê-la em um manto esvoaçante."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BINDO_ALTOVITI"] =
    "Retrato a óleo do alto Renascimento italiano de um jovem e rico banqueiro romano. Um belo rapaz de longos cabelos dourados e barrete preto olha de volta para você por cima do ombro nu, uma das mãos trazida ao peito. Ele veste um manto azul sobre uma roupa preta, e seu rosto pálido reluz contra um fundo verde profundo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_DRAGON"] =
    "Pintura do início do Renascimento italiano com o encanto rígido e ilustrativo de um conto de fadas. À direita, um cavaleiro armado sobre um cavalo branco empinado crava sua lança nas fauces abertas de um dragão verde alado com asas manchadas semelhantes às de uma mariposa. À esquerda, uma princesa serena em um longo vestido cor-de-rosa segura a fera ferida por uma coleira como a um bicho de estimação, diante de sua caverna escura, enquanto uma estranha tempestade em espiral se forma atrás do cavaleiro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CREATION_OF_ADAM"] =
    "Afresco do Renascimento italiano do teto da Capela Sistina, fonte de um dos gestos mais famosos da arte. Um Adão nu reclina sobre uma colina verde à esquerda, um braço estendido frouxamente, enquanto Deus, uma figura de barba grisalha em um esvoaçante sudário cor-de-rosa cheio de anjos, irrompe pela direita. Seus dedos indicadores estendidos se aproximam um do outro através de uma pequena lacuna, o instante antes da centelha da vida."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GALLERY_OF_THE_LOUVRE"] =
    "Pintura americana a óleo de uma galeria dentro do Louvre, pintada pelo mesmo Morse que mais tarde inventou o código do telégrafo. Um grandioso salão de paredes vermelhas está coberto do chão ao teto por dezenas de pinturas de antigos mestres em molduras douradas, incluindo uma minúscula Mona Lisa. No primeiro plano, estudantes de arte sentam-se copiando diante de cavaletes enquanto o professor deles se inclina sobre o ombro de uma jovem para corrigir o trabalho dela, e um corredor em arco de outras galerias se abre ao longe."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WASHINGTON_CROSSING"] =
    "Pintura histórica americana heroica a óleo, um ícone da Guerra de Independência. O General Washington está de pé, ereto, na proa de um bote lotado enquanto seus soldados empurram e remam por um rio congestionado de blocos de gelo, um oficial atrás dele erguendo ao alto a bandeira americana. A luz da aurora rompe pela bruma fria, e mais botes cheios de homens e cavalos seguem atrás."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ARRANGEMENT_IN_GREY"] =
    "Pintura americana a óleo universalmente conhecida como a Mãe de Whistler. Uma mulher idosa em um longo vestido preto e touca de renda branca está sentada em rigoroso perfil, voltada para a esquerda, as mãos cruzadas no colo e os pés sobre um pequeno banquinho. O cômodo é austero e plano: uma parede cinza, uma escura cortina estampada e um único quadro emoldurado, toda a composição equilibrada como um estudo em cinza e preto, exatamente como diz o título."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BREEZING_UP"] =
    "Pintura realista americana a óleo de uma pequena embarcação à vela ao largo da costa da Nova Inglaterra. Um homem e três garotos recostam-se em um pequeno barco a vela chamado Gloucester enquanto ele aderna a um vento firme, a espuma salpicando da proa e a pesca do dia empilhada aos pés deles. O mar é de um verde agitado sob nuvens esparsas, com uma escuna de dois mastros no horizonte."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_THOUSAND_LI"] =
    "Rolo de mão chinês de paisagem azul e verde, pintado sobre seda por um prodígio adolescente da corte Song e com quase doze metros de comprimento. Montanhas em vívido azul e verde minerais erguem-se em crista após crista a partir de um calmo rio dourado, com minúsculas aldeias, pontes e árvores desnudas aninhadas entre as encostas. Colunas de caligrafia pincelada e selos vermelhos de colecionadores preenchem o céu acima dos picos."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DWELLING_IN_THE_FUCHUN"] =
    "Rolo de mão chinês a tinta, uma obra-prima da pintura de paisagem letrada da dinastia Yuan, feita inteiramente em tons de tinta preta sobre papel. Montanhas arredondadas construídas a partir de pinceladas secas em camadas erguem-se acima de um amplo rio calmo, com pinheiros, casebres dispersos e barcos de pesca ao longo das margens. A atmosfera é vagarosa e contemplativa, o papel pontilhado de selos vermelhos de colecionadores acumulados ao longo de séculos de admiradores."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ALONG_THE_RIVER"] =
    "Rolo de mão chinês da dinastia Song sobre seda, um famoso panorama da vida urbana cotidiana com mais de cinco metros de comprimento. A seção mostrada centra-se no grande portão da cidade capital, uma maciça torre de madeira sobre uma muralha inclinada, com as ruas abaixo fervilhando de vida: barracas de mercado, carros de boi, uma caravana de camelos passando pelo portão e carregadores levando cargas em varas ao ombro. Cada figura é minúscula, mas desenhada com precisão em fino traço de tinta com tons terrosos suaves."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LEAF_2"] =
    "Folha de álbum chinesa da dinastia Qing, pintura de corte em traço fino e cor delicada. Damas elegantes em longas robes esvoaçantes de branco, verde e azul reúnem-se em um pavilhão de jardim drapeado com pano de azul vivo, uma delas queimando incenso a uma mesa atrás de uma balaustrada vermelha. Em torno delas há rochas de jardim, bambu e uma trepadeira florida subindo pelo telhado do pavilhão."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EMPEROR_TAIZONG"] =
    "Rolo de mão chinês da dinastia Tang sobre seda, um registro de corte de um encontro diplomático. À direita, o Imperador Taizong está sentado em uma plataforma carregada por damas do palácio, que também seguram dois grandes leques e um dossel vermelho acima dele. À esquerda, três figuras menores se aproximam em poses respeitosas: um arauto da corte em vermelho, o enviado tibetano em uma robe estampada e um intérprete em branco, todos contra uma seda dourada quente coberta de selos vermelhos."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SPRING_MORNING"] =
    "Rolo de mão chinês da dinastia Ming sobre seda, um longo panorama de mulheres do palácio em lazer numa manhã de primavera. Dezenas de damas elegantes preenchem salões abertos, varandas e pátios: fazendo música, pintando um retrato, brincando com crianças e passeando entre salgueiros, rochas de jardim e até pavões. A arquitetura do palácio percorre todo o comprimento do rolo em vermelhos e verdes quentes, cada biombo, balaustrada e robe representados em meticuloso detalhe de traço fino."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_GREAT_WAVE"] =
    "Xilogravura japonesa ukiyo-e, a imagem mais famosa de toda a arte japonesa. Uma enorme onda de azul intenso empina-se à esquerda e se enrola sobre toda a cena, sua crista quebrando em dedos de espuma branca semelhantes a garras. Sob ela, três longos botes abertos cheios de remadores cavalgam as cavas das ondas, e bem ao longe, pequeno no centro de tudo, está o cone de cume nevado do Monte Fuji."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EVENING_SHOWER"] =
    "Xilogravura japonesa ukiyo-e, uma das cenas de chuva mais admiradas já feitas. Um aguaceiro repentino, desenhado como lâminas de finas linhas inclinadas, surpreende as pessoas a meio caminho de uma longa ponte de madeira; elas se apressam em ambas as direções sob chapéus e guarda-chuvas, uma se abrigando debaixo de uma esteira de palha. O rio abaixo é uma faixa de azul-esverdeado com um jangadeiro solitário impelindo a jangada com uma vara, e a margem distante esmaece em uma mancha escura sob a tempestade."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_L_ABSINTHE"] =
    "Pintura impressionista francesa a óleo, uma cena impiedosa da vida de café parisiense. Uma mulher em vestido e chapéu pálidos está sentada, abatida, a uma mesa de café de mármore, os olhos baixos, um copo de absinto verde leitoso diante dela; ao lado dela um homem barbudo em um casaco amarfanhado olha fixamente para a direita com um cachimbo na boca. Os dois estão sentados juntos e ainda assim totalmente apartados, pintados em cinzas e marrons sem brilho que carregam o ar de solidão da pintura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_UPAUPA_SCHNEKLUD"] =
    "Retrato pós-impressionista a óleo de um violoncelista em plena apresentação. O músico se debruça sobre seu violoncelo de um vivo vermelho-alaranjado, os olhos baixos em concentração, o braço do arco varrendo as cordas, seu terno azul-escuro emoldurando o brilho do instrumento. Atrás dele, o fundo se divide em zonas planas de marrom e verde-musgo salpicadas de pálidas formas abstratas, no estilo de cor ousado e simplificado de Gauguin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_BAR_AT_THE_FOLIES"] =
    "Pintura francesa a óleo da vida moderna, a última grande obra de Manet. Uma garçonete em um corpete de veludo preto com uma flor ao peito está de pé atrás de um balcão de mármore apinhado de garrafas de champanhe, uma tigela de laranjas e uma taça com uma rosa, olhando para fora com uma expressão cansada e distante. Atrás dela, um enorme espelho reflete o salão de música reluzente, seus lustres e a multidão, e, estranhamente deslocada para a direita, as próprias costas dela enquanto se inclina em direção a um homem de cartola."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BALL_AT_THE_MOULIN"] =
    "Pintura pós-impressionista a óleo da vida noturna parisiense no famoso cabaré. Um grupo de homens de cartola e mulheres de chapéus emplumados senta-se em torno de uma mesa com bebidas, enquanto uma mulher ruiva arruma o cabelo no salão de dança iluminado de verde atrás deles. O rosto de uma mulher surge na borda direita, iluminado de um verde fantasmagórico por baixo, e um longo corrimão diagonal corta o primeiro plano no estilo de cartaz de Lautrec."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS"] =
    "Pintura vienense a óleo do art nouveau, recoberta de folha de ouro verdadeira, a obra mais famosa de Klimt. Um casal está ajoelhado preso em um abraço sobre um prado florido, o homem inclinando-se para beijar a face da mulher enquanto ela ergue o rosto com os olhos fechados. Seus corpos se fundem em um único manto dourado, padronizado com retângulos para ele e círculos brilhantes para ela, reluzindo contra um plano de fundo dourado plano e cintilante."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AMERICAN_GOTHIC"] =
    "Pintura regionalista americana a óleo, infinitamente parodiada e reconhecida no ato. Um fazendeiro severo e calvo, de óculos redondos e macacão de brim, está de pé segurando um forcado de três pontas na vertical, com uma mulher em um vestido-avental de estampa escura ao seu lado, olhando para longe com reprovação de lábios cerrados. Atrás deles está a casa de fazenda branca que dá nome à pintura, com uma janela gótica de arco ogival em sua empena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SRI_SHANMUKAHA"] =
    "Pintura devocional indiana no estilo acadêmico europeu que Ravi Varma tornou famoso por toda a Índia. O deus hindu Murugan, com seis cabeças coroadas e muitos braços que seguram armas, monta seu pavão, ladeado por suas duas consortes em saris cor-de-rosa vivo. A cauda do pavão se abre atrás deles como um gigantesco leque de olhos verdes e dourados, enquanto a ave imobiliza uma naja sob suas patas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DAUD_RECEIVES_A_ROBE"] =
    "Miniatura mogol de uma crônica imperial ilustrada, em aquarela opaca e ouro sobre papel. O detalhe mostrado centra-se em um jovem e esguio servidor em uma túnica pálida, gorro vermelho e faixa dourada, carregando o manto dourado de honra, dobrado, para a cerimônia de entrega. Ele está de pé contra uma parede de tenda de um azul brilhante recoberta de delicadas trepadeiras floridas, cada dobra e flor pintada com precisão de miniatura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YUSEF_AND_ZULEYKHA"] =
    "Miniatura persa de um manuscrito ilustrado, a obra mais celebrada do grande mestre de Herat, Behzad. A página é preenchida por um palácio intrincado visto em corte transversal achatado, um labirinto de escadarias, sacadas e portais azulejados em azul, laranja e ouro. Em uma câmara superior, o profeta Yusef, com a auréola de chama, foge das mãos estendidas de Zuleykha, enquanto painéis de caligrafia persa emolduram a arquitetura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ASCENT_OF_MUHAMMAD"] =
    "Miniatura persa de um manuscrito real, retratando a viagem noturna do Profeta pelos céus. Maomé, o rosto velado de branco e envolto em chama dourada, monta o corcel Buraq de cabeça humana através de um céu de azul intenso semeado de nuvens encrespadas orladas de ouro. Anjos em vestes de vermelho, verde e laranja rodopiam ao seu redor por todos os lados, trazendo presentes e turíbulos, com linhas de versos persas emoldurando a cena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LIBERTY_LEADING_THE_PEOPLE"] =
    "Pintura francesa romântica a óleo, a imagem definidora da revolução. A própria Liberdade, uma mulher de seios desnudos em um vestido amarelo e gorro vermelho, avança a passos largos sobre uma barricada de escombros e corpos caídos, erguendo a bandeira tricolor francesa rumo ao céu enfumaçado. Ao seu redor surge uma onda de cidadãos armados de toda classe, entre eles um cavalheiro de cartola com um mosquete e um menino brandindo duas pistolas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_JEROME_IN_HIS_STUDY"] =
    "Pintura do início do Renascimento a óleo, de notável precisão de miniatura. Vista através de um grandioso arco de pedra, São Jerônimo, em vestes vermelhas, está sentado lendo em um gabinete de madeira construído como um palco dentro de um espaço de catedral abobadado, cercado de prateleiras de livros e potes. A luz jorra de janelas em todos os lados, um pavão e uma perdiz se empoleiram na soleira à frente, e seu leão ronda nas sombras à direita."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PARTHENON_FRIEZE"] =
    "Pintura vitoriana a óleo imaginando a Atenas antiga; no jogo, esta obra acompanha a maravilha do Partenon. O escultor Fídias está de pé em um andaime de madeira ao lado de seu friso de mármore recém-pintado de cavaleiros, ainda nas cores de oficina, segurando uma corda enquanto o apresenta. Um pequeno grupo de atenienses em vestes drapejadas, Péricles entre eles, se inclina para admirar a talha sob a luz quente no interior do templo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUE_DE_PARIS"] =
    "Pintura realista francesa a óleo da Paris moderna em um dia chuvoso, nítida e fotográfica onde seus amigos impressionistas eram soltos. Um casal bem vestido, partilhando um guarda-chuva, caminha em sua direção sobre paralelepípedos reluzentes, o homem de cartola e a mulher em um longo vestido escuro com um brinco captando a luz. Ao redor deles, outros transeuntes carregando guarda-chuvas atravessam um amplo cruzamento ladeado por quarteirões de prédios cinzentos em forma de cunha, com um poste de luz verde dividindo a cena ao meio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_NIGHT_WATCH"] =
    "Pintura holandesa da Era de Ouro a óleo, em escala imensa, o mais famoso retrato de grupo já feito. Uma companhia de milícia da cidade irrompe em movimento de uma sombra profunda: o capitão, de preto com uma faixa vermelha, avança dando uma ordem ao seu tenente em dourado pálido, enquanto atrás deles mosquetes são carregados, um estandarte é erguido e um tambor marca o compasso. Uma menininha em um vestido dourado reluzente brilha misteriosamente na multidão, iluminada como um holofote na penumbra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DEATH_OF_MARAT"] =
    'Pintura francesa neoclássica a óleo, a grande imagem mártir da Revolução Francesa. O jornalista revolucionário Marat jaz morto em sua banheira, tombado como um santo caído, a cabeça envolta em um turbante branco e um braço pendendo até o chão ainda segurando sua pena. Em sua outra mão está a carta que seu assassino usou para conseguir entrada; a metade superior da tela é parede escura e nua, e o simples caixote de madeira ao seu lado traz a dedicatória pintada "A Marat, David."'
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ETIENNE_CHEVALIER"] =
    "Pintura francesa em painel do fim da Idade Média, uma das alas de um famoso díptico devocional. O tesoureiro real Etienne Chevalier está ajoelhado em uma rica robe vermelha com as mãos unidas em oração, apresentado por seu padroeiro Santo Estêvão, que está de pé ao seu lado em uma vestimenta azul e dourada. O santo carrega um livro encimado por uma pedra denteada, o símbolo de seu martírio, e ambos estão em um salão de mármore branco com o nome do doador esculpido ao longo da parede."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_FRANCIS"] =
    "Pintura a óleo do Barroco espanhol de austera devoção monástica. São Francisco está de pé, sozinho, em um simples hábito com capuz da cor da areia, o rosto meio perdido na sombra profunda do capuz, os olhos baixos em oração. Ele segura nas mãos um crânio humano como lembrança da morte, iluminado por uma única luz dura contra um fundo quase negro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HATAORI"] =
    "Gravura japonesa ukiyo-e em xilogravura de uma tecelã em seu trabalho. Uma jovem em um quimono de anil estampado está sentada descalça diante de um grande tear manual de madeira, erguendo os olhos do trabalho com uma lançadeira em uma das mãos, fios de vermelho, azul e branco estendidos por todo o comprimento da máquina. As cores são cremes suaves e azuis suaves, com uma coluna de poesia pincelada preenchendo o canto superior esquerdo da folha."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JANE_GREY"] =
    "Pintura histórica acadêmica francesa, teatral e dilacerante. A jovem rainha, vendada e vestida em cetim branco que reluz contra a escura câmara de pedra, está ajoelhada e tateia às cegas em busca do cepo da execução, enquanto um oficial idoso guia gentilmente suas mãos até ele. Suas damas desabam de dor contra um pilar atrás dela, e o carrasco aguarda à direita, apoiado em seu machado com os olhos desviados."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WANDERER"] =
    "Pintura a óleo do Romantismo alemão, a imagem que define o homem sozinho diante da natureza. Um jovem em um casaco verde escuro está de pé, de costas para você, sobre um cume rochoso, apoiado em uma bengala, os cabelos agitados pelo vento. Abaixo dele um oceano de neblina branca engole o vale, com apenas cristas e rochedos rompendo através como ilhas e pálidas montanhas se esmaecendo na distância."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BABEL"] =
    "Pintura a óleo do Renascimento flamengo da torre condenada da Bíblia, fervilhando de detalhes. Uma colossal torre espiral de arcos, parte em pedra branca e parte em cru tijolo vermelho, sobe tortamente até as nuvens, seu topo ainda em obra e inacabado. Em torno de sua base estende-se uma cidade portuária com navios ancorados, e em primeiro plano um rei inspeciona uma equipe de canteiros que se ajoelham a seus pés entre seus blocos."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YOUNG_LADY"] =
    "Retrato a óleo dos primeiros tempos dos Países Baixos, pequeno, sereno e estranhamente moderno. Uma jovem pálida de rosto liso como porcelana olha para você de lado, sob um alto toucado de veludo preto guarnecido de ouro. Ela usa um vestido azul com uma gola de pele branca e um colar justo de faixas de ouro e preto, posta contra uma simples parede em penumbra em vez do habitual vazio escuro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_KINDRED"] =
    "Pintura a óleo americana da Escola do Rio Hudson, um tributo à amizade entre um pintor e um poeta. Dois homens de casaco estão de pé conversando sobre uma saliência de rocha que se projeta sobre um desfiladeiro arborizado nas montanhas Catskill, um deles apontando com um pincel para a vista. Um riacho despenca sobre as pedras abaixo, emoldurado por um arco de árvores pendentes, com picos enevoados se dissolvendo na luz dourada ao fundo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BLUE_BOY"] =
    "Retrato a óleo inglês no Grande Estilo, a obra mais famosa do artista. Um menino de cerca de doze anos está de pé, de corpo inteiro, em um cintilante traje de cetim azul com calções até o joelho e uma gola de renda, uma das mãos no quadril, a outra segurando um chapéu emplumado ao lado do corpo. Ele olha para fora com tranquila confiança, recortado contra uma paisagem marrom, escura e tempestuosa, que faz o traje azul resplandecer."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SECOND_OF_MAY"] =
    "Pintura a óleo espanhola, um dos primeiros e maiores protestos contra a guerra na arte. À luz de uma lanterna, um pelotão de fuzilamento francês está em uma fileira sem rosto, os fuzis apontados para um grupo de cativos espanhóis em uma colina nua nos arredores de Madri. No centro, um homem de camisa branca abre os braços diante das armas, ajoelhado entre os corpos dos que já foram fuzilados, sua pose ecoando uma crucificação."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_CART"] =
    "Pintura militar a óleo francesa da Guerra Franco-Prussiana, uma famosa imagem de derradeira resistência desafiadora. Um punhado de soldados franceses defende a casa arruinada de uma aldeia, atirando de uma janela enquanto os feridos sentam-se abatidos contra as paredes e um oficial conta sua munição final. O cômodo está destroçado, uma porta arrancada das dobradiças, reboco caindo do teto, a luz do dia inundando através do vão da porta onde companheiros seguem lutando."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EARLY_AUTUMN"] =
    "Rolo de mão chinês em tinta e cor suave, um estudo da natureza em primeiro plano de um lago de lótus que definha. Libélulas em vermelho, verde e azul pairam sobre juncos ressecados e folhas de lótus esfarrapadas, enquanto gafanhotos, uma abelha e pequenas rãs cuidam de suas vidas abaixo. O clima é de suave decadência, a vida do verão seguindo entre plantas que apenas começam a murchar, com selos vermelhos de colecionadores ao longo de ambas as bordas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_APPRECIATING_LOTUSES"] =
    "Rolo suspenso japonês em tinta e cor pelo fundador da escola Kano, pintado à maneira chinesa da paisagem de eruditos. Um erudito chinês em vestes vagueia em um pequeno barco à beira de um lago de lótus, contemplando as folhas flutuantes sob um salgueiro retorcido que se inclina a partir da margem rochosa. A maior parte do alto rolo é bruma e água aberta, com algumas copas de pinheiros se esmaecendo na névoa."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EQUESTRIAN_PORTRAIT"] =
    "Pintura a óleo do Renascimento veneziano, o modelo para séculos de governantes a cavalo. O Sacro Imperador Romano-Germânico cavalga para fora de um bosque escuro em plena armadura reluzente com um elmo de pluma vermelha, lança em punho, comemorando sua vitória em Muhlberg. Seu cavalo negro está ajaezado em carmesim, e um baixo sol da tarde rompe dourado e rosado sob pesadas nuvens de tempestade."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ARMADA"] =
    "Retrato de propaganda Tudor a óleo, pintado para celebrar a derrota da Armada Espanhola. A Rainha Isabel está sentada em um imenso vestido de pérolas e laços, o rosto emoldurado por um vasto rufo branco de renda, uma das mãos pousada possessivamente sobre um globo com os dedos sobre as Américas. Pelas janelas atrás dela a história se desenrola duas vezes: a frota inglesa em mares calmos de um lado, navios espanhóis naufragados em uma tempestade do outro. Sua coroa cravejada de joias repousa ao seu lado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRANCIS_I"] =
    "Retrato real renascentista francês a óleo. O rei o encara da cintura para cima em um espetacular traje de corte, mangas talhadas de cetim branco e dourado riscado de preto, uma corrente de ouro pelo peito e um gorro preto com uma pluma branca na cabeça. Seu rosto astuto, barbado e de nariz comprido, destaca-se contra um fundo de damasco carmesim padronizado com coroas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SELF_PORTRAIT"] =
    "Autorretrato a óleo do maneirismo nórdico, pelo pintor de corte flamengo do Imperador Rodolfo II. O artista o fita por cima do ombro, um homem robusto e barbado de cabelos encaracolados sob um suave gorro preto, vestindo uma gola branca franzida sobre um gibão azul-acinzentado. O tratamento é caloroso e direto contra um fundo marrom liso, e seu olhar avaliador de lado prende o seu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VERTUMNUS"] =
    "Pintura maneirista a óleo, a mais famosa das fantásticas cabeças compostas de Arcimboldo. É um retrato do Imperador Rodolfo II como o deus romano das estações, todo o seu rosto e peito montados a partir de frutas, legumes e flores: pálpebras de vagem de ervilha, um nariz de pera, lábios de cereja, suíças de espiga de trigo e cabelos de uva. À distância é um governante digno; de perto se dissolve em uma banca de feira, tudo contra um fundo preto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_SUPPER"] =
    "Pintura a óleo do final do Renascimento veneziano que reinventa a cena familiar. Em vez de encará-lo de frente, a mesa da ceia mergulha para longe em uma íngreme diagonal adentro de um escuro salão de taverna, com Cristo resplandecendo no meio de seu comprimento ao oferecer pão aos apóstolos. Criados carregam comida e um gato enfia o focinho em um cesto no primeiro plano, enquanto uma flamejante lamparina de óleo enche de anjos translúcidos em redemoinho o ar enfumaçado lá no alto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_A_MAN"] =
    "Pintura a óleo do início da escola flamenga, possivelmente o próprio rosto do artista e um dos primeiros verdadeiros autorretratos. Um homem de meia-idade, de rosto marcado e olhar penetrante, fita-o diretamente a partir de uma sombra profunda, usando um extravagante toucado vermelho enrolado e atado em dobras escultóricas. O detalhe é fino como agulha, cada ruga e fio de barba por fazer captados, com a figura em um casaco escuro debruado de pele contra um fundo preto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRONT_OF_THE_MIRROR"] =
    "Pintura a óleo do Renascimento veneziano, a serena obra-prima tardia do idoso Bellini. Uma jovem nua de cabelos ruivos está sentada sobre um tecido vermelho, arranjando o cabelo com calma enquanto segura um pequeno espelho de mão, um segundo espelho redondo na parede atrás refletindo as costas de seu toucado padronizado. Uma janela ao seu lado se abre para um campo verde com distantes montanhas azuis sob um céu nublado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ADORATION"] =
    "Afresco italiano antigo da Capela dos Scrovegni, pelo pintor a quem se credita ter trazido o sentimento humano natural de volta à arte ocidental. Sob um dossel de madeira, Maria segura o menino Cristo enquanto o mais velho dos três reis se ajoelha para beijar os pés da criança, a coroa posta de lado; camelos esperam à esquerda. Acima do estábulo um cometa risca o céu de azul profundo no lugar da estrela habitual, tudo nas figuras sólidas e simples e nas cores claras de Giotto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUBENS_AND_ISABELLA"] =
    "Pintura barroca flamenga a óleo, o retrato nupcial que o artista fez de si mesmo e de sua noiva. O jovem casal está sentado bem junto sob um arbusto de madressilva, a mão direita dela pousada com ternura sobre a dele, o quieto centro da pintura. Ele está sentado acima dela em um gibão preto com uma perna cruzada, ela ajoelhada em uma saia violeta, corpete bordado a ouro, largo rufo e alto chapéu de palha, ambos olhando para fora com um calmo contentamento."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CHILDS_BATH"] =
    "Pintura impressionista americana a óleo de ternura cotidiana, influenciada pelas gravuras japonesas em seu ponto de vista elevado e padrões planos. Uma mãe em um vestido de listras ousadas segura no colo uma criança envolta em uma toalha, lavando os pés do pequenino em uma bacia de água. As duas cabeças se inclinam juntas sobre a tarefa, e o cômodo ao redor delas é uma colcha de retalhos de padrões: papel de parede florido, baú pintado, tapete ornamentado e um jarro branco."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_CARD_PLAYERS"] =
    "Pintura pós-impressionista a óleo, uma de uma famosa série sobre este tema. Dois camponeses de chapéu estão sentados frente a frente diante de uma pequena mesa de madeira, absortos em suas cartas, uma única garrafa de vinho de pé entre eles como o centro imóvel da composição. Um deles fuma um cachimbo; a tinta é construída em pinceladas pacientes e maciças de marrom terroso, ocre e violeta suave que fazem as figuras parecerem talhadas e permanentes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_SWING"] =
    "Pintura rococó francesa a óleo, frívola, secreta e a imagem mais famosa da época. Em um jardim exuberante e tomado pelo mato, uma jovem em um vaporoso vestido rosa balança alto em um balanço de corda, lançando um chinelo ao ar, enquanto um idoso oculto puxa as cordas a partir das sombras atrás dela. Seu jovem amante está estirado nas roseiras abaixo, posto na posição perfeita para olhar por baixo de suas saias, e uma estátua de pedra de cupido leva um dedo aos lábios."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIANT_MAGNOLIAS"] =
    "Natureza-morta americana a óleo, exuberante e de sensação quase tropical. Duas enormes flores de magnólia, brancas e cremosas, jazem cortadas sobre um pano drapejado de veludo azul profundo, rodeadas por suas folhas escuras e lustrosas, com um terceiro botão ainda fechado. As pétalas resplandecem contra o fundo quase preto, pintadas com precisão cerosa e sensual."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_KILLING"] =
    "Pintura catalã gótica em painel, em têmpera e ouro. São Jorge, em armadura preta com um halo dourado, inclina-se de seu cavalo branco empinado para cravar uma longa lança fundo na boca escancarada de um dragão com asas de morcego, o chão à volta deles juncado de ossos e crânios. A princesa de vestido rosa reza sobre uma saliência rochosa atrás, e espectadores se aglomeram nas brancas muralhas do castelo acima."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JACQUES_AND_BERTHE"] =
    "Duplo retrato modernista a óleo do escultor Lipchitz e sua esposa, pintado no inconfundível estilo de Modigliani. O marido está de pé em um terno escuro, com a mão pousada sobre o ombro da esposa sentada, cujo rosto de faces rosadas se ergue de uma gola branca de renda. Ambos têm os rostos alongados, narizes longos e olhos amendoados e vazios característicos do artista, com seus nomes rabiscados pelo alto da tela."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DASH_FOR_TIMBER"] =
    "Pintura a óleo do Oeste americano, o tipo de cena de ação em galope que definiu o Velho Oeste no imaginário popular. Oito vaqueiros galopam direto em sua direção a toda, os cascos dos cavalos fora do chão, dois cavaleiros torcendo o corpo na sela para atirar contra o bando de apaches montados que os persegue na poeira atrás. Um homem ferido tomba contra um companheiro enquanto correm para as árvores na borda esquerda da planície seca."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GEORGE_WASHINGTON_PORTRAIT"] =
    "Retrato de Estado americano a óleo, a imagem oficial da primeira presidência. Washington está de pé de corpo inteiro em um simples terno preto de veludo, um braço estendido em um gesto de discurso, o outro segurando uma espada de gala, ao lado de uma mesa com pena e tinteiro. Os adornos ao seu redor são a grandeza republicana: uma cadeira dourada com o escudo de estrelas e listras, colunas de mármore e um arranjo drapeado de cortina carmesim, com um arco-íris rompendo entre nuvens de tempestade ao longe."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ATTACK_ON_BEIJING"] =
    "Gravura colorida japonesa no estilo da ilustração noticiosa de guerra, com legendas em japonês e inglês. Tropas aliadas tomam de assalto as muralhas do palácio imperial de Pequim: soldados britânicos de casaco vermelho com uma bandeira do Reino Unido avançam pelo primeiro plano, enquanto a infantaria japonesa de uniforme branco avança à direita. Explosões de projéteis pairam como baforadas brancas sobre o verde campo de parada, com o portão de telhado azul do palácio e as muralhas fumegantes atrás."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUMO_WRESTLER"] =
    "Gravura japonesa ukiyo-e em xilogravura, um retrato de celebridade de um lutador famoso fora de serviço. O homenzarrão está de pé em toda a sua altura em um quimono preto sobre vestes estampadas, espadas na faixa, enxugando a testa com um pano xadrez enquanto carrega uma capa enrolada sobre um ombro. Seu nome corre pelo lado direito em vivos painéis de caligrafia vermelha, a figura plana e monumental contra o papel liso."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_TIGER_IN_TROPICAL_STORM"] =
    "Pintura a óleo de estilo naif do autodidata funcionário aduaneiro francês que nunca viu uma selva. Um tigre de olhos arregalados se agacha na relva alta açoitada pelo vento, com os dentes à mostra, surpreendido por uma tempestade que verga todas as plantas para o lado. A selva é um padrão denso de folhas estilizadas em verdes e vermelhos, com riscos prateados e oblíquos de chuva traçados por toda a tela como uma gaze."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_HOME_GUARD"] =
    "Retrato a óleo húngaro estilo Biedermeier da revolução de 1848. Um cidadão-soldado barbado está sentado em um simples casaco de linho cru, ambas as mãos enluvadas pousadas sobre o punho de seu sabre erguido, a braçadeira nacional vermelha, branca e verde na manga declarando sua causa. Ele olha para o lado com calma determinação, iluminado em tons quentes contra uma cortina vermelha escura, o casaco de forro vermelho atirado sobre a cadeira."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CEREMONIAL_SITTING"] =
    "Pintura realista russa a óleo de escala imensa, um retrato de grupo de todo o conselho dirigente do império. Dezenas de idosos estadistas em uniformes escuros carregados de galão dourado e faixas vermelhas estão sentados em torno de uma grande ferradura de cadeiras vermelhas em um salão de colunas brancas, ornado com candelabros e retratos reais. Cada um dos mais de sessenta rostos é um retrato individual, pintado com o realismo rápido e seguro de Repin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUSSIAN_TSAR"] =
    "Pintura histórica russa a óleo que recria uma procissão real do século dezesseis. Um czar de gorro de pele em um manto de brocado dourado monta um cavalo branco pela neve, precedido por guardas em vivos casacos vermelhos empunhando altas alabardas curvas. A multidão se ajoelha e se curva até o chão dos dois lados da estrada nevada e pisada, com as construções de madeira de uma antiga cidade russa sob um pálido céu de inverno."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CRUCIFIXION_OF_SAINT_PETER"] =
    "Pintura italiana barroca a óleo, brutal e física no estilo característico de Caravaggio. Três trabalhadores se esforçam para erguer uma cruz de madeira na qual o idoso São Pedro foi pregado de cabeça para baixo, um puxando uma corda, outro agachado sob a viga, os rostos ocultos. O santo de barba branca levanta a cabeça para olhar a própria mão pregada, seu velho corpo musculoso irrompendo da escuridão total sob uma única luz dura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LANDSCAPE_WITH_ANT_BEAR"] =
    "Paisagem colonial holandesa a óleo, pintada pelo primeiro artista de formação europeia a trabalhar no Brasil. Um amplo vale ensolarado com um rio se abre sob um céu vasto entre duas altas palmeiras, com um povoado colonial de casas brancas nas colinas ao fundo. Um grupo de figuras afro-brasileiras caminha por uma trilha no primeiro plano carregando trouxas, e o tamanduá de focinho longo do título fuça a vegetação rasteira no canto inferior direito."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DUTCH_MEN_O_WAR"] =
    "Pintura marinha a óleo do Século de Ouro holandês feita pelo maior pintor de navios da época. Altos navios de guerra de madeira repousam ancorados sobre águas lisas como vidro, suas velas pendendo frouxas e os cascos espelhados no mar, cada linha do cordame exata. Botes a remo transportam passageiros entre as embarcações sob um céu vasto de nuvens cúmulus ensolaradas, toda a cena banhada em uma calma dourada."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HARBOR_IN_BALAKLAVA"] =
    "Litografia matizada da Guerra da Crimeia, desenhada por um dos primeiros artistas de guerra a documentar uma campanha no próprio local. Em uma desolada praia portuária, soldados doentes e feridos envoltos em cobertores brancos são ajudados a sair de macas carregadas por mulas para um bote a remo que os aguarda. Colinas pardas e nuas se erguem atrás do aglomerado de figuras, com cabanas e tendas do exército pontilhando a encosta, as cores contidas e documentais."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PEACEMAKERS"] =
    "Pintura histórica americana a óleo de um verdadeiro conselho da Guerra Civil em seus últimos dias. O presidente Lincoln está sentado na cabine de um barco a vapor, ouvindo atentamente, o queixo apoiado na mão, enquanto o general Sherman gesticula em meio a um argumento; o general Grant e o almirante Porter completam o círculo de quatro figuras de terno escuro. Pelas janelas da cabine atrás deles, um arco-íris rompe entre céus que clareiam, o sinal silencioso da pintura de uma paz que se aproxima."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_CHITASEI"] =
    "Gravura japonesa ukiyo-e em xilogravura da famosa série de Kuniyoshi sobre os 108 heróis do romance chinês Margem da Água. O erudito estrategista Wu Yong está de pé em um manto escuro e fluido estampado com dragões, afagando a barba pensativo sob um céu noturno salpicado de estrelas. Ao seu lado repousa um grande globo celeste sobre um suporte ornamentado, e painéis de texto japonês emolduram a figura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_LOUIS"] =
    "Retrato inglês a óleo do século XVIII de um escultor flagrado em pleno trabalho. Roubiliac, de gorro macio e camisa aberta com as mangas arregaçadas, faz uma pausa com a espátula de modelar erguida, lançando o olhar de lado enquanto trabalha em uma estatueta de argila de Shakespeare sobre um suporte. O escultor aponta para sua própria criação com a mão livre, banhado por uma luz quente contra um fundo escuro de ateliê."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_NASSER"] =
    "Retrato cortesão persa da dinastia Qajar a óleo, com o esplendor real aplicado em camada espessa. O jovem xá de bigode senta-se ereto e rígido em um uniforme escarlate incrustado de bordado dourado, cordões de pérolas, dragonas enjoiadas e uma faixa azul, uma das mãos sobre uma espada cravejada de gemas. Ele usa um alto chapéu preto com um ramo de diamantes, os olhos contornados de escuro fitando para fora contra um fundo verde-oliva profundo estampado com uma inscrição real."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FIELD_WITH_SHEAFS"] =
    "Paisagem a óleo de inclinação expressionista alemã, pintada em pinceladas largas e enérgicas. Um campo de trigo ceifado preenche o primeiro plano com fileiras de feixes dourados empilhados em molhos inclinados, o amarelo aplicado espesso e vivo. Uma linha de árvores verde-escuras fecha o campo, com um céu de azul-violeta pálido de nuvens varridas pelo vento acima."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AT_THE_EDGE_OF_THE_BROOK"] =
    "Pintura acadêmica francesa a óleo, polida até a perfeição vítrea pela qual Bouguereau era famoso. Duas crianças camponesas descalças sentam-se sobre uma pedra à beira de um riacho, a menina mais nova tirando uma meia enquanto sua companheira de cabelos escuros levanta a saia para entrar na água. Elas trocam um olhar no meio da conversa, a pele e os cabelos despenteados pintados com suavidade fotográfica contra uma paisagem rural suave."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS_ALT"] =
    "Pintura romântica italiana a óleo, o beijo mais famoso da arte italiana e um emblema patriótico oculto da unificação. Em um corredor medieval de pedra, um jovem de chapéu emplumado e capa marrom inclina uma mulher para trás em um beijo apaixonado, um pé já no degrau como se fizesse uma pausa em plena fuga. O vestido dela de cetim azul pálido derrama luz sobre a cena, enquanto uma figura sombria se aproxima pelo arco ao fundo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MOVING_HOUSE"] =
    "Pintura realista russa a óleo de uma pobreza urbana silenciosa. Um casal idoso atravessa a passos pesados o gelo do rio congelado de São Petersburgo carregando tudo o que possui em uma trouxa de pano, o homem apoiado em uma bengala, ambos agasalhados em casacos gastos e lenços de cabeça contra o frio. Um cãozinho trota à frente deles, e a agulha dourada da fortaleza de Pedro e Paulo se ergue pela bruma de inverno ao fundo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MEXICAN_EXPEDITION"] =
    "Pintura francesa de história naval a óleo, em estilo de reportagem e repleta de ação. Um navio de guerra francês hasteando a tricolor domina o primeiro plano à esquerda, oficiais em seu convés dirigindo um bombardeio da fortaleza mexicana de San Juan de Ulua, a fumaça subindo sobre a água. Projéteis espirram perto dos botes a remo que transportam homens entre os navios, com um vulcão de cume nevado no horizonte enevoado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_DAY_OF_POMPEII"] =
    "Pintura romântica russa a óleo sobre uma tela enorme, a epopeia de catástrofe de seu século. O céu acima de Pompeia arde em vermelho e preto enquanto o Vesúvio entra em erupção, estátuas tombam de um telhado, e raios cortam a nuvem de cinzas. Multidões de habitantes em trajes romanos fogem pelos destroços que caem, abrigando crianças e idosos sob mantos, enquanto uma mulher caída jaz estendida ao lado de uma carruagem tombada no centro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ACCOLADE"] =
    "Pintura a óleo de estilo pré-rafaelita inglês, uma visão de livro de contos da cavalaria. Uma rainha de cabelos dourados em um esvoaçante vestido branco toca uma espada no ombro de um cavaleiro ajoelhado, sagrando-o diante de uma pequena corte. Ele inclina a cabeça em sua cota de malha e um sobreveste vermelho, o elmo no chão ao seu lado, o salão de pedra e o estrado vermelho pintados em detalhe romântico e luminoso."
