-- Mod-authored victory and defeat screen descriptions, de_DE overlay.
-- Baseline in CivVAccess_VictoryDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_MISSING"] = "Keine Beschreibung für diesen Bildschirm."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_CULTURAL"] =
    "Von einer grasbewachsenen Anhöhe im Schatten eines dunklen Baumes blicken zwei Gestalten als Silhouetten sitzend über eine goldene Stadt hinaus. Unter ihnen überquert eine Menschenmenge eine gewölbte Steinbrücke, die von klassischen Statuen auf Sockeln gesäumt ist, dahinter erhebt sich eine kuppelgekrönte Halle. Jenseits einer Parklandschaft steigt die Skyline in schlanke futuristische Türme auf, die sich in bernsteinfarbenem Dunst auflösen. Menschen sind über die Rasenflächen verstreut: Kinder laufen unter einem Drachen umher, der hoch an seiner Schnur steht, eine Gestalt schlendert unter einem gelben Sonnenschirm, und auf dem fernen Wasser zeigen sich durch den Dunst weiße Segel. Die ganze Szene ist in warmes goldenes Licht getaucht, halb später Nachmittag und halb Traum, mit Vögeln, die über den Himmel verstreut sind."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DIPLOMATIC"] =
    "Eine Zeremonie auf einer grünen Rasenfläche vor der hohen weißen Platte des Hauptquartiers der Vereinten Nationen. Im Vordergrund steht eine Menschenmenge mit dem Rücken zum Betrachter, gekleidet in Anzüge, Gewänder und Kopftücher vieler Nationen, während rechts ein Fernsehkameramann von einem Stativ aus filmt. Fahnenmasten umringen den Rasen und tragen Dutzende Nationalflaggen, unter ihnen sind die Vereinigten Staaten und Mexiko zu erkennen. In der Mitte ruht unter sich ausbreitenden Bäumen ein großer steinerner Globus auf einem quadratischen Sockel, seine Kontinente im Relief erhaben. Davor wartet eine Reihe Kinder in den Trachten verschiedener Länder; eine Frau in Blau beugt sich herab, um einem kleinen Mädchen in gelbem Kleid etwas zu reichen, das danach greift. Blumenbeete in Rot und Weiß säumen am unteren Rand des Bildes einen stillen Teich, und weiches graues Tageslicht gleicht alles aus."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DOMINATION"] =
    "Eine Siegesparade in Plakatfarben gemalt, ganz in Gold, Oliv und Rot. Im rechten Vordergrund umfasst ein junger Offizier in weißer Galauniform mit Goldlitze an der Schulter den Schaft einer riesigen roten Fahne, die sich über den Himmel hin aufbläht, seine Schirmmütze rot umbändert mit einem goldenen Abzeichen. Hinter ihm stehen Reihen von Soldaten in gleichen weißen Uniformen, die Gewehre mit aufgepflanzten Bajonetten aufrecht an der Schulter, weitere rote Fahnen steigen aus der Kolonne auf. Über der Parade steht auf einem hohen Sockel eine bronzene Statue eines Befehlshabers auf einem ausschreitenden Pferd, dahinter ein großes kuppelgekröntes Kapitolgebäude. Dünne rote Banner flattern in Bändern über einen glühenden gelbgrünen Himmel, dunkle Zypressen und dunstige Berge schließen die Ferne ab."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_SPACE_RACE"] =
    "Tiefer Weltraum, der Blick von unten hinauf zu einer riesigen Orbitalstation. Ihr dunkler Rumpf erstreckt sich über den oberen Rand des Bildes, an seiner Unterseite Reihen hoher, warm erleuchteter Fenster und grün leuchtender Buchten. Dampfschwaden treiben über das Metall. Flache, gegitterte Solarpaneele breiten sich an Gitterauslegern vom Rumpf aus, und vom anderen Ende fällt ein langer, mit Paneelen verkleideter Gittermast an der rechten Seite des Bildes herab. Darunter erstreckt sich die Nachtseite eines Planeten in tiefem Violett und Weinrot, ihr Horizont krümmt sich über den unteren Rand der Szene. Die Sonne bricht gerade über diesem Horizont in einem weißgoldenen Aufflammen hervor, das Bänder rosa und cremefarbener Wolken entlang der Wölbung erhellt. Im Vordergrund durchquert ein einzelnes geflügeltes Schiff das Dunkel auf einer langen leuchtenden türkisfarbenen Spur, und kleinere Fahrzeuge blitzen in der Ferne grün und orange vor den Sternen auf."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_TIME"] =
    "Die eigene Titelillustration des Spiels, vergrößert auf den ganzen Bildschirm. Ein Globus, zusammengesetzt aus antiken sepiafarbenen Landkarten, beherrscht das Bild, der Titel Sid Meier's Civilization steht in erhabenen, polierten Metallbuchstaben quer darüber, durch eine riesige messingfarbene römische Fünf gefädelt. Eine abgegriffene finnische Briefmarke ist oben links aufgeklebt, ein Reiter auf einem geschmückten Pferd zum Gedenken an das Epos Kalevala. Verblasste Poststempel sind ringsherum eingedruckt. Hinter dem Globus liegt eine Collage aus türkis gefärbtem Papier, ein messingfarbener Meridianring spannt sich um den unteren Rand des Globus, und das Licht fällt von oben links ein, als läge ein Sammlerstück unter einer Lampe."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_DEFEAT"] =
    "Ein totes Reich unter einem Wüstenhimmel. Der kolossale Steinkopf einer Statue liegt auf seiner Wange im Sand, die Augen geschlossen, das Gesicht gelassen, während nahebei eine gebrochene Steinhand aus dem Boden greift, die Finger zum Himmel gekrümmt. Eine Ausgrabung umgibt ihn: Gräben sind in die Erde des Vordergrunds geschnitten, eine Zaunlinie aus Pfosten und Draht und eine einzelne Gestalt in heller Kleidung steht auf einer hölzernen Treppenplattform, neben dem Gesicht, das sie betrachtet, winzig klein. Ein Lasttier wartet weiter links. Das leere Tal reicht zurück an verstreuten aufrechten Bruchstücken vorbei zu flachgekrönten Tafelbergen am Horizont. Alles ist sandfarben und rostbraun unter einem dünnen blauen Himmel, der einsame und ebene Sand aus Shelleys Ozymandias erstreckt sich weit hinaus."
