-- Mod-authored world wonder splash painting descriptions, de_DE overlay.
-- Baseline in CivVAccess_WonderDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_MISSING"] = "Für dieses Wunder gibt es keine Beschreibung."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOTHERLAND_STATUE"] =
    "Das Spiel wurde ohne ein Gemälde für dieses Wunder ausgeliefert; es gibt kein Bild zu beschreiben."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ALHAMBRA"] =
    "Aus dem Schatten unter einer schlanken Steinsäule öffnet sich ein Palasthof um ein langes spiegelndes Wasserbecken, der Myrtenhof der Alhambra. Das Becken läuft auf einen Arkadenportikus aus rosafarbenem Stein zu, dessen Bögen sich im stillen Wasser spiegeln. Ein quadratischer Festungsturm erhebt sich warm vor dem blauen Himmel dahinter. Niedrige geschnittene Hecken säumen den Rand des Wassers, ein getopftes Gewächs steht im Vordergrund, und kleine Gruppen in langen Gewändern stehen an den sonnenbeschienenen Wegen und unterhalten sich. Helle Nachmittagssonne erfüllt den Hof, weiß dort, wo sie auf das Pflaster trifft. Tiefer Schatten liegt unter der Kolonnade."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ANGKOR_WAT"] =
    "Eine Gruppe gestufter grauer Steintürme in der Form geschlossener Lotosknospen erhebt sich im Hintergrund, halb von Palmen verdeckt unter einem heißen blassen Himmel. Der Vordergrund ist eine Festprozession: ein grauer Elefant schreitet durch eine dichte Menge, mit einem Reiter auf dem Nacken und einem überdachten Sitz auf dem Rücken, beschattet von einem hohen rot-orangefarbenen Sonnenschirm. Die Menge drängt von allen Seiten heran, in weißen, safranfarbenen und pflaumenfarbenen Gewändern; die Köpfe sind umwickelt, die Schultern bloß, und jedes Gesicht wendet sich dem Elefanten zu, während er vorüberzieht. Die Szene ist sonnendurchglüht und staubig, und der Stein ist kühl grüngrau gegen die warme Haut und den warmen Stoff darunter."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BIG_BEN"] =
    "Ein gotischer Uhrenturm steht bei Nacht am Ende der Westminster Bridge, seine vierseitige Uhr glüht bernsteinfarben nahe der Spitze. Über der Uhr verschwimmt die Turmspitze in einem tiefblauen Himmel. Die lange Front der Londoner Houses of Parliament erstreckt sich nach links, Fenster und Steinwerk warm golden von Flutlicht erhellt. Türme mit Fialen erheben sich an ihrem fernen Ende. Die Brücke quert den Vordergrund mit einer Reihe glühender Laternenpfähle. Einige Kutschen und Gestalten zeichnen sich klein und dunkel auf der Fahrbahn ab. Die ganze Szene ist in Nachtblautönen gegen das Gold der Laternen und des erhellten Steins gemalt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BOROBUDUR"] =
    "Eine Stufenpyramide aus grauem vulkanischem Stein erhebt sich wie ein terrassierter Hügel aus dem Dschungel, ihre oberen Stufen von kleinen glockenförmigen Stupas umringt. Eine größere Stupa krönt den Gipfel. Palmen wachsen aus den unteren Terrassen, und der Wald drängt eng um ihren Fuß. Im Vordergrund steigt eine Reihe von Mönchen in orangefarbenen und roten Gewändern auf einem beschatteten Dschungelpfad zum Tempel hinauf, und Vögel stieben über den dunstigen Himmel darüber. Die Palette ist ein nebliges Graugrün, und die Gewänder sind der einzige kräftige Farbton."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BRANDENBURG_GATE"] =
    "Ein breites klassizistisches Tor aus verwittertem Sandstein steht über die Rückseite eines belebten Stadtplatzes, getragen von paarweise gestellten Reihen schwerer Säulen und gekrönt von der Quadriga, der bronzenen Statue eines Viergespanns, die dunkel vor einem blassen bedeckten Himmel steht. Ein niedrigerer Säulenflügel läuft nach rechts hin zu den umstehenden Steingebäuden. Der Platz davor ist das Berlin des neunzehnten Jahrhunderts: von Pferden gezogene Kutschen rollen über das Kopfsteinpflaster, dazu Reiter und Menschenmengen in langen dunklen Mänteln und Zylindern, links erhebt sich ein Laternenpfahl. Die Farben sind nüchterne Grau- und Brauntöne, und das Licht ist flach und gleichmäßig."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BROADWAY"] =
    "Ein Theaterviertel bei Nacht im frühen zwanzigsten Jahrhundert, die Straße nass vom Regen und schimmernd vom gespiegelten Licht. Erleuchtete Vordächer und Schilder drängen sich auf beiden Seiten der Avenue, weiße und rote Glühbirnen, die Stücktitel buchstabieren. Eine lange helle Theaterfront leuchtet in der Mitte des Häuserblocks. Menschenmengen in dunklen Mänteln und Hüten füllen die Gehsteige und ergießen sich auf die Straße zwischen einige alte Automobile, alle klein vor den hohen dunklen Bürohäusern, die in den Nachthimmel aufragen. Die Palette ist ein tiefes Blauschwarz, durchbrochen von Pfützen warmen weißen, roten und gelben elektrischen Lichts."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CN_TOWER"] =
    "Eine schlanke Betonnadel erhebt sich im Zentrum der Skyline von Toronto, schwillt nahe der Spitze zu einer gerundeten Aussichtskanzel an und verjüngt sich weiter zu einer Antennenspitze. Gewitterwolken reißen rings um sie auf, und Sonnenstrahlen ergießen sich hinter dem Turm durch die Lücke herab und umhüllen die Bürohäuser zu beiden Seiten mit Dunst. Der Vordergrund ist eine abgesenkte Schnellstraße, dicht befahren, Scheinwerfer und rote Rücklichter glühen im Trüben zwischen Betonböschungen. Die ganze Szene ist stahlgrau und golden. Die Stadt liegt halb im Gewitterschatten, halb im aufbrechenden Licht."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CHICHEN_ITZA"] =
    "Eine Stufenpyramide, El Castillo, steht im Zentrum unter einem brennend orangefarbenen Himmel, neun quadratische Stufen steigen zu einem kleinen Tempel auf dem Gipfel empor. Eine breite Treppe läuft gerade über ihre Vorderseite hinauf. Ein zweiter gestufter Tempel erhebt sich am linken Rand, und Rauch zieht über die Sonne dort, wo sie tief und rot steht. Ein Platz darunter ist von einer Menge Mayas erfüllt, die meisten von ihnen abgewandt: bloße Schultern, Federkopfschmuck, erhobene Stäbe und Speere. Eine Gruppe von Kriegern steht rechts auf einer Steinplattform. Alles ist in rostfarbenes und bernsteinfarbenes Dämmerlicht getaucht. Die Menge fällt in dunkle Silhouette gegen den glühenden Stein."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CRISTO_REDENTOR"] =
    "Ein kolossaler heller Stein-Christus, von hinten und von oben gesehen, steht auf seinem Bergsockel mit weit über die Bucht darunter ausgebreiteten Armen. Sein bekleideter Rücken und die ausgestreckten Arme füllen den nahen Bildraum, der Kopf leicht nach vorn geneigt. Jenseits und weit darunter breitet sich Rio de Janeiro um das Wasser aus, in weißen Schwaden von Gebäuden, der gerundete Buckel des Zuckerhuts erhebt sich aus der Bucht zwischen grünen Inseln und ankernden Schiffen. Dunst mildert die Ferne und lässt Stadt und Meer in blassen Blau- und Grautönen zurück, während die Schultern der Statue das Tageslicht einfangen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_COLOSSUS"] =
    "Ein bronzener Riese steht weit entfernt an der felsigen Hafeneinfahrt, einen Arm erhoben, halb im goldenen Dunst aufgelöst. Vor einem Himmel von der Farbe des Messings ist er mehr Silhouette als Statue. Der Vordergrund gehört dem Meer: ein kleines Segelboot neigt sich unter einem einzigen breiten Segel auf den Betrachter zu, zwei oder drei Mann der Besatzung sind am Heck zu sehen. Weitere Segel sind über den Hafen verstreut. Niedrige Felsen ziehen sich rechts entlang der Wasserlinie, und das Wasser trägt dasselbe warme Gold wie der Himmel. Das ganze Gemälde ist eine einzige Farbe, bernsteinfarbenes Licht und Dunst. Der Koloss leuchtet hindurch wie eine Gestalt in einem Traum."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOSQUE_OF_DJENNE"] =
    "Eine lange Erdwand aus Türmen und Zinnen erstreckt sich über den Hintergrund, Lehmziegel in tiefem Rotbraun. Ihre Flächen starren von toron, Reihen von Holzbalken, die wie Dornen aus den Mauern ragen. Der Himmel dahinter ist dicht von orangem Staub und Rauch, die Sonne im Dunst verloren. Der ganze Vordergrund ist ein Markttag: Planen und Baldachine in Rot und Weiß, Tiere zwischen den Ständen und eine dichte Menge in leuchtenden Gewändern, die sich zwischen ihnen bewegt. Hitze und Staub vereinen die Szene, und alles ist in Orange-, Rost- und Brauntönen gemalt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_EIFFEL_TOWER"] =
    "Ein dunkles Eisengitter aus Stützen und verstrebten Plattformen füllt den oberen linken Bildbereich, so nah, dass die Spitze vom Bildrand abgeschnitten wird. Darunter zeigt die Szene einen Nachmittag der Belle Epoque auf dem Gras: Gruppen in langen weißen Kleidern und dunklen Anzügen picknicken auf einer breiten grünen Wiese, Sonnenschirme, Sonnenhüte und Körbe um sie herum ausgebreitet. Eine Frau in Weiß steht in der Mitte. Hinter der Wiese gleitet die Seine vorbei, und der helle Stein von Paris zieht sich am fernen Ufer unter einem sanften grauen Himmel entlang. Die Palette besteht aus kühlen Grün- und Grautönen. Die weißen Kleider fangen das wenige Licht ein, das es gibt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_FORBIDDEN_PALACE"] =
    "Palasthallen mit weit geschwungenen golden gedeckten Dächern und tiefroten Wänden stehen jenseits eines weiten gepflasterten Hofes, gesehen von einer erhöhten Marmorterrasse im Vordergrund. Eine dunkle steinerne Wächterlöwenstatue kauert links auf der Balustrade der Terrasse, und in Gewänder gekleidete Gestalten stehen entlang der Treppen. Unten im Hof sind Reihen von Soldaten in dichter Formation vor der zentralen Halle aufgestellt, von der Architektur ringsum verzwergt. Eine fahle Sonne hängt in einem dunstigen bernsteinfarbenen Himmel, und die ganze Szene ist in staubigem Gold gegen das Rot der Wände getaucht."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GLOBE_THEATER"] =
    "Ein rundes Holztheater, gesehen von seiner eigenen Bühne mitten in einer Aufführung. Drei Ränge umlaufender Galerien schwingen sich um den zentralen Innenhof, jede Brüstung dicht mit Zuschauern besetzt. Auf dem offenen Boden darunter drängen sich die groundlings, die einfachen Stehzuschauer, ein fahles Meer von Gesichtern. Auf der Bühne spielt ein Schauspieler in einem dunklen Wams eine Szene hin zu zwei Frauen in langen Gewändern, von denen eine mit ausgestrecktem Arm gestikuliert. Das bemalte Baldachindach ragt oben rechts auf einem geschnitzten Pfosten herein. Sanftes Tageslicht fällt vom offenen Himmel über dem Innenhof herab. Das Holz ist warmes Cremeweiß und Braun, und die Menge ist blass um die schärferen Gestalten auf der Bühne skizziert."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_FIREWALL"] =
    "Eine abstrakte digitale Szene ohne Gebäude, ein dunkler Cyberspace in Grün und Schwarz wiedergegeben. Breite geschwungene Flächen ziehen wie Datenwälle durch das Bild, ihre Oberflächen mit leuchtenden grünen Binärziffern gekachelt, und glühende Spuren streichen über sie hin wie Verkehr auf einer Autobahn bei Nacht. Geisterhafte Bildschirme und Gitter schweben im Dunkel darüber und deuten Schaltkreise und Überwachung an. Das ganze Bild hat den Anschein der inneren Welt eines Computers, phosphorgrünes Licht auf Schwarz."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIBRARY"] =
    "Eine monumentale klassische Halle steht vor einem sonnenbeschienenen Platz, hohe rote Banner zwischen den Säulen ihres langen Säulengangs aufgehängt. Ein geschnitzter Fries läuft über den Säulen entlang, und breite Stufen breiten sich zum Pflaster hinab. Der Platz ist von einem schattigen Portikus im Vordergrund aus gesehen: links erhebt sich eine Säule, rechts sitzt eine steinerne Sphinx auf einem Sockel, und in der Ferne dahinter zeigt sich eine weiße Kuppel. Gelehrte und Bürger in Togen und farbigen Gewändern versammeln sich auf den Stufen und über den Platz, die meisten zu zweit und zu dritt im Gespräch stehend, während eine Gestalt allein mit einer Schriftrolle sitzt. Der Stein ist warmes Cremeweiß im Sonnenlicht unter einem blauen, von Wolken durchzogenen Himmel, und die Banner sind das stärkste Rot der Szene."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIGHTHOUSE"] =
    "Ein hoher heller Turm aus gestapelten Stufen steht weit entfernt rechts, von einer Lücke im Sturm beleuchtet, sein Leuchtfeuer glüht an der Spitze. Der Rest des Bildes ist raue See: eine Reihe antiker Galeeren unter rot-weiß gestreiften Rahsegeln kämpft sich durch schwere graugrüne Wogen dem Licht entgegen, die Buge hoch geschwungen. Gischt spritzt weiß gegen die Rümpfe. Dunkle Sturmwolken drücken über die ganze Szene herab, und der Himmel öffnet sich nur um den Turm, als liefen die Schiffe darauf zu. Die Segel tragen die einzige warme Farbe in einem Gemälde aus Schiefer, Schaum und Regen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_WALL"] =
    "Ein breiter steinerner Wall läuft vom unteren Bildrand gerade hinauf und über die Berge, seine zinnenbewehrten Brustwehren erklimmen die Bergkämme, bis die Mauer auf den fernsten Gipfeln zu einem Faden schrumpft. Ein quadratischer zweistöckiger Wachturm mit Bogenfenstern und einem kleinen überdachten Pavillon obenauf steht an der ersten Anhöhe. Der Verlauf der Mauer biegt durch ihn hindurch. Die Berge sind gefaltet und grün, dicht bewachsene Hänge, die Tal um Tal in den Dunst abfallen. Nirgends auf der Mauer zeigt sich eine Gestalt. Das Licht ist kühl und klar, grauer Stein gegen tiefes Grün unter einem fahlen Himmel."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HAGIA_SOPHIA"] =
    "Eine große Kuppelbasilika krönt zur goldenen Stunde ein Stadtpanorama, ihre breite Mittelkuppel steigt aus einem Berg von verstrebten Mauern und Halbkuppeln empor. Vier schlanke Minarette stehen an den Ecken, das Gebäude als die Moschee dargestellt, zu der es später wurde. Um die Hagia Sophia herum fallen die Dächer Istanbuls in Sandbraun und Grau den Hang hinab, unterbrochen von Bäumen, kleineren Kuppeln und fernen Türmen, die sich im Dunst auflösen. Ein Glitzern von Wasser und niedrige Hügel schließen links die Ferne ab. Alles liegt unter einem warmen bernsteinfarbenen Himmel, und die Silhouette der Kuppel ist dunkelgolden gegen das Licht."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HANGING_GARDEN"] =
    "Ein Gartenhof liegt innerhalb von Mauern aus warmen Sandsteinbögen. Palmen ragen über die Wege empor, und Grün ergießt sich über jeden Bogen und jeden Sims. Gewandete Gestalten schlendern und sprechen zu zweit und zu dritt entlang der schattigen Pfade zwischen Beeten und kleinen Bäumen. Durch den zentralen Bogen und über der Mauer steigt eine weiße Palaststadt in gestaffelten Terrassen einen Hügel hinauf und schimmert in der Ferne wie die Krone des Gartens. Alles steht in hellem Sonnenlicht, tiefgrünes Laub gegen goldenen Stein und einen blassen Himmel."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HIMEJI_CASTLE"] =
    "Ein weißer Burgturm erhebt sich am oberen Bildrand aus einem bewaldeten Hügel, Stockwerk um Stockwerk blasser Mauern unter geschwungenen grauen Dächern. Kleinere weiße Türmchen drängen sich darunter zwischen den Bäumen. Die Straße hinauf führt durch ein Dorf aus dunklen Ziegeldächern, und ein rot gerahmtes Tor überspannt den Weg im Mittelgrund. Berittene Samurai reiten durch den Vordergrund darauf zu, hohe rote Banner ragen von ihren Rücken auf. Gerüstete Fußsoldaten warten rechts bei den Häusern. Der Tag ist sanft und bedeckt, und die Szene ist ganz in Grün- und Grautönen rund um den weißen Turm gehalten. Die Banner sind das schärfste Rot in der Szene."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HUBBLE"] =
    "Ein langer silberner Zylinder, in Folienpaneele gehüllt, schwebt im Orbit, seine angelenkte Aperturklappe am nahen Ende geöffnet, sodass die dunkle Öffnung der Optik freiliegt. Flache Solarpaneele in kupfergoldenen Rahmen breiten sich von seinen Seiten aus, und ein Astronaut im Raumanzug arbeitet an seiner Flanke, klein gegen das Instrument. Ein Teil eines angedockten Raumschiffs ragt unten rechts ins Bild. Hinter allem füllt die Erde das Bild, eine Wölbung aus blauem Ozean und weißer Wolke, die in den schwarzen Weltraum abfällt. Die Palette ist Silber und Gold gegen das Blau der Erde."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_KREMLIN"] =
    "Schnee fällt über den Roten Platz, wo eine Festungsmauer aus dunkelrotem Backstein rechts unter einem schweren grauen Winterhimmel entlangläuft. Eine rote Fahne weht vom gedrungenen gestuften Block des Lenin-Mausoleums, das an die Mauer gesetzt ist, und weiter entfernt erhebt sich ein hoher Turm in den Dunst, seine Spitze wie ein steiles Zelt geformt. Menschenmengen in langen dunklen Mänteln und Pelzmützen ziehen in einer langsamen Schlange über den schneebedeckten Platz, einzelne Gestalten stapfen mit dem Rücken zum Betrachter durch den Vordergrund. Das Bild ist nahezu monochrom, weißer Schnee und Kohlegrau, mit dem Backstein und der Fahne als einzigem Rot."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LEANING_TOWER"] =
    "Ein runder weißer Glockenturm erhebt sich aus einer grünen Wiese, Stockwerk um Stockwerk von offenen Marmorarkaden umringt und unverkennbar nach rechts geneigt. Der Schiefe Turm von Pisa steht hell vor einem dunklen Gewitterhimmel. Die blasse Flanke des Doms von Pisa steht am rechten Bildrand, und niedrigere Stadtgebäude in Ocker schließen links das Grün ab. Stadtbewohner und Mönche in langen braunen und roten Gewändern queren die Wiese in lockeren Prozessionen, klein unter dem Turm. Das Licht ist theatralisch: ein Riss in den Wolken setzt den weißen Marmor ins Rampenlicht, während der Himmel dahinter nahezu schwarz bleibt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LOUVRE"] =
    "Ein grauer Steinpalast erstreckt sich über den Hintergrund, ein hoher Mittelpavillon mit geschnitztem Zierwerk und steilen Schiefermansarddächern, mit Flügeln, die zu beiden Seiten abgehen. Die Künstler zeigen den Louvre in seinen Tagen als Königspalast, lange vor der gläsernen Pyramide des modernen Museums. Davor liegen formale Gärten: flache Rasenflächen, von Kieswegen durchzogen, junge Bäume und ein kleiner Brunnen, der links Wasser wirft. Spaziergänger in Kleidung des neunzehnten Jahrhunderts sprenkeln die Wege, Frauen in langen weißen Gewändern und Männer in dunklen Mänteln und Zylindern. Ein Paar verweilt rechts beieinander. Der Tag ist sanft und perlmuttfarben. Alles ist grauer Stein und gedämpftes Grün unter einem blassen Himmel."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MACHU_PICHU"] =
    "Eine Steinstadt liegt in einem hohen Bergsattel, landwirtschaftliche Terrassen steigen den Hang hinauf zu Gruppen von Giebelgebäuden unter Strohdächern. Hinter ihr klimmt der steile Gipfel des Huayna Picchu in die Wolken. Nebel hängt über den umliegenden Bergketten, und das Tal fällt unten in den Schatten ab. Auf dem Pfad im Vordergrund arbeitet sich eine kleine Gruppe mit Lasttieren, Lamas, zu den Stadttoren hinauf, winzig gegen die Terrassen. Das Licht fällt in blassen Strahlen durch das Wetter und hebt das warme sandbraune Mauerwerk aus dem Grün und Grau der Anden heraus."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MAUSOLEUM_HALICARNASSUS"] =
    "Ein gewaltiges quadratisches Podium aus weißem Marmor, mit skulptierten Friesen gebändert, steigt zu einem Säulenkranz am oberen Bildrand empor. Es überragt einen Platz, auf dem Statuen auf hohen Pfeilern stehen, darunter eine gerüstete Gestalt und ein Reiter. Dunkle Zypressen sind zwischen die Pflasterflächen gepflanzt. Gestalten in weißen und roten Gewändern versammeln sich unten, winzig neben dem Bauwerk. Der Tag ist hell und klar. Weißer Marmor und aufgetürmte weiße Wolken stehen gegen einen tiefblauen Himmel."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NEUSCHWANSTEIN"] =
    "Eine blasse Erscheinung von einer Burg steht auf einem bewaldeten Bergrücken, weiße Mauern und gedrängte Türme halb im fallenden Schnee aufgelöst, oben links im Bild. Der Vordergrund ist die Straße hinauf zu Neuschwanstein: eine dunkle geschlossene Kutsche wartet an der Kehre, während Reiter den Hang hinauf vorbeiziehen und den Schnee auf der Fahrbahn aufwühlen. Schneebestäubte Tannen säumen den Weg und schließen sich über dem Tal unten. Das Bild ist durchweg in Wintergrau und Weiß. Die Reiter und die Kutsche sind die einzigen dunklen Formen darin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NOTRE_DAME"] =
    "Eine gotische Kathedrale erhebt sich aus dem mittelalterlichen Paris, von oben gesehen, ihre beiden viereckigen Türme, der zentrale Vierungsturm und das lange von Strebebögen gestützte Langhaus ragen weit über jedes Dach ringsum hinaus. Die Stadt drängt sich bis an ihre Mauern in einem dichten Geflecht aus Giebelhäusern und rauchenden Schornsteinen, und die Seine windet sich durch den Vordergrund vorbei an Kais und kleinen Booten. Der Himmel ist schwer und grau, doch Sonnenstrahlen brechen durch die Wolken und fallen unmittelbar auf die Kathedrale, lassen ihren Stein golden leuchten, während die Stadt im schiefergrauen Schatten bleibt. Der Horizont verliert sich flach und blass jenseits der Dächer."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ORACLE"] =
    "Ein runder von Säulen umgebener Tempel unter einer steinernen Kuppel, ein Tholos, steht auf einer Meeresklippe am Ende einer felsigen Landzunge, und ein natürlicher Bogen öffnet sich durch den Fels darunter. Die Künstler setzten das Heiligtum an die Küste statt an den Berghang von Delphi. Ein Pfad windet sich hinaus zu ihm vorbei an Gezeitentümpeln und aufragenden Felsen. Im Vordergrund ziehen Pilger in roten, blauen und weißen Gewändern in kleinen Gruppen den Pfad entlang, gerahmt von dunklen Pinien, die sich von beiden Seiten hereinneigen. Es ist ein kühler früher Abend mit einem blassen mondbeschienenen Himmel und grüngrauer See rund um den warmen Stein des Schreins."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PARTHENON"] =
    "Ein langer dorischer Tempel steht über die gesamte Bildoberseite, seine Säulenreihe trägt einen mit Skulpturen geschmückten und bemalten Giebel. Der Marmor ist warm golden unter einem Himmel aus ziehenden grauen Wolken. Breite Stufen führen von ihm hinab durch Bänke aus niedrigem grünem Gebüsch, mit bronzenen Statuen auf Sockeln zur Linken. Die Stufen herab kommt eine Prozession von Griechen in karmesinroten Umhängen, und in der Mitte wendet sich ein einzelner Hoplit dem Betrachter zu, mit einem Helm samt Helmbusch und einem runden Schild am Arm. Das Rot der Umhänge brennt gegen den Stein, und das Licht hat die schwere Helligkeit eines Tages kurz vor dem Gewitter."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PENTAGON"] =
    "Eine Luftansicht des fünfseitigen Hauptquartiergebäudes, seine konzentrischen fünfeckigen Ringe aus blassem Beton und dunklem Dach stufen sich nach innen zu einem grünen Innenhof in der Mitte ab. Straßen und Parkplätze umschließen das Gebäude, dahinter Rasenflächen und herbstlich getönte Bäume. Der Potomac fließt hinter ihm, von Brücken überspannt. Am fernen Ufer liegt die Hauptstadt im Dunst, der weiße Obelisk des Washington Monument und die Kuppel des Kapitols klein am Horizont. Der Tag ist schlicht und grau; nichts in der Szene sticht hervor außer der Form des Gebäudes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PETRA"] =
    "Der Betrachter steht im Siq, der schmalen Schluchtenzufahrt, zwischen rosenroten Felswänden, die auf beiden Seiten des Bildes im Schatten aufragen. Durch die Lücke, von vollem Sonnenlicht beschienen, steht Al-Khazneh, das Schatzhaus, eine geradewegs in die Klippe gehauene Fassade. Ihre zwei Stockwerke aus klassischen Säulen und Giebeln erheben sich in rosa Sandstein, mit einem runden Pavillon in der Mitte der oberen Ebene. Reisende ziehen über den sandigen Schluchtgrund darauf zu: zwei Reiter schaukeln auf Kamelen im nahen Vordergrund, und verhüllte Gestalten gehen dahinter. Das Gemälde ist ganz aus warmen Rottönen und schattigen Brauntönen, die gehauene Front leuchtet am Ende des dunklen Durchgangs."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PORCELAIN_TOWER"] =
    "Eine hohe Pagode erhebt sich über einem Tempelgarten, Stockwerk um Stockwerk dunkler geschwungener Dachvorsprünge auf einem schlanken Körper. Sie steht über den Ziegeldächern der Hallen an ihrem Fuß. Der Garten breitet sich im Vordergrund um einen stillen Teich aus: gestutzte Pinien, Weiden, Steinlaternen und eine gehauene Löwenstatue auf einem Sockel am linken Rand. Verhüllte Gestalten schlendern zu zweit und zu dritt über die Kieswege, und bewaldete Hügel erheben sich dunstig hinter dem Turm. Die Szene ist ruhig und grün, weiches Tageslicht auf dem Wasser, die Pagode dunkel gegen einen blassen Himmel."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PRORA_RESORT"] =
    "Ein monolithischer Resortblock zieht sich am Ufer entlang, scheinbar ohne Ende. Seine blasse Fassade trägt immer wieder dieselben Fensterreihen, erstreckt sich den Strand hinab, bis sie zum Horizont hin verschwindet. Der hinterste Abschnitt ist noch von Gerüsten bedeckt. Am nahen Ende steht ein großer runder Trommelbau, von Säulen umringt auf einem dunkelroten Sockel, eine rote Fahne weht von seinem Dach. Unten ist der Strand belebt: Badende und Spaziergänger klein über den Sand verstreut, mit der grüngrauen See, die rechts heranrollt. Aufragende sonnenbeschienene Wolken füllen den Himmel über einem hellen Nachmittag am Meer, cremefarbener Beton gegen blaues Wasser."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PYRAMID"] =
    "Zwei große Pyramiden stehen blass im Wüstendunst, die nähere füllt den oberen rechten Bereich des Bildes. Eine dritte steht klein am Horizont. Die Sphinx kauert zwischen ihnen in der mittleren Entfernung. Palmen stehen in einer dünnen Reihe entlang des Sandes, und niedrige verfallene Mauern und Blöcke säumen eine Senke im Vordergrund. Ein Reiter in Rot sitzt auf einem Kamel rechts unten, und eine kleine Kamelkarawane überquert den Sand links, begleitet von Gestalten, die nebenher gehen. Alles ist sandfarben, hellbraun und beinweiß unter einem dunstigen weißen Himmel. Der rote Reiter ist die einzige scharfe Farbe."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_RED_FORT"] =
    "Eine Festung aus tiefrotem Sandstein unter Angriff: hohe Mauern und runde Bastionen füllen das Bild, weiße Pavillons mit Kuppeln stehen entlang der Wehrgänge, Gras wächst aus den Simsen, und Säulen aus schwarzem Rauch steigen von Bränden im Inneren auf. Verteidiger drängen sich auf den Zinnen über dem Tor. Im Vordergrund drücken gepanzerte Soldaten in gerundeten Helmen gegen die Mauern, vorbei an einem hölzernen Katapult und seiner Bedienung am linken Rand. Das Gemälde ist schwer von rotem Stein und Rauch, und die weißen Pavillons und ein Streifen blassen Himmels sind die einzige Aufhellung."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SISTINE_CHAPEL"] =
    "Eine Zeremonie im Inneren der Kapelle, aus der Mitte der Gemeinde gesehen. Die Stirnwand hinter dem Altar ist vom Boden bis zur Decke vom Fresko des Jüngsten Gerichts bedeckt, einem Wirbel von Gestalten auf Blau, und gemalte Szenen und Behänge säumen die Seitenwände unter hohen Bogenfenstern. Das mit Fresken bemalte Gewölbe ragt gerade noch in die Bildoberseite hinein. Geistliche in Weiß zelebrieren am kerzenbeschienenen Altar, während Kardinäle in Scharlachrot den Vordergrund und die Bänke entlang der Wände füllen. Ihr Rot ist die kräftigste Farbe im düsteren Inneren. Was an Tageslicht da ist, fällt grau von den Fenstern auf die bemalten Wände."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_INTERNATIONAL_SPACE_STATION"] =
    "Eine Gitterstation hängt im Orbit vor dem Schwarz des Weltraums: ein langer zentraler Tragbalken, gekreuzt von Paaren großer blaugrauer Sonnensegel, mit der Kette aus weißen zylindrischen Modulen und Andockknoten in seiner Mitte gebündelt. Eine Kapsel hat am nahen Ende der Modulkette festgemacht, und Radiatorpaneele fächern flach unter dem Tragbalken auf. Hinter ihr krümmt sich die Erde in tiefem Blau hinweg, helle Wolkenwirbel auf ihrer Nachtseite. Sterne sind über das Schwarz darüber verstreut. Das Bild ist klar und fotografisch: weißes Metall, ein blauer Planet und nirgends eine Gestalt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_OF_LIBERTY"] =
    "Eine in ein Gewand gehüllte Kupfergestalt, von der Witterung blassgrün verfärbt, steht auf ihrem Steinsockel am linken Rand eines geschäftigen Hafens, den Fackelarm hoch erhoben gegen einen Himmel aus aufgebrochenen Wolken. An ihr vorbei dampft ein Ozeandampfer des frühen zwanzigsten Jahrhunderts, schwarzrumpfig mit zwei rot-schwarzen Schornsteinen, die Kohlerauch hinter sich herziehen, während Schlepper neben ihm durch den Wellengang pflügen. Die Skyline von New York liegt flach und dunstig über dem Wasser zur Rechten. Die Szene ist in Meeresgrau und Meeresgrün gemalt, Rauch und Wolken vermischen sich. Die blassgrüne Statue ist die deutlichste Form in all dem Rauch und den Wolken."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STONEHENGE"] =
    "Ein Kreis aus großen aufrecht stehenden Steinen, gekrönt von Decksteinen, steht bei Nacht auf dunklem Moorland und glüht warm von Feuern, die irgendwo im Inneren entzündet sind, als wäre eine Zeremonie im Gange. Ein Komet schießt am sternenklaren Himmel darüber herab. Vereinzelte abseits gelegene Steine ragen im schattigen Vordergrund aus der Heide, mit einigen kleinen Feuern und schemenhaften Gestalten, die über die Ebene verstreut sind. Alles ist in tiefem Nachtblau gehalten, außer dem bernsteinfarbenen Licht, das sich am Monument sammelt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SYDNEY_OPERA_HOUSE"] =
    "Große weiße segelförmige Dachschalen füllen aus der Nähe den rechten Teil des Bildes und überlappen sich vor einem hellblauen Himmel. Das Glas und das dunkle Mauerwerk des Gebäudesockels zeigen sich darunter. Ein großes weißes Kreuzfahrtschiff liegt gleich dahinter vertäut, und eine schnittige Motoryacht durchschneidet den Wellengang im Vordergrund. Über dem funkelnden Hafen stehen Sydneys Türme weit entfernt zur Linken. Der Tag ist hell und klar. Weiße Dächer und weiße Schiffe heben sich auf dem tiefen blaugrünen Wasser ab."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TAJ_MAHAL"] =
    "Ein weißes Marmormausoleum steht frontal am Ende seines langen Gartens, seine große zentrale Kuppel wölbt sich über einer Bogenportalnische empor. Kleinere kuppelbekrönte Pavillons sitzen zu beiden Seiten der großen Kuppel, und an jeder Ecke der Plattform ragt ein Minarettturm empor. Der Garten verläuft gerade auf es zu: ein schmaler Wasserkanal in der Mitte, gesäumt von gepflasterten Wegen, Reihen dunkler Zypressen und niedrigen grünen Gartenbeeten. Einige kleine Gestalten in Gewändern gehen die Wege entlang. Der Himmel dahinter ist ein sanfter Sonnenuntergang in Pfirsich und Gold, und der Marmor nimmt die Farbe an, Weiß, das ins Cremefarbene und Rosige übergeht."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TEMPLE_ARTEMIS"] =
    "Eine lange Marmorkolonnade unter einem skulptierten Giebel krönt eine Anhöhe im Hintergrund der Szene, mit einer Reiterstatue, die vor der Treppe aufragt, und Zypressen, die dunkel entlang des Zugangs stehen. Eine breite Terrasse davor ist voller Leben: Gestalten in weißen Togen und farbigen Gewändern flanieren und handeln, Verkäufer kauern zur Linken bei Körben, und verschleierte Frauen ziehen nah im rechten Vordergrund vorbei. Eine rote Säule rahmt den Blick am linken Bildrand, mit grüner Tallandschaft und einem Fluss, die weit unten abfallen. Die Mittagssonne brennt auf weißem Marmor und hellem Tuch unter einem blauen Himmel voller aufgetürmter Wolken."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_ZEUS"] =
    "In einer Tempelhalle ragt der thronende Gott in Gold und Elfenbein bis zur Decke empor, bärtig und mit nacktem Oberkörper, ein Gewand über dem Schoß. Die eine Hand hält eine kleine geflügelte Siegesgestalt über die Halle hinaus, die andere umfasst ein hohes Zepter. Sein Thron ist in Gold gearbeitet vor einer Wand aus warmem Rot, und Reihen von Säulen ziehen sich an beiden Seiten der Kammer entlang und lassen die Seitenschiffe im Schatten. Verehrer in blassen Gewändern versammeln sich zu Füßen der Zeus-Statue, keiner von ihnen reicht ihr bis an die Schienbeine. Kleine Flammen brennen entlang der Wände. Licht fällt von irgendwo hoch oben herab und sammelt sich golden auf der Statue, während die Halle ringsum schummrig bleibt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TERRACOTTA_ARMY"] =
    "Reihen von Tonsoldaten füllen das Bild von Wand zu Wand, Reihe um Reihe lebensgroßer Krieger in gepanzerten Röcken, die in Habachtstellung stehen. Sie ziehen sich in langen Korridoren zwischen erdenen Trennwänden zurück. Jede Reihe verblasst tiefer in die Grube hinein, bis die fernsten nur noch Silhouetten gegen ein goldenes Glühen sind, das im hinteren Teil der Kammer hereinbricht. Die Figuren sind erdbraun und grau, ihre Schultern und Helme vom warmen Licht umrandet. Die Stimmung ist still und gewaltig, ein Heer der Toten, das im Dunkeln aufgestellt ist."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UNITED_NATIONS"] =
    "Ein Blick auf Straßenebene auf den Platz der Vereinten Nationen. Der flache Glasblock des Sekretariatsturms ragt zur Linken empor, über dem langen niedrigen Schwung des Versammlungsgebäudes. Eine Reihe von Fahnenmasten trägt die Flaggen vieler Nationen den Häuserblock hinunter. Der Platz ist voller Delegierter: Männer und Frauen in Geschäftsanzügen, gemischt mit Nationaltrachten, eine Gestalt in weißem Golfgewand mit Kopftuch im Zentrum der Menge, Gruppen, die auf ihrem Weg hinein im Gespräch innehalten. Ein gelbes Taxi wartet rechts am Bordstein, und hinter den Flaggen erhebt sich die Skyline von New York. Es ist später Nachmittag, mit langen Schatten über dem Pflaster und tiefer Sonne, die sich im Glas fängt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UFFIZI"] =
    "Zwei lange Galerieflügel stehen einander über einem schmalen Innenhof gegenüber, hohe Renaissancefassaden aus grauem Stein und cremefarbenem Putz, mit Statuen, die in Nischen über der Erdgeschoss-Loggia stehen. Der Innenhof verläuft tief ins Bild hinein, auf eine Bogenöffnung am fernen Ende zu, und dahinter zeichnet sich ein Turm gegen den Himmel ab. Unten ist der Innenhof voller Florentiner in langen Kleidern und dunklen Mänteln, Skulpturen, die auf Sockeln in der Mitte ausgestellt sind, und einem rot überdachten Stand, der im linken Vordergrund aufgebaut ist. Die Nachmittagssonne fällt schräg von einer Seite herein und erleuchtet die oberen Stockwerke warm, während die Loggia darunter kühlen Schatten birgt."
