-- Mod-authored victory and defeat screen descriptions, it_IT overlay.
-- Baseline in CivVAccess_VictoryDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_MISSING"] = "Nessuna descrizione per questa schermata."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_CULTURAL"] =
    "Dalla cima erbosa di una collina ombreggiata da un albero scuro, due figure siedono in controluce e guardano una città dorata. Sotto di loro una folla attraversa un ponte di pietra ad arco fiancheggiato da statue classiche su piedistalli, con una sala a cupola che si eleva alle sue spalle. Oltre una distesa di parco, lo skyline sale in slanciate torri futuristiche che si dissolvono in una foschia ambrata. Persone punteggiano i prati: dei bambini corrono sotto un aquilone che vola alto sul suo filo, una figura passeggia sotto un parasole giallo, e vele bianche si scorgono su acque lontane attraverso la bruma. L'intera scena è immersa in una calda luce dorata, metà tardo pomeriggio e metà sogno, con uccelli sparsi nel cielo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DIPLOMATIC"] =
    "Una cerimonia su un prato verde davanti all'alta lastra bianca della sede delle Nazioni Unite. In primo piano una folla sta in piedi dandoti le spalle, vestita con abiti, vesti e foulard di molte nazioni, mentre un cameraman televisivo riprende da un treppiede sulla destra. Pennoni circondano il prato portando decine di bandiere nazionali, tra cui si riconoscono gli Stati Uniti e il Messico. Al centro un grande globo di pietra poggia su un piedistallo quadrato sotto alberi dalla chioma ampia, i continenti in rilievo. Davanti a esso attende una fila di bambini nei costumi popolari di diversi paesi; una donna in blu si china per porgere qualcosa a una bambina in abito giallo che alza le mani per prenderlo. Aiuole rosse e bianche bordano un laghetto immobile sul fondo dell'inquadratura, e una morbida luce diurna grigia uniforma ogni cosa."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DOMINATION"] =
    "Una parata della vittoria dipinta a colori da manifesto, tutta oro, oliva e rosso. In primo piano a destra un giovane ufficiale in alta uniforme bianca con alamari dorati sulla spalla impugna l'asta di un'enorme bandiera rossa che si gonfia nel cielo, il berretto a visiera fasciato di rosso con un fregio dorato. Dietro di lui file di soldati in uniformi bianche identiche stanno con i fucili a baionetta ritti sulle spalle, altre bandiere rosse che si levano dalla colonna. Sopra la parata una statua di bronzo di un comandante su un cavallo al passo si erge in cima a un alto piedistallo, con un grande edificio del parlamento a cupola alle spalle. Sottili stendardi rossi sventolano in nastri attraverso un cielo giallo-verde luminoso, con cipressi scuri e montagne velate a chiudere la distanza."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_SPACE_RACE"] =
    "Spazio profondo, con lo sguardo rivolto dal basso verso una vasta stazione orbitale. Il suo scafo scuro si estende lungo la parte alta dell'inquadratura, con file di alte finestre dalla luce calda e di hangar dal bagliore verde lungo il ventre. Sbuffi di vapore scorrono sul metallo. Pannelli solari piatti a griglia si dispiegano dallo scafo su travature, e una lunga torre a traliccio rivestita di pannelli scende dalla sua estremità lungo il lato destro dell'inquadratura. Sotto, il lato notturno di un pianeta si allontana in viola profondo e color vino, l'orizzonte che si curva sul fondo della scena. Il sole sta appena sorgendo su quell'orizzonte in un bagliore bianco e oro che illumina fasce di nubi rosa e crema lungo la curva. In primo piano una solitaria nave alata attraversa il buio su una lunga scia luminosa color verde acqua, e velivoli più piccoli brillano di verde e arancione in lontananza contro le stelle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_TIME"] =
    "L'illustrazione di copertina del gioco ingrandita a riempire lo schermo. Un globo composto da antiche mappe color seppia domina l'inquadratura, con il titolo Sid Meier's Civilization che lo attraversa in lettere di metallo lucido in rilievo intrecciate a un gigantesco numero romano cinque in ottone. Un consunto francobollo finlandese è incollato in alto a sinistra, un cavaliere su un cavallo addobbato a commemorare l'epopea del Kalevala. Deboli timbri postali sono impressi tutt'intorno. Dietro il globo si stende un collage di carta tinta di verde acqua, un anello meridiano di ottone si incurva attorno al bordo inferiore del globo, e la luce cade dall'alto a sinistra come su un oggetto da collezione sotto una lampada."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_DEFEAT"] =
    "Un impero morto sotto un cielo desertico. La colossale testa di pietra di una statua giace sulla guancia nella sabbia, gli occhi chiusi e il volto sereno, mentre una mano di pietra spezzata emerge dal terreno lì accanto, le dita ricurve verso il cielo. Uno scavo la circonda: trincee tagliate nella terra in primo piano, una linea di recinzione di pali e filo, e una figura solitaria in abiti chiari ferma su una piattaforma di legno con scala, resa minuscola dal volto che studia. Una bestia da soma attende sulla sinistra. La valle deserta si ritira oltre frammenti sparsi ancora eretti fino a mesa dalla cima piatta all'orizzonte. Tutto è color sabbia e ruggine sotto un sottile cielo azzurro, le sabbie solitarie e piatte dell'Ozymandias di Shelley che si estendono lontano."
