-- Mod-authored victory and defeat screen descriptions, pt_BR overlay.
-- Baseline in CivVAccess_VictoryDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_MISSING"] = "Nenhuma descrição para esta tela."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_CULTURAL"] =
    "Do alto de uma colina gramada sombreada por uma árvore escura, duas figuras estão sentadas em silhueta e olham para uma cidade dourada. Abaixo delas, uma multidão atravessa uma ponte de pedra em arco ladeada por estátuas clássicas sobre pedestais, com um salão abobadado erguendo-se atrás dela. Além de uma faixa de parque, o horizonte sobe em esguias torres futuristas que se dissolvem em uma névoa âmbar. Pessoas pontilham os gramados: crianças correm sob uma pipa que voa alto presa em sua linha, uma figura passeia sob uma sombrinha amarela, e velas brancas aparecem em águas distantes através da névoa. Toda a cena está embebida em uma luz dourada e quente, meio fim de tarde e meio sonho, com pássaros espalhados pelo céu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DIPLOMATIC"] =
    "Uma cerimônia em um gramado verde diante da alta laje branca da sede das Nações Unidas. No primeiro plano, uma multidão está de costas para você, vestida em ternos, túnicas e lenços de cabeça de muitas nações, enquanto um cinegrafista de televisão filma de um tripé à direita. Mastros circundam o gramado erguendo dezenas de bandeiras nacionais, com os Estados Unidos e o México reconhecíveis entre elas. Ao centro, um grande globo de pedra repousa sobre um pedestal quadrado sob árvores frondosas, seus continentes erguidos em relevo. Diante dele aguarda uma fila de crianças nos trajes folclóricos de diferentes países; uma mulher de azul se inclina para entregar algo a uma garotinha de vestido amarelo que estende os braços para alcançá-lo. Canteiros de flores em vermelho e branco margeiam um lago tranquilo na parte inferior do quadro, e uma luz suave e cinzenta do dia equilibra tudo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DOMINATION"] =
    "Um desfile de vitória pintado em cores de cartaz, todo dourado, oliva e vermelho. No primeiro plano à direita, um jovem oficial em uniforme branco de gala com galões dourados no ombro segura o mastro de uma enorme bandeira vermelha que se desdobra pelo céu, seu quepe debruado de vermelho com um distintivo dourado. Atrás dele, fileiras de soldados em uniformes brancos combinantes estão de pé com fuzis de baioneta calada erguidos sobre os ombros, mais bandeiras vermelhas elevando-se da coluna. Acima do desfile, uma estátua de bronze de um comandante sobre um cavalo a passos largos ergue-se no topo de um alto pedestal, com um grande capitólio abobadado atrás dela. Finas faixas vermelhas esvoaçam em fitas pelo céu de um amarelo esverdeado luminoso, com ciprestes escuros e montanhas enevoadas fechando a distância."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_SPACE_RACE"] =
    "O espaço profundo, visto de baixo olhando para uma vasta estação orbital. Seu casco escuro estende-se pelo topo do quadro, com fileiras de altas janelas de luz quente e baías de brilho verde ao longo de sua face inferior. Fiapos de vapor passam à deriva sobre o metal. Painéis solares planos e quadriculados estendem-se do casco em vigas treliçadas, e uma longa torre de treliça revestida de painéis desce de sua extremidade distante pelo lado direito do quadro. Abaixo, o lado noturno de um planeta estende-se ao longe em violeta e vinho profundos, seu horizonte arqueando-se pela parte inferior da cena. O sol está justamente surgindo sobre aquele horizonte em um clarão branco-dourado que ilumina faixas de nuvens cor de rosa e creme ao longo da curva. No primeiro plano, uma solitária nave alada cruza a escuridão em uma longa esteira luminosa de turquesa, e naves menores reluzem em verde e laranja ao longe contra as estrelas."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_TIME"] =
    "A própria arte de capa do jogo ampliada para preencher a tela. Um globo composto de mapas antigos em tom sépia domina o quadro, com o título Sid Meier's Civilization atravessando-o em letras de metal polido em relevo entrelaçadas em um gigantesco algarismo romano cinco em latão. Um gasto selo postal finlandês está colado no canto superior esquerdo, um cavaleiro sobre um cavalo enfeitado comemorando a epopeia Kalevala. Carimbos postais desbotados estão impressos ao seu redor. Atrás do globo há uma colagem de papel manchado de turquesa, um anel meridiano de latão arqueia-se em torno da borda inferior do globo, e a luz incide do canto superior esquerdo como sobre uma curiosidade sob um abajur."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_DEFEAT"] =
    "Um império morto sob um céu de deserto. A colossal cabeça de pedra de uma estátua jaz sobre a bochecha na areia, olhos fechados e rosto sereno, enquanto uma mão de pedra quebrada se ergue do solo ali perto, os dedos curvados para o céu. Uma escavação a circunda: trincheiras cortadas na terra do primeiro plano, uma linha de cerca de postes e arame, e uma figura solitária em roupas pálidas de pé sobre uma plataforma de escada de madeira, diminuída pelo rosto que estuda. Um animal de carga aguarda mais à esquerda. O vale vazio recua para trás passando por fragmentos esparsos ainda de pé até mesas de topo plano no horizonte. Tudo é castanho e ferrugem sob um fino céu azul, as areias solitárias e planas do Ozymandias de Shelley estendendo-se ao longe."
