-- Mod-authored victory and defeat screen descriptions, fr_FR overlay.
-- Baseline in CivVAccess_VictoryDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_MISSING"] = "Aucune description pour cet écran."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_CULTURAL"] =
    "Depuis un sommet de colline herbeux ombragé par un arbre sombre, deux silhouettes sont assises à contre-jour et contemplent une ville dorée. En contrebas, une foule traverse un pont de pierre en arc bordé de statues classiques sur des piédestaux, une salle à coupole s'élevant derrière lui. Au-delà d'une étendue de parc, l'horizon monte en sveltes tours futuristes qui se fondent dans une brume ambrée. Des gens parsèment les pelouses : des enfants courent sous un cerf-volant porté haut au bout de son fil, une silhouette se promène sous un parasol jaune, et des voiles blanches se distinguent sur l'eau lointaine à travers la brume. Toute la scène baigne dans une chaude lumière dorée, moitié fin d'après-midi et moitié rêve, des oiseaux éparpillés dans le ciel."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DIPLOMATIC"] =
    "Une cérémonie sur une pelouse verte devant la haute dalle blanche du siège des Nations Unies. Au premier plan, une foule se tient de dos, vêtue de costumes, de robes et de foulards de nombreuses nations, tandis qu'un cameraman de télévision filme depuis un trépied à droite. Des mâts cernent la pelouse et portent des dizaines de drapeaux nationaux, parmi lesquels on reconnaît les États-Unis et le Mexique. Au centre, un grand globe de pierre repose sur un piédestal carré sous des arbres étalés, ses continents saillant en relief. Devant lui attend une file d'enfants en costumes folkloriques de différents pays ; une femme en bleu se penche pour tendre quelque chose à une petite fille en robe jaune qui lève les bras pour le prendre. Des parterres de fleurs rouges et blanches bordent un bassin immobile au bas du cadre, et une douce lumière du jour grise nivelle l'ensemble."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_DOMINATION"] =
    "Un défilé de la victoire peint en couleurs d'affiche, tout en or, en olive et en rouge. Au premier plan à droite, un jeune officier en uniforme blanc d'apparat aux galons d'or à l'épaule empoigne la hampe d'un immense drapeau rouge qui se déploie à travers le ciel, sa casquette à visière cerclée de rouge et frappée d'un insigne d'or. Derrière lui, des rangs de soldats en uniformes blancs assortis se tiennent, fusils à baïonnette dressés contre l'épaule, d'autres drapeaux rouges s'élevant de la colonne. Au-dessus du défilé, une statue de bronze d'un commandant sur un cheval au pas se dresse au sommet d'un haut piédestal, un grand capitole à coupole derrière elle. De minces banderoles rouges flottent en rubans à travers un ciel jaune-vert lumineux, des cyprès sombres et des montagnes voilées fermant le lointain."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_SPACE_RACE"] =
    "L'espace profond, le regard levé vers une vaste station orbitale vue d'en bas. Sa coque sombre s'étire en haut du cadre, des rangées de hautes fenêtres à la lueur chaude et de baies au rayonnement vert courant le long de sa face inférieure. Des volutes de vapeur dérivent sur le métal. Des panneaux solaires plats et quadrillés s'étendent depuis la coque sur des bras à poutrelles, et une longue tour en treillis revêtue de panneaux descend de son extrémité opposée le long du côté droit du cadre. En dessous, la face nocturne d'une planète s'éloigne en violet profond et en lie-de-vin, son horizon s'arquant au bas de la scène. Le soleil perce tout juste cet horizon en un éclat blanc doré qui illumine des bandes de nuages rose et crème le long de la courbe. Au premier plan, un vaisseau ailé solitaire traverse l'obscurité sur un long sillage turquoise lumineux, et de plus petits engins luisent en vert et en orange au loin contre les étoiles."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_VICTORY_TIME"] =
    "La propre illustration de couverture du jeu agrandie pour remplir l'écran. Un globe assemblé à partir de vieilles cartes sépia domine le cadre, le titre Sid Meier's Civilization s'étalant en travers en lettres de métal poli en relief enfilées dans un gigantesque chiffre romain cinq en laiton. Un timbre-poste finlandais usé est collé en haut à gauche, un cavalier sur un cheval orné commémorant l'épopée du Kalevala. De pâles cachets de la poste sont encrés tout autour. Derrière le globe s'étend un collage de papier teinté de turquoise, un anneau méridien en laiton s'arque autour du bord inférieur du globe, et la lumière tombe d'en haut à gauche comme sur une curiosité sous une lampe."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VICTORYDESC_DEFEAT"] =
    "Un empire mort sous un ciel de désert. La tête de pierre colossale d'une statue gît sur la joue dans le sable, les yeux clos et le visage serein, tandis qu'une main de pierre brisée surgit du sol tout près, les doigts recourbés vers le ciel. Une excavation l'entoure : des tranchées creusées dans la terre au premier plan, une ligne de clôture en poteaux et fil de fer, et une silhouette solitaire en habits pâles debout sur une plateforme d'escalier en bois, écrasée par le visage qu'elle étudie. Une bête de somme attend sur la gauche. La vallée déserte recule au-delà de fragments dressés épars jusqu'à des mesas à sommet plat à l'horizon. Tout est fauve et rouille sous un mince ciel bleu, les sables solitaires et plats de l'Ozymandias de Shelley s'étendant au loin."
