-- Mod-authored great work descriptions, fr_FR overlay.
-- Baseline in CivVAccess_GreatWorkDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_MISSING"] = "Aucune description d'image pour cette oeuvre d'art."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LITERATURE"] =
    "Un bureau d'écrivain vu de près, faiblement éclairé par la lumière chaude d'une bougie. Des feuilles de manuscrit couvertes d'une écriture cursive fluide recouvrent la surface, une unique plume d'oie grise posée en travers. Un rouleau noué d'un ruban rouge repose sur le bord gauche, et un encrier de verre luit en haut à droite."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MUSIC"] =
    "Une salle de concert sombre éclairée par la lumière chaude des bougies. Au centre, un chef d'orchestre en habit bleu et bas blancs se tient debout, sa baguette levée, face à un orchestre assis de musiciens en perruques poudrées qui lisent sur leurs pupitres. Une galerie supérieure dorée, sculptée de panneaux en relief, court le long du mur du fond, et un grand lustre à bougies flamboie sur la droite, tandis que les têtes du public se découpent en formes sombres au premier plan."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIRL_WITH_PEARL_EARRING"] =
    "Peinture à l'huile du Siècle d'or néerlandais, l'un des portraits les plus aimés de l'art occidental. Une jeune femme se retourne par-dessus son épaule pour croiser votre regard, surgissant d'un fond sombre et uni, les lèvres juste entrouvertes comme sur le point de parler. Elle porte un turban bleu et or dont l'étoffe retombe dans son dos, et une unique grande perle en forme de larme accroche la lumière à son oreille."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HENRY_VIII"] =
    "Portrait de cour Tudor à l'huile, l'image qui a fixé la façon dont le monde se représente Henri VIII. Le roi se tient face à vous en pied, les pieds largement écartés, large d'épaules et corpulent, une main posée sur une dague à la ceinture. Il porte un pourpoint d'argent serti de joyaux sous un manteau cramoisi doublé de fourrure, un chapeau plat à plume et des chaînes d'or, debout sur un tapis à motifs entre des colonnes de marbre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HUNTERS_IN_THE_SNOW"] =
    "Peinture à l'huile de la Renaissance flamande, un paysage d'hiver vu du sommet d'une colline. Au premier plan, trois chasseurs épuisés et leur meute de chiens avancent péniblement dans la neige profonde, la tête baissée, avec un seul renard pour tout butin. En contrebas, un village s'étend sous un ciel gris-vert, de minuscules patineurs s'amusant sur des étangs gelés et des pics déchiquetés se dressant au loin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LES_DEMOISELLES"] =
    "Peinture à l'huile du premier modernisme, la toile qui a lancé le cubisme. Cinq femmes nues, debout ou assises, occupent un espace peu profond de plans roses, blancs et bleus déchiquetés, leurs corps brisés en formes anguleuses tranchantes. Les deux visages de droite sont peints comme des masques africains, striés et déformés, tandis que les autres regardent droit devant elles de leurs grands yeux en amande ; une petite coupe de fruits se trouve au bord inférieur."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LUNCHEON"] =
    "Peinture à l'huile de l'impressionnisme français représentant des amis s'attardant après un repas. Un groupe animé en tenue d'été se presse sur un balcon au bord de l'eau sous un store rayé orange et blanc, bavardant, flirtant et s'appuyant à la rambarde ; au premier plan, une jeune femme joue avec un petit chien. La table est jonchée de bouteilles de vin, de verres et de fruits, le tout peint en touches chaudes et libres de couleur ensoleillée."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MONA_LISA"] =
    "Huile sur panneau de bois de la Renaissance italienne, sans doute le portrait le plus célèbre du monde. Une femme est assise, les mains croisées, légèrement tournée vers vous devant un paysage brumeux de rivières sinueuses et de montagnes bleues lointaines. Ses yeux croisent directement les vôtres, ce regard célèbre qui semble vous suivre où que vous soyez. Son léger demi-sourire est le centre du tableau, peint en bruns et verts doux sans contours nets, de sorte que son expression semble changer à mesure que vous la regardez."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUNDAY_AFTERNOON"] =
    "Peinture à l'huile pointilliste, entièrement construite à partir de minuscules points de couleur pure. Des Parisiens endimanchés se détendent sur une pelouse ensoleillée au bord de l'eau, flânant sous des ombrelles, allongés dans l'herbe ou promenant de petits chiens, des voiliers sur l'eau derrière eux. Tout le monde est étrangement immobile et figé, comme des personnages d'une frise, la lumière décomposée en un chatoiement de points verts, orange et violets."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VIEW_OF_TOLEDO"] =
    "Peinture à l'huile de la Renaissance espagnole, l'un des tout premiers paysages purs de l'art occidental et d'une noirceur inhabituelle. La ville espagnole de Tolède, perchée sur sa colline, se dresse au loin sous un ciel d'orage violent, ses flèches et ses remparts gris éclairés d'une lumière argentée inquiétante. Des collines vertes descendent vers une rivière au premier plan, toute la scène peinte en verts profonds et noirs bleutés qui tiennent plus du rêve que du plein jour."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WATER_LILIES"] =
    "Peinture à l'huile de l'impressionnisme français, tirée de la célèbre série de Monet sur le bassin de son jardin à Giverny. Toute la toile est la surface de l'eau, sans horizon ni rive : des îlots de nénuphars verts dérivent sur une eau bleue et lavande parsemée de fleurs roses et rouges. Les nuages et les arbres n'apparaissent que sous forme de reflets diffus, la touche assez libre pour que tout semble flotter."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_STARRY_NIGHT"] =
    "Peinture à l'huile postimpressionniste, l'une des images les plus reconnues de l'art moderne. Un ciel nocturne animé de mouvement occupe la majeure partie de la toile : les étoiles flamboient au coeur de halos tourbillonnants, et la lune brûle, orange, dans le coin tandis qu'un grand courant en spirale roule au milieu du ciel. En dessous, un village paisible au clocher d'église pointu dort parmi les collines, et un sombre cyprès s'élève en flammes le long du bord gauche, le tout en touches épaisses et visibles de bleu et d'or."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BIRTH_OF_VENUS"] =
    "Peinture de la Renaissance italienne représentant la déesse de l'amour arrivant de la mer, parmi les images les plus célèbres de la mythologie classique. Vénus se tient nue sur une immense coquille Saint-Jacques, se couvrant de ses mains et d'une longue chevelure dorée. À gauche, deux dieux du vent ailés la poussent vers le rivage à travers une pluie de roses roses, tandis qu'à droite une femme en robe fleurie se précipite pour l'envelopper d'un manteau gonflé par le vent."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BINDO_ALTOVITI"] =
    "Portrait à l'huile de la Haute Renaissance italienne d'un jeune et riche banquier romain. Un beau jeune homme aux longs cheveux dorés et coiffé d'un bonnet noir vous regarde par-dessus son épaule nue, une main ramenée sur sa poitrine. Il porte un manteau bleu par-dessus un vêtement noir, et son visage pâle rayonne sur un fond vert profond."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_DRAGON"] =
    "Peinture du début de la Renaissance italienne, avec le charme raide et imagé d'un conte de fées. À droite, un chevalier en armure sur un cheval blanc cabré enfonce sa lance dans la gueule ouverte d'un dragon vert ailé aux ailes tachetées semblables à celles d'un papillon de nuit. À gauche, une princesse sereine en longue robe rose tient la bête blessée en laisse comme un animal de compagnie, devant sa sombre caverne, tandis qu'une étrange tempête en spirale se rassemble derrière le chevalier."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CREATION_OF_ADAM"] =
    "Fresque de la Renaissance italienne au plafond de la chapelle Sixtine, source de l'un des gestes les plus célèbres de l'art. Un Adam nu est allongé sur un coteau verdoyant à gauche, un bras tendu mollement, tandis que Dieu, figure à la barbe grise dans un linceul rose gonflé et empli d'anges, déferle depuis la droite. Leurs index tendus se rejoignent presque par-dessus un petit intervalle, l'instant qui précède l'étincelle de la vie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GALLERY_OF_THE_LOUVRE"] =
    "Peinture à l'huile américaine représentant une galerie à l'intérieur du Louvre, par ce même Morse qui inventa plus tard le code télégraphique. Un grand salon aux murs rouges est couvert du sol au plafond de dizaines de tableaux de maîtres anciens dans des cadres dorés, dont une minuscule Mona Lisa. Au premier plan, des étudiants en art copient, assis à leurs chevalets, tandis que leur professeur se penche par-dessus l'épaule d'une jeune femme pour corriger son travail, et un couloir voûté ouvrant sur d'autres galeries s'enfonce au loin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WASHINGTON_CROSSING"] =
    "Peinture d'histoire américaine héroïque à l'huile, une icône de la guerre d'Indépendance. Le général Washington se tient debout à la proue d'une barque bondée tandis que ses soldats poussent à la perche et rament à travers un fleuve encombré de plaques de glace, un officier derrière lui brandissant le drapeau américain bien haut. La lumière de l'aube perce la brume froide, et d'autres barques pleines d'hommes et de chevaux suivent derrière."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ARRANGEMENT_IN_GREY"] =
    "Peinture à l'huile américaine universellement connue sous le nom de Mère de Whistler. Une femme âgée en longue robe noire et bonnet de dentelle blanche est assise de profil strict, tournée vers la gauche, les mains croisées sur les genoux et les pieds sur un petit tabouret. La pièce est austère et dépouillée : un mur gris, un sombre rideau à motifs et un seul tableau encadré, l'ensemble de la composition équilibré comme une étude en gris et noir, exactement comme le dit le titre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BREEZING_UP"] =
    "Peinture à l'huile réaliste américaine d'une sortie en petit voilier au large de la côte de Nouvelle-Angleterre. Un homme et trois garçons se penchent en arrière dans un petit catboat nommé Gloucester qui gîte sous une brise vive, les embruns se brisant à la proue et la prise du jour entassée à leurs pieds. La mer est d'un vert agité sous des nuages épars, avec une goélette à deux mâts à l'horizon."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_THOUSAND_LI"] =
    "Rouleau de paysage bleu-vert chinois, peint sur soie par un prodige adolescent de la cour des Song et long de près de douze mètres. Des montagnes d'un bleu et d'un vert minéral éclatants s'élèvent crête après crête au-dessus d'une calme rivière dorée, avec de minuscules villages, des ponts et des arbres dénudés nichés entre les pentes. Des colonnes de calligraphie au pinceau et des sceaux rouges de collectionneurs remplissent le ciel au-dessus des sommets."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DWELLING_IN_THE_FUCHUN"] =
    "Rouleau à l'encre chinois, chef-d'oeuvre de la peinture de paysage lettrée de la dynastie Yuan, exécuté entièrement en nuances d'encre noire sur papier. Des montagnes arrondies, bâties de coups de pinceau secs et superposés, s'élèvent au-dessus d'une large rivière calme, avec des pins, des chaumières éparses et des barques de pêche le long des berges. L'atmosphère est paisible et contemplative, le papier parsemé de sceaux rouges de collectionneurs accumulés au fil de siècles d'admirateurs."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ALONG_THE_RIVER"] =
    "Rouleau sur soie de la dynastie Song chinoise, célèbre panorama de la vie quotidienne urbaine long de plus de cinq mètres. La section montrée est centrée sur la grande porte de la capitale, une tour de bois massive au sommet d'un rempart en pente, avec en dessous des rues grouillantes de vie : étals de marché, charrettes à boeufs, une caravane de chameaux franchissant la porte, et des porteurs transportant des charges sur des perches d'épaule. Chaque personnage est minuscule mais dessiné avec précision au fin trait d'encre dans des tons de terre estompés."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LEAF_2"] =
    "Feuille d'album de la dynastie Qing chinoise, peinture de cour au trait fin et à la couleur délicate. D'élégantes dames en longues robes flottantes blanches, vertes et bleues se rassemblent dans un pavillon de jardin tendu d'étoffe bleu vif, l'une faisant brûler de l'encens à une table derrière une rambarde rouge. Autour d'elles se trouvent des rochers de jardin, du bambou et une vigne fleurie grimpant sur le toit du pavillon."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EMPEROR_TAIZONG"] =
    "Rouleau sur soie de la dynastie Tang chinoise, registre de cour d'une rencontre diplomatique. À droite, l'empereur Taizong est assis sur une estrade portée par des dames du palais qui tiennent aussi deux grands éventails et un dais rouge au-dessus de lui. À gauche, trois figures plus petites s'approchent en postures respectueuses : un huissier de cour en rouge, l'ambassadeur tibétain en robe à motifs et un interprète en blanc, le tout sur une soie d'un or chaud couverte de sceaux rouges."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SPRING_MORNING"] =
    "Rouleau sur soie de la dynastie Ming chinoise, long panorama de femmes du palais à leurs loisirs par un matin de printemps. Des dizaines d'élégantes dames emplissent les salles ouvertes, les vérandas et les cours : faisant de la musique, peignant un portrait, jouant avec des enfants, et se promenant parmi les saules, les rochers de jardin et même des paons. L'architecture du palais s'étend sur toute la longueur du rouleau dans des rouges et des verts chauds, chaque paravent, chaque rambarde et chaque robe rendus dans un détail méticuleux au trait fin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_GREAT_WAVE"] =
    "Estampe sur bois japonaise ukiyo-e, l'image la plus célèbre de tout l'art japonais. Une énorme vague d'un bleu profond se dresse à gauche et déferle sur toute la scène, sa crête se brisant en doigts d'écume blanche semblables à des griffes. En dessous, trois longues barques ouvertes pleines de rameurs chevauchent les creux, et loin dans le fond, petit au centre de tout cela, se dresse le cône enneigé du mont Fuji."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EVENING_SHOWER"] =
    "Estampe sur bois japonaise ukiyo-e, l'une des scènes de pluie les plus admirées jamais réalisées. Une averse soudaine, rendue par des nappes de fines lignes obliques, surprend des gens à mi-chemin sur un long pont de bois ; ils se hâtent dans les deux sens sous des chapeaux et des parapluies, l'un s'abritant sous une natte de paille. La rivière en dessous est une bande bleu-vert qu'un radeleur solitaire traverse à la perche, et la rive opposée se fond en une tache sombre sous l'orage."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_L_ABSINTHE"] =
    "Peinture à l'huile impressionniste française, scène impitoyable de la vie des cafés parisiens. Une femme en robe et chapeau pâles est assise affaissée à une table de café en marbre, les yeux baissés, un verre d'absinthe vert laiteux devant elle ; à côté d'elle, un homme barbu en manteau froissé regarde au loin vers la droite, la pipe à la bouche. Les deux sont ensemble et pourtant totalement séparés, peints dans des gris et des bruns ternes qui portent l'air de solitude du tableau."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_UPAUPA_SCHNEKLUD"] =
    "Portrait à l'huile post-impressionniste d'un violoncelliste en pleine prestation. Le musicien se penche sur son violoncelle d'un rouge orangé éclatant, les yeux baissés dans la concentration, le bras d'archet balayant les cordes, son costume bleu foncé encadrant la lueur de l'instrument. Derrière lui, le fond se divise en zones plates de brun et de vert mousse parsemées de formes abstraites pâles, dans le style de couleur audacieux et simplifié de Gauguin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_BAR_AT_THE_FOLIES"] =
    "Peinture à l'huile française de la vie moderne, dernière grande œuvre de Manet. Une serveuse en corsage de velours noir, une fleur à la poitrine, se tient derrière un comptoir de marbre encombré de bouteilles de champagne, d'une coupe d'oranges et d'un verre où trône une rose, le regard perdu dans une expression lasse et lointaine. Derrière elle, un immense miroir reflète la salle de spectacle scintillante, ses lustres et sa foule, et, étrangement décalé vers la droite, le dos de la femme elle-même tandis qu'elle se penche vers un homme en haut-de-forme."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BALL_AT_THE_MOULIN"] =
    "Peinture à l'huile postimpressionniste de la vie nocturne parisienne au célèbre cabaret. Un groupe d'hommes en haut-de-forme et de femmes en chapeaux à plumes sont assis autour d'une table garnie de boissons, tandis qu'une femme aux cheveux roux rajuste sa coiffure dans la salle de bal éclairée de vert derrière eux. Un visage de femme surgit au bord droit, éclairé d'un vert spectral par en dessous, et une longue balustrade en diagonale tranche le premier plan dans le style d'affiche propre à Lautrec."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS"] =
    "Peinture à l'huile Art nouveau viennoise rehaussée de feuille d'or véritable, l'œuvre la plus célèbre de Klimt. Un couple est agenouillé, enlacé sur une prairie fleurie, l'homme se penchant pour embrasser la joue de la femme tandis qu'elle renverse le visage en arrière, les yeux clos. Leurs corps se fondent en un seul manteau doré, à motifs de rectangles pour lui et de cercles éclatants pour elle, qui resplendit sur un fond d'or plat et chatoyant."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AMERICAN_GOTHIC"] =
    "Peinture à l'huile régionaliste américaine, parodiée à l'infini et instantanément reconnaissable. Un fermier sévère et dégarni, à lunettes rondes et en salopette en jean, se tient debout en brandissant droit une fourche à trois dents, une femme en robe-tablier à motifs sombres à ses côtés, le regard détourné, les lèvres pincées de désapprobation. Derrière eux se dresse la ferme blanche qui donne son nom au tableau, percée dans son pignon d'une fenêtre gothique en arc brisé."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SRI_SHANMUKAHA"] =
    "Peinture dévotionnelle indienne dans le style académique européen que Ravi Varma rendit célèbre dans toute l'Inde. Le dieu hindou Murugan chevauche sa monture, un paon, doté de six têtes couronnées et de nombreux bras qui tiennent des armes, flanqué de ses deux épouses en saris rose vif. La queue du paon se déploie derrière eux comme un éventail géant d'yeux verts et or, tandis que l'oiseau cloue un cobra sous ses pattes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DAUD_RECEIVES_A_ROBE"] =
    "Miniature moghole tirée d'une chronique impériale illustrée, à l'aquarelle opaque et à l'or sur papier. Le détail montré est centré sur un jeune serviteur svelte en robe pâle, coiffe rouge et ceinture dorée, portant le caftan d'honneur doré et plié pour la cérémonie de remise. Il se tient devant la paroi d'une tente d'un bleu éclatant couverte de fines vrilles fleuries, chaque pli et chaque fleur peints avec une précision de miniaturiste."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YUSEF_AND_ZULEYKHA"] =
    "Miniature persane tirée d'un manuscrit illustré, l'œuvre la plus célèbre du grand maître de Hérat, Behzad. La page est emplie d'un palais minutieux vu en coupe aplatie, un dédale d'escaliers, de balcons et de portes carrelés de bleu, d'orange et d'or. Dans une chambre haute, le prophète Yusuf, auréolé de flammes, fuit l'étreinte tendue de Zulaikha, tandis que des panneaux de calligraphie persane encadrent l'architecture."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ASCENT_OF_MUHAMMAD"] =
    "Miniature persane tirée d'un manuscrit royal, représentant le voyage nocturne du Prophète à travers les cieux. Mahomet, le visage voilé de blanc et nimbé d'une flamme dorée, chevauche Bouraq, la monture à tête humaine, à travers un ciel d'un bleu profond parsemé de nuages enroulés bordés d'or. Des anges en robes rouges, vertes et orange tourbillonnent autour de lui de tous côtés, portant offrandes et encensoirs, des vers persans encadrant la scène."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LIBERTY_LEADING_THE_PEOPLE"] =
    "Peinture à l'huile romantique française, l'image emblématique de la révolution. La Liberté elle-même, femme aux seins nus en robe jaune et bonnet rouge, enjambe une barricade de gravats et de corps tombés, brandissant le drapeau tricolore français vers le ciel enfumé. Autour d'elle déferlent des citoyens armés de toutes les classes, parmi lesquels un gentleman en haut-de-forme avec un mousquet et un garçon agitant deux pistolets."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_JEROME_IN_HIS_STUDY"] =
    "Peinture à l'huile du début de la Renaissance, d'une remarquable précision de miniature. Vu à travers une grande arche de pierre, saint Jérôme en robe rouge est assis et lit dans un cabinet de bois aménagé comme une scène à l'intérieur d'un espace de cathédrale voûté, entouré d'étagères de livres et de pots. La lumière entre à flots par des fenêtres de tous côtés, un paon et une perdrix se perchent sur le seuil au premier plan, et son lion rôde dans l'ombre à droite."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PARTHENON_FRIEZE"] =
    "Peinture à l'huile victorienne imaginant l'Athènes antique ; dans le jeu, cette œuvre accompagne la merveille du Parthénon. Le sculpteur Phidias se tient sur un échafaudage de bois auprès de sa frise de marbre de cavaliers fraîchement peinte, encore dans ses couleurs d'atelier, retenant une corde tandis qu'il la présente. Un petit groupe d'Athéniens en robes drapées, Périclès parmi eux, se penchent pour admirer la sculpture à la chaude lumière de l'intérieur du temple."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUE_DE_PARIS"] =
    "Peinture à l'huile réaliste française du Paris moderne par temps de bruine, nette et photographique là où ses amis impressionnistes avaient la touche plus libre. Un couple bien vêtu partageant un parapluie marche vers vous sur des pavés luisants, l'homme en haut-de-forme et la femme en longue robe sombre, une boucle d'oreille accrochant la lumière. Autour d'eux, d'autres promeneurs munis de parapluies traversent un large carrefour bordé d'immeubles gris en forme de coin, un réverbère vert fendant la scène en son milieu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_NIGHT_WATCH"] =
    "Peinture à l'huile du Siècle d'or néerlandais à très grande échelle, le portrait de groupe le plus célèbre jamais réalisé. Une compagnie de milice urbaine s'élance hors d'une ombre profonde : le capitaine, en noir avec une écharpe rouge, s'avance en donnant un ordre à son lieutenant vêtu d'or pâle, tandis que derrière eux des mousquets se chargent, une bannière se lève et un tambour bat la mesure. Une petite fille en robe dorée rayonnante brille mystérieusement dans la foule, éclairée comme par un projecteur dans la pénombre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DEATH_OF_MARAT"] =
    "Peinture à l'huile néoclassique française, la grande image de martyr de la Révolution française. Le journaliste révolutionnaire Marat gît mort dans sa baignoire, affaissé comme un saint tombé, la tête enveloppée d'un turban blanc et un bras pendant jusqu'au sol, tenant encore sa plume. Dans son autre main se trouve la lettre dont son assassin se servit pour s'introduire ; la moitié supérieure de la toile n'est qu'un mur sombre et nu, et la simple caisse de bois à côté de lui porte la dédicace peinte \"A Marat, David.\""
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ETIENNE_CHEVALIER"] =
    "Peinture française sur panneau de la fin du Moyen Âge, l'un des volets d'un célèbre diptyque de dévotion. Le trésorier royal Étienne Chevalier est agenouillé dans une riche robe rouge, les mains jointes en prière, présenté par son saint patron saint Étienne, qui se tient à côté de lui dans un vêtement bleu et or. Le saint porte un livre surmonté d'une pierre déchiquetée, symbole de son martyre, et tous deux se tiennent dans une salle de marbre blanc où le nom du donateur est gravé le long du mur."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_FRANCIS"] =
    "Peinture à l'huile baroque espagnole d'une dévotion monastique austère. Saint François se tient seul dans un simple habit à capuche couleur de sable, le visage à demi perdu dans l'ombre profonde du capuchon, les yeux baissés en prière. Il tient un crâne humain entre ses mains en rappel de la mort, éclairé par une unique lumière crue sur un fond presque noir."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HATAORI"] =
    "Estampe japonaise ukiyo-e sur bois gravé représentant une tisserande au travail. Une jeune femme vêtue d'un kimono indigo à motifs est assise pieds nus devant un grand métier à tisser à main en bois, levant les yeux de son ouvrage avec une navette dans une main, des fils rouges, bleus et blancs tendus sur toute la longueur de la machine. Les couleurs sont des crèmes douces et des bleus assourdis, avec une colonne de poésie au pinceau remplissant le coin supérieur gauche de la feuille."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JANE_GREY"] =
    "Peinture d'histoire académique française, théâtrale et déchirante. La jeune reine, les yeux bandés et vêtue d'un satin blanc qui rayonne contre la sombre salle de pierre, est agenouillée et cherche à l'aveugle le billot de l'exécution, tandis qu'un vieux dignitaire guide doucement ses mains vers lui. Ses dames de compagnie s'effondrent de chagrin contre un pilier derrière elle, et le bourreau attend à droite, appuyé sur sa hache, les yeux détournés."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WANDERER"] =
    "Peinture à l'huile romantique allemande, l'image par excellence de l'homme seul face à la nature. Un jeune homme en manteau vert foncé se tient de dos sur un sommet rocheux, appuyé sur une canne de marche, les cheveux agités par le vent. Au-dessous de lui, un océan de brouillard blanc engloutit la vallée ; seules des crêtes et des roches escarpées émergent comme des îles, et de pâles montagnes s'estompent au loin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BABEL"] =
    "Peinture à l'huile flamande de la Renaissance représentant la tour condamnée de la Bible, fourmillante de détails. Une colossale tour en spirale faite d'arches, en partie de pierre blanche et en partie de brique rouge brute, s'élève de travers dans les nuages, son sommet encore brut et inachevé. Autour de sa base s'étend une ville portuaire avec des navires à l'ancre, et au premier plan un roi inspecte une équipe de tailleurs de pierre agenouillés à ses pieds parmi leurs blocs."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YOUNG_LADY"] =
    "Portrait à l'huile des premiers Pays-Bas, petit, immobile et étrangement moderne. Une jeune femme pâle au visage lisse comme la porcelaine vous regarde de côté sous une haute coiffe de velours noir bordée d'or. Elle porte une robe bleue à col de fourrure blanche et un collier serré fait de bandes d'or et de noir, sur un fond de simple mur sombre plutôt que l'habituel vide ténébreux."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_KINDRED"] =
    "Peinture à l'huile américaine de la Hudson River School, un hommage à l'amitié entre un peintre et un poète. Deux hommes en manteau se tiennent debout et conversent sur une corniche rocheuse qui surplombe une gorge boisée des montagnes Catskill, l'un désignant le panorama d'un pinceau. Un torrent dévale les rochers en contrebas, encadré par une arche d'arbres en surplomb, avec des sommets brumeux se dissolvant dans une lumière dorée à l'arrière-plan."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BLUE_BOY"] =
    "Portrait à l'huile anglais dans le grand style, l'oeuvre la plus célèbre de l'artiste. Un garçon d'environ douze ans se tient en pied dans un chatoyant costume de satin bleu à culotte et col de dentelle, une main sur la hanche, l'autre tenant à son côté un chapeau à plume. Il regarde au-dehors avec une aisance assurée, devant un paysage brun sombre et orageux qui fait flamboyer le costume bleu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SECOND_OF_MAY"] =
    "Peinture à l'huile espagnole, l'une des premières et des plus grandes protestations contre la guerre dans l'art. À la lumière d'une lanterne, un peloton d'exécution français se tient en une rangée sans visage, fusils braqués sur un groupe de captifs espagnols serrés les uns contre les autres sur une colline nue à l'extérieur de Madrid. Au centre, un homme en chemise blanche écarte grand les bras devant les fusils, agenouillé parmi les corps de ceux déjà fusillés, sa pose évoquant une crucifixion."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_CART"] =
    "Peinture à l'huile militaire française de la guerre franco-prussienne, une image célèbre d'une ultime résistance acharnée. Une poignée de soldats français défendent la maison en ruine d'un village, tirant depuis une fenêtre tandis que les blessés sont affaissés contre les murs et qu'un officier compte leurs dernières cartouches. La pièce est dévastée, une porte arrachée de ses gonds, du plâtre tombant du plafond, la lumière du jour inondant l'embrasure où des camarades continuent de se battre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EARLY_AUTUMN"] =
    "Rouleau à main chinois à l'encre et à la couleur douce, une étude de nature en gros plan d'un étang de lotus déclinant. Des libellules rouges, vertes et bleues volent au-dessus de roseaux desséchés et de feuilles de lotus en lambeaux, tandis que des sauterelles, une abeille et de petites grenouilles vaquent à leurs occupations en dessous. L'atmosphère est celle d'un doux déclin, la vie de l'été se poursuivant parmi des plantes qui commencent tout juste à se faner, avec des sceaux rouges de collectionneurs le long des deux bords."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_APPRECIATING_LOTUSES"] =
    "Rouleau suspendu japonais à l'encre et à la couleur, par le fondateur de l'école Kano, peint à la manière chinoise du paysage de lettré. Un lettré chinois en robe dérive dans une petite barque au bord d'un étang de lotus, contemplant les feuilles flottantes sous un saule noueux qui se penche depuis la rive rocheuse. La plus grande partie du haut rouleau n'est que brume et eau libre, avec quelques cimes de pins s'estompant dans la brume."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EQUESTRIAN_PORTRAIT"] =
    "Peinture à l'huile vénitienne de la Renaissance, le modèle de siècles de portraits de souverains à cheval. L'empereur du Saint-Empire romain germanique sort d'un bois sombre en pleine armure étincelante, le heaume orné d'un panache rouge, la lance à la main, commémorant sa victoire à Muhlberg. Son cheval noir est drapé de cramoisi, et un soleil bas du soir perce d'or et de rose sous de lourds nuages d'orage."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ARMADA"] =
    "Portrait de propagande Tudor à l'huile, peint pour célébrer la défaite de l'Armada espagnole. La reine Élisabeth est assise dans une immense robe de perles et de noeuds, son visage encadré d'une vaste fraise de dentelle blanche, une main posée d'un geste possessif sur un globe, ses doigts sur les Amériques. Par des fenêtres derrière elle, l'histoire se déroule deux fois : la flotte anglaise sur des mers calmes d'un côté, les navires espagnols brisés par une tempête de l'autre. Sa couronne sertie de joyaux est posée à côté d'elle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRANCIS_I"] =
    "Portrait royal français de la Renaissance, à l'huile. Le roi vous fait face à mi-corps dans une spectaculaire tenue de cour : des manches taillées de satin blanc et or rayé de noir, une chaîne d'or en travers de la poitrine et une toque noire ornée d'un plumet blanc sur la tête. Son visage barbu, rusé et au long nez se détache sur un fond de damas cramoisi orné d'un motif de couronnes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SELF_PORTRAIT"] =
    "Autoportrait à l'huile du maniérisme nordique, par le peintre de cour flamand de l'empereur Rodolphe II. L'artiste se retourne vers vous par-dessus son épaule, homme robuste et barbu aux cheveux bouclés sous une souple toque noire, vêtu d'un col blanc à fraise sur un pourpoint gris-bleu. Le traitement est chaleureux et direct sur un simple fond brun, et son regard scrutateur en coin retient le vôtre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VERTUMNUS"] =
    "Peinture maniériste à l'huile, la plus célèbre des têtes composites fantastiques d'Arcimboldo. C'est un portrait de l'empereur Rodolphe II en dieu romain des saisons, son visage et son buste entièrement assemblés à partir de fruits, de légumes et de fleurs : des paupières en cosses de pois, un nez en poire, des lèvres de cerises, des moustaches en épis de blé et des cheveux de raisins. De loin, c'est un souverain plein de dignité ; de près, il se dissout en un étal de marché, le tout sur un fond noir."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_SUPPER"] =
    "Peinture à l'huile vénitienne de la fin de la Renaissance, qui réinvente la scène familière. Au lieu de vous faire face de front, la table du repas plonge en forte diagonale vers une sombre salle de taverne, le Christ rayonnant à mi-longueur tandis qu'il offre le pain aux apôtres. Des serviteurs portent des plats et un chat fourre son nez dans un panier au premier plan, pendant qu'une lampe à huile flamboyante remplit d'anges translucides et tourbillonnants l'air enfumé au-dessus de la scène."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_A_MAN"] =
    "Peinture à l'huile des premiers Pays-Bas, peut-être le propre visage de l'artiste et l'un des premiers véritables autoportraits. Un homme d'âge mûr au visage marqué et au regard perçant vous fixe droit dans les yeux depuis une ombre profonde, coiffé d'une extravagante coiffe rouge enroulée et nouée en plis sculpturaux. Le détail est d'une finesse d'aiguille, chaque ride et chaque poil de barbe saisis, la figure vêtue d'un manteau sombre bordé de fourrure sur un fond noir."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRONT_OF_THE_MIRROR"] =
    "Peinture à l'huile de la Renaissance vénitienne, le serein chef-d'oeuvre tardif du vieux Bellini. Une jeune femme nue aux cheveux auburn est assise sur une étoffe rouge, arrangeant calmement sa chevelure tout en tenant un petit miroir à main, un second miroir rond accroché au mur derrière elle reflétant l'arrière de sa coiffe à motifs. Une fenêtre à côté d'elle ouvre sur une campagne verdoyante avec de lointaines montagnes bleues sous un ciel nuageux."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ADORATION"] =
    "Fresque italienne ancienne de la chapelle des Scrovegni, par le peintre à qui l'on attribue le retour du sentiment humain naturel dans l'art occidental. Sous un dais de bois, Marie tient l'enfant Jésus tandis que le plus âgé des trois rois s'agenouille pour baiser les pieds de l'enfant, sa couronne posée de côté ; des chameaux attendent à gauche. Au-dessus de l'étable, une comète raye le ciel d'un bleu profond à la place de l'étoile habituelle, le tout dans les figures solides et simples de Giotto et ses couleurs claires."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUBENS_AND_ISABELLA"] =
    "Peinture à l'huile baroque flamande, le portrait de mariage que l'artiste a fait de lui-même et de son épouse. Le jeune couple est assis tout près l'un de l'autre sous un buisson de chèvrefeuille, la main droite d'elle reposant tendrement sur celle de lui, le centre paisible du tableau. Il est assis au-dessus d'elle dans un pourpoint noir, une jambe croisée ; elle est agenouillée en jupe violette, corsage brodé d'or, large fraise et haut chapeau de paille, tous deux jetant un regard au-dehors avec un contentement calme."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CHILDS_BATH"] =
    "Peinture à l'huile impressionniste américaine d'une tendresse quotidienne, influencée par les estampes japonaises dans son point de vue élevé et ses motifs plats. Une mère vêtue d'une robe à rayures marquées tient sur ses genoux un enfant enveloppé d'une serviette, lui lavant les pieds dans une bassine d'eau. Les deux têtes se penchent ensemble sur la tâche, et la pièce autour d'elles est un patchwork de motifs : papier peint fleuri, coffre peint, tapis ouvragé et un pichet blanc."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_CARD_PLAYERS"] =
    "Peinture à l'huile post-impressionniste, l'une d'une célèbre série sur ce sujet. Deux hommes paysans coiffés de chapeaux sont assis face à face de part et d'autre d'une petite table en bois, absorbés par leurs cartes, une unique bouteille de vin dressée entre eux comme le centre immobile de la composition. L'un fume la pipe ; la peinture est construite en touches patientes et compactes de brun terreux, d'ocre et de violet sourd qui donnent aux figures une impression de pierre taillée et de permanence."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_SWING"] =
    "Peinture à l'huile rococo française, frivole, secrète, et l'image la plus célèbre de l'époque. Dans un jardin luxuriant et envahi de végétation, une jeune femme en robe rose vaporeuse s'élance haut sur une balançoire à corde, lançant un soulier en l'air, tandis qu'un vieil homme caché tire sur les cordes depuis l'ombre derrière elle. Son jeune amant est vautré dans les rosiers en contrebas, parfaitement placé pour regarder sous ses jupes, et une statue de cupidon en pierre porte un doigt à ses lèvres."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIANT_MAGNOLIAS"] =
    "Nature morte à l'huile américaine, opulente et presque tropicale dans son atmosphère. Deux énormes fleurs de magnolia d'un blanc crème reposent, coupées, sur une draperie de velours bleu profond, entourées de leurs feuilles sombres et luisantes, avec un troisième bouton encore fermé. Les pétales rayonnent sur le fond presque noir, peints avec une précision cireuse et sensuelle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_KILLING"] =
    "Panneau peint gothique catalan, à la détrempe et à l'or. Saint Georges, en armure noire avec une auréole dorée, se penche depuis son cheval blanc cabré pour enfoncer une longue lance dans la gueule béante d'un dragon aux ailes de chauve-souris, le sol autour d'eux jonché d'os et de crânes. La princesse en robe rose prie sur un éperon rocheux derrière, et des spectateurs se pressent en haut des murs blancs du château."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JACQUES_AND_BERTHE"] =
    "Double portrait moderniste à l'huile du sculpteur Lipchitz et de son épouse, peint dans le style reconnaissable entre tous de Modigliani. Le mari se tient debout dans un costume sombre, la main posée sur l'épaule de sa femme assise, dont le visage aux joues roses émerge d'un col de dentelle blanche. Tous deux ont les visages allongés caractéristiques de l'artiste, les longs nez et les yeux en amande vides, leurs noms étant griffonnés en haut de la toile."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DASH_FOR_TIMBER"] =
    "Peinture à l'huile du western américain, le genre de scène d'action au galop qui a fixé le Far West dans l'imaginaire collectif. Huit cow-boys foncent droit sur vous à bride abattue, les sabots des chevaux ne touchant plus le sol, deux cavaliers se retournant sur leur selle pour faire feu sur la bande d'Apaches montés qui les poursuit dans la poussière. Un homme blessé s'affaisse contre un compagnon tandis qu'ils filent vers les arbres au bord gauche de la plaine aride."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GEORGE_WASHINGTON_PORTRAIT"] =
    "Portrait d'apparat américain à l'huile, l'image officielle de la première présidence. Washington se tient debout en pied dans un sobre costume de velours noir, un bras tendu dans un geste d'allocution, l'autre tenant une épée de cérémonie, près d'une table garnie d'une plume et d'un encrier. Les ornements qui l'entourent évoquent la grandeur républicaine : une chaise dorée à l'écusson étoilé et rayé, des colonnes de marbre, et une draperie cramoisie en festons avec un arc-en-ciel perçant des nuages d'orage au loin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ATTACK_ON_BEIJING"] =
    "Estampe japonaise en couleurs dans le style de l'illustration de presse de guerre, légendée à la fois en japonais et en anglais. Les troupes alliées prennent d'assaut les murs du palais impérial de Pékin : des soldats britanniques en habit rouge portant un Union Jack chargent au premier plan tandis que l'infanterie japonaise en uniforme blanc avance sur la droite. Les éclats d'obus restent suspendus en bouffées blanches au-dessus de la place d'armes verdoyante, avec la porte au toit bleu du palais et ses murs fumants derrière."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUMO_WRESTLER"] =
    "Estampe japonaise ukiyo-e sur bois, portrait de célébrité d'un lutteur vedette hors du ring. L'homme massif se tient debout de toute sa hauteur dans un kimono noir par-dessus des robes à motifs, des sabres à la ceinture, s'épongeant le front d'un linge à carreaux tandis qu'il porte une cape roulée sur une épaule. Son nom court le long du côté droit en cartouches de calligraphie rouge vif, la figure plate et monumentale se détachant sur le papier nu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_TIGER_IN_TROPICAL_STORM"] =
    "Peinture à l'huile de style naïf par l'employé des douanes français autodidacte qui ne vit jamais de jungle. Un tigre aux yeux écarquillés se tapit au ras des hautes herbes fouettées par le vent, les crocs découverts, surpris par une tempête qui couche toutes les plantes de côté. La jungle est un dense motif de feuilles stylisées en verts et en rouges, avec des traînées argentées et obliques de pluie tracées sur toute la toile comme une gaze."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_HOME_GUARD"] =
    "Portrait à l'huile hongrois de style Biedermeier, issu de la révolution de 1848. Un citoyen-soldat barbu est assis dans une veste de lin écru, ses deux mains gantées reposant sur la poignée de son sabre dressé, le brassard national rouge, blanc et vert sur sa manche proclamant sa cause. Il regarde sur le côté avec une résolution sereine, éclairé d'une lumière chaude sur fond de rideau rouge sombre, son manteau doublé de rouge jeté sur la chaise."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CEREMONIAL_SITTING"] =
    "Peinture à l'huile réaliste russe de très grand format, portrait de groupe de tout le conseil dirigeant de l'empire. Des dizaines de vieux hommes d'État en uniformes sombres alourdis de galons d'or et d'écharpes rouges sont assis autour d'un grand fer à cheval de chaises rouges dans une salle à colonnes blanches ornée de lustres et de portraits royaux. Chacun des plus de soixante visages est un portrait individuel, peint avec le réalisme vif et assuré de Repine."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUSSIAN_TSAR"] =
    "Peinture historique russe à l'huile recréant une procession royale du seizième siècle. Un tsar coiffé d'une toque de fourrure, dans une robe de brocart d'or, chevauche un cheval blanc à travers la neige, précédé de gardes en éclatants manteaux rouges portant de hautes haches d'armes recourbées. La foule s'agenouille et se prosterne jusqu'à terre de part et d'autre de la route enneigée et piétinée, avec les bâtiments en rondins d'une vieille ville russe sous un pâle ciel d'hiver."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CRUCIFIXION_OF_SAINT_PETER"] =
    "Peinture à l'huile baroque italienne, brutale et physique dans le style caractéristique du Caravage. Trois ouvriers s'efforcent de hisser une croix de bois sur laquelle le vieux saint Pierre a été cloué la tête en bas, l'un tirant sur une corde, un autre accroupi sous la poutre, leurs visages cachés. Le saint à la barbe blanche lève la tête pour regarder sa propre main clouée, son vieux corps musculeux jaillissant de l'obscurité totale dans une unique lumière crue."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LANDSCAPE_WITH_ANT_BEAR"] =
    "Paysage colonial hollandais à l'huile, peint par le premier artiste de formation européenne à travailler au Brésil. Une large vallée ensoleillée parcourue d'une rivière s'ouvre sous un vaste ciel entre deux hauts palmiers, avec un établissement colonial de maisons blanches sur les collines lointaines. Un groupe de figures afro-brésiliennes chemine au premier plan en portant des ballots, et le fourmilier au long museau du titre fouine dans les broussailles en bas à droite."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DUTCH_MEN_O_WAR"] =
    "Marine à l'huile de l'âge d'or hollandais par le plus grand peintre de navires de l'époque. De hauts vaisseaux de guerre en bois mouillent à l'ancre sur une eau lisse comme du verre, leurs voiles pendant molles et leurs coques se reflétant dans la mer, chaque ligne de gréement exacte. Des chaloupes transportent des passagers entre les navires sous un vaste ciel de cumulus ensoleillés, toute la scène baignée d'un calme doré."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HARBOR_IN_BALAKLAVA"] =
    "Lithographie teintée de la guerre de Crimée, dessinée par l'un des premiers artistes de guerre à documenter une campagne sur le terrain. Sur le rivage désolé d'un port, des soldats malades et blessés enveloppés de couvertures blanches sont aidés à descendre de litières portées par des mulets pour gagner une chaloupe qui attend. Des collines brunes et nues s'élèvent derrière le groupe de figures, avec des baraquements et des tentes parsemant la pente, les couleurs sourdes et documentaires."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PEACEMAKERS"] =
    "Peinture historique américaine à l'huile représentant un véritable conseil de la guerre de Sécession dans ses derniers jours. Le président Lincoln est assis dans la cabine d'un vapeur, écoutant avec attention, le menton sur la main, tandis que le général Sherman gesticule au milieu d'un argument ; le général Grant et l'amiral Porter complètent le cercle de quatre figures vêtues de sombre. À travers les fenêtres de la cabine derrière eux, un arc-en-ciel perce un ciel qui s'éclaircit, signe discret de la paix à venir dans le tableau."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_CHITASEI"] =
    "Estampe japonaise ukiyo-e sur bois, tirée de la célèbre série de Kuniyoshi sur les 108 héros du roman chinois Au bord de l'eau. Le lettré-stratège Wu Yong se tient dans une ample robe sombre ornée de dragons, caressant sa barbe d'un air pensif sous un ciel nocturne constellé d'étoiles. À côté de lui repose un grand globe céleste sur un socle ouvragé, et des cartouches de texte japonais encadrent la figure."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_LOUIS"] =
    "Portrait à l'huile anglais du dix-huitième siècle saisissant un sculpteur au travail. Roubiliac, coiffé d'un bonnet souple et vêtu d'une chemise ouverte aux manches retroussées, s'interrompt l'ébauchoir levé, jetant un regard de côté tandis qu'il travaille à une statuette d'argile de Shakespeare posée sur un socle. De sa main libre, le sculpteur désigne sa propre création, chaudement éclairé sur le fond sombre de l'atelier."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_NASSER"] =
    "Portrait de cour persan qajar à l'huile, la splendeur royale étalée à profusion. Le jeune Shah moustachu est assis raide et droit dans un uniforme écarlate incrusté de broderies d'or, de chapelets de perles, d'épaulettes serties de joyaux et d'une écharpe bleue, une main posée sur un sabre incrusté de pierreries. Il porte un haut bonnet noir orné d'une aigrette de diamants, ses yeux soulignés de noir fixant le spectateur sur un fond vert olive profond frappé d'une inscription royale."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FIELD_WITH_SHEAFS"] =
    "Paysage à l'huile d'inspiration expressionniste allemande, peint à grands coups de pinceau énergiques. Un champ de blé moissonné emplit le premier plan de rangées de gerbes dorées dressées en bottes penchées, le jaune posé épais et éclatant. Une ligne d'arbres vert sombre ferme le champ, surmontée d'un ciel bleu violet pâle aux nuages poussés par le vent."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AT_THE_EDGE_OF_THE_BROOK"] =
    "Peinture à l'huile académique française, polie jusqu'à la perfection lisse qui a fait la renommée de Bouguereau. Deux enfants de paysans pieds nus sont assis sur une pierre au bord d'un ruisseau, la plus jeune fille retirant un bas tandis que sa compagne aux cheveux bruns relève sa jupe pour patauger. Elles échangent un regard au milieu de leur conversation, leur peau et leurs cheveux ébouriffés peints avec une douceur photographique sur un doux paysage champêtre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS_ALT"] =
    "Peinture à l'huile romantique italienne, le baiser le plus célèbre de l'art italien et un emblème patriotique secret de l'unification. Dans un couloir de pierre médiéval, un jeune homme coiffé d'un chapeau à plume et vêtu d'une cape brune renverse une femme en arrière dans un baiser passionné, un pied déjà sur la marche comme s'il s'arrêtait au milieu de sa fuite. Sa robe de satin bleu pâle déverse la lumière dans la scène, tandis qu'une silhouette dans l'ombre approche par l'arche au-delà."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MOVING_HOUSE"] =
    "Peinture à l'huile réaliste russe d'une pauvreté urbaine silencieuse. Un couple âgé traverse péniblement la glace du fleuve gelé de Saint-Pétersbourg en portant tout ce qu'il possède dans un ballot de toile, l'homme s'appuyant sur une canne, tous deux emmitouflés dans des manteaux et des fichus usés contre le froid. Un petit chien trotte devant eux, et la flèche dorée de la forteresse Pierre-et-Paul s'élève à travers la brume hivernale derrière."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MEXICAN_EXPEDITION"] =
    "Peinture d'histoire navale française à l'huile, dans le style du reportage et grouillante d'action. Un navire de guerre français battant le tricolore domine le premier plan à gauche, ses officiers sur le pont dirigeant le bombardement de la forteresse mexicaine de Saint-Jean-d'Ulloa, la fumée s'élevant au-dessus de l'eau. Des obus éclaboussent près des chaloupes qui transportent les hommes d'un navire à l'autre, avec un volcan enneigé sur l'horizon brumeux."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_DAY_OF_POMPEII"] =
    "Peinture à l'huile romantique russe sur une toile immense, l'épopée de catastrophe de son siècle. Le ciel au-dessus de Pompéi brûle de rouge et de noir tandis que le Vésuve entre en éruption, des statues basculent d'un toit et la foudre déchire le nuage de cendres. Des foules d'habitants en costume romain fuient à travers les débris qui tombent, abritant enfants et vieillards sous des manteaux, tandis qu'une femme tombée gît étendue près d'un char renversé au centre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ACCOLADE"] =
    "Peinture à l'huile anglaise de style préraphaélite, une vision de chevalerie sortie d'un livre de contes. Une reine aux cheveux d'or, vêtue d'une longue robe blanche fluide, touche de son épée l'épaule d'un chevalier agenouillé pour l'adouber devant un petit auditoire de cour. Il incline la tête dans sa cotte de mailles et son surcot rouge, son heaume posé sur le sol à côté de lui, la salle de pierre et l'estrade rouge peintes dans un détail romantique rayonnant."
