-- Mod-authored great work descriptions, de_DE overlay.
-- Baseline in CivVAccess_GreatWorkDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_MISSING"] = "Keine Bildbeschreibung für dieses große Werk."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIRL_WITH_PEARL_EARRING"] =
    "Ölgemälde des niederländischen Goldenen Zeitalters, eines der beliebtesten Porträts der westlichen Kunst. Eine junge Frau wendet sich über die Schulter zurück und sucht aus einem schlichten dunklen Hintergrund deinen Blick, die Lippen leicht geöffnet, als wolle sie gleich sprechen. Sie trägt einen blau-goldenen Turban, dessen Tuch ihr über den Rücken fällt, und eine einzelne große tropfenförmige Perle fängt das Licht an ihrem Ohr."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HENRY_VIII"] =
    "Höfisches Tudor-Porträt in Öl, das Bild, das festlegte, wie die Welt sich Heinrich VIII. vorstellt. Der König steht dir in voller Gestalt zugewandt, die Füße breit aufgestellt, breitschultrig und schwer, eine Hand auf einem Dolch an seiner Hüfte ruhend. Er trägt ein juwelenbesetztes silbernes Wams unter einem pelzgefütterten purpurroten Mantel, einen flachen Federhut und Goldketten und steht auf einem gemusterten Teppich zwischen Marmorsäulen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HUNTERS_IN_THE_SNOW"] =
    "Flämisches Renaissance-Ölgemälde, eine Winterlandschaft von einer Anhöhe aus betrachtet. Drei erschöpfte Jäger und ihre Hundemeute stapfen im Vordergrund durch tiefen Schnee, die Köpfe gesenkt, mit nur einem einzigen Fuchs als Ausbeute der Jagd. Unter ihnen breitet sich ein Dorf unter einem graugrünen Himmel aus, mit winzigen Schlittschuhläufern auf zugefrorenen Teichen und zackigen Gipfeln, die sich in der Ferne erheben."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LES_DEMOISELLES"] =
    "Frühes modernistisches Ölgemälde, die Leinwand, die den Kubismus auslöste. Fünf nackte Frauen stehen und sitzen in einem flachen Raum aus zackigen rosa, weißen und blauen Flächen, ihre Körper in scharfe kantige Formen zerlegt. Die beiden Gesichter rechts sind wie afrikanische Masken gemalt, gestreift und verzerrt, während die anderen mit weiten mandelförmigen Augen geradeaus starren; eine kleine Obstschale steht am unteren Rand."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LUNCHEON"] =
    "Französisches impressionistisches Ölgemälde von Freunden, die nach einem Mahl verweilen. Eine lebhafte Gruppe in sommerlicher Kleidung drängt sich auf einem Balkon am Fluss unter einer orange-weiß gestreiften Markise, redend, flirtend und an die Brüstung gelehnt; eine junge Frau im Vordergrund spielt mit einem kleinen Hund. Der Tisch ist übersät mit Weinflaschen, Gläsern und Obst, alles in warmen, lockeren Tupfern sonnendurchfluteter Farbe gemalt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MONA_LISA"] =
    "Italienisches Renaissance-Ölgemälde auf einer Holztafel, wohl das berühmteste Porträt der Welt. Eine Frau sitzt mit gefalteten Händen, leicht dir zugewandt, vor einer dunstigen Landschaft aus gewundenen Flüssen und fernen blauen Bergen. Ihre Augen begegnen den deinen unmittelbar, jener berühmte Blick, der dir zu folgen scheint, wo immer du stehst. Ihr feines Halblächeln ist das Zentrum des Bildes, gemalt in sanften Braun- und Grüntönen ohne harte Konturen, sodass ihr Ausdruck sich zu wandeln scheint, je länger du hinsiehst."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUNDAY_AFTERNOON"] =
    "Pointillistisches Ölgemälde, ganz aus winzigen Punkten reiner Farbe aufgebaut. Pariser in ihrer Sonntagskleidung entspannen sich auf einer sonnigen Uferwiese, schlendern mit Sonnenschirmen, lagern im Gras und führen kleine Hunde aus, hinter ihnen Segelboote auf dem Wasser. Alle sind seltsam still und förmlich, wie Figuren in einem Fries, das Licht in ein Schimmern aus grünen, orangefarbenen und violetten Tüpfeln zerlegt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VIEW_OF_TOLEDO"] =
    "Spanisches Renaissance-Ölgemälde, eine der frühesten reinen Landschaften der westlichen Kunst und eine ungewöhnlich düstere. Die spanische Hügelstadt Toledo erhebt sich in der Ferne unter einem tobenden Sturmhimmel, ihre grauen Türme und Mauern von einem unheimlichen silbernen Licht beleuchtet. Grüne Hügel ziehen sich im Vordergrund zu einem Fluss hinab, die ganze Szene in tiefen Grün- und Blauschwarztönen gemalt, die mehr nach Traum als nach Tageslicht wirken."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WATER_LILIES"] =
    "Französisches impressionistisches Ölgemälde aus Monets berühmter Serie seines Gartenteichs in Giverny. Die ganze Leinwand ist die Oberfläche des Wassers, ohne Horizont oder Ufer: Flöße aus grünen Seerosenblättern treiben über blaues und lavendelfarbenes Wasser, gesprenkelt mit rosa und roten Blüten. Wolken und Bäume erscheinen nur als sanfte Spiegelungen, der Pinselstrich locker genug, dass alles zu schweben scheint."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_STARRY_NIGHT"] =
    "Postimpressionistisches Ölgemälde, eines der bekanntesten Bilder der modernen Kunst. Ein von Bewegung erfüllter Nachthimmel füllt den größten Teil der Leinwand: Sterne lodern in wirbelnden Höfen, der Mond brennt orange in der Ecke, während eine große spiralige Strömung quer über die Mitte des Himmels rollt. Darunter schläft ein stilles Dorf mit einem spitzen Kirchturm zwischen Hügeln, und eine dunkle Zypresse lodert am linken Rand empor, alles in dicken, sichtbaren Strichen aus Blau und Gold."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BIRTH_OF_VENUS"] =
    "Italienisches Renaissance-Gemälde der Liebesgöttin, die aus dem Meer ankommt, eines der berühmtesten Bilder des klassischen Mythos. Venus steht nackt auf einer riesigen Jakobsmuschel und bedeckt sich mit ihren Händen und einer Strähne langen goldenen Haares. Links wehen sie zwei geflügelte Windgötter durch einen Regen aus rosa Rosen zum Ufer, während rechts eine Frau in einem geblümten Kleid herbeieilt, um sie in einen bauschenden Mantel zu hüllen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BINDO_ALTOVITI"] =
    "Italienisches Ölporträt der Hochrenaissance, das einen wohlhabenden jungen römischen Bankier zeigt. Ein hübscher junger Mann mit langem goldenem Haar und einer schwarzen Kappe blickt über seine bloße Schulter zu dir zurück, eine Hand an die Brust gezogen. Er trägt einen blauen Umhang über einem schwarzen Gewand, und sein blasses Gesicht leuchtet vor einem tiefgrünen Hintergrund."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_DRAGON"] =
    "Frühes italienisches Renaissance-Gemälde mit dem steifen, bilderbuchhaften Charme eines Märchens. Rechts stößt ein gepanzerter Ritter auf einem sich aufbäumenden weißen Pferd seine Lanze in die geöffneten Kiefer eines geflügelten grünen Drachen mit gefleckten mottenartigen Flügeln. Links hält eine ruhige Prinzessin in einem langen rosa Gewand das verwundete Untier an einer Leine wie ein Haustier, vor seiner dunklen Höhle, während sich hinter dem Ritter ein seltsamer spiraliger Sturm zusammenbraut."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CREATION_OF_ADAM"] =
    "Italienisches Renaissance-Fresko von der Decke der Sixtinischen Kapelle, Quelle einer der berühmtesten Gesten der Kunst. Ein nackter Adam lehnt links an einem grünen Hang, einen Arm schlaff ausgestreckt, während Gott, eine graubärtige Gestalt in einem bauschenden rosafarbenen Tuch voller Engel, von rechts heranbraust. Ihre ausgestreckten Zeigefinger reichen über eine kleine Lücke hinweg aufeinander zu, im Augenblick vor dem Funken des Lebens."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GALLERY_OF_THE_LOUVRE"] =
    "Amerikanisches Ölgemälde einer Galerie im Louvre, gemalt von demselben Morse, der später den Telegrafencode erfand. Ein prachtvoller rotwandiger Salon ist vom Boden bis zur Decke mit Dutzenden alter Meistergemälde in goldenen Rahmen bedeckt, darunter eine winzige Mona Lisa. Im Vordergrund sitzen Kunstschüler an Staffeleien und kopieren, während sich ihr Lehrer über die Schulter einer jungen Frau beugt, um ihre Arbeit zu korrigieren, und in der Ferne öffnet sich ein gewölbter Korridor mit weiteren Galerien."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WASHINGTON_CROSSING"] =
    "Heroisches amerikanisches Historiengemälde in Öl, eine Ikone des Unabhängigkeitskriegs. General Washington steht aufrecht am Bug eines überfüllten Ruderboots, während seine Soldaten durch einen mit Eisschollen verstopften Fluss staken und rudern; hinter ihm hält ein Offizier die amerikanische Flagge empor. Das Licht der Morgendämmerung bricht durch den kalten Dunst, und weitere Boote voller Männer und Pferde folgen dahinter."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ARRANGEMENT_IN_GREY"] =
    "Amerikanisches Ölgemälde, allgemein bekannt als Whistlers Mutter. Eine ältere Frau in einem langen schwarzen Kleid und weißer Spitzenhaube sitzt in strengem Profil, nach links gewandt, die Hände im Schoß gefaltet und die Füße auf einem kleinen Fußschemel. Der Raum ist karg und flach: eine graue Wand, ein dunkler gemusterter Vorhang und ein einziges gerahmtes Bild, die ganze Komposition ausgewogen wie eine Studie in Grau und Schwarz, genau wie der Titel sagt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BREEZING_UP"] =
    "Amerikanisches realistisches Ölgemälde vom Segeln in kleinen Booten vor der Küste Neuenglands. Ein Mann und drei Jungen lehnen sich in einem kleinen Catboot namens Gloucester zurück, während es in einer steifen Brise krängt, Gischt am Bug aufspritzt und der Tagesfang zu ihren Füßen aufgehäuft liegt. Die See ist ein bewegtes Grün unter aufgerissenen Wolken, mit einem zweimastigen Schoner am Horizont."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_THOUSAND_LI"] =
    "Chinesische blaugrüne Landschaft als Querrolle, von einem jugendlichen Wunderkind des Song-Hofes auf Seide gemalt und beinahe zwölf Meter lang. In leuchtendem Mineralblau und -grün steigen Berge in Kamm um Kamm aus einem ruhigen goldenen Fluss empor, mit winzigen Dörfern, Brücken und kahlen Bäumen zwischen die Hänge gebettet. Spalten gepinselter Kalligrafie und rote Sammlersiegel füllen den Himmel über den Gipfeln."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DWELLING_IN_THE_FUCHUN"] =
    "Chinesische Tuschequerrolle, ein Meisterwerk der Gelehrtenmalerei der Yuan-Dynastie, ganz in Schattierungen schwarzer Tusche auf Papier ausgeführt. Runde Berge, aus geschichteten trockenen Pinselstrichen aufgebaut, erheben sich über einem weiten ruhigen Fluss, mit Kiefern, verstreuten Hütten und Fischerbooten entlang der Ufer. Die Stimmung ist gemächlich und besinnlich, das Papier mit roten Sammlersiegeln gesprenkelt, die sich über Jahrhunderte von Bewunderern angesammelt haben."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ALONG_THE_RIVER"] =
    "Chinesische Querrolle auf Seide aus der Song-Dynastie, ein berühmtes Panorama des täglichen Stadtlebens von über fünf Metern Länge. Der gezeigte Abschnitt hat das große Stadttor der Hauptstadt im Mittelpunkt, einen massiven hölzernen Turm auf einem ansteigenden Wall, mit Straßen darunter, die von Leben wimmeln: Marktstände, Ochsenkarren, eine Kamelkarawane, die durch das Tor zieht, und Träger, die Lasten an Schulterstangen schleppen. Jede Gestalt ist winzig, aber präzise in feiner Tuschelinie und gedämpften Erdtönen gezeichnet."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LEAF_2"] =
    "Chinesisches Albumblatt aus der Qing-Dynastie, Hofmalerei in feiner Linie und zarter Farbe. Elegante Damen in langen fließenden Gewändern in Weiß, Grün und Blau versammeln sich in einem Gartenpavillon, der mit leuchtend blauem Tuch behangen ist; eine verbrennt Weihrauch an einem Tisch hinter einem roten Geländer. Um sie herum stehen Gartensteine, Bambus und eine blühende Ranke, die über das Pavillondach klettert."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EMPEROR_TAIZONG"] =
    "Chinesische Querrolle auf Seide aus der Tang-Dynastie, eine Hofaufzeichnung eines diplomatischen Treffens. Rechts sitzt Kaiser Taizong auf einer Plattform, die von Palastdamen getragen wird, welche auch zwei große Fächer und einen roten Baldachin über ihm halten. Links nähern sich drei kleinere Gestalten in ehrerbietigen Haltungen: ein Hofzeremoniar in Rot, der tibetische Gesandte in einem gemusterten Gewand und ein Dolmetscher in Weiß, alle vor warmer goldener Seide, die mit roten Siegeln bedeckt ist."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SPRING_MORNING"] =
    "Chinesische Querrolle auf Seide aus der Ming-Dynastie, ein langes Panorama von Palastfrauen bei Muße an einem Frühlingsmorgen. Dutzende eleganter Damen füllen offene Hallen, Veranden und Höfe: sie musizieren, malen ein Porträt, spielen mit Kindern und lustwandeln zwischen Weiden, Gartensteinen und sogar Pfauen. Die Palastarchitektur zieht sich über die ganze Länge der Rolle in warmen Rot- und Grüntönen, jeder Wandschirm, jedes Geländer und jedes Gewand mit akribisch feingezeichnetem Detail wiedergegeben."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_GREAT_WAVE"] =
    "Japanischer Ukiyo-e-Holzschnitt, das wohl berühmteste Bild der japanischen Kunst. Eine gewaltige tiefblaue Welle bäumt sich links auf und krümmt sich über die ganze Szene, ihr Kamm bricht in klauenartige Finger aus weißer Gischt. Darunter reiten drei lange offene Boote voller Ruderer durch die Wellentäler, und weit in der Ferne, klein im Zentrum von allem, ragt der schneebedeckte Kegel des Fuji auf."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EVENING_SHOWER"] =
    "Japanischer Ukiyo-e-Holzschnitt, eine der meistbewunderten Regenszenen, die je geschaffen wurden. Ein plötzlicher Wolkenbruch, als Schleier feiner schräger Linien gezeichnet, überrascht Menschen auf halbem Weg über eine lange hölzerne Brücke; sie eilen in beide Richtungen unter Hüten und Schirmen, einer sucht Schutz unter einer Strohmatte. Der Fluss darunter ist ein Band aus Blaugrün mit einem einzelnen Floßfahrer, der hindurchstakt, und das gegenüberliegende Ufer verblasst zu einem dunklen Fleck unter dem Sturm."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_L_ABSINTHE"] =
    "Französisches impressionistisches Ölgemälde, eine schonungslose Szene des Pariser Cafélebens. Eine Frau in einem blassen Kleid und Hut sitzt zusammengesunken an einem marmornen Cafétisch, den Blick gesenkt, vor ihr ein Glas milchig grünen Absinths; neben ihr starrt ein bärtiger Mann in einem zerknitterten Mantel mit einer Pfeife im Mund nach rechts ins Leere. Die beiden sitzen beisammen und doch völlig getrennt, gemalt in tristen Grau- und Brauntönen, die die Atmosphäre der Einsamkeit des Bildes tragen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_UPAUPA_SCHNEKLUD"] =
    "Postimpressionistisches Ölporträt eines Cellisten mitten im Spiel. Der Musiker beugt sich über sein leuchtend orangerotes Cello, die Augen in Konzentration gesenkt, der Bogenarm streicht über die Saiten, sein dunkelblauer Anzug rahmt das Glühen des Instruments. Hinter ihm teilt sich der Hintergrund in flache Zonen aus Braun und moosigem Grün, mit blassen abstrakten Formen übersät, in Gauguins kühnem, vereinfachtem Farbstil."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_BAR_AT_THE_FOLIES"] =
    "Französisches Ölgemälde des modernen Lebens, Manets letztes großes Werk. Eine Bardame in einem schwarzen Samtmieder mit einer Blume an der Brust steht hinter einem Marmortresen, der mit Champagnerflaschen, einer Schale mit Orangen und einem Glas mit einer Rose vollgestellt ist, und blickt mit einem müden, entrückten Ausdruck nach vorne. Hinter ihr spiegelt ein riesiger Spiegel den glitzernden Musiksaal wider, seine Kronleuchter und die Menge, und, seltsam nach rechts verschoben, ihren eigenen Rücken, während sie sich zu einem Mann mit Zylinder hinüberlehnt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BALL_AT_THE_MOULIN"] =
    "Postimpressionistisches Ölgemälde des Pariser Nachtlebens im berühmten Cabaret. Eine Gruppe von Männern mit Zylindern und Frauen mit Federhüten sitzt um einen Tisch mit Getränken, während eine rothaarige Frau im grün beleuchteten Tanzsaal dahinter ihr Haar richtet. Ein Frauengesicht ragt am rechten Rand auf, gespenstisch grün von unten beleuchtet, und eine lange diagonale Brüstung schneidet in Lautrecs plakathaftem Stil quer durch den Vordergrund."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS"] =
    "Wiener Jugendstil-Ölgemälde, mit echtem Blattgold überzogen, Klimts berühmtestes Werk. Ein Paar kniet eng umschlungen auf einer Blumenwiese, der Mann beugt sich, um die Wange der Frau zu küssen, während sie mit geschlossenen Augen ihr Gesicht emporneigt. Ihre Körper verschmelzen zu einem einzigen goldenen Umhang, gemustert mit Rechtecken für ihn und leuchtenden Kreisen für sie, der vor einem flachen schimmernden Goldhintergrund leuchtet. Der Kuss."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AMERICAN_GOTHIC"] =
    "Amerikanisches Ölgemälde des Regionalismus, endlos parodiert und sofort erkennbar. Ein strenger, kahl werdender Farmer mit runder Brille und Jeans-Latzhose steht da und hält eine dreizinkige Mistgabel aufrecht, eine Frau in einem dunklen gemusterten Schürzenkleid an seiner Seite, die mit zusammengepressten Lippen missbilligend zur Seite blickt. Hinter ihnen steht das weiße Bauernhaus, nach dem das Gemälde American Gothic benannt ist, mit einem spitzbogigen gotischen Fenster im Giebel."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SRI_SHANMUKAHA"] =
    "Indisches Andachtsgemälde im europäischen akademischen Stil, den Ravi Varma in ganz Indien berühmt machte. Der hinduistische Gott Murugan reitet auf seinem Pfauenreittier, mit sechs gekrönten Köpfen und vielen Armen, die Waffen halten, flankiert von seinen beiden Gemahlinnen in leuchtend rosa Saris. Der Schwanz des Pfaus breitet sich hinter ihnen aus wie ein riesiger Fächer aus grünen und goldenen Augen, während der Vogel eine Kobra unter seinen Füßen festhält. Sri Shanmukha Subramania Swami."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DAUD_RECEIVES_A_ROBE"] =
    "Mogulische Miniaturmalerei aus einer illustrierten kaiserlichen Chronik, in deckenden Wasserfarben und Gold auf Papier. Der gezeigte Ausschnitt stellt einen schlanken jungen Diener in den Mittelpunkt, in einem hellen Gewand, einer roten Kappe und einer goldenen Schärpe, der das zusammengefaltete goldene Ehrengewand für die Überreichungszeremonie trägt. Er steht vor einer leuchtend blauen Zeltwand, die mit zarten blühenden Ranken bedeckt ist, jede Falte und Blüte mit miniaturhafter Präzision gemalt. Daud erhält ein Ehrengewand von Munim Khan."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YUSEF_AND_ZULEYKHA"] =
    "Persische Miniatur aus einer illustrierten Handschrift, das gefeiertste Werk des großen Herater Meisters Behzad. Die Seite wird von einem verschachtelten Palast ausgefüllt, der in flachem Querschnitt zu sehen ist, ein Labyrinth aus Treppen, Balkonen und Türen, in Blau, Orange und Gold gekachelt. In einer oberen Kammer flieht der Prophet Yusuf, mit einem Heiligenschein aus Flammen umgeben, vor dem ausgestreckten Griff Zulaikhas, während Felder persischer Kalligraphie die Architektur einrahmen. Yusuf und Zulaikha."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ASCENT_OF_MUHAMMAD"] =
    "Persische Miniatur aus einer königlichen Handschrift, die die nächtliche Reise des Propheten durch die Himmel darstellt. Mohammed, sein Gesicht in Weiß verschleiert und von goldener Flamme umkränzt, reitet das menschenköpfige Reittier Buraq durch einen tiefblauen Himmel, der mit sich kringelnden goldgesäumten Wolken übersät ist. Engel in Gewändern aus Rot, Grün und Orange wirbeln auf jeder Seite um ihn, mit Gaben und Weihrauchfässern, während Zeilen persischer Verse die Szene einrahmen. Himmelfahrt Mohammeds."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LIBERTY_LEADING_THE_PEOPLE"] =
    "Französisches Ölgemälde der Romantik, das prägende Bild der Revolution. Die Freiheit selbst, eine barbusige Frau in einem gelben Kleid und einer roten Mütze, schreitet über eine Barrikade aus Trümmern und gefallenen Körpern und reckt die französische Trikolore in den verqualmten Himmel. Um sie her drängen bewaffnete Bürger jeder Schicht, darunter ein Gentleman mit Zylinder und Muskete und ein Junge, der zwei Pistolen schwenkt. Die Freiheit führt das Volk."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_JEROME_IN_HIS_STUDY"] =
    "Frührenaissance-Ölgemälde von bemerkenswerter miniaturhafter Präzision. Durch einen großen steinernen Torbogen gesehen, sitzt der heilige Hieronymus in roten Gewändern lesend an einem hölzernen Studierplatz, der wie eine Bühne in einem gewölbten Kathedralraum gebaut ist, umgeben von Regalen mit Büchern und Töpfen. Licht strömt von Fenstern auf allen Seiten herein, ein Pfau und ein Rebhuhn sitzen vorne auf der Schwelle, und sein Löwe streift im Schatten zur Rechten umher. Der heilige Hieronymus im Gehäuse."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PARTHENON_FRIEZE"] =
    "Viktorianisches Ölgemälde, das sich das antike Athen vorstellt; im Spiel gehört dieses Werk zum Weltwunder Parthenon. Der Bildhauer Phidias steht auf einem hölzernen Gerüst neben seinem frisch bemalten Marmorfries mit Reitern, noch in seinen Werkstattfarben, und hält ein Seil zurück, während er den Fries vorstellt. Eine kleine Gruppe von Athenern in drapierten Gewändern, unter ihnen Perikles, beugt sich vor, um das Schnitzwerk im warmen Licht im Inneren des Tempels zu bewundern. Phidias zeigt seinen Freunden den Fries im Parthenon (Lawrence Alma-Tadema)."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUE_DE_PARIS"] =
    "Französisches realistisches Ölgemälde des modernen Paris an einem nieseligen Tag, scharf und fotografisch dort, wo seine impressionistischen Freunde locker waren. Ein gut gekleidetes Paar, das sich einen Schirm teilt, schlendert auf dich zu über glänzendes Kopfsteinpflaster, der Mann mit Zylinder und die Frau in einem langen dunklen Kleid mit einem Ohrring, der das Licht einfängt. Um sie herum überqueren andere Spaziergänger mit Schirmen eine breite Kreuzung, gesäumt von keilförmigen grauen Wohnhäusern, mit einem grünen Laternenpfahl, der die Szene in der Mitte teilt. Straße in Paris an einem regnerischen Tag."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_NIGHT_WATCH"] =
    "Niederländisches Ölgemälde des Goldenen Zeitalters von gewaltigem Ausmaß, das berühmteste Gruppenporträt, das je geschaffen wurde. Eine städtische Bürgerwehr-Kompanie setzt sich aus tiefem Schatten in Bewegung: der Hauptmann in Schwarz mit einer roten Schärpe schreitet voran und gibt seinem Leutnant in blassem Gold einen Befehl, während dahinter Musketen geladen werden, ein Banner gehisst wird und ein Trommler den Takt schlägt. Ein kleines Mädchen in einem leuchtend goldenen Kleid strahlt geheimnisvoll in der Menge, wie ein Scheinwerfer im Dunkel beleuchtet. Die Nachtwache."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DEATH_OF_MARAT"] =
    "Französisches Ölgemälde des Klassizismus, das große Märtyrerbild der Französischen Revolution. Der revolutionäre Journalist Marat liegt tot in seiner Badewanne, zusammengesunken wie ein gefallener Heiliger, den Kopf in einen weißen Turban gewickelt und einen Arm zum Boden hängend, der noch immer seine Feder hält. In seiner anderen Hand ist der Brief, mit dem sein Mörder sich Einlass verschaffte; die obere Hälfte der Leinwand ist kahle dunkle Wand, und die schlichte hölzerne Kiste neben ihm trägt die gemalte Widmung A Marat, David. Der Tod des Marat."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ETIENNE_CHEVALIER"] =
    "Französische spätmittelalterliche Tafelmalerei, ein Flügel eines berühmten Andachtsdiptychons. Der königliche Schatzmeister Étienne Chevalier kniet in einem prächtigen roten Gewand, die Hände zum Gebet aneinandergelegt, vorgestellt von seinem Schutzpatron, dem heiligen Stephanus, der in einem blau-goldenen Messgewand neben ihm steht. Der Heilige trägt ein Buch, auf dem ein zackiger Stein liegt, das Sinnbild seines Martyriums, und beide stehen in einer Halle aus weißem Marmor, in deren Wand der Name des Stifters eingemeißelt ist."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_FRANCIS"] =
    "Spanisches barockes Ölgemälde strenger mönchischer Frömmigkeit. Der heilige Franz von Assisi steht allein in einer schlichten Kapuzenkutte von der Farbe des Sandes, sein Gesicht halb im tiefen Schatten der Kapuze verloren, die Augen im Gebet niedergeschlagen. In seinen Händen hält er einen menschlichen Schädel als Mahnung an den Tod, von einem einzigen harten Licht vor einem fast schwarzen Hintergrund beleuchtet."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HATAORI"] =
    "Japanischer Ukiyo-e-Holzschnitt einer Weberin bei der Arbeit. Eine junge Frau in einem gemusterten indigoblauen Kimono sitzt barfuß an einem großen hölzernen Handwebstuhl und blickt mit einem Webschiffchen in einer Hand von ihrer Arbeit auf, während sich rote, blaue und weiße Fäden über die gesamte Länge des Stuhls spannen. Die Farben sind weiche Cremetöne und gedämpftes Blau, und eine Spalte hingepinselter Dichtung füllt die obere linke Ecke des Blattes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JANE_GREY"] =
    "Französisches akademisches Historiengemälde, theatralisch und herzzerreißend. Die jugendliche Königin, mit verbundenen Augen und in weißem Satin gekleidet, der vor der dunklen Steinkammer leuchtet, kniet und tastet blind nach dem Richtblock, während ein betagter Beamter ihre Hände sanft dorthin führt. Ihre Hofdamen brechen vor Kummer an einem Pfeiler hinter ihr zusammen, und der Henker wartet rechts, auf sein Beil gestützt und mit abgewandtem Blick."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WANDERER"] =
    "Deutsches romantisches Ölgemälde, das Sinnbild des einsamen Menschen vor der Natur. Ein junger Mann in einem dunkelgrünen Rock steht mit dem Rücken zum Betrachter auf einem felsigen Gipfel, auf einen Wanderstock gestützt, das Haar vom Wind bewegt. Unter ihm verschlingt ein Meer aus weißem Nebel das Tal, aus dem nur Grate und Felszacken wie Inseln hervorbrechen, während blasse Berge in der Ferne verschwimmen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BABEL"] =
    "Flämisches Ölgemälde der Renaissance vom biblischen Turm, der dem Untergang geweiht ist, von Einzelheiten wimmelnd. Ein gewaltiger spiralförmiger Turm aus Bögen, teils weißer Stein und teils roher roter Ziegel, steigt schief in die Wolken empor, seine Spitze noch roh und unfertig. Um seinen Fuß breitet sich eine Hafenstadt mit vor Anker liegenden Schiffen aus, und im Vordergrund inspiziert ein König eine Schar von Steinmetzen, die zwischen ihren Steinblöcken zu seinen Füßen knien."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YOUNG_LADY"] =
    "Frühniederländisches Ölporträt, klein, still und seltsam modern. Eine blasse junge Frau mit porzellanglattem Gesicht blickt von unter einer hohen, mit Gold besetzten schwarzen Samthaube von der Seite zum Betrachter heraus. Sie trägt ein blaues Kleid mit weißem Pelzkragen und eine enge Halskette aus goldenen und schwarzen Bändern, vor einer schlichten, gedämpft beleuchteten Wand statt der üblichen dunklen Leere."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_KINDRED"] =
    "Amerikanisches Ölgemälde der Hudson River School, eine Hommage an die Freundschaft zwischen einem Maler und einem Dichter. Zwei Männer in Mänteln stehen im Gespräch auf einem Felsvorsprung, der über eine bewaldete Schlucht in den Catskill Mountains hinausragt, während einer mit einem Pinsel auf die Aussicht deutet. Ein Bach stürzt unten über Felsen, gerahmt von einem Bogen überhängender Bäume, und dunstige Gipfel lösen sich dahinter in goldenem Licht auf."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BLUE_BOY"] =
    "Englisches Ölporträt im Grand-Manner-Stil, das berühmteste Werk des Künstlers. Ein etwa zwölfjähriger Junge steht in voller Gestalt in einem schimmernden Anzug aus blauem Satin mit Kniehosen und einem Spitzenkragen, eine Hand in die Hüfte gestützt, in der anderen einen mit Federn geschmückten Hut an seiner Seite. Er blickt mit gelassener Selbstsicherheit aus einer dunklen, stürmischen braunen Landschaft heraus, die das blaue Gewand aufflammen lässt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SECOND_OF_MAY"] =
    "Spanisches Ölgemälde, einer der ersten und größten Proteste gegen den Krieg in der Kunst. Im Laternenlicht steht ein französisches Erschießungskommando in gesichtsloser Reihe, die Gewehre auf eine zusammengedrängte Gruppe spanischer Gefangener auf einem kahlen Hügel außerhalb Madrids gerichtet. In der Mitte breitet ein Mann in weißem Hemd die Arme vor den Gewehren weit aus, kniend zwischen den Körpern der bereits Erschossenen, seine Haltung an eine Kreuzigung erinnernd."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_CART"] =
    "Französisches militärisches Ölgemälde aus dem Deutsch-Französischen Krieg, ein berühmtes Bild trotzigen letzten Widerstands. Eine Handvoll französischer Soldaten verteidigt ein zerschossenes Dorfhaus, feuernd aus einem Fenster, während die Verwundeten an den Wänden zusammengesunken sitzen und ein Offizier ihre letzten Patronen zählt. Der Raum ist verwüstet, eine Tür aus den Angeln gerissen, Putz fällt von der Decke, und Tageslicht strömt durch die Tür, hinter der die Kameraden weiterkämpfen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EARLY_AUTUMN"] =
    "Chinesische Querrolle in Tusche und zarter Farbe, eine Nahaufnahme der Natur an einem welkenden Lotusteich. Libellen in Rot, Grün und Blau schweben über trocknendem Schilf und zerfetzten Lotusblättern, während Heuschrecken, eine Biene und kleine Frösche darunter ihren Geschäften nachgehen. Die Stimmung ist sanftes Verwelken, das Leben des Sommers, das zwischen eben erst welkenden Pflanzen weitergeht, mit roten Sammlersiegeln entlang beider Ränder."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_APPRECIATING_LOTUSES"] =
    "Japanische Hängerolle in Tusche und Farbe vom Begründer der Kano-Schule, gemalt in der Manier der chinesischen Gelehrtenlandschaft. Ein chinesischer Gelehrter im Gewand treibt in einem kleinen Boot am Rand eines Lotusteichs und betrachtet die schwimmenden Blätter unter einer knorrigen Weide, die sich vom felsigen Ufer hinauslehnt. Der größte Teil der hohen Rolle ist Nebel und offenes Wasser, mit ein paar Kiefernwipfeln, die sich im Dunst verlieren."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EQUESTRIAN_PORTRAIT"] =
    "Venezianisches Ölgemälde der Renaissance, das Vorbild für jahrhundertelange Darstellungen von Herrschern zu Pferde. Der Heilige Römische Kaiser reitet in voller glänzender Rüstung mit einem rot befederten Helm aus einem dunklen Wald hervor, die Lanze in der Hand, zum Gedenken an seinen Sieg bei Mühlberg. Sein schwarzes Pferd ist in Karmesinrot gehüllt, und eine tiefstehende Abendsonne bricht golden und rosa unter schweren Gewitterwolken hervor."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ARMADA"] =
    "Tudorzeitliches Propagandaporträt in Öl, gemalt zur Feier der Niederlage der spanischen Armada. Königin Elisabeth I. sitzt in einem gewaltigen Gewand aus Perlen und Schleifen, ihr Gesicht von einer riesigen weißen Spitzenkrause umrahmt, eine Hand besitzergreifend auf einem Globus ruhend, die Finger über Amerika. Durch Fenster hinter ihr entfaltet sich die Geschichte zweimal: die englische Flotte auf ruhiger See zur einen Seite, spanische Schiffe im Sturm gestrandet zur anderen. Ihre juwelenbesetzte Krone steht neben ihr."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRANCIS_I"] =
    "Französisches Renaissance-Königsporträt in Öl. Der König blickt dich von der Hüfte aufwärts in prachtvoller Hoftracht an, geschlitzte Ärmel aus weißem und goldenem Satin, schwarz gestreift, eine Goldkette über der Brust und eine schwarze Kappe mit weißer Feder auf dem Kopf. Sein verschlagenes, bärtiges Gesicht mit langer Nase hebt sich von einem purpurroten Damasthintergrund ab, der mit Kronen gemustert ist."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SELF_PORTRAIT"] =
    "Selbstporträt in Öl im nordischen Manierismus vom flämischen Hofmaler Kaiser Rudolfs II. Der Künstler blickt über die Schulter zu dir zurück, ein kräftiger bärtiger Mann mit lockigem Haar unter einer weichen schwarzen Kappe, einen weißen Rüschenkragen über einem graublauen Wams. Die Malweise ist warm und direkt vor einem schlichten braunen Hintergrund, und sein prüfender seitlicher Blick hält dein Auge fest."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VERTUMNUS"] =
    "Ölgemälde des Manierismus, der berühmteste von Arcimboldos fantastischen zusammengesetzten Köpfen. Es ist ein Porträt Kaiser Rudolfs II. als römischen Gott der Jahreszeiten, sein ganzes Gesicht und seine Brust aus Früchten, Gemüse und Blumen zusammengesetzt: Erbsenschoten-Lider, eine Birnennase, Kirschlippen, Ähren-Barthaare und Trauben als Haar. Aus der Ferne ein würdevoller Herrscher; aus der Nähe löst er sich in einen Marktstand auf, alles vor einem schwarzen Hintergrund."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_SUPPER"] =
    "Venezianisches Ölgemälde der Spätrenaissance, das die vertraute Szene neu erfindet. Statt dir frontal gegenüberzustehen, stürzt der Abendmahlstisch in steiler Diagonale in einen dunklen Schenkensaal hinein; Christus leuchtet auf halber Länge, als er den Aposteln Brot reicht. Diener schleppen Speisen, und eine Katze stupst im Vordergrund die Nase in einen Korb, während eine lodernde Öllampe die rauchige Luft darüber mit durchscheinenden, wirbelnden Engeln füllt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_A_MAN"] =
    "Frühniederländisches Ölgemälde, möglicherweise das eigene Gesicht des Künstlers und eines der ersten echten Selbstporträts. Ein Mann mittleren Alters mit faltigem, scharfäugigem Gesicht blickt aus tiefem Schatten geradeaus zu dir, einen aufwendigen roten Kopfschmuck tragend, in skulpturale Falten gewunden und geknotet. Die Detailtreue ist nadelfein, jede Falte und jedes Stoppelhaar eingefangen, die Gestalt in einem dunklen, pelzbesetzten Mantel vor einem schwarzen Hintergrund."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRONT_OF_THE_MIRROR"] =
    "Venezianisches Renaissance-Ölgemälde, das heitere späte Meisterwerk des betagten Bellini. Eine nackte junge Frau mit kastanienbraunem Haar sitzt auf einem roten Tuch und ordnet ruhig ihr Haar, während sie einen kleinen Handspiegel hält; ein zweiter runder Spiegel an der Wand dahinter zeigt die Rückseite ihres gemusterten Kopfschmucks. Ein Fenster neben ihr öffnet sich auf eine grüne Landschaft mit fernen blauen Bergen unter einem bewölkten Himmel."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ADORATION"] =
    "Frühes italienisches Fresko aus der Scrovegni-Kapelle, vom Maler, dem es zugeschrieben wird, das natürliche menschliche Gefühl in die westliche Kunst zurückgebracht zu haben. Unter einem hölzernen Baldachin hält Maria das Christuskind, während der älteste der drei Könige niederkniet, um die Füße des Kindes zu küssen, seine Krone beiseitegelegt; Kamele warten zur Linken. Über dem Stall zieht ein Komet anstelle des üblichen Sterns über den tiefblauen Himmel, alles in Giottos festen, schlichten Gestalten und klaren Farben."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUBENS_AND_ISABELLA"] =
    "Flämisches Barockgemälde in Öl, das Hochzeitsporträt des Künstlers von sich selbst und seiner Braut. Das junge Paar sitzt dicht beieinander unter einem Geißblattstrauch, ihre rechte Hand zärtlich auf der seinen ruhend, der stille Mittelpunkt des Bildes. Er sitzt erhöht über ihr in einem schwarzen Wams mit übergeschlagenem Bein, sie kniet in einem violetten Rock, goldbesticktem Mieder, breiter Krause und hohem Strohhut, beide mit ruhiger Zufriedenheit nach außen blickend."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CHILDS_BATH"] =
    "Amerikanisches impressionistisches Ölgemälde von alltäglicher Zärtlichkeit, in seiner hohen Blickachse und den flächigen Mustern von japanischen Drucken beeinflusst. Eine Mutter in einem kräftig gestreiften Kleid hält ein in ein Handtuch gewickeltes Kind auf ihrem Schoß und wäscht die Füße des Kleinen in einem Becken mit Wasser. Beide Köpfe neigen sich gemeinsam über die Arbeit, und der Raum um sie herum ist ein Flickwerk aus Mustern: geblümte Tapete, bemalte Truhe, verzierter Teppich und ein weißer Krug."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_CARD_PLAYERS"] =
    "Postimpressionistisches Ölgemälde, eines aus einer berühmten Reihe zu diesem Thema. Zwei Bauern mit Hüten sitzen einander an einem kleinen Holztisch gegenüber, in ihre Karten vertieft, eine einzelne Weinflasche als ruhender Mittelpunkt der Komposition zwischen ihnen. Der eine raucht eine Pfeife; die Farbe ist in geduldigen, blockigen Strichen aus erdigem Braun, Ocker und gedämpftem Violett aufgebaut, die die Gestalten wie gemeißelt und beständig wirken lassen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_SWING"] =
    "Französisches Rokoko-Ölgemälde, frivol, verstohlen und das berühmteste Bild seiner Epoche. In einem üppig verwachsenen Garten schwingt eine junge Frau in einem schäumenden rosa Kleid hoch auf einer Seilschaukel und schleudert einen Pantoffel in die Luft, während ein verborgener alter Mann aus dem Schatten hinter ihr an den Seilen zieht. Ihr junger Liebhaber liegt im Rosengebüsch darunter, genau richtig platziert, um ihr unter den Rock zu blicken, und eine steinerne Amorstatue legt einen Finger an die Lippen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIANT_MAGNOLIAS"] =
    "Amerikanisches Stillleben in Öl, üppig und in der Stimmung fast tropisch. Zwei riesige cremeweiße Magnolienblüten liegen abgeschnitten auf einer Drapierung aus tiefblauem Samt, umgeben von ihren glänzenden dunklen Blättern, eine dritte Knospe noch geschlossen. Die Blütenblätter leuchten vor dem fast schwarzen Hintergrund, gemalt mit wachsartiger, sinnlicher Präzision."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_KILLING"] =
    "Katalanisches gotisches Tafelbild in Tempera und Gold. Der Heilige Georg, in schwarzer Rüstung mit goldenem Heiligenschein, beugt sich von seinem sich aufbäumenden weißen Pferd, um eine lange Lanze in das aufgerissene Maul eines fledermausflügeligen Drachen zu treiben, der Boden um sie herum mit Knochen und Schädeln übersät. Die rosa gewandete Prinzessin betet auf einem felsigen Vorsprung dahinter, und Zuschauer drängen sich oben auf den weißen Burgmauern."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JACQUES_AND_BERTHE"] =
    "Modernistisches Ölgemälde, ein Doppelporträt des Bildhauers Lipchitz und seiner Frau, gemalt in Modiglianis unverkennbarem Stil. Der Ehemann steht in einem dunklen Anzug, die Hand auf der Schulter seiner sitzenden Frau, deren rotwangiges Gesicht aus einem weißen Spitzenkragen aufsteigt. Beide haben die für den Künstler typischen langgezogenen Gesichter, langen Nasen und ausdruckslosen Mandelaugen, und ihre Namen sind quer über den oberen Rand der Leinwand gekritzelt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DASH_FOR_TIMBER"] =
    "Ölgemälde aus dem amerikanischen Westen, die Art von stürmender Actionszene, die den Alten Westen in der Vorstellung der Öffentlichkeit geprägt hat. Acht Cowboys galoppieren in vollem Lauf direkt auf den Betrachter zu, die Hufe der Pferde vom Boden gelöst, zwei Reiter im Sattel verdreht, um auf die Schar berittener Apachen zurückzufeuern, die im Staub hinter ihnen verfolgen. Ein verwundeter Mann sackt gegen einen Gefährten, während sie auf die Bäume am linken Rand der trockenen Ebene zureiten."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GEORGE_WASHINGTON_PORTRAIT"] =
    "Amerikanisches Staatsporträt in Öl, das offizielle Bildnis der ersten Präsidentschaft. Washington steht in voller Gestalt in einem schlichten schwarzen Samtanzug, einen Arm in einer Redegeste ausgestreckt, in der anderen Hand einen Galadegen, neben einem Tisch mit Feder und Tintenfass. Die Ausstattung um ihn herum ist republikanische Pracht: ein vergoldeter Stuhl mit dem Wappenschild aus Sternen und Streifen, Marmorsäulen und ein Behang aus karmesinrotem Drapierstoff, dahinter ein Regenbogen, der durch Sturmwolken bricht."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ATTACK_ON_BEIJING"] =
    "Japanischer Farbholzschnitt im Stil einer Kriegsnachrichtenillustration, betitelt auf Japanisch und auf Englisch. Alliierte Truppen stürmen die Mauern des Kaiserpalasts in Peking: rotuniformierte britische Soldaten mit einem Union Jack stürmen aus dem Vordergrund, während weißuniformierte japanische Infanterie auf der rechten Seite vorrückt. Granateinschläge stehen als weiße Wölkchen über dem grünen Exerzierplatz, dahinter das blaugedeckte Tor des Palastes und die rauchenden Mauern."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUMO_WRESTLER"] =
    "Japanischer Ukiyo-e-Holzschnitt, ein Prominentenporträt eines berühmten Ringers außer Dienst. Der große Mann steht in voller Höhe in einem schwarzen Kimono über gemusterten Gewändern, Schwerter im Gürtel, und tupft sich mit einem karierten Tuch die Stirn, während er einen zusammengebündelten Umhang über einer Schulter trägt. Sein Name verläuft an der rechten Seite in kräftigen roten Kalligrafietafeln, die Figur flach und monumental vor schlichtem Papier."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_TIGER_IN_TROPICAL_STORM"] =
    "Naives Ölgemälde des autodidaktischen französischen Zollbeamten, der nie einen Dschungel gesehen hat. Ein Tiger mit weit aufgerissenen Augen duckt sich tief in hohem, vom Wind gepeitschtem Gras, die Zähne gebleckt, gefangen in einem Sturm, der jede Pflanze zur Seite biegt. Der Dschungel ist ein dichtes Muster stilisierter Blätter in Grün- und Rottönen, mit schrägen silbernen Regenstreifen, die wie ein Schleier über die ganze Leinwand gezogen sind."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_HOME_GUARD"] =
    "Ungarisches Biedermeier-Ölporträt aus der Revolution von 1848. Ein bärtiger Bürgersoldat sitzt in einer schlichten ungefärbten Leinenjacke, beide behandschuhten Hände auf dem Griff seines aufrecht gestellten Säbels, die rot-weiß-grüne Nationalbinde am Ärmel verkündet seine Sache. Er blickt mit ruhiger Entschlossenheit zur Seite, warm beleuchtet vor einem dunkelroten Vorhang, seinen rotgefütterten Mantel über den Stuhl geworfen."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CEREMONIAL_SITTING"] =
    "Russisches realistisches Ölgemälde von gewaltigem Ausmaß, ein Gruppenporträt des gesamten Regierungsrates des Reiches. Dutzende betagter Staatsmänner in dunklen Uniformen, schwer von Goldlitzen und roten Schärpen, sitzen um ein großes Hufeisen aus roten Stühlen in einem weißgesäulten Saal, behängt mit Kronleuchtern und königlichen Porträts. Jedes der mehr als sechzig Gesichter ist ein eigenes Porträt, gemalt mit Repins schnellem, selbstsicherem Realismus."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUSSIAN_TSAR"] =
    "Russisches Historiengemälde in Öl, das einen königlichen Zug aus dem sechzehnten Jahrhundert nachstellt. Ein Zar mit Pelzmütze in einer Robe aus Goldbrokat reitet auf einem weißen Pferd durch den Schnee, vorangeführt von Wachen in leuchtend roten Mänteln, die hohe gekrümmte Hellebarden tragen. Die Menge kniet und verbeugt sich zu beiden Seiten der zertrampelten verschneiten Straße bis zum Boden, dahinter die Blockhäuser einer alten russischen Stadt unter einem blassen Winterhimmel."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CRUCIFIXION_OF_SAINT_PETER"] =
    "Italienisches barockes Ölgemälde, brutal und körperlich in Caravaggios charakteristischem Stil. Drei Arbeiter mühen sich, ein hölzernes Kreuz aufzurichten, an das der greise Petrus kopfüber genagelt worden ist, einer zieht an einem Seil, ein anderer kauert unter dem Balken, ihre Gesichter verborgen. Der weißbärtige Heilige hebt den Kopf, um auf seine eigene angenagelte Hand zu blicken, sein muskulöser alter Körper lodert aus pechschwarzer Dunkelheit in einem einzigen harten Licht hervor."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LANDSCAPE_WITH_ANT_BEAR"] =
    "Niederländische Koloniallandschaft in Öl, gemalt vom ersten europäisch ausgebildeten Künstler, der in Brasilien tätig war. Ein weites sonnenbeschienenes Tal mit einem Fluss öffnet sich unter einem großen Himmel zwischen zwei hohen Palmen, auf den fernen Hügeln eine koloniale Siedlung aus weißen Häusern. Eine Gruppe afrobrasilianischer Gestalten geht im Vordergrund einen Pfad entlang und trägt Bündel, und der langnasige Ameisenbär des Titels stöbert rechts unten durch das Gestrüpp."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DUTCH_MEN_O_WAR"] =
    "Marinegemälde des niederländischen Goldenen Zeitalters in Öl, gemalt vom größten Schiffsmaler der Epoche. Hohe hölzerne Kriegsschiffe liegen vor Anker auf einem Wasser, glatt wie Glas, ihre Segel hängen schlaff und ihre Rümpfe spiegeln sich in der See, jede Linie der Takelage genau wiedergegeben. Ruderboote setzen Passagiere zwischen den Schiffen über unter einem weiten Himmel aus sonnenbeschienenen Quellwolken, die ganze Szene in goldene Ruhe getaucht."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HARBOR_IN_BALAKLAVA"] =
    "Kolorierte Lithografie aus dem Krimkrieg, gezeichnet von einem der ersten Kriegszeichner, der einen Feldzug an Ort und Stelle dokumentierte. An einer trostlosen Hafenküste werden kranke und verwundete Soldaten, in weiße Decken gewickelt, von maultiergetragenen Tragen in ein wartendes Ruderboot gehoben. Kahle braune Hügel erheben sich hinter der zusammengedrängten Gruppe von Gestalten, Militärhütten und Zelte sprenkeln den Hang, die Farben gedämpft und dokumentarisch."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PEACEMAKERS"] =
    "Amerikanisches Historiengemälde in Öl, das einen realen Kriegsrat des Bürgerkriegs in seinen letzten Tagen zeigt. Präsident Lincoln sitzt in einer Dampferkabine und hört aufmerksam zu, das Kinn auf die Hand gestützt, während General Sherman mitten im Wortwechsel gestikuliert; General Grant und Admiral Porter vervollständigen den Kreis von vier dunkel gekleideten Gestalten. Durch die Kabinenfenster hinter ihnen bricht ein Regenbogen durch den aufklarenden Himmel, das stille Zeichen des Gemäldes für den kommenden Frieden."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_CHITASEI"] =
    "Japanischer Ukiyo-e-Holzschnitt aus Kuniyoshis berühmter Serie der 108 Helden des chinesischen Romans Die Räuber vom Liang-Schan-Moor. Der Gelehrte und Stratege Wu Yong steht in einer wallenden dunklen Robe, die mit Drachen gemustert ist, und streicht sich nachdenklich den Bart unter einem mit Sternen übersäten Nachthimmel. Neben ihm steht ein großer Himmelsglobus auf einem verzierten Ständer, und Tafeln mit japanischem Text rahmen die Figur ein."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_LOUIS"] =
    "Englisches Ölporträt aus dem achtzehnten Jahrhundert, das einen Bildhauer bei der Arbeit zeigt. Roubiliac, in einer weichen Mütze und einem offenen Hemd mit hochgekrempelten Ärmeln, hält mit erhobenem Modellierwerkzeug inne und blickt zur Seite, während er an einer Tonstatuette Shakespeares auf einem Ständer arbeitet. Mit der freien Hand weist der Bildhauer auf sein eigenes Werk, warm beleuchtet vor einem dunklen Atelierhintergrund."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_NASSER"] =
    "Persisches Hofporträt der Kadscharen in Öl, mit dick aufgetragener königlicher Pracht. Der junge schnurrbärtige Schah sitzt steif aufrecht in einer scharlachroten Uniform, übersät mit Goldstickerei, Perlenschnüren, juwelenbesetzten Epauletten und einer blauen Schärpe, eine Hand auf einem edelsteinbesetzten Schwert. Er trägt einen hohen schwarzen Hut mit einem Büschel aus Diamanten, seine dunkel umrandeten Augen blicken hinaus vor einem tief olivfarbenen Hintergrund, der mit einer königlichen Inschrift geprägt ist."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FIELD_WITH_SHEAFS"] =
    "Zum deutschen Expressionismus neigende Landschaft in Öl, in breiten, energischen Strichen gemalt. Ein abgeerntetes Weizenfeld füllt den Vordergrund mit Reihen goldener Kornhocken, in geneigten Bündeln gestapelt, das Gelb dick und leuchtend aufgetragen. Eine Reihe dunkelgrüner Bäume schließt das Feld ab, darüber ein blassviolett-blauer Himmel mit windgetriebenen Wolken."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AT_THE_EDGE_OF_THE_BROOK"] =
    "Französisches akademisches Ölgemälde, bis zur glasklaren Vollkommenheit poliert, für die Bouguereau berühmt war. Zwei barfüßige Bauernkinder sitzen auf einem Stein am Rand eines Baches, das jüngere Mädchen zieht einen Strumpf aus, während seine dunkelhaarige Gefährtin ihren Rock rafft, um zu waten. Mitten im Gespräch wechseln sie einen Blick, ihre Haut und ihr zerzaustes Haar mit fotografischer Glätte gemalt, vor einer sanften ländlichen Landschaft."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS_ALT"] =
    "Italienisches romantisches Ölgemälde, der berühmteste Kuss der italienischen Kunst und ein verborgenes patriotisches Sinnbild der Einigung. In einem mittelalterlichen Steinflur biegt ein junger Mann in einem Federhut und einem braunen Umhang eine Frau in einem leidenschaftlichen Kuss nach hinten, einen Fuß bereits auf der Treppe, als hielte er mitten in der Flucht inne. Ihr blassblaues Satinkleid ergießt Licht in die Szene, während sich durch den Bogengang dahinter eine schattenhafte Gestalt nähert."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MOVING_HOUSE"] =
    "Russisches realistisches Ölgemälde stiller städtischer Armut. Ein altes Paar stapft über das gefrorene Flusseis von Sankt Petersburg und trägt all seine Habe in einem Tuchbündel, der Mann auf einen Stock gestützt, beide in abgetragene Mäntel und Kopftücher gegen die Kälte gehüllt. Ein kleiner Hund trottet ihnen voran, und die vergoldete Turmspitze der Peter-und-Paul-Festung erhebt sich durch den Winterdunst dahinter."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MEXICAN_EXPEDITION"] =
    "Französisches Marinegeschichtsgemälde in Öl, im Reportagestil und voller Bewegung. Ein französisches Kriegsschiff unter der Trikolore beherrscht den linken Vordergrund, Offiziere auf seinem Deck leiten ein Bombardement der mexikanischen Festung San Juan de Ulua, Rauch steigt über dem Wasser auf. Granaten platschen neben Ruderbooten, die Männer zwischen den Schiffen übersetzen, und am dunstigen Horizont steht ein schneebedeckter Vulkan."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_DAY_OF_POMPEII"] =
    "Russisches romantisches Ölgemälde auf einer riesigen Leinwand, das Katastrophenepos seines Jahrhunderts. Der Himmel über Pompeji brennt rot und schwarz, als der Vesuv ausbricht, Statuen stürzen von einem Dach, und ein Blitz spaltet die Aschewolke. Scharen von Stadtbewohnern in römischer Kleidung fliehen durch die fallenden Trümmer und schützen Kinder und Greise unter Umhängen, während im Zentrum eine gestürzte Frau neben einem umgekippten Streitwagen ausgestreckt liegt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ACCOLADE"] =
    "Ölgemälde im Stil der englischen Präraffaeliten, eine märchenhafte Vision des Rittertums. Eine goldhaarige Königin in einem wallenden weißen Gewand berührt mit einem Schwert die Schulter eines knienden Ritters und schlägt ihn vor einem kleinen Hofpublikum zum Ritter. Er neigt den Kopf in Kettenhemd und rotem Waffenrock, sein Helm liegt neben ihm auf dem Boden, der steinerne Saal und das rote Podest in leuchtenden romantischen Einzelheiten gemalt."
