-- Mod-authored world wonder splash painting descriptions, fr_FR overlay.
-- Baseline in CivVAccess_WonderDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_MISSING"] = "Aucune description pour cette merveille."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOTHERLAND_STATUE"] =
    "Le jeu est sorti sans peinture pour cette merveille ; il n'y a aucune image à décrire."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ALHAMBRA"] =
    "À l'ombre d'une fine colonne de pierre, une cour de palais s'ouvre autour d'un long bassin réfléchissant, la cour des Myrtes de l'Alhambra. Le bassin s'éloigne vers un portique à arcades de pierre rose dont les arches se reflètent dans l'eau immobile. Une tour de forteresse carrée se dresse, chaude, contre le ciel bleu derrière. De basses haies taillées bordent le rebord de l'eau, une plante en pot se trouve au premier plan, et de petits groupes en longues robes discutent debout le long des allées ensoleillées. Le vif soleil d'après-midi emplit la cour, blanc là où il frappe le pavage. Une ombre profonde s'étend sous la colonnade."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ANGKOR_WAT"] =
    "Un groupe de tours étagées en pierre grise, en forme de boutons de lotus fermés, s'élève à l'arrière-plan, à demi masqué par des palmiers sous un ciel chaud et pâle. Le premier plan est une procession de fête : un éléphant gris avance à grands pas dans une foule dense, un cornac sur sa nuque et un siège à baldaquin sur son dos, ombragé par un haut parasol rouge orangé. La foule presse de tous côtés en robes blanches, safran et prune ; les têtes sont enturbannées, les épaules nues, et chaque visage se tourne vers l'éléphant à son passage. La scène est inondée de soleil et poussiéreuse, et la pierre est d'un vert-gris frais contre la peau chaude et les étoffes en dessous."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BIG_BEN"] =
    "Une tour-horloge gothique se dresse de nuit au bout du pont de Westminster, son horloge à quatre cadrans luisant d'un éclat ambré près du sommet. Au-dessus de l'horloge, la flèche se fond dans un ciel d'un bleu profond. La longue façade du palais de Westminster, à Londres, s'étend au loin vers la gauche, fenêtres et pierres baignées d'un or chaud par les projecteurs. Des tours à pinacles s'élèvent à son extrémité. Le pont traverse le premier plan avec une rangée de réverbères allumés. Quelques attelages et silhouettes se détachent, petits et sombres, sur la chaussée. Toute la scène est peinte dans des bleus nocturnes contre l'or des lampes et de la pierre éclairée."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BOROBUDUR"] =
    "Une pyramide à degrés de pierre volcanique grise s'élève de la jungle comme une colline en terrasses, ses étages supérieurs ceints de petits stupas en forme de cloche. Un stupa plus grand couronne le sommet. Des palmiers poussent sur les terrasses inférieures et la forêt presse de près contre sa base. Au premier plan, une file de moines en robes orange et rouges gravit vers le temple un sentier de jungle ombragé, et des oiseaux se dispersent dans le ciel embrumé au-dessus. La palette est d'un vert-gris vaporeux, et les robes sont la seule note de couleur forte."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BRANDENBURG_GATE"] =
    "Une large porte classique en grès patiné se dresse au fond d'une place de ville animée, élevée sur des rangées jumelées de lourdes colonnes et couronnée par le quadrige, la statue de bronze d'un char à quatre chevaux, qui se découpe sombre sur un ciel pâle et couvert. Une aile à colonnade plus basse s'étend vers la droite en direction des bâtiments de pierre environnants. La place devant est le Berlin du dix-neuvième siècle : des attelages roulant sur les pavés, des cavaliers, et des foules en longs manteaux sombres et hauts-de-forme, avec un réverbère s'élevant à gauche. Les couleurs sont des gris et des bruns sobres, et la lumière est plate et uniforme."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_BROADWAY"] =
    "Un quartier de théâtres la nuit, au début du vingtième siècle, la rue mouillée de pluie et brillante de lumière reflétée. Marquises et enseignes lumineuses se pressent des deux côtés de l'avenue, des ampoules blanches et rouges épelant des titres de spectacles. Une longue et claire façade de théâtre rayonne au centre du pâté de maisons. Des foules en manteaux et chapeaux sombres emplissent les trottoirs et débordent dans la rue parmi quelques vieilles automobiles, chacun minuscule contre les hauts et sombres immeubles de bureaux qui s'élèvent dans le ciel nocturne. La palette est d'un bleu-noir profond rompu par des flaques de lumière électrique blanche, rouge et jaune chaude."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CN_TOWER"] =
    "Une fine aiguille de béton s'élève au centre de la ligne d'horizon de Toronto, s'élargissant en une nacelle d'observation arrondie près du sommet et s'effilant ensuite en une flèche d'antenne. Des nuages d'orage se déchirent autour d'elle, et des rais de soleil tombent en cascade derrière la Tour CN par la trouée, embrumant les immeubles de bureaux de part et d'autre. Le premier plan est une voie rapide en contrebas où s'écoule le trafic, phares et feux arrière rouges brillant dans la pénombre entre des talus de béton. Toute la scène est gris acier et or. La ville est à demi dans l'ombre de l'orage, à demi dans la lumière qui perce."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CHICHEN_ITZA"] =
    "Une pyramide à degrés, El Castillo, se dresse au centre sous un ciel orange embrasé, neuf étages carrés montant vers un petit temple au sommet. Un large escalier grimpe tout droit sur sa face. Un second temple à étages s'élève au bord gauche, et de la fumée dérive devant le soleil suspendu bas et rouge. Une place en contrebas est emplie d'une foule de Mayas, la plupart tournés de dos : épaules nues, coiffes de plumes, bâtons et lances brandis. Un groupe de guerriers se tient sur une plate-forme de pierre à droite. Tout baigne dans la lumière rouille et ambrée du crépuscule. La foule se mue en silhouette sombre contre la pierre rougeoyante."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_CRISTO_REDENTOR"] =
    "Un colossal Christ de pierre pâle, vu de dos et de haut, se tient sur son piédestal au sommet de la montagne, les bras grand ouverts au-dessus de la baie en contrebas. Son dos drapé et ses bras tendus emplissent le cadre proche, la tête légèrement inclinée vers l'avant. Au-delà et loin en contrebas, Rio de Janeiro s'étend autour de l'eau en traînées blanches de bâtiments, avec la bosse arrondie du Pain de Sucre se dressant de la baie parmi des îles vertes et des navires à l'ancre. La brume adoucit le lointain, laissant la ville et la mer dans des bleus et des gris pâles, tandis que les épaules de la statue captent la lumière du jour."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_COLOSSUS"] =
    "Un géant de bronze se dresse au loin sur l'embouchure rocheuse du port, un bras levé, à demi dissous dans une brume dorée. Il tient plus de la silhouette que de la statue contre un ciel couleur de laiton. Le premier plan appartient à la mer : un petit voilier penche vers le spectateur sous une unique voile large, deux ou trois hommes d'équipage visibles à la poupe. D'autres voiles sont éparpillées à travers le port. De basses roches courent le long de la ligne d'eau à droite, et l'eau porte le même or chaud que le ciel. Tout le tableau est d'une seule couleur, lumière et brume d'ambre. Le Colosse y rayonne comme une figure de rêve."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MOSQUE_OF_DJENNE"] =
    "Un long mur de terre fait de tours et de pinacles s'étend à travers l'arrière-plan, en brique de boue d'un rouge-brun profond. Ses faces sont hérissées de toron, des rangées de poutres de bois sortant des murs comme des épines. Le ciel derrière lui est épais de poussière orange et de fumée, le soleil perdu dans la brume. Tout le premier plan est un jour de marché : des auvents et des baldaquins rouges et blancs, des animaux parmi les étals, et une foule dense en robes vives circulant entre eux. La chaleur et la poussière unifient la scène, et tout est peint dans des oranges, des rouilles et des bruns."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_EIFFEL_TOWER"] =
    "Une sombre charpente de fer faite de jambes et de plateformes à poutrelles emplit le coin supérieur gauche du cadre, si proche que le sommet est coupé par le bord de l'image. En dessous, la scène est un après-midi de la belle époque sur l'herbe : des groupes en longues robes blanches et en costumes sombres pique-niquent sur une vaste pelouse verte, avec des ombrelles, des chapeaux de soleil et des paniers étalés autour d'eux. Une femme en blanc se tient au centre. Derrière la pelouse, la Seine glisse, et la pierre pâle de Paris s'étire le long de la rive lointaine sous un ciel gris et doux. La palette est faite de verts et de gris froids. Les robes blanches captent le peu de lumière qu'il y a."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_FORBIDDEN_PALACE"] =
    "Des salles de palais aux toits de tuiles dorées élancés et aux murs rouge profond se dressent au-delà d'une vaste cour pavée, vues depuis une terrasse de marbre surélevée au premier plan. Une sombre statue de lion gardien est tapie sur la balustrade de la terrasse à gauche, et des figures en robe se tiennent le long des escaliers. En bas, dans la cour, des rangs de soldats sont alignés en formation serrée devant la salle centrale, écrasés par l'architecture qui les entoure. Un soleil pâle est suspendu dans un ciel d'ambre brumeux, et toute la scène est baignée d'un or poussiéreux contre le rouge des murs."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GLOBE_THEATER"] =
    "Un théâtre rond en bois vu depuis sa propre scène en pleine représentation. Trois étages de balcons à galeries s'incurvent autour du parterre central, chaque rambarde bondée de spectateurs. Sur le sol ouvert en dessous, les groundlings, les spectateurs debout du parterre, se pressent, une mer pâle de visages. Sur la scène, un acteur en pourpoint sombre joue une scène vers deux femmes en longues robes, l'une d'elles faisant un geste du bras tendu. Le toit peint en auvent fait saillie en haut à droite sur un poteau sculpté. Une douce lumière du jour tombe du ciel ouvert au-dessus du parterre. Le bois est d'un crème et d'un brun chauds, et la foule est esquissée pâle autour des figures plus nettes sur la scène."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_FIREWALL"] =
    "Une scène numérique abstraite sans aucun bâtiment, un cyberespace sombre rendu dans des verts et du noir. De larges surfaces courbes balaient le cadre comme des remparts de données, leurs faces carrelées de chiffres binaires verts lumineux, et des traces luisantes filent le long d'elles comme la circulation sur une autoroute la nuit. Des écrans et des grilles fantomatiques flottent dans l'obscurité au-dessus, suggérant des circuits et de la surveillance. Toute l'image a l'allure du monde intérieur d'un ordinateur, une lumière vert phosphore sur fond noir."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIBRARY"] =
    "Une salle classique monumentale fait face à une place ensoleillée, de hautes bannières rouges suspendues entre les colonnes de sa longue colonnade. Une frise sculptée court au-dessus des colonnes, et de larges marches descendent jusqu'au pavé. La place est vue depuis un portique ombragé au premier plan : une colonne s'élève à gauche, un sphinx de pierre est assis sur un socle à droite, et un dôme blanc se montre au loin par-delà. Des érudits et des citoyens en toges et en robes colorées se rassemblent sur les marches et à travers la place, la plupart se tenant par deux ou trois en conversation tandis qu'une figure est assise seule avec un rouleau. La pierre est d'un crème chaud sous le soleil, sous un ciel bleu zébré de nuages, et les bannières sont le rouge le plus fort de la scène."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_LIGHTHOUSE"] =
    "Une haute tour pâle en gradins superposés se dresse au loin à droite, éclairée par une éclaircie dans la tempête, son fanal rougeoyant au sommet. Le reste de l'image est une mer agitée : une file d'antiques galères sous des voiles carrées rayées de rouge et de blanc peine à travers de lourdes houles gris-vert vers la lumière, les proues recourbées haut. L'écume éclate blanche contre les coques. De sombres nuages d'orage pèsent sur toute la scène, et le ciel ne s'ouvre qu'autour de la tour, comme si les navires couraient vers elle. Les voiles portent la seule couleur chaude dans un tableau d'ardoise, d'écume et de pluie."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_GREAT_WALL"] =
    "Un large rempart de pierre court depuis le bas du cadre tout droit vers le haut et par-dessus les montagnes, ses parapets crénelés gravissant les lignes de crête jusqu'à ce que le mur se réduise à un fil sur les pics les plus lointains. Une tour de guet carrée à deux étages, dotée de fenêtres en arc et d'un petit pavillon couvert au sommet, se dresse à la première montée. Le tracé du mur s'infléchit à travers elle. Les montagnes sont plissées et vertes, des pentes broussailleuses plongeant dans la brume, vallée après vallée. Aucune figure ne se montre nulle part sur le mur. La lumière est froide et claire, la pierre grise contre le vert profond sous un ciel pâle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HAGIA_SOPHIA"] =
    "Une grande basilique à coupole couronne un panorama urbain à l'heure dorée, son large dôme central s'élevant d'un amas de murs contrebutés et de demi-coupoles. Quatre minarets élancés se dressent aux angles, l'édifice étant représenté comme la mosquée qu'il devint plus tard. Tout autour, les toits d'Istanbul dévalent la colline dans des tons fauves et gris, rompus par des arbres, des coupoles secondaires et des tours lointaines qui se dissolvent dans la brume. Un reflet d'eau et quelques basses collines ferment l'horizon sur la gauche. Tout repose sous un ciel d'ambre chaud, et la silhouette du dôme se découpe en or sombre contre la lumière."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HANGING_GARDEN"] =
    "Une cour de jardin s'étend à l'intérieur de murs d'arcades en grès chaud. Des palmiers s'élèvent au-dessus des allées, et la verdure déborde sur chaque arche et chaque rebord. Des personnages en robe se promènent et conversent par deux ou trois le long des chemins ombragés, parmi les parterres et les petits arbres. À travers l'arche centrale et au-dessus du mur, une cité-palais blanche gravit une colline en terrasses étagées, étincelant au loin comme la couronne du jardin. Tout se tient sous un soleil éclatant, le feuillage vert profond se détachant sur la pierre dorée et un ciel pâle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HIMEJI_CASTLE"] =
    "Un donjon de château blanc s'élève d'une colline boisée en haut du cadre, étage après étage de murs pâles sous des toits gris incurvés. De plus petites tourelles blanches se groupent en dessous parmi les arbres. La route qui y mène traverse un village aux toits de tuiles sombres, et une porte à cadre rouge enjambe le chemin à mi-distance. Des samouraïs montés chevauchent vers le château à travers le premier plan, de hautes bannières rouges dressées dans leur dos. Des fantassins en armure attendent près des maisons sur la droite. Le jour est doux et couvert, et la scène n'est que verts et gris autour du donjon blanc. Les bannières sont le rouge le plus vif de la scène."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_HUBBLE"] =
    "Un long cylindre argenté enveloppé de panneaux de feuille métallisée flotte en orbite, sa trappe d'ouverture articulée ouverte à l'extrémité proche pour exposer la bouche sombre de l'optique. De plats panneaux solaires montés dans des cadres cuivre et or se déploient de ses flancs, et un astronaute en scaphandre travaille à son côté, minuscule auprès de l'instrument. Une partie d'un vaisseau spatial amarré entre dans le coin inférieur droit du cadre. Derrière tout cela, la Terre emplit l'image, une courbe d'océan bleu et de nuages blancs s'effaçant dans le noir de l'espace. La palette est d'argent et d'or contre le bleu de la Terre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_KREMLIN"] =
    "La neige tombe sur la place Rouge, où un mur de forteresse en briques rouge foncé court le long de la droite sous un ciel d'hiver gris et pesant. Un drapeau rouge flotte au-dessus du bloc trapu et à gradins du mausolée de Lénine adossé au mur, et plus loin une haute tour s'élève dans la brume, sa flèche en forme de tente abrupte. Des foules en longs manteaux sombres et chapeaux de fourrure traversent la place enneigée en une lente file, des silhouettes isolées avançant péniblement au premier plan, le dos tourné au spectateur. La peinture est presque monochrome, neige blanche et gris charbon, avec la brique et le drapeau pour seuls rouges."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LEANING_TOWER"] =
    "Un campanile rond et blanc s'élève d'une pelouse verte, cerné étage après étage d'arcades de marbre ouvertes et penchant indubitablement vers la droite. Il se découpe avec éclat sur un ciel d'orage sombre. Le flanc pâle de la cathédrale de Pise se dresse au bord droit du cadre, et de plus basses constructions de la ville, dans des tons ocre, ferment la pelouse sur la gauche. Habitants et moines en longues robes brunes et rouges traversent la pelouse en cortèges épars, minuscules sous la Tour penchée de Pise. La lumière est théâtrale : une trouée dans les nuages illumine le marbre blanc tandis que le ciel derrière reste presque noir."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_LOUVRE"] =
    "Un palais de pierre grise s'étend en arrière-plan, un haut pavillon central orné de sculptures et de toits mansardés abrupts en ardoise, avec des ailes se prolongeant de part et d'autre. Les artistes le montrent à l'époque où il était le palais royal, bien avant la pyramide de verre du musée moderne. Devant s'étendent des jardins à la française : des pelouses plates traversées d'allées de gravier, de jeunes arbres, et une petite fontaine qui jaillit sur la gauche. Des promeneurs en costume du dix-neuvième siècle parsèment les allées, des femmes en longues robes blanches et des hommes en manteaux sombres et hauts-de-forme. Un couple s'attarde ensemble sur la droite. Le jour est doux et nacré. Tout est pierre grise et vert atténué sous un ciel pâle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MACHU_PICHU"] =
    "Une cité de pierre se niche dans un haut col de montagne, des terrasses agricoles gravissant la pente jusqu'à des groupes de bâtiments à pignons sous des toits de chaume. Derrière elle, le pic abrupt du Huayna Picchu s'élève dans les nuages. La brume s'étend sur les chaînes environnantes, et la vallée plonge dans l'ombre en contrebas. Sur le sentier du premier plan, une petite troupe avec des lamas de bât se fraye un chemin vers les portes de la cité, minuscule contre les terrasses. La lumière vient en pâles faisceaux à travers les intempéries, détachant la chaude pierre fauve du vert et du gris des Andes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_MAUSOLEUM_HALICARNASSUS"] =
    "Un massif podium carré de marbre blanc, ceint de frises sculptées, s'élève vers une couronne de colonnes en haut du cadre. Il domine une place où des statues se dressent sur de hauts piliers, parmi elles une figure en armure et un cavalier. De sombres cyprès sont plantés entre les pavements. Des personnages en robes blanches et rouges se rassemblent en contrebas, écrasés par le monument. Le jour est lumineux et clair. Le marbre blanc et les nuages blancs amoncelés se détachent sur un ciel d'un bleu profond."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NEUSCHWANSTEIN"] =
    "La pâle apparition d'un château se dresse sur une crête boisée, murs blancs et tours groupées à demi dissous dans la neige qui tombe, en haut à gauche du cadre. Le premier plan est la route qui y monte : une sombre voiture fermée attend au virage tandis que des cavaliers défilent en remontant la pente, remuant la neige sur la piste. Des sapins poudrés de neige bordent le chemin et se referment au-dessus de la vallée en contrebas. La peinture est gris et blanc d'hiver d'un bout à l'autre. Les cavaliers et la voiture sont les seules formes sombres qui s'y détachent."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_NOTRE_DAME"] =
    "Une cathédrale gothique s'élève au-dessus du Paris médiéval, vue de haut, ses deux tours carrées jumelles, sa flèche centrale et sa longue nef arc-boutée dominant de loin tous les toits alentour. La ville se presse jusqu'à ses murs en un tissu dense de maisons à pignons et de cheminées fumantes, et la Seine s'incurve au premier plan le long des quais et de petits bateaux. Le ciel est lourd et gris, mais des rais de soleil percent les nuages et tombent droit sur la cathédrale, dorant sa pierre tandis que la ville reste dans une ombre ardoise. L'horizon s'efface, plat et pâle, au-delà des toits."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_ORACLE"] =
    "Un temple rond à colonnade sous un dôme de pierre, un tholos, se dresse sur un rocher marin à l'extrémité d'un promontoire rocheux, et une arche naturelle s'ouvre dans la falaise en dessous. Les artistes ont placé le sanctuaire sur la côte plutôt que sur le flanc de la montagne de Delphes. Un sentier serpente vers lui en longeant des cuvettes de marée et des rochers dressés. Au premier plan, des pèlerins en robes rouges, bleues et blanches cheminent par petits groupes le long du sentier, encadrés par de sombres pins penchés des deux côtés. C'est un début de soirée fraîche, avec un ciel pâle éclairé par la lune et une mer gris-vert autour de la pierre chaude du sanctuaire."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PARTHENON"] =
    "Un long temple dorique se dresse intact en haut de l'image, sa colonnade portant un fronton sculpté et peint. Le marbre est d'un or chaud sous un ciel de nuages gris roulants. De larges marches en descendent à travers des massifs de buissons verts bas, avec des statues de bronze dressées sur des socles à gauche. Les marches voient descendre une procession de Grecs en capes cramoisies, et au centre un seul hoplite fait face au spectateur, coiffé d'un casque à cimier, un bouclier rond au bras. Les rouges des capes flamboient contre la pierre, et la lumière a l'éclat lourd d'un jour sur le point d'éclater en orage."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PENTAGON"] =
    "Une vue aérienne du bâtiment du quartier général à cinq côtés, ses anneaux pentagonaux concentriques de béton pâle et de toiture sombre s'étageant vers l'intérieur jusqu'à une cour verte au centre. Des routes et des parkings entourent le bâtiment, avec des pelouses et des arbres aux teintes d'automne au-delà. Le Potomac coule derrière lui, traversé par des ponts. Sur la rive opposée, la capitale s'étend dans la brume, l'obélisque blanc du Washington Monument et le dôme du Capitole petits à l'horizon. Le jour est terne et gris ; rien dans la scène ne ressort, sinon la forme du bâtiment."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PETRA"] =
    "Le spectateur se tient à l'intérieur du Siq, l'étroit défilé d'accès, entre des parois de roche rouge rosé qui se dressent dans l'ombre des deux côtés de l'image. Par la fente, éclairé en plein soleil, se dresse Al-Khazneh, le Trésor, une façade taillée à même la falaise. Ses deux étages de colonnes et de frontons classiques s'élèvent dans le grès rose, avec un pavillon rond au centre du niveau supérieur. Des voyageurs avancent vers lui le long du fond sablonneux du défilé : deux cavaliers se balancent sur des chameaux au premier plan proche, et des silhouettes en robe marchent derrière. La peinture n'est faite que de rouges chauds et de bruns ombreux, la façade sculptée rougeoyant au bout du sombre passage."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PORCELAIN_TOWER"] =
    "Une haute pagode s'élève au-dessus d'un jardin de temple, étage après étage d'avant-toits sombres et galbés sur un corps élancé. Elle domine les toits de tuiles des pavillons à sa base. Le jardin s'étend au premier plan autour d'un bassin immobile : pins taillés, saules, lanternes de pierre et une statue de lion sculptée sur un socle au bord gauche. Des silhouettes en robe flânent sur les allées de gravier par deux et par trois, et des collines boisées se dressent dans la brume derrière la tour. La scène est calme et verte, la lumière du jour douce sur l'eau, la pagode se découpant sombre contre un ciel pâle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PRORA_RESORT"] =
    "Un bloc monolithique de complexe balnéaire longe le rivage, apparemment sans fin. Sa façade pâle répète encore et encore les mêmes rangées de fenêtres, s'étirant le long de la plage jusqu'à disparaître vers l'horizon. La portion la plus éloignée est encore couverte d'échafaudages. À l'extrémité proche se dresse un grand bâtiment en forme de tambour rond cerné de colonnes sur une base rouge foncé, un drapeau rouge flottant sur son toit. En contrebas, la plage est animée : baigneurs et promeneurs épars en petites figures sur le sable, avec la mer gris-vert qui déferle à droite. D'imposants nuages ensoleillés emplissent le ciel au-dessus d'un lumineux après-midi en bord de mer, le béton crème contre l'eau bleue."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_PYRAMID"] =
    "Deux grandes Pyramides se dressent pâles dans la brume du désert, la plus proche emplissant le coin supérieur droit de l'image. Une troisième se dresse, petite, à l'horizon. Le Sphinx est accroupi entre elles à mi-distance. Des palmiers s'alignent en une mince rangée le long du sable, et de basses murailles en ruine et des blocs bordent une dépression au premier plan. Un cavalier en rouge est assis sur un chameau en bas à droite, et une petite caravane de chameaux traverse le sable à gauche avec des silhouettes qui marchent à côté. Tout est couleur de sable, fauve et os sous un ciel blanc et brumeux. Le cavalier rouge est la seule couleur vive."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_RED_FORT"] =
    "Une forteresse de grès rouge foncé sous l'assaut : de hautes murailles et des bastions ronds emplissent l'image, des pavillons blancs à dôme se dressent le long des remparts, de l'herbe pousse sur les corniches, et des colonnes de fumée noire montent des incendies à l'intérieur. Les défenseurs se pressent sur les créneaux au-dessus de la porte. Au premier plan, des soldats en armure et casques arrondis se ruent vers les murs, passant devant une catapulte de bois et ses servants au bord gauche. La peinture est lourde de pierre rouge et de fumée, et les pavillons blancs et une bande de ciel pâle sont le seul répit."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SISTINE_CHAPEL"] =
    "Une cérémonie à l'intérieur de la chapelle, vue depuis l'assemblée des fidèles. Le mur du fond derrière l'autel est couvert du sol au plafond par la fresque du Jugement dernier, un tourbillon de figures sur fond bleu, et des scènes peintes et des tentures garnissent les murs latéraux sous de hautes fenêtres en arc. La voûte ornée de fresques entre tout juste en haut de l'image. Des membres du clergé en blanc célèbrent à l'autel éclairé aux chandelles tandis que des cardinaux en écarlate emplissent le premier plan et les bancs le long des murs. Leur rouge est la couleur la plus forte de cet intérieur obscur. Le peu de lumière du jour tombe, gris, des fenêtres sur les murs peints."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_INTERNATIONAL_SPACE_STATION"] =
    "Une station en treillis flotte en orbite sur le noir de l'espace : une longue poutre centrale traversée par des paires de grandes ailes solaires bleu-gris, avec la chaîne de modules cylindriques blancs et de noeuds d'amarrage groupés en son centre. Une capsule est amarrée à l'extrémité proche de la chaîne de modules, et des panneaux radiateurs se déploient à plat sous la poutre. Derrière elle, la Terre s'incurve au loin dans un bleu profond, des volutes de nuages éclatant sur sa face nocturne. Des étoiles se dispersent dans le noir au-dessus. L'image est nette et photographique : du métal blanc, une planète bleue, et aucun personnage nulle part."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_OF_LIBERTY"] =
    "Une figure de cuivre drapée, patinée d'un vert pâle, se tient sur son socle de pierre à gauche d'un port animé, le bras à la torche levé haut contre un ciel de nuages déchirés. Devant elle passe à vapeur un paquebot du début du XXe siècle, à coque noire et à deux cheminées rouge et noir traînant une fumée de charbon, tandis que des remorqueurs brassent l'eau à ses côtés à travers le clapot. La ligne d'horizon de New York s'étend basse et brumeuse au-delà de l'eau, à droite. La scène est peinte dans des gris et des verts marins, fumée et nuages se mêlant. La statue vert pâle est la forme la plus nette dans toute cette fumée et ces nuages."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STONEHENGE"] =
    "Un cercle de grandes pierres dressées, coiffées de linteaux, se tient sur une lande sombre la nuit, rougeoyant d'une lueur chaude venue de feux allumés quelque part à l'intérieur, comme si une cérémonie était en cours. Une comète zèbre le ciel étoilé au-dessus. Des pierres isolées en périphérie s'élèvent de la bruyère dans le premier plan ombragé, avec quelques petits feux et de vagues silhouettes parsemés à travers la plaine. Tout est d'un bleu nuit profond, sauf la lumière ambrée flaquée autour du monument."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_SYDNEY_OPERA_HOUSE"] =
    "De grandes coques de toit blanches en forme de voiles emplissent la droite du cadre vues de tout près, se chevauchant contre un ciel bleu éclatant. Le verre et la sombre maçonnerie de la base du bâtiment apparaissent en dessous. Un grand navire de croisière blanc est à quai juste au-delà, et un yacht à moteur effilé fend le clapot du premier plan. De l'autre côté du port scintillant, les tours de Sydney se dressent au loin à gauche. Le jour est clair et lumineux. Toits blancs et navires blancs se détachent sur une eau bleu-vert profond."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TAJ_MAHAL"] =
    "Un mausolée de marbre blanc se dresse de face au bout de son long jardin, son grand dôme central se gonflant au-dessus du renfoncement d'un portail en arc. De plus petits kiosques à dôme sont disposés de part et d'autre du grand dôme, et une tour minaret s'élève à chaque angle de la plateforme. Le jardin court tout droit vers lui : un étroit canal réfléchissant au milieu, flanqué d'allées pavées, de rangées de sombres cyprès et de basses plates-bandes vertes. Quelques petites silhouettes en robes marchent dans les allées. Le ciel derrière est un doux coucher de soleil de pêche et d'or, et le marbre prend cette couleur, le blanc nuançant vers le crème et le rose."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TEMPLE_ARTEMIS"] =
    "Une longue colonnade de marbre sous un fronton sculpté couronne une hauteur au fond de la scène, avec la statue d'un cavalier dressée devant les marches et des cyprès sombres alignés le long de l'accès. Une vaste terrasse au premier plan déborde de vie : des personnages en toges blanches et en robes colorées flânent et commercent, des marchands s'accroupissent près de paniers à gauche, et des femmes voilées passent tout près au premier plan droit. Une colonne rouge encadre la vue au bord gauche, avec une verte campagne de vallée et une rivière qui s'enfoncent loin en contrebas. Le soleil de midi flamboie sur le marbre blanc et les étoffes vives sous un ciel bleu chargé de nuages."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_STATUE_ZEUS"] =
    "Dans la salle d'un temple, le dieu trônant s'élève jusqu'au plafond en or et en ivoire, barbu et torse nu, une robe sur les genoux. Une main tient une petite figure ailée de la Victoire tendue au-dessus de la salle, et l'autre empoigne un grand sceptre. Son trône est travaillé en or contre un mur rouge chaud, et des rangées de colonnes s'étirent des deux côtés de la chambre, laissant les bas-côtés dans l'ombre. Des fidèles en robes pâles se rassemblent aux pieds de la statue, aucun n'atteignant ses tibias. De petites flammes brûlent le long des murs. La lumière tombe de quelque part en haut, flaquant l'or sur la statue tandis que la salle alentour reste sombre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_TERRACOTTA_ARMY"] =
    "Des rangs de soldats d'argile emplissent le cadre d'un mur à l'autre, file après file de guerriers grandeur nature en cottes d'armure au garde-à-vous. Ils s'éloignent en longs corridors entre des murs de séparation en terre. Chaque rangée s'estompe plus profondément dans la fosse jusqu'à ce que les plus lointains ne soient que des silhouettes contre une lueur dorée qui perce au fond de la chambre. Les figures sont brun terre et gris, leurs épaules et leurs casques bordés par la lumière chaude. L'atmosphère est silencieuse et vaste, une armée de morts rangée en bataille dans l'obscurité."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UNITED_NATIONS"] =
    "Une vue au niveau de la rue de la place des Nations unies. La dalle de verre plate de la tour du Secrétariat s'élève à gauche, au-dessus du long et bas déploiement du bâtiment de l'Assemblée. Une rangée de mâts porte les drapeaux de nombreuses nations le long de la rue. La place est pleine de délégués : des hommes et des femmes en costumes d'affaires mêlés à des tenues nationales, un personnage en robes et coiffe blanches du Golfe au centre de la foule, des groupes s'arrêtant pour converser en chemin vers l'entrée. Un taxi jaune attend au bord du trottoir à droite, et la ligne d'horizon de New York se dresse derrière les drapeaux. C'est la fin de l'après-midi, avec de longues ombres sur le pavé et un soleil bas accrochant le verre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_WONDERDESC_BUILDING_UFFIZI"] =
    "Deux longues ailes de galerie se font face de part et d'autre d'une cour étroite, hautes façades Renaissance de pierre grise et de plâtre crème avec des statues dressées dans des niches au-dessus de la loggia du rez-de-chaussée. La cour s'enfonce profondément dans le tableau vers une ouverture en arc au fond, et une tour se découpe sur le ciel au-delà. En bas, la cour est animée de Florentins en longues robes et en manteaux sombres, des sculptures exposées sur des socles le long du milieu, et un étal à auvent rouge installé au premier plan gauche. Le soleil de l'après-midi entre obliquement d'un côté, éclairant chaudement les étages supérieurs tandis que la loggia en dessous garde une ombre fraîche."
