-- Mod-authored localized strings, in-game Context.
-- Looked up by Text.key / Text.format in CivVAccess_Text.lua. Sets a global
-- (rather than returning) so the offline test harness can dofile() it without
-- relying on Civ V's include() semantics.
CivVAccess_Strings = CivVAccess_Strings or {}
CivVAccess_Strings["TXT_KEY_CIVVACCESS_BOOT_INGAME"]     = "Civilization V accessibility loaded in-game."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_BUTTON_DISABLED"] = "disabled"
-- Help overlay strings (see FrontEnd strings for the authoring rationale).
-- Duplicated here because Contexts are sandboxed: in-game Contexts that
-- eventually wire SetInputHandler through InputRouter need their own copy.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_HELP"]                 = "Help"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_ENTRY"]                  = "{1_Key}, {2_Description}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_AZ09"]               = "Letters"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_UP_DOWN"]            = "Up or down"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_HOME_END"]           = "Home or end"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ENTER_SPACE"]        = "Enter or space"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_LEFT_RIGHT"]         = "Left or right"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_SHIFT_LEFT_RIGHT"]   = "Shift plus left or right"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_CTRL_UP_DOWN"]       = "Control plus up or down"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_TAB"]                = "Tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_SHIFT_TAB"]          = "Shift plus tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_F1"]                 = "F1"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ESC"]                = "Escape"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ENTER"]              = "Enter"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_QUESTION"]           = "Question mark"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_SEARCH"]            = "Type to search"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_NAV_ITEMS"]         = "Navigate items"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_JUMP_FIRST_LAST"]   = "Jump to first or last"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ACTIVATE"]          = "Activate"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ADJUST"]            = "Adjust value or drill in"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ADJUST_BIG"]        = "Adjust value in larger steps"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_JUMP_GROUP"]        = "Jump to previous or next group"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_NEXT_TAB"]          = "Next tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_PREV_TAB"]          = "Previous tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_READ_HEADER"]       = "Read screen header"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CANCEL"]            = "Cancel"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CLOSE"]             = "Close"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CANCEL_EDIT"]       = "Cancel edit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_COMMIT_EDIT"]       = "Commit edit"
-- Civilopedia (picker/reader two-tab) strings.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PEDIA_CATEGORIES_TAB"]        = "Categories"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PEDIA_CONTENT_TAB"]           = "Content"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PEDIA_NO_ARTICLE"]            = "No article text available."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PICKER_READER_EMPTY"]         = "No content for this entry."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PICKER_READER_NO_SELECTION"]  = "No entry selected. Switch to the categories tab to pick one."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PEDIA_INTRO"]                 = "Intro"
-- Spoken replacements for [ICON_*] markup. Registered into TextFilter by
-- CivVAccess_Icons.lua; the filter substitutes the bracket token inline
-- with the spoken text. Singular / plural wording is deliberately relaxed
-- ("turns", "whales") because screen-reader users tolerate minor grammar
-- over awkward branching, and Civ's text uses these icons in both counts.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GOLD"]                    = "gold"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_FOOD"]                    = "food"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_PRODUCTION"]              = "production"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_CULTURE"]                 = "culture"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_SCIENCE"]                 = "science"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RESEARCH"]                = "research"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_FAITH"]                   = "faith"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_TOURISM"]                 = "tourism"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_INFLUENCE"]               = "influence"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_STRENGTH"]                = "combat strength"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RANGE_STRENGTH"]          = "ranged strength"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_MOVEMENT"]                = "movement"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_SWAP"]                    = "swap"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_HAPPY"]                   = "happy"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_UNHAPPY"]                 = "unhappy"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_CAPITAL"]                 = "capital"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_CITIZEN"]                 = "citizen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_CONNECTED"]               = "connected"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_OCCUPIED"]                = "occupied"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_PUPPET"]                  = "puppet"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RAZING"]                  = "razing"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RESISTANCE"]              = "resistance"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_BLOCKADED"]               = "blockaded"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE"]            = "great people"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_WORK"]               = "great work"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GOLDEN_AGE"]               = "golden age"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_TRADE_ROUTE"]              = "trade route"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_SPY"]                      = "spy"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_DIPLOMAT"]                 = "diplomat"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_TURNS"]                    = "turns"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_ARROW_LEFT"]               = "left"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_ARROW_RIGHT"]              = "right"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_PLUS"]                     = "plus"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_MINUS"]                    = "minus"
-- Empty value: bullet glyphs are purely visual separators; speaking anything
-- at all would add noise. Registered so the token doesn't log the miss-warn
-- on every pedia article that happens to use one.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_BULLET"]                   = ""
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_TROPHY_BRONZE"]            = "bronze trophy"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_TROPHY_SILVER"]            = "silver trophy"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_TROPHY_GOLD"]              = "gold trophy"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_VICTORY_CULTURE"]          = "cultural victory"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_VICTORY_DIPLOMACY"]        = "diplomatic victory"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_VICTORY_DOMINATION"]       = "domination victory"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_VICTORY_SCIENCE"]          = "science victory"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION"]                 = "religion"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_PANTHEON"]        = "pantheon"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_BUDDHISM"]        = "Buddhism"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_CHRISTIANITY"]    = "Christianity"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_CONFUCIANISM"]    = "Confucianism"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_HINDUISM"]        = "Hinduism"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_ISLAM"]           = "Islam"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_JUDAISM"]         = "Judaism"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_ORTHODOX"]        = "Orthodox Christianity"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_PROTESTANT"]      = "Protestantism"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_SHINTO"]          = "Shinto"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_SIKHISM"]         = "Sikhism"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_TAOISM"]          = "Taoism"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_TENGRI"]          = "Tengri"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RELIGION_ZOROASTRIANISM"]  = "Zoroastrianism"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_ALUMINUM"]             = "aluminum"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_ARTIFACT"]             = "artifact"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_HIDDEN_ARTIFACT"]      = "hidden artifact"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_BANANA"]               = "bananas"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_BISON"]                = "bison"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_CITRUS"]               = "citrus"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_CLOVES"]               = "cloves"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_COAL"]                 = "coal"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_COCOA"]                = "cocoa"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_COPPER"]               = "copper"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_COTTON"]               = "cotton"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_CATTLE"]               = "cattle"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_CRAB"]                 = "crab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_DEER"]                 = "deer"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_DYE"]                  = "dye"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_FISH"]                 = "fish"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_FUR"]                  = "fur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_GEMS"]                 = "gems"
-- Disambiguate from the gold currency to avoid identical speech for two
-- distinct concepts; the game's resource name is also "Gold" but speaking
-- it as-is would collide with [ICON_GOLD] every time a tech description
-- mentions both.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_GOLD_ORE"]             = "gold ore"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_HORSES"]               = "horses"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_INCENSE"]              = "incense"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_IRON"]                 = "iron"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_IVORY"]                = "ivory"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_JEWELRY"]              = "jewelry"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_MANPOWER"]             = "manpower"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_MARBLE"]               = "marble"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_NUTMEG"]               = "nutmeg"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_OIL"]                  = "oil"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_PEARLS"]               = "pearls"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_PEPPER"]               = "pepper"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_PORCELAIN"]            = "porcelain"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_SALT"]                 = "salt"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_SHEEP"]                = "sheep"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_SILK"]                 = "silk"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_SILVER"]               = "silver"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_SPICES"]               = "spices"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_STONE"]                = "stone"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_SUGAR"]                = "sugar"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_TRUFFLES"]             = "truffles"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_URANIUM"]              = "uranium"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_WHALES"]               = "whales"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_WHEAT"]                = "wheat"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RES_WINE"]                 = "wine"
