-- Scanner directional beep. One short tone fired on every scanner cycle
-- (item / instance / subcategory / category cycles, search land, End-key
-- distance probe) that encodes the displacement from the readout's origin
-- to the cycled-to entry's plot. Pan, pitch, and volume use the same
-- per-axis math as the audio beacons (see CivVAccess_Beacons.lua's
-- updateBeaconParams): pan scales linearly with the row-corrected column
-- delta, pitch shifts one semitone per row, volume linearly fades over
-- the user's configured BeaconRange. ONI Access fires two separate beeps
-- (vertical then horizontal); the Civ V beacon math already encodes both
-- axes in a single tone, so one beep per cycle is enough.
--
-- Off by default. The toggle (TXT_KEY_CIVVACCESS_SETTINGS_SCANNER_DIRECTION_BEEP)
-- lives in the F12 Scanner group. Cycling through scanner entries already
-- speaks the direction, so the beep is opt-in for users who want a
-- pre-attentive spatial cue layered on top of the spoken readout.
--
-- Sound asset (sounds/scanner_beep.wav): a 75 ms 457 Hz sine with 5 ms
-- linear fade in / out, derived from ONI's ScannerDirectionEarcon segment
-- shape (extra 20 ms to register reliably in a cycle-keystroke context;
-- 20 percent hotter peak so the per-cycle beep punches through against
-- the spoken readout). 457 Hz sits in the middle of the +/-1 octave
-- pitch modulation so the lower-rail playback (228 Hz) stays comfortably
-- above sub-bass and the upper rail (914 Hz) stays below piercing.
-- Generated by tools/generate-scanner-beep.py and committed under
-- sounds/; the WAV ships through deploy.ps1's Sounds/ copy alongside the
-- beacon and per-hex terrain cues.
--
-- Voice allocation. One independent voice via
-- audio.load_voice_in_beacon_group so the per-voice pan / pitch /
-- volume state cannot collide with a beacon, a per-hex terrain cue, or
-- another consumer of the audio bank, AND the voice rides the beacon
-- master fader rather than the per-hex master.
-- set_loop(false) so each audio.play plays once and
-- stops at the end of the WAV; the proxy's audio.play rearms the slot
-- (stop + seek to 0 + start) so back-to-back cycle keystrokes restart
-- the beep cleanly rather than queueing or overlapping. Initial volume
-- is 0 so a stray play before the first parameter push (which shouldn't
-- happen, but) does not blast the user.
--
-- Origin choice mirrors ScannerNav.formatInstance so the beep and the
-- spoken direction always agree on what "from" they're encoding: live
-- cursor when auto-move is off (user-driven origin), snapshot origin
-- when auto-move is on (the sort anchor the snapshot was built against,
-- since the cursor has been warped to each entry by prior auto-moves).
-- The resolution stays in ScannerNav because it owns the snapshot; this
-- module takes explicit (originX, originY, targetX, targetY).
--
-- Encoding (constants match Beacons.lua):
--   * Pan = clamp(dcol / PAN_SAT_HEXES, -1, 1). PAN_SAT_HEXES = 12 hexes
--     east / west for full pan. HexGeom.displacement applies the row-
--     parity half-column offset so a NE / NW step lands at +/-0.5 pan
--     rather than 0.
--   * Pitch = 2^(drow / 12), capped at +/-PITCH_MAX_SEMITONES (= 12, one
--     octave). One semitone per row north / south.
--   * Volume = 1 - dist / BeaconRange.get(). Clamped at 0 (silent past
--     the range). The user-set beacon master attenuates this voice the
--     same way it attenuates bookmark beacons: see ScannerBeep.loadAll's
--     load_voice_in_beacon_group call below, which parents the voice
--     under the proxy's beacon mixer group. The F12 Beacon group is the
--     single point of control for this entire family of spatial audio
--     cues.
--
-- The beep does not fire from ScannerNav.jumpToEntry (Home): the cursor
-- jumps onto the entry, so displacement is 0 and the beep would carry no
-- bearing information. Returning to the pre-jump cell (Backspace) is
-- similarly skipped -- the user already knows the source cell because
-- they jumped from it.

ScannerBeep = {}

local PAN_SAT_HEXES = 12
local PITCH_MAX_SEMITONES = 12

-- Hydrate the on-off toggle on the shared table on first include. Default
-- is false: the spoken direction already conveys the bearing, so the beep
-- is an opt-in layer for users who want a pre-attentive cue. Settings.lua's
-- defineBoolPref is a no-op once this line runs; both reads go through
-- civvaccess_shared.scannerDirectionBeep so toggling in Settings takes
-- effect on the next cycle without an explicit notification path.
if civvaccess_shared.scannerDirectionBeep == nil then
    civvaccess_shared.scannerDirectionBeep = Prefs.getBool("ScannerDirectionBeep", false)
end

local function clamp(v, lo, hi)
    if v < lo then
        return lo
    end
    if v > hi then
        return hi
    end
    return v
end

-- Allocate the one voice. Idempotent across re-entry (Civ V re-runs the
-- WorldView Boot on load-from-game) because the proxy's audio bank slots
-- survive across game transitions; civvaccess_shared.scannerBeepHandle is
-- the install-once guard, mirroring Beacons.loadAll. Logs once at boot so
-- a failure (audio binding missing, bank full) is visible in Lua.log.
function ScannerBeep.loadAll()
    if civvaccess_shared.scannerBeepHandle ~= nil then
        return
    end
    if audio == nil then
        Log.warn("ScannerBeep.loadAll: audio binding missing")
        return
    end
    local h = audio.load_voice_in_beacon_group("scanner_beep")
    if h == nil then
        Log.error("ScannerBeep.loadAll: load_voice_in_beacon_group returned nil")
        return
    end
    -- Non-looping: each audio.play plays the WAV through once and stops.
    -- Initial volume 0 so a stray play before the first parameter push
    -- can't surprise the user.
    audio.set_loop(h, false)
    audio.set_volume(h, 0)
    civvaccess_shared.scannerBeepHandle = h
    Log.info("ScannerBeep.loadAll: loaded")
end

-- Fire the beep encoding (originX, originY) -> (targetX, targetY). No-op
-- when the toggle is off, when the audio binding / handle is missing, or
-- when origin coordinates are unavailable (caller resolved a nil cursor).
-- Math mirrors Beacons.updateBeaconParams; see the constants block above
-- for the saturation thresholds and falloff shape.
function ScannerBeep.play(originX, originY, targetX, targetY)
    if civvaccess_shared.scannerDirectionBeep ~= true then
        return
    end
    if audio == nil then
        return
    end
    local h = civvaccess_shared.scannerBeepHandle
    if h == nil then
        return
    end
    if originX == nil or originY == nil or targetX == nil or targetY == nil then
        return
    end
    -- Silent when the readout origin already sits on the entry's plot.
    -- Mirrors formatInstance's "here" speech branch: with no displacement
    -- the beep carries no directional information, and a centered full-
    -- volume tone on every cycle while the cursor sits on the entry would
    -- be a redundant ping the user did not ask for. End-key probe path
    -- (distanceFromCursor) short-circuits to SCANNER_HERE before reaching
    -- this function, so this guard is the cycle-path equivalent.
    if originX == targetX and originY == targetY then
        return
    end
    local dcol, drow = HexGeom.displacement(originX, originY, targetX, targetY)
    local pan = clamp(dcol / PAN_SAT_HEXES, -1, 1)
    local semitones = clamp(drow, -PITCH_MAX_SEMITONES, PITCH_MAX_SEMITONES)
    local pitchRate = 2 ^ (semitones / 12)
    local dist = Map.PlotDistance(originX, originY, targetX, targetY)
    local maxDist = BeaconRange.get()
    local vol = 1 - dist / maxDist
    if vol < 0 then
        vol = 0
    end
    audio.set_pan(h, pan)
    audio.set_pitch(h, pitchRate)
    audio.set_volume(h, vol)
    audio.play(h)
end
