-- Mod-authored great work descriptions, it_IT overlay.
-- Baseline in CivVAccess_GreatWorkDescStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_MISSING"] = "Nessuna descrizione dell'immagine per quest'opera d'arte."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LITERATURE"] =
    "Una scrivania da scrittore vista da vicino, illuminata da una luce fioca e calda di candele. Fogli di manoscritto scritti a mano in corsivo fluente ricoprono la superficie, con una singola penna d'oca grigia posata di traverso su di essi. Un rotolo avvolto e legato con un nastro rosso si trova sul bordo sinistro, e un calamaio di vetro brilla in alto a destra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MUSIC"] =
    "Una sala da concerto fiocamente illuminata dalla luce calda delle candele. Al centro un direttore d'orchestra in abito blu e calze bianche sta con la bacchetta alzata, rivolto a un'orchestra seduta di musicisti in parrucche incipriate che leggono i spartiti sui leggii. Una galleria superiore dorata intagliata con pannelli a rilievo corre sulla parete di fondo e un grande lampadario a candele arde a destra, mentre le teste del pubblico appaiono come forme scure in primo piano."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIRL_WITH_PEARL_EARRING"] =
    "Dipinto a olio del secolo d'oro olandese, uno dei ritratti più amati dell'arte occidentale. Una giovane donna si volta indietro sopra la spalla per incontrare il tuo sguardo da uno sfondo scuro e spoglio, le labbra appena schiuse come se stesse per parlare. Indossa un turbante blu e oro la cui stoffa le scende lungo la schiena, e un'unica grande perla a goccia coglie la luce all'orecchio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HENRY_VIII"] =
    "Ritratto di corte Tudor a olio, l'immagine che ha fissato il modo in cui il mondo immagina Enrico VIII. Il re sta in piedi rivolto verso di te a figura intera, i piedi piantati ben divaricati, dalle spalle larghe e dal corpo massiccio, una mano poggiata su un pugnale alla cintura. Indossa un farsetto d'argento ingioiellato sotto un soprabito cremisi foderato di pelliccia, un berretto piatto piumato e catene d'oro, in piedi su un tappeto a motivi tra colonne di marmo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HUNTERS_IN_THE_SNOW"] =
    "Dipinto a olio del Rinascimento fiammingo, un paesaggio invernale visto dalla cima di una collina. Tre cacciatori stanchi e la loro muta di cani arrancano nella neve profonda in primo piano, le teste chine, con una sola volpe a mostrare il frutto della caccia. Sotto di loro un villaggio si distende sotto un cielo grigio-verde, con minuscoli pattinatori che giocano su stagni ghiacciati e cime frastagliate che si innalzano in lontananza."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LES_DEMOISELLES"] =
    "Dipinto a olio del primo modernismo, la tela che diede avvio al Cubismo. Cinque donne nude stanno in piedi e sedute in uno spazio poco profondo di piani frastagliati rosa, bianchi e blu, i loro corpi spezzati in forme angolari e taglienti. I due volti a destra sono dipinti come maschere africane, striati e deformati, mentre gli altri fissano dritto davanti a sé con grandi occhi a mandorla; una piccola coppa di frutta sta sul bordo inferiore."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LUNCHEON"] =
    "Dipinto a olio dell'Impressionismo francese, amici che si attardano dopo un pasto. Un gruppo vivace in abiti estivi affolla un balcone in riva al fiume sotto una tenda a strisce arancioni e bianche, parlando, civettando e appoggiandosi alla ringhiera; una giovane donna in primo piano gioca con un cagnolino. La tavola è disseminata di bottiglie di vino, bicchieri e frutta, tutto dipinto con caldi e liberi tocchi di colore illuminato dal sole."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MONA_LISA"] =
    "Olio su tavola di legno del Rinascimento italiano, probabilmente il ritratto più famoso del mondo. Una donna siede con le mani intrecciate, leggermente voltata verso di te, contro un paesaggio velato di fiumi tortuosi e lontane montagne azzurre. I suoi occhi incontrano i tuoi direttamente, il celebre sguardo che sembra seguirti ovunque ti trovi. Il suo lieve mezzo sorriso è il fulcro del dipinto, reso in morbidi marroni e verdi senza contorni netti, così che la sua espressione sembra mutare quanto più a lungo la guardi."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUNDAY_AFTERNOON"] =
    "Dipinto a olio puntinista, costruito interamente con minuscoli punti di colore puro. Parigini nei loro abiti della domenica si rilassano su un prato soleggiato in riva al fiume, passeggiando con i parasoli, oziando sull'erba e portando a spasso cagnolini, con barche a vela sull'acqua dietro di loro. Tutti sono stranamente immobili e composti, come figure di un fregio, la luce scomposta in un brulichio di puntini verdi, arancioni e violetti."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VIEW_OF_TOLEDO"] =
    "Dipinto a olio del Rinascimento spagnolo, uno dei primi paesaggi puri dell'arte occidentale e insolitamente cupo. La città spagnola di Toledo, sulle colline, si innalza in lontananza sotto un cielo di tempesta violenta, le sue guglie e mura grigie illuminate da una luce argentea inquietante. Verdi colline degradano verso un fiume in primo piano, l'intera scena dipinta in verdi profondi e neri bluastri che sembrano più sogno che luce del giorno."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WATER_LILIES"] =
    "Dipinto a olio dell'Impressionismo francese, dalla celebre serie di Monet dedicata allo stagno del suo giardino a Giverny. L'intera tela è la superficie dell'acqua, senza orizzonte né riva: distese di foglie di ninfea verdi galleggiano su un'acqua blu e lavanda punteggiata di fiori rosa e rossi. Nuvole e alberi compaiono solo come morbidi riflessi, la pennellata abbastanza libera da far sembrare che tutto fluttui."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_STARRY_NIGHT"] =
    "Dipinto a olio post-impressionista, una delle immagini più riconoscibili dell'arte moderna. Un cielo notturno animato dal movimento riempie quasi tutta la tela: le stelle ardono dentro aloni vorticosi, e la luna brucia arancione in un angolo mentre una grande corrente a spirale percorre il centro del cielo. In basso, un quieto villaggio con un campanile a punta dorme tra le colline, e un cipresso scuro si leva come una fiamma lungo il bordo sinistro, tutto in spesse e visibili pennellate di blu e oro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BIRTH_OF_VENUS"] =
    "Dipinto del Rinascimento italiano della dea dell'amore che arriva dal mare, tra le immagini più famose del mito classico. Venere sta nuda in piedi su una gigantesca conchiglia a ventaglio, coprendosi con le mani e con una cascata di lunghi capelli dorati. A sinistra due divinità alate del vento la sospingono verso la riva attraverso una pioggia di rose rosa, mentre a destra una donna in abito a fiori accorre per avvolgerla in un mantello svolazzante."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BINDO_ALTOVITI"] =
    "Ritratto a olio dell'alto Rinascimento italiano di un giovane e ricco banchiere romano. Un bel giovane dai lunghi capelli dorati e dal berretto nero ti guarda voltandosi sopra la spalla nuda, una mano portata al petto. Indossa un mantello blu sopra una veste nera, e il suo volto pallido risplende contro uno sfondo verde profondo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_DRAGON"] =
    "Dipinto del primo Rinascimento italiano, con il fascino rigido e fiabesco di una favola. A destra, un cavaliere in armatura su un cavallo bianco impennato conficca la lancia nelle fauci spalancate di un drago verde alato dalle ali maculate simili a quelle di una falena. A sinistra una principessa serena in una lunga veste rosa tiene la bestia ferita al guinzaglio come un animale domestico, davanti alla sua caverna scura, mentre una strana tempesta a spirale si addensa dietro il cavaliere."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CREATION_OF_ADAM"] =
    "Affresco del Rinascimento italiano dalla volta della Cappella Sistina, origine di uno dei gesti più famosi dell'arte. Un Adamo nudo è adagiato su una collina verde a sinistra, un braccio teso languidamente, mentre Dio, una figura dalla barba grigia avvolta in un sudario color rosa svolazzante e pieno di angeli, irrompe da destra. I loro indici tesi si protendono l'uno verso l'altro attraverso un piccolo spazio vuoto, l'istante prima della scintilla della vita."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GALLERY_OF_THE_LOUVRE"] =
    "Dipinto a olio americano di una galleria all'interno del Louvre, opera dello stesso Morse che in seguito inventò il codice del telegrafo. Un grande salone dalle pareti rosse è coperto dal pavimento al soffitto da decine di dipinti di antichi maestri in cornici dorate, tra cui una minuscola Monna Lisa. In primo piano, alcuni studenti d'arte siedono a copiare ai cavalletti mentre il loro maestro si china sopra la spalla di una giovane donna per correggerne il lavoro, e un corridoio ad arco di ulteriori gallerie si apre in lontananza."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WASHINGTON_CROSSING"] =
    "Eroico dipinto a olio di storia americana, un'icona della guerra d'indipendenza. Il generale Washington sta in piedi eretto a prua di una barca a remi affollata mentre i suoi soldati spingono e remano attraverso un fiume ingombro di lastre di ghiaccio, e un ufficiale dietro di lui regge alta la bandiera americana. La luce dell'alba squarcia la fredda foschia, e altre barche cariche di uomini e cavalli seguono alle spalle."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ARRANGEMENT_IN_GREY"] =
    "Dipinto a olio americano universalmente noto come La madre di Whistler. Un'anziana donna in un lungo abito nero e una cuffia di pizzo bianco siede in rigoroso profilo, rivolta a sinistra, le mani in grembo e i piedi su un piccolo poggiapiedi. La stanza è austera e piatta: una parete grigia, una scura tenda a motivi, e un solo quadro incorniciato, l'intera composizione equilibrata come uno studio in grigio e nero, esattamente come dice il titolo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BREEZING_UP"] =
    "Dipinto a olio realista americano di una piccola barca a vela al largo della costa del New England, intitolato Breezing Up (Vento a favore). Un uomo e tre ragazzi si sporgono all'indietro in una piccola barca a vela di nome Gloucester mentre questa si inclina sotto una brezza vigorosa, gli spruzzi che si infrangono sulla prua e il pescato della giornata ammucchiato ai loro piedi. Il mare è di un verde mosso sotto nuvole sparse, con una goletta a due alberi all'orizzonte."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_THOUSAND_LI"] =
    "Rotolo orizzontale di paesaggio cinese in azzurro e verde, intitolato Mille Li di fiumi e montagne, dipinto su seta da un prodigio adolescente della corte Song e lungo quasi dodici metri. Montagne di un vivido blu e verde minerale si ergono cresta dopo cresta da un placido fiume dorato, con minuscoli villaggi, ponti e alberi spogli annidati tra i pendii. Colonne di calligrafia pennellata e rossi sigilli di collezionisti riempiono il cielo sopra le vette."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DWELLING_IN_THE_FUCHUN"] =
    "Rotolo orizzontale a inchiostro cinese, intitolato Abitazione tra le montagne del Fuchun, un capolavoro della pittura paesaggistica dei letterati di epoca Yuan eseguito interamente in toni di inchiostro nero su carta. Montagne arrotondate costruite con pennellate secche e stratificate si ergono sopra un ampio fiume calmo, con pini, casolari sparsi e barche da pesca lungo le rive. L'atmosfera è tranquilla e contemplativa, la carta punteggiata di rossi sigilli di collezionisti accumulati nei secoli dagli ammiratori."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ALONG_THE_RIVER"] =
    "Rotolo orizzontale cinese di epoca Song su seta, intitolato Lungo il fiume durante la festa di Qingming, un famoso panorama della vita cittadina quotidiana lungo oltre cinque metri. La sezione mostrata è incentrata sulla grande porta cittadina della capitale, una massiccia torre di legno in cima a un bastione in pendenza, con le strade sottostanti brulicanti di vita: bancarelle del mercato, carri trainati da buoi, una carovana di cammelli che passa attraverso la porta, e portatori che reggono carichi su bilancieri appoggiati alle spalle. Ogni figura è minuscola ma resa con precisione in fine tratto a inchiostro con toni terrosi smorzati."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LEAF_2"] =
    "Foglio d'album cinese di epoca Qing, intitolato Foglia 2 (Dipinti di dame), pittura di corte in fine tratto e colore delicato. Eleganti dame in lunghe vesti fluenti di bianco, verde e blu si riuniscono in un padiglione da giardino drappeggiato di tessuto azzurro vivo, una di esse intenta a bruciare incenso a un tavolo dietro una ringhiera rossa. Intorno a loro vi sono rocce da giardino, bambù, e una vite fiorita che si arrampica sul tetto del padiglione."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EMPEROR_TAIZONG"] =
    "Rotolo orizzontale cinese di epoca Tang su seta, intitolato L'imperatore Taizong riceve l'inviato tibetano, una cronaca di corte di un incontro diplomatico. A destra, l'imperatore Taizong siede su una piattaforma portata da dame di palazzo che reggono anche due grandi ventagli e un baldacchino rosso sopra di lui. A sinistra, tre figure più piccole si avvicinano in pose deferenti: un cerimoniere di corte in rosso, l'inviato tibetano in una veste a motivi, e un interprete in bianco, tutti su una calda seta dorata coperta di sigilli rossi."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SPRING_MORNING"] =
    "Rotolo orizzontale cinese di epoca Ming su seta, intitolato Mattina di primavera nel palazzo di Han, un lungo panorama di donne di palazzo in ozio in una mattina di primavera. Decine di eleganti dame riempiono sale aperte, verande e cortili: fanno musica, dipingono un ritratto, giocano con i bambini, e passeggiano tra salici, rocce da giardino e perfino pavoni. L'architettura del palazzo corre per tutta la lunghezza del rotolo in caldi rossi e verdi, ogni paravento, ringhiera e veste resi in un meticoloso dettaglio dal tratto fine."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_GREAT_WAVE"] =
    "Stampa giapponese ukiyo-e da matrice xilografica, intitolata La grande onda di Kanagawa, l'immagine più famosa in assoluto dell'arte giapponese. Un'enorme onda di un blu intenso si erge a sinistra e si arriccia sopra l'intera scena, la sua cresta che si spezza in dita di schiuma bianca simili ad artigli. Sotto di essa, tre lunghe barche aperte piene di rematori cavalcano gli avvallamenti, e lontano sullo sfondo, piccolo al centro di tutto, si erge il cono innevato del Monte Fuji."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EVENING_SHOWER"] =
    "Stampa giapponese ukiyo-e da matrice xilografica, intitolata Acquazzone ad Atake e il grande ponte, una delle scene di pioggia più ammirate mai realizzate. Un improvviso scroscio, reso come fitte cortine di sottili linee oblique, sorprende le persone a metà di un lungo ponte di legno; esse si affrettano in entrambe le direzioni sotto cappelli e ombrelli, una riparandosi sotto una stuoia di paglia. Il fiume sottostante è una fascia color verde acqua con un solitario zatteriere che lo attraversa spingendosi col remo, e la riva opposta sfuma in una macchia scura sotto il temporale."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_L_ABSINTHE"] =
    "Dipinto a olio impressionista francese, intitolato L'Absinthe, una scena impietosa della vita dei caffè parigini. Una donna in abito e cappello chiari siede curva a un tavolino di caffè in marmo, gli occhi bassi, un bicchiere di assenzio di un verde lattiginoso davanti a lei; accanto a lei un uomo barbuto in un cappotto sgualcito fissa lontano verso destra con una pipa in bocca. I due siedono insieme eppure del tutto separati, dipinti in spenti grigi e bruni che recano l'aria di solitudine del quadro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_UPAUPA_SCHNEKLUD"] =
    "Ritratto a olio postimpressionista di un violoncellista nel mezzo di un'esecuzione, intitolato Upaupa Schneklud. Il musicista si china sul suo violoncello di un acceso rosso arancio, gli occhi abbassati nella concentrazione, il braccio dell'archetto che spazza le corde, il suo abito blu scuro a incorniciare il bagliore dello strumento. Dietro di lui lo sfondo si divide in zone piatte di bruno e verde muschio sparse di pallide forme astratte, nello stile cromatico audace e semplificato di Gauguin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_A_BAR_AT_THE_FOLIES"] =
    "Dipinto a olio francese di vita moderna, l'ultima grande opera di Manet. Una barista in un corpetto di velluto nero con un fiore al petto sta dietro un bancone di marmo affollato di bottiglie di champagne, una coppa di arance e un bicchiere con una rosa, e guarda davanti a sé con un'espressione stanca e assente. Dietro di lei un enorme specchio riflette lo scintillante music hall, i suoi lampadari e la folla, e, stranamente spostata sulla destra, la sua stessa schiena mentre si china verso un uomo con il cilindro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BALL_AT_THE_MOULIN"] =
    "Dipinto a olio post-impressionista della vita notturna parigina nel celebre cabaret. Un gruppo di uomini con il cilindro e di donne con cappelli piumati siede attorno a un tavolo con dei drink, mentre alle loro spalle una donna dai capelli rossi si sistema l'acconciatura nella sala da ballo illuminata di verde. Il viso di una donna incombe sul bordo destro, illuminato dal basso di un verde spettrale, e una lunga ringhiera diagonale taglia il primo piano nello stile da manifesto di Lautrec."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS"] =
    "Dipinto a olio viennese in stile Art Nouveau stratificato con vera foglia d'oro, l'opera più famosa di Klimt. Una coppia è inginocchiata stretta in un abbraccio su un prato fiorito, mentre l'uomo si china a baciare la guancia della donna e lei inclina il viso all'insù con gli occhi chiusi. I loro corpi si fondono in un unico manto dorato, con motivi a rettangoli per lui e a cerchi luminosi per lei, che risplende contro un piatto e scintillante sfondo d'oro."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AMERICAN_GOTHIC"] =
    "Dipinto a olio del Regionalismo americano, infinitamente parodiato e immediatamente riconoscibile. Un contadino severo e stempiato, con occhiali tondi e una salopette di denim, sta in piedi reggendo dritto un forcone a tre rebbi, con al suo fianco una donna in un grembiule scuro a stampa che guarda altrove con una smorfia di disapprovazione. Dietro di loro c'è la casa colonica bianca che dà il nome al dipinto, con una finestra gotica ad arco acuto nel suo frontone."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SRI_SHANMUKAHA"] =
    "Dipinto devozionale indiano nello stile accademico europeo che Ravi Varma rese celebre in tutta l'India. Il dio indù Murugan cavalca la sua cavalcatura, un pavone, con sei teste coronate e molte braccia che reggono armi, affiancato dalle sue due consorti in sari rosa acceso. La coda del pavone si apre alle loro spalle come un gigantesco ventaglio di occhi verdi e oro, mentre l'uccello tiene inchiodato un cobra sotto le zampe."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DAUD_RECEIVES_A_ROBE"] =
    "Miniatura moghul tratta da una cronaca imperiale illustrata, ad acquerello opaco e oro su carta. Il particolare mostrato è incentrato su un giovane e snello attendente in una veste chiara, berretto rosso e fascia dorata, che porta la veste onorifica dorata ripiegata per la cerimonia di presentazione. Sta in piedi contro una sfolgorante parete di tenda blu coperta di delicati tralci fioriti, ogni piega e ogni fiore dipinti con precisione miniaturistica."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YUSEF_AND_ZULEYKHA"] =
    "Miniatura persiana tratta da un manoscritto illustrato, l'opera più celebre del grande maestro di Herat Behzad. La pagina è riempita da un intricato palazzo visto in spaccato appiattito, un labirinto di scale, balconi e porte rivestiti di piastrelle blu, arancio e oro. In una camera superiore il profeta Yusef, aureolato di fiamma, fugge dalla presa protesa di Zuleykha, mentre pannelli di calligrafia persiana incorniciano l'architettura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ASCENT_OF_MUHAMMAD"] =
    "Miniatura persiana tratta da un manoscritto reale, che raffigura il viaggio notturno del Profeta attraverso i cieli. Maometto, con il viso velato di bianco e cinto di fiamma dorata, cavalca il destriero dalla testa umana Buraq attraverso un cielo blu profondo cosparso di nubi ondeggianti orlate d'oro. Angeli in vesti rosse, verdi e arancioni gli volteggiano intorno da ogni lato recando doni e incensieri, con versi di poesia persiana a incorniciare la scena."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LIBERTY_LEADING_THE_PEOPLE"] =
    "Dipinto a olio del Romanticismo francese, l'immagine per eccellenza della rivoluzione. La Libertà stessa, una donna dal seno scoperto in un abito giallo e un berretto rosso, avanza a grandi passi su una barricata di macerie e di corpi caduti, levando la bandiera tricolore francese verso il cielo fumoso. Intorno a lei si accalcano cittadini armati di ogni ceto, tra cui un gentiluomo con il cilindro e un moschetto e un ragazzo che agita due pistole."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_JEROME_IN_HIS_STUDY"] =
    "Dipinto a olio del primo Rinascimento di notevole precisione miniaturistica. Visto attraverso una grande arcata di pietra, San Girolamo in veste rossa siede a leggere in uno studio di legno costruito come un palcoscenico dentro uno spazio di cattedrale a volta, circondato da scaffali di libri e da vasi. La luce entra a fiotti dalle finestre su ogni lato, un pavone e una pernice si posano sulla soglia davanti, e il suo leone si aggira nell'ombra sulla destra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PARTHENON_FRIEZE"] =
    "Dipinto a olio vittoriano che immagina l'antica Atene; nel gioco quest'opera accompagna la meraviglia del Partenone. Lo scultore Fidia sta su un'impalcatura di legno accanto al suo fregio marmoreo di cavalieri appena dipinto, ancora nei colori di bottega, e trattiene una fune mentre lo presenta. Un piccolo gruppo di ateniesi in vesti drappeggiate, tra cui Pericle, si china ad ammirare l'intaglio alla calda luce all'interno del tempio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUE_DE_PARIS"] =
    "Dipinto a olio realista francese della Parigi moderna in una giornata piovigginosa, nitido e fotografico là dove i suoi amici impressionisti erano sciolti. Una coppia ben vestita che condivide un ombrello passeggia verso di te su ciottoli luccicanti, l'uomo con il cilindro e la donna in un lungo abito scuro con un orecchino che cattura la luce. Intorno a loro altri passanti con l'ombrello attraversano un ampio incrocio fiancheggiato da palazzi grigi a cuneo, con un lampione verde che divide la scena nel mezzo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_NIGHT_WATCH"] =
    "Dipinto a olio del Secolo d'oro olandese di enorme scala, il più famoso ritratto di gruppo mai realizzato. Una compagnia di milizia cittadina irrompe in movimento fuori da un'ombra profonda: il capitano in nero con una fascia rossa avanza dando un ordine al suo luogotenente in oro chiaro, mentre alle loro spalle si caricano i moschetti, si leva uno stendardo e un tamburino batte il tempo. Una bambina in un abito dorato e luminoso brilla misteriosamente tra la folla, illuminata come da un riflettore nella penombra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DEATH_OF_MARAT"] =
    "Dipinto a olio del Neoclassicismo francese, la grande immagine del martire della Rivoluzione francese. Il giornalista rivoluzionario Marat giace morto nella sua vasca da bagno, accasciato come un santo caduto, il capo avvolto in un turbante bianco e un braccio che pende fino al pavimento tenendo ancora la sua penna. Nell'altra mano c'è la lettera con cui la sua assassina ottenne di entrare; la metà superiore della tela è nuda parete scura, e la semplice cassa di legno accanto a lui reca la dedica dipinta \"A Marat, David.\""
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ETIENNE_CHEVALIER"] =
    "Dipinto su tavola francese del tardo Medioevo, una delle ante di un celebre dittico devozionale. Il tesoriere reale Etienne Chevalier è inginocchiato in una ricca veste rossa, le mani giunte in preghiera, presentato dal suo patrono santo Stefano, che gli sta accanto in un paramento azzurro e oro. Il santo regge un libro sormontato da una pietra dai bordi frastagliati, simbolo del suo martirio, ed entrambi si trovano in una sala di marmo bianco, con il nome del donatore inciso lungo la parete."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_FRANCIS"] =
    "Dipinto a olio barocco spagnolo di severa devozione monastica. San Francesco sta in piedi da solo in un semplice saio incappucciato color sabbia, il viso per metà perso nell'ombra profonda del cappuccio, gli occhi abbassati in preghiera. Tiene tra le mani un teschio umano come monito della morte, illuminato da un'unica luce dura su uno sfondo quasi nero."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HATAORI"] =
    "Stampa giapponese ukiyo-e da matrice di legno di una tessitrice al lavoro. Una giovane donna in un kimono a fantasia color indaco siede a piedi nudi a un grande telaio a mano in legno, alzando lo sguardo dal lavoro con una spola in una mano, fili rossi, blu e bianchi tesi per tutta la lunghezza della macchina. I colori sono morbidi crema e blu attenuati, con una colonna di poesia tracciata a pennello che riempie l'angolo in alto a sinistra del foglio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JANE_GREY"] =
    "Dipinto storico accademico francese, teatrale e straziante. La giovane regina, bendata e vestita di raso bianco che risplende contro la scura camera di pietra, è inginocchiata e cerca a tentoni il ceppo del boia, mentre un anziano funzionario le guida con delicatezza le mani verso di esso. Le sue dame crollano nel dolore contro un pilastro alle sue spalle, e il boia attende sulla destra, appoggiato alla sua ascia con lo sguardo distolto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_WANDERER"] =
    "Dipinto a olio romantico tedesco, l'immagine per eccellenza dell'uomo solo davanti alla natura. Un giovane in una redingote verde scuro sta in piedi di spalle a te su una cima rocciosa, appoggiato a un bastone da passeggio, i capelli mossi dal vento. Sotto di lui un oceano di nebbia bianca inghiotte la valle, e solo creste e rupi affiorano come isole, mentre pallide montagne svaniscono in lontananza."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BABEL"] =
    "Dipinto a olio rinascimentale fiammingo della torre condannata della Bibbia, brulicante di particolari. Una colossale torre a spirale di archi, in parte di pietra bianca e in parte di nudo mattone rosso, sale storta tra le nuvole, la sommità ancora grezza e incompiuta. Attorno alla sua base si estende una città portuale con navi all'ancora, e in primo piano un re ispeziona una squadra di scalpellini inginocchiati ai suoi piedi tra i loro blocchi."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_YOUNG_LADY"] =
    "Ritratto a olio dei primi Paesi Bassi, piccolo, immobile e stranamente moderno. Una pallida giovane donna dal viso liscio come porcellana ti guarda di sbieco da sotto un alto copricapo di velluto nero bordato d'oro. Indossa un abito blu con un colletto di pelliccia bianca e una stretta collana di fasce d'oro e nere, posta contro una semplice parete fioca anziché il consueto buio vuoto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_KINDRED"] =
    "Dipinto a olio americano della Hudson River School, un omaggio all'amicizia tra un pittore e un poeta. Due uomini in cappotto stanno in piedi a conversare su un ripiano roccioso che sporge su una gola boscosa nelle montagne dei Catskill, uno dei due che indica la veduta con un pennello. Sotto, un ruscello scorre tumultuoso sulle rocce, incorniciato da un arco di alberi sporgenti, con vette nebbiose che si dissolvono in una luce dorata sullo sfondo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_BLUE_BOY"] =
    "Ritratto a olio inglese in stile Grand Manner, l'opera più famosa dell'artista. Un ragazzo di circa dodici anni sta in piedi a figura intera in un luccicante abito di raso blu con calzoni al ginocchio e un colletto di pizzo, una mano sul fianco, l'altra che regge un cappello piumato al suo lato. Guarda fuori con disinvolta sicurezza da un paesaggio scuro e tempestoso color bruno che fa avvampare il costume blu."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SECOND_OF_MAY"] =
    "Dipinto a olio spagnolo, una delle prime e più grandi proteste contro la guerra nell'arte. Alla luce di una lanterna, un plotone d'esecuzione francese sta schierato in una fila senza volto, i fucili puntati contro un gruppo di prigionieri spagnoli ammassati su una collina spoglia fuori Madrid. Al centro un uomo in camicia bianca spalanca le braccia davanti ai fucili, inginocchiato tra i corpi di chi è già stato fucilato, la posa che richiama una crocifissione."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_CART"] =
    "Dipinto a olio militare francese della guerra franco-prussiana, una celebre immagine di estrema resistenza di sfida. Una manciata di soldati francesi difende la casa devastata di un villaggio, sparando da una finestra mentre i feriti siedono accasciati contro le pareti e un ufficiale conta le loro ultime munizioni. La stanza è a pezzi, una porta strappata dai cardini, l'intonaco che cade dal soffitto, la luce del giorno che inonda l'ingresso dove i commilitoni continuano a combattere."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EARLY_AUTUMN"] =
    "Rotolo orizzontale cinese a inchiostro e colori tenui, uno studio ravvicinato di natura su uno stagno di loto che appassisce. Libellule rosse, verdi e blu volteggiano sopra canne secche e foglie di loto sfrangiate, mentre cavallette, un'ape e piccole rane si occupano delle loro faccende più in basso. L'atmosfera è di delicata decadenza, la vita dell'estate che prosegue tra piante che hanno appena iniziato ad avvizzire, con rossi sigilli di collezionisti lungo entrambi i bordi."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_APPRECIATING_LOTUSES"] =
    "Rotolo verticale giapponese a inchiostro e colori del fondatore della scuola Kano, dipinto nella maniera del paesaggio cinese degli eruditi. Un erudito cinese in veste fluttua su una piccola barca al bordo di uno stagno di loto, contemplando le foglie galleggianti sotto un salice nodoso che si protende dalla riva rocciosa. La maggior parte dell'alto rotolo è foschia e acqua aperta, con poche cime di pini che svaniscono nella bruma."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_EQUESTRIAN_PORTRAIT"] =
    "Dipinto a olio rinascimentale veneziano, il modello per secoli di sovrani a cavallo. Il Sacro Romano Imperatore esce a cavallo da un bosco scuro in una scintillante armatura completa con un elmo dal pennacchio rosso, la lancia in pugno, a commemorazione della sua vittoria a Muhlberg. Il suo cavallo nero è coperto di cremisi, e un basso sole della sera filtra oro e rosa sotto pesanti nubi tempestose."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ARMADA"] =
    "Ritratto di propaganda dei Tudor a olio, dipinto per celebrare la sconfitta dell'Invincibile Armada. La regina Elisabetta siede in un'immensa veste di perle e fiocchi, il viso incorniciato da un'ampia gorgiera di pizzo bianco, una mano posata in atto di possesso su un globo con le dita sulle Americhe. Attraverso le finestre alle sue spalle la vicenda si svolge due volte: la flotta inglese in un mare calmo da un lato, le navi spagnole naufragate in una tempesta dall'altro. La sua corona ingioiellata è posata accanto a lei."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRANCIS_I"] =
    "Ritratto regale rinascimentale francese a olio. Il re ti guarda di fronte dalla vita in su in uno spettacolare abito di corte, maniche tagliuzzate di raso bianco e oro rigato di nero, una catena d'oro sul petto e in testa un berretto nero con un pennacchio bianco. Il suo viso barbuto, scaltro e dal naso lungo, risalta contro uno sfondo di damasco cremisi decorato a corone."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SELF_PORTRAIT"] =
    "Autoritratto a olio del manierismo nordico, opera del pittore di corte fiammingo dell'imperatore Rodolfo II. L'artista ti guarda voltandosi sopra la spalla, un uomo robusto e barbuto dai capelli ricci sotto un morbido berretto nero, che indossa un colletto bianco arricciato sopra un farsetto grigio-azzurro. La resa è calda e diretta contro uno sfondo bruno uniforme, e il suo sguardo di lato indagatore ti trattiene."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_VERTUMNUS"] =
    "Dipinto a olio manierista, la più celebre delle teste composite fantastiche dell'Arcimboldo. È un ritratto dell'imperatore Rodolfo II nei panni di Vertumno, il dio romano delle stagioni, con l'intero volto e il petto assemblati da frutta, ortaggi e fiori: palpebre di baccelli di pisello, un naso a pera, labbra di ciliegia, baffi di spighe di grano e capelli d'uva. Da lontano è un sovrano dignitoso; da vicino si dissolve in un banco di mercato, tutto contro uno sfondo nero."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_SUPPER"] =
    "Dipinto a olio veneziano del tardo Rinascimento che reinventa la scena familiare. Invece di porsi frontalmente davanti a te, la tavola dell'ultima Cena precipita in una ripida diagonale verso una sala buia di taverna, con il Cristo che risplende a metà della sua lunghezza mentre offre il pane agli apostoli. I servi trasportano le vivande e un gatto fruga in un cesto in primo piano, mentre una fiammeggiante lampada a olio riempie l'aria fumosa in alto di angeli traslucidi che turbinano."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_A_MAN"] =
    "Dipinto a olio dei primitivi fiamminghi, forse il volto dell'artista stesso e uno dei primi veri autoritratti. Un uomo di mezza età, dal viso segnato e dallo sguardo acuto, ti guarda dritto dall'ombra profonda, indossando uno stravagante copricapo rosso avvolto e annodato in pieghe scultoree. Il dettaglio è fine come un ago, ogni ruga e ogni pelo della barba colti, con la figura in una scura veste bordata di pelliccia contro uno sfondo nero."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FRONT_OF_THE_MIRROR"] =
    "Dipinto a olio del Rinascimento veneziano, il sereno capolavoro tardo dell'anziano Bellini. Una giovane donna nuda dai capelli ramati siede su un panno rosso, sistemandosi con calma i capelli mentre regge un piccolo specchio a mano, e un secondo specchio rotondo sulla parete dietro riflette il retro del suo copricapo decorato. Una finestra accanto a lei si apre su una verde campagna con lontane montagne azzurre sotto un cielo nuvoloso."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ADORATION"] =
    "Affresco italiano delle origini, dalla Cappella degli Scrovegni, opera del pittore a cui si attribuisce l'aver riportato il sentimento umano naturale nell'arte occidentale. Sotto una tettoia di legno, Maria regge il Cristo bambino mentre il più anziano dei tre re si inginocchia a baciare i piedi del bimbo, la corona deposta da parte; i cammelli attendono a sinistra. Sopra la stalla una cometa solca il cielo blu profondo al posto della consueta stella, tutto reso nelle figure solide e semplici e nei colori chiari di Giotto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUBENS_AND_ISABELLA"] =
    "Dipinto a olio del barocco fiammingo, il ritratto di nozze dell'artista con se stesso e la sua sposa. La giovane coppia siede stretta insieme sotto un cespuglio di caprifoglio, la mano destra di lei posata teneramente sopra quella di lui, il quieto centro del dipinto. Lui siede più in alto di lei in un farsetto nero con una gamba accavallata, lei si inginocchia in una gonna viola, corpetto ricamato d'oro, ampia gorgiera e alto cappello di paglia, entrambi rivolti fuori con calmo appagamento."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CHILDS_BATH"] =
    "Dipinto a olio impressionista americano di tenerezza quotidiana, influenzato dalle stampe giapponesi nel suo punto di vista dall'alto e nei motivi piatti. Una madre in un abito a righe decise tiene in grembo un bambino avvolto in un asciugamano, lavando i piedini del piccolo in un catino d'acqua. Le due teste si chinano insieme sul compito, e la stanza intorno a loro è un mosaico di motivi: carta da parati a fiori, cassa dipinta, tappeto ornato e una brocca bianca."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_CARD_PLAYERS"] =
    "Dipinto a olio postimpressionista, uno di una celebre serie su questo soggetto. Due contadini con il cappello siedono uno di fronte all'altro a un piccolo tavolo di legno, assorti nelle loro carte, con un'unica bottiglia di vino in piedi tra loro come centro immobile della composizione. Uno fuma la pipa; il colore è steso in pennellate pazienti e squadrate di bruno terroso, ocra e violetto attenuato che rendono le figure scolpite e permanenti."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_SWING"] =
    "Dipinto a olio rococò francese, frivolo, segreto, e l'immagine più famosa dell'epoca. In un lussureggiante giardino incolto, una giovane donna in un vaporoso abito rosa si dondola alta su un'altalena a corde, scalciando una pantofola in aria, mentre un anziano nascosto tira le corde dall'ombra alle sue spalle. Il suo giovane amante è sdraiato tra i cespugli di rose in basso, collocato perfettamente per guardarle sotto le gonne, e una statua di cupido in pietra porta un dito alle labbra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GIANT_MAGNOLIAS"] =
    "Natura morta a olio americana, rigogliosa e quasi tropicale nel sentimento. Due enormi fiori di magnolia di un bianco crema giacciono recisi su un drappo di velluto blu intenso, circondati dalle loro foglie scure e lucide, con un terzo bocciolo ancora chiuso. I petali risplendono contro lo sfondo quasi nero, dipinti con precisione cerea e sensuale."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SAINT_GEORGE_KILLING"] =
    "Tavola gotica catalana a tempera e oro. San Giorgio, in armatura nera con un'aureola dorata, si protende dal suo cavallo bianco impennato per conficcare una lunga lancia giù nelle fauci spalancate di un drago dalle ali di pipistrello, il terreno intorno a loro cosparso di ossa e teschi. La principessa in veste rosa prega su uno sperone di roccia dietro, e gli spettatori si accalcano sulle bianche mura del castello in alto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_JACQUES_AND_BERTHE"] =
    "Doppio ritratto modernista a olio dello scultore Lipchitz e di sua moglie, dipinto nell'inconfondibile stile di Modigliani. Il marito sta in piedi in un abito scuro, la mano posata sulla spalla della moglie seduta, il cui viso dalle guance rosee si solleva da un colletto di pizzo bianco. Entrambi hanno i caratteristici volti allungati dell'artista, i nasi lunghi e gli occhi a mandorla vuoti, con i loro nomi scarabocchiati in alto sulla tela."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DASH_FOR_TIMBER"] =
    "Dipinto a olio del West americano, il genere di scena d'azione al galoppo che ha definito il vecchio West nell'immaginario collettivo. Otto cowboy galoppano dritti verso di te a briglia sciolta, gli zoccoli dei cavalli sollevati da terra, due cavalieri girati in sella a sparare indietro contro la banda di Apache a cavallo che li inseguono nella polvere alle loro spalle. Un uomo ferito si accascia contro un compagno mentre corrono verso gli alberi sul margine sinistro dell'arida pianura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_GEORGE_WASHINGTON_PORTRAIT"] =
    "Ritratto di stato americano a olio, l'immagine ufficiale della prima presidenza. Washington sta in piedi a figura intera in un semplice abito di velluto nero, un braccio teso in un gesto oratorio, l'altro che regge una spada da cerimonia, accanto a un tavolo con penna d'oca e calamaio. Gli ornamenti intorno a lui sono di grandiosità repubblicana: una sedia dorata con lo scudo a stelle e strisce, colonne di marmo, e un drappeggio di tessuto cremisi con un arcobaleno che squarcia nubi temporalesche in lontananza."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_ATTACK_ON_BEIJING"] =
    "Stampa giapponese a colori nello stile dell'illustrazione di cronaca di guerra, con didascalia in giapponese e in inglese. Le truppe alleate assaltano le mura del palazzo imperiale di Pechino: soldati britannici in giubba rossa con una Union Jack caricano dal primo piano mentre fanti giapponesi in uniforme bianca avanzano sulla destra. Le esplosioni dei proiettili restano sospese come sbuffi bianchi sopra la verde piazza d'armi, con il portale dal tetto blu del palazzo e le mura fumanti sullo sfondo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_SUMO_WRESTLER"] =
    "Stampa ukiyo-e giapponese su blocco di legno, il ritratto da celebrità di un lottatore famoso fuori dal ring. L'omone sta in piedi a figura intera in un kimono nero sopra vesti a motivi, le spade alla cintura, mentre si tampona la fronte con un panno a quadri e porta un mantello arrotolato su una spalla. Il suo nome scorre lungo il lato destro in vistosi pannelli di calligrafia rossa, la figura piatta e monumentale contro la carta nuda."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_TIGER_IN_TROPICAL_STORM"] =
    "Dipinto a olio in stile naif dell'autodidatta doganiere francese che non vide mai una giungla. Una tigre dagli occhi spalancati si acquatta nell'erba alta sferzata dal vento, le zanne scoperte, sorpresa da una tempesta che piega ogni pianta di lato. La giungla è un fitto motivo di foglie stilizzate in verdi e rossi, con oblique striature argentee di pioggia tracciate su tutta la tela come una garza."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_HOME_GUARD"] =
    "Ritratto a olio ungherese in stile Biedermeier dalla rivoluzione del 1848. Un cittadino soldato barbuto siede in una semplice giacca di lino grezzo, entrambe le mani guantate posate sull'elsa della sciabola tenuta dritta, la fascia da braccio nazionale rossa, bianca e verde sulla manica a proclamare la sua causa. Guarda di lato con calma determinazione, illuminato di luce calda contro una tenda rosso scuro, il suo cappotto foderato di rosso gettato sulla sedia."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CEREMONIAL_SITTING"] =
    "Dipinto a olio realista russo di vaste dimensioni, un ritratto di gruppo dell'intero consiglio di governo dell'impero. Decine di anziani statisti in uniformi scure cariche di galloni d'oro e fasce rosse siedono attorno a un grande ferro di cavallo di sedie rosse in una sala dalle colonne bianche, addobbata di lampadari e ritratti reali. Ciascuno degli oltre sessanta volti è un ritratto individuale, dipinto con il realismo rapido e sicuro di Repin."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_RUSSIAN_TSAR"] =
    "Dipinto storico a olio russo che ricostruisce una processione reale del sedicesimo secolo. Uno zar dal copricapo di pelliccia, in una veste di broccato d'oro, cavalca un cavallo bianco nella neve, preceduto da guardie in giubbe rosso brillante che portano alte alabarde ricurve. La folla si inginocchia e si prostra a terra ai due lati della strada innevata e calpestata, con gli edifici di tronchi di un'antica città russa sotto un pallido cielo invernale."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_CRUCIFIXION_OF_SAINT_PETER"] =
    "Dipinto a olio barocco italiano, brutale e fisico nello stile inconfondibile di Caravaggio. Tre operai si sforzano di issare una croce di legno su cui l'anziano San Pietro è stato inchiodato a testa in giù, uno tirando una fune, un altro accovacciato sotto la trave, i loro volti nascosti. Il santo dalla barba bianca solleva il capo a guardare la propria mano inchiodata, il suo vecchio corpo muscoloso che divampa fuori dal buio pesto in un'unica luce dura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LANDSCAPE_WITH_ANT_BEAR"] =
    "Paesaggio coloniale olandese a olio, dipinto dal primo artista di formazione europea ad operare in Brasile. Un'ampia valle assolata con un fiume si apre sotto un grande cielo tra due palme alte, con un insediamento coloniale di case bianche sulle colline lontane. Un gruppo di figure afrobrasiliane percorre un sentiero in primo piano portando dei fagotti, e il formichiere dal lungo muso del titolo fruga tra la macchia in basso a destra."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_DUTCH_MEN_O_WAR"] =
    "Dipinto a olio marino del Secolo d'oro olandese, opera del più grande pittore di navi dell'epoca. Alte navi da guerra in legno stanno all'ancora su un'acqua liscia come il vetro, le vele afflosciate e gli scafi rispecchiati nel mare, ogni linea del sartiame esatta. Barche a remi traghettano passeggeri tra i vascelli sotto un vasto cielo di cumuli illuminati dal sole, l'intera scena immersa in una calma dorata."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_HARBOR_IN_BALAKLAVA"] =
    "Litografia colorata dalla guerra di Crimea, disegnata da uno dei primi artisti di guerra a documentare una campagna sul posto. Su una desolata riva del porto, soldati malati e feriti avvolti in coperte bianche vengono aiutati a scendere da lettighe portate da muli per salire su una barca a remi in attesa. Spogli colli bruni si innalzano dietro il gruppo di figure, con baracche e tende dell'esercito sparse sul pendio, i colori smorzati e documentari."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PEACEMAKERS"] =
    "Dipinto storico a olio americano di un vero consiglio militare della guerra civile nei suoi giorni finali. Il presidente Lincoln siede nella cabina di un battello a vapore ascoltando attento, il mento sulla mano, mentre il generale Sherman gesticola nel pieno di una discussione; il generale Grant e l'ammiraglio Porter completano il cerchio delle quattro figure in abito scuro. Attraverso i finestrini della cabina alle loro spalle un arcobaleno squarcia il cielo che si rasserena, il quieto segno della pace imminente nel dipinto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_CHITASEI"] =
    "Stampa ukiyo-e giapponese su blocco di legno dalla celebre serie di Kuniyoshi sui 108 eroi del romanzo cinese I briganti. Lo studioso stratega Wu Yong sta in piedi in un'ampia veste scura a motivi di draghi, accarezzandosi la barba pensieroso sotto un cielo notturno costellato di stelle. Accanto a lui poggia un grande globo celeste su un supporto ornato, e pannelli di testo giapponese incorniciano la figura."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_LOUIS"] =
    "Ritratto a olio inglese del Settecento di uno scultore colto al lavoro. Roubiliac, con un morbido berretto e una camicia aperta dalle maniche rimboccate, si ferma con lo strumento da modellatore alzato, lo sguardo rivolto di lato mentre lavora a una statuetta in argilla di Shakespeare posata su un supporto. Con la mano libera lo scultore indica la propria creazione, illuminato da una luce calda contro lo sfondo scuro dello studio."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_PORTRAIT_OF_NASSER"] =
    "Ritratto di corte persiano dei Qajar a olio, con lo splendore regale steso in abbondanza. Il giovane Scia dai baffi siede rigidamente eretto in un'uniforme scarlatta incrostata di ricami in oro, fili di perle, spalline ingioiellate e una fascia azzurra, una mano posata su una spada tempestata di gemme. Porta un alto cappello nero ornato da uno spruzzo di diamanti, gli occhi dal contorno scuro che guardano fuori contro uno sfondo verde oliva profondo impresso con un'iscrizione regale."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_FIELD_WITH_SHEAFS"] =
    "Paesaggio a olio di tendenza espressionista tedesca, dipinto con pennellate larghe ed energiche. Un campo di grano mietuto riempie il primo piano con file di covoni dorati ammassati in fasci inclinati, il giallo steso denso e luminoso. Una linea di alberi verde scuro chiude il campo, sopra il quale si apre un cielo viola azzurrognolo pallido di nuvole spinte dal vento."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_AT_THE_EDGE_OF_THE_BROOK"] =
    "Dipinto a olio accademico francese, rifinito fino a quella perfezione levigata e vitrea per cui Bouguereau era celebre. Due bambini contadini scalzi siedono su una pietra in riva a un ruscello, la bambina più piccola che si sfila una calza mentre la sua compagna dai capelli scuri si solleva la gonna per guadare. Si scambiano uno sguardo nel mezzo di una conversazione, la pelle e i capelli arruffati dipinti con liscezza fotografica contro un dolce paesaggio rurale."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_KISS_ALT"] =
    "Dipinto a olio romantico italiano, il bacio più celebre dell'arte italiana e un emblema patriottico nascosto dell'unificazione. In un corridoio medievale di pietra, un giovane con un cappello piumato e un mantello marrone piega all'indietro una donna in un bacio appassionato, un piede già sul gradino come se si fermasse nel mezzo della fuga. Il suo abito di raso azzurro pallido riversa luce nella scena, mentre una figura in ombra si avvicina attraverso l'arcata oltre."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MOVING_HOUSE"] =
    "Dipinto a olio realista russo di quieta povertà urbana. Una coppia di anziani arranca sul ghiaccio del fiume gelato di San Pietroburgo portando tutto ciò che possiede in un fagotto di stoffa, l'uomo appoggiato a un bastone, entrambi infagottati in cappotti logori e foulard contro il freddo. Un cagnolino trotterella davanti a loro, e la guglia dorata della fortezza di Pietro e Paolo si leva attraverso la foschia invernale sullo sfondo."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_MEXICAN_EXPEDITION"] =
    "Dipinto a olio di storia navale francese, in stile cronaca e affollato di azione. Una nave da guerra francese che batte bandiera tricolore domina il primo piano a sinistra, gli ufficiali sul ponte che dirigono il bombardamento della fortezza messicana di San Juan de Ulua, con il fumo che si leva sull'acqua. Le granate schizzano vicino alle barche a remi che traghettano uomini tra le navi, con un vulcano dalla cima innevata sull'orizzonte velato."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_LAST_DAY_OF_POMPEII"] =
    "Dipinto a olio romantico russo su una tela enorme, l'epopea del disastro del suo secolo. Il cielo sopra Pompei arde di rosso e di nero mentre il Vesuvio erutta, le statue precipitano da un tetto, e un fulmine spacca la nube di cenere. Folle di cittadini in abiti romani fuggono tra i detriti che cadono, riparando bambini e anziani sotto i mantelli, mentre al centro una donna caduta giace riversa accanto a un carro rovesciato."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GWDESC_GREAT_WORK_THE_ACCOLADE"] =
    "Dipinto a olio in stile preraffaellita inglese, una visione fiabesca della cavalleria. Una regina dai capelli d'oro in una fluente veste bianca posa una spada sulla spalla di un cavaliere inginocchiato, nominandolo davanti a una piccola corte. Egli china il capo nella cotta di maglia e in una sopravveste rossa, l'elmo a terra accanto a lui, la sala di pietra e la pedana rossa dipinte in un dettaglio romantico e luminoso."
