-- Mod-authored strings, de_DE overlay. Baseline in CivVAccess_FrontEndStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_BOOT_FRONTEND"] = "Barrierefreiheit-Mod bereit."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MUTE_PAUSED"] = "Mod pausiert"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MUTE_RESUMED"] = "Mod fortgesetzt"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LEADERBOARD_PREV_PAGE"] = "Vorherige Seite"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LEADERBOARD_NEXT_PAGE"] = "Nächste Seite"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_BUTTON_DISABLED"] = "deaktiviert"

-- Front-end screen handler display names.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MAIN_MENU"] = "Hauptmenü"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_OTHER_MENU"] = "Sonstiges"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SINGLE_PLAYER"] = "Einzelspieler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MULTIPLAYER_SELECT"] = "Mehrspieler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_EXIT_CONFIRM"] = "Spiel beenden"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LEGAL"] = "Rechtliche Hinweise"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_EULA"] = "Endbenutzer-Lizenzvertrag"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_ERROR"] = "Mod-Fehler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_FRONT_END_POPUP"] = "Hinweis"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_MENU"] = "Mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_SINGLE_PLAYER"] = "Mods Einzelspieler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_MULTIPLAYER"] = "Mods Mehrspieler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CONTENT_SWITCH"] = "Spieldaten werden aktualisiert"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_WAITING_PLAYERS"] = "Warten auf Spieler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_JOINING_ROOM"] = "Raum wird betreten"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LOBBY"] = "Lobby"

-- StagingRoom.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_STAGING_ROOM"] = "Mehrspieler-Vorbereitungsraum"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_PLAYERS_TAB"] = "Spieler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_OPTIONS_TAB"] = "Spieloptionen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SLOT_TYPE"] = "Slot-Typ"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEAM"] = "Team"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CIVILIZATION"] = "Zivilisation"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_READY"] = "bereit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_HOST"] = "Gastgeber"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_STATUS"] = "{1_Name}, {2_Status}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_CIV"] = "{1_Name}, {2_Civ}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_TEAM"] = "{1_Name}, {2_Team}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_HANDICAP"] = "{1_Name}, {2_Handicap}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_READY"] = "{1_Name} bereit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_UNREADY"] = "{1_Name} nicht bereit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_MSG"] = "{1_Name}: {2_Text}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_HOST_MIGRATION"] = "{1_Name} ist jetzt Gastgeber"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DISCONNECT"] = "{1_Name} hat die Verbindung getrennt"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_COUNTDOWN_START"] = "Start in 10 Sekunden"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_COUNTDOWN_CANCEL"] = "Countdown abgebrochen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_COUNTDOWN_TICK"] = "{1_Seconds}"

-- Chat panel.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_PANEL"] = "Chat"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_MESSAGES_TAB"] = "Nachrichten"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_COMPOSE_TAB"] = "Verfassen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_COMPOSE"] = "Nachricht"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_EMPTY"] = "Noch keine Nachrichten."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_HELP_OPEN"] = "Chat öffnen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_HELP_KEY_CLOSE"] = "Backslash oder Escape"

-- Lobby.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_SERVERS_TAB"] = "Server"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_DETAILS_TAB"] = "Server-Details"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_NO_SERVERS"] = "Keine Server gefunden."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_MEMBERS"] = "{1_Num} von {2_Max}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_PICKER_ROW"] = "{1_Server}, {2_Members}, {3_Map}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_SORT_ASC"] = "aufsteigend"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_SORT_DESC"] = "absteigend"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_NO_SELECTION"] =
    "Kein Server ausgewählt. Wechselt zum Server-Tab, um einen auszuwählen."

-- More front-end screen handler display names.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_OPTIONS"] = "Optionen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CREDITS"] = "Mitwirkende"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_GAME_SETUP"] = "Spiel einrichten"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MAP_TYPE"] = "Kartentyp"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MAP_SIZE"] = "Kartengröße"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_DIFFICULTY"] = "Schwierigkeit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_GAME_SPEED"] = "Spielgeschwindigkeit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CIVILIZATION"] = "Zivilisation"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SET_CIV_NAMES"] = "Zivilisation benennen"

-- Mod / scenario / DLC browser screens.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SCENARIOS"] = "Szenarien"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CUSTOM_MOD_GAME"] = "Eigenes Mod-Spiel"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_TUTORIAL"] = "Tutorial"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_BROWSER"] = "Mods durchsuchen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_PREMIUM_CONTENT"] = "DLC"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_WORLD_PICKER"] = "Weltgröße"

CivVAccess_Strings["TXT_KEY_CIVVACCESS_TUTORIAL_COMPLETED"] = "abgeschlossen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHOICE_SELECTED"] = "ausgewählt"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHOICE_SELECTED_NAMED"] = "ausgewählt, {1_Label}"

-- Civ-picker entry prefixes.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_ABILITY"] = "Einzigartige Fähigkeit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_ABILITY_NAMED"] = "{1_Name}, einzigartige Fähigkeit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_UNIT"] = "Einzigartige Einheit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_BUILDING"] = "Einzigartiges Gebäude"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_IMPROVEMENT"] = "Einzigartige Modernisierung"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LOADING"] = "Spiel wird geladen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLACES"] = "ersetzt {1_Name}"

-- Generic templates.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LABEL_STATE"] = "{1_Label}, {2_State}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LABEL_VALUE"] = "{1_Label} {2_Value}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LABELED_LIST"] = "{1_Label} {2_List}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHECK_ON"] = "an"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHECK_OFF"] = "aus"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_EDIT"] = "bearbeiten"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_BLANK"] = "leer"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_EDITING"] = "{1_Label} bearbeiten"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_RESTORED"] = "{1_Label} wiederhergestellt"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_BUTTON"] = "Schaltfläche"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_CHECKBOX"] = "Kontrollkästchen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_SLIDER"] = "Schieberegler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_PULLDOWN"] = "Kombinationsfeld"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_GROUP"] = "Untermenü"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VERBOSE_POSITION"] = "{1_Num} von {2_Num}"

-- Disambiguating labels.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPSCREEN_SMTP_FROM_EMAIL"] = "Absender-E-Mail-Adresse"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPSCREEN_RESOLUTION_FS"] = "Vollbildauflösung"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPSCREEN_RESOLUTION_W"] = "Fensterauflösung"

-- Checkbox-gated numeric fields.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_FIELD_MAX_TURNS"] = "Rundenanzahl"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_FIELD_TURN_TIMER"] = "Timersekunden"

CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPTIONS_COUNTDOWN_INTRO"] = "{1_Message}. Wird in 20 Sekunden zurückgesetzt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPTIONS_COUNTDOWN_EXPIRED"] = "Zeit abgelaufen, zurückgesetzt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MP_RECONNECTING"] = "Verbindung wird wiederhergestellt"

-- Advanced Setup + MP Setup.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_ADVANCED_SETUP"] = "Erweiterte Einrichtung"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MP_GAME_SETUP"] = "Mehrspieler-Einrichtung"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_AI_SLOT"] = "KI {1_Num}, {2_Civ}, {3_Team}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HUMAN_SLOT"] = "Ihr, {1_Civ}, {2_Team}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_PLAYERS"] = "Spieler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_AI_PLAYERS"] = "KI-Spieler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_VICTORY_CONDITIONS"] = "Siegbedingungen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_GAME_OPTIONS"] = "Spieloptionen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_DLC_ALLOWED"] = "Erlaubte DLC"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNKNOWN_PLAYERS_STATUS"] =
    "KI-Spieler können nicht angepasst werden, solange eine zufällige Kartengröße ausgewählt ist. Wählt eine bestimmte Kartengröße, um die Spielerliste zu bearbeiten."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_FIELD_GAME_NAME"] = "Spielname"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MAP_SIZE_ONLY"] = "nur {1_Size}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MAP_SIZE_LIMITED"] = "Größen: {1_Sizes}"

-- Type-ahead search feedback.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SEARCH_NO_MATCH"] = "kein Treffer für {1_Buffer}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SEARCH_CLEARED"] = "Suche zurückgesetzt"

-- Help overlay.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_HELP"] = "Hilfe"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_ENTRY"] = "{1_Key}, {2_Description}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_AZ09"] = "Buchstaben"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_UP_DOWN"] = "Auf oder Ab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_HOME_END"] = "Pos1 oder Ende"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ENTER_SPACE"] = "Eingabe oder Leertaste"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_LEFT_RIGHT"] = "Links oder Rechts"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_SHIFT_LEFT_RIGHT"] = "Umschalt plus Links oder Rechts"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_CTRL_UP_DOWN"] = "Strg plus Auf oder Ab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_TAB"] = "Tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_SHIFT_TAB"] = "Umschalt plus Tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_F1"] = "F1"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_BACKSLASH"] = "Backslash"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ESC"] = "Escape"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ENTER"] = "Eingabe"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_QUESTION"] = "Fragezeichen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_SEARCH"] = "Tippen zum Suchen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_NAV_ITEMS"] = "Elemente durchblättern"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_JUMP_FIRST_LAST"] = "Zum ersten oder letzten springen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ACTIVATE"] = "Aktivieren"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ADJUST"] = "Wert ändern oder hineingehen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ADJUST_BIG"] = "Wert in größeren Schritten ändern"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_JUMP_GROUP"] = "Zur vorherigen oder nächsten Gruppe springen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_NEXT_TAB"] = "Nächster Tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_PREV_TAB"] = "Vorheriger Tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_READ_HEADER"] = "Bildschirmüberschrift vorlesen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CANCEL"] = "Abbrechen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CLOSE"] = "Schließen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CANCEL_EDIT"] = "Bearbeitung abbrechen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_COMMIT_EDIT"] = "Bearbeitung übernehmen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_F12"] = "F12"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_CTRL_SHIFT_F12"] = "Strg plus Umschalt plus F12"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_OPEN_SETTINGS"] = "Einstellungen öffnen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CLOSE_SETTINGS"] = "Einstellungen schließen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_TOGGLE_MUTE"] = "Mod pausieren oder fortsetzen"

-- Settings overlay.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SETTINGS"] = "Einstellungen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_CUE_MODE"] = "Audiosignal-Modus"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_SPEECH_ONLY"] = "Nur Sprache"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_SPEECH_PLUS_CUES"] = "Sprache und Audiosignale"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_VERBOSE_UI"] = "Ausführliche Ansagen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_CUES_ONLY"] = "Nur Audiosignale"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_MASTER_VOLUME"] = "Gesamtlautstärke"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_VOLUME_VALUE"] = "Gesamtlautstärke, {1_Num} Prozent"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_BEACON_RANGE"] = "Hörbare Distanz des Leuchtfeuers"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_BEACON_RANGE_VALUE"] = "Hörbare Distanz des Leuchtfeuers, {1_Num} Hexfelder"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_SCANNER_AUTO_MOVE"] = "Scanner bewegt Cursor automatisch"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_FOLLOWS_SELECTION"] = "Cursor folgt ausgewählter Einheit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_MODE"] = "Cursor-Koordinaten beim Bewegen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_OFF"] = "Aus"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_PREPEND"] = "Vor der Bewegungsansage sprechen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_APPEND"] = "Nach der Bewegungsansage sprechen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_BORDER_ALWAYS_ANNOUNCE"] = "Territorium immer im Geländefeld-Bericht ansagen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_SCANNER_COORDS"] = "Scanner zeigt Koordinaten"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_READ_SUBTITLES"] = "Untertitel vorlesen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_REVEAL_ANNOUNCE"] = "Sichtbarkeitsänderungen beim Bewegen ansagen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AI_COMBAT_ANNOUNCE"] = "KI-Kampfauflösung ansagen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_FOREIGN_UNIT_WATCH_ANNOUNCE"] =
    "Sichtbarkeitsänderungen am Rundenanfang ansagen"

-- LoadMenu.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_SORT_BY"] = "Sortieren nach"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_SAVES_TAB"] = "Spielstände"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_DETAILS_TAB"] = "Spielstand-Details"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_NO_SAVES"] = "Keine Spielstände in dieser Liste."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_DELETE_CONFIRM"] = "{1_Name} löschen?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_DELETED"] = "Spielstand gelöscht."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_MOD_VERSION"] = "{1_Name} Version {2_Version}"

-- LoadReplayMenu.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LOAD_REPLAY"] = "Wiederholung laden"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_LIST_TAB"] = "Wiederholungen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_DETAILS_TAB"] = "Wiederholungs-Details"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_DELETED"] = "Wiederholung gelöscht."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_NO_SELECTION"] =
    "Keine Wiederholung ausgewählt. Wechselt zum Wiederholungs-Tab, um eine auszuwählen."

-- ReplayViewer.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_REPLAY_VIEWER"] = "Wiederholung"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_PANEL_LABEL"] = "Bereich"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_TURN_GROUP"] = "Runde {1_Turn}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PICKER_READER_EMPTY"] = "Kein Inhalt für diesen Eintrag."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PICKER_READER_NO_SELECTION"] =
    "Kein Spielstand ausgewählt. Wechselt zum Spielstand-Tab, um einen auszuwählen."

-- InstalledPanel.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_INSTALLED_PANEL"] = "Installierte Mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_LIST_TAB"] = "Mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DETAILS_TAB"] = "Details"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_NO_MODS"] = "Keine Mods installiert."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_SORT_BY"] = "Sortieren nach"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_APPLY_OPTIONS"] = "Übernehmen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_STATE"] = "Status"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_STATE_ENABLED"] = "aktiviert"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_STATE_DISABLED"] = "deaktiviert"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_ENABLE_BLOCKED"] = "Aktivieren nicht möglich: {1_Reason}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_PICKER_ROW"] = "{1_Name}, {2_State}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_PICKER_NEEDS_UPDATE"] = "{1_Name}, {2_State}, Aktualisierung erforderlich"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_VERSION_RANGE"] = "{1_Name} Version {2_MinVersion} bis {3_MaxVersion}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_VERSION_SUFFIX"] = "{1_Name} Version {2_Version}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DISABLE_CONFIRM"] = "{1_Name} deaktivieren?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DELETE_CONFIRM"] = "{1_Name} löschen?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_UNSUBSCRIBE_CONFIRM"] = "{1_Name} abbestellen?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DELETE_WITH_USER_DATA"] = "Mit Benutzerdaten löschen"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DELETED"] = "Mod entfernt."

-- Spoken replacements for [ICON_*] markup.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GOLD"] = "Gold"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_FOOD"] = "Nahrung"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_PRODUCTION"] = "Produktion"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_CULTURE"] = "Kultur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_SCIENCE"] = "Forschung"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RESEARCH"] = "Forschung"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_FAITH"] = "Glaube"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_TOURISM"] = "Tourismus"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE"] = "Große Persönlichkeiten"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT"] = "Große Persönlichkeit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT_ARTIST"] = "Gr.-Künstler-Punkte"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT_ENGINEER"] = "Gr.-Ingenieur-Punkte"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT_MERCHANT"] = "Gr.-Händler-Punkte"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT_SCIENTIST"] = "Gr.-Wissensch.-Punkte"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_WORK"] = "Großes Werk"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_STRENGTH"] = "Kampfstärke"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_STRENGTH_ALT"] = "Stärke"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RANGE_STRENGTH"] = "Fernkampfstärke"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RANGE_STRENGTH_ALT"] = ""
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_MOVEMENT"] = "Bewegungspunkte"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_HAPPY"] = "Zufriedenheit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_HAPPY_ALT"] = "zufrieden"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_UNHAPPY"] = "Unzufriedenheit"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_UNHAPPY_ALT"] = "unzufrieden"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_ARROW_LEFT"] = "links"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_ARROW_RIGHT"] = "rechts"
