-- Mod-authored strings, fr_FR overlay. Baseline in CivVAccess_FrontEndStrings_en_US.lua.
CivVAccess_Strings = CivVAccess_Strings or {}
CivVAccess_Strings["TXT_KEY_CIVVACCESS_BOOT_FRONTEND"] = "Mod d'accessibilité prêt."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MUTE_PAUSED"] = "mod en pause"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MUTE_RESUMED"] = "mod repris"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LEADERBOARD_PREV_PAGE"] = "Page précédente"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LEADERBOARD_NEXT_PAGE"] = "Page suivante"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_BUTTON_DISABLED"] = "désactivé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MAIN_MENU"] = "Menu principal"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_OTHER_MENU"] = "Autre"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SINGLE_PLAYER"] = "Solo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MULTIPLAYER_SELECT"] = "Multijoueur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_EXIT_CONFIRM"] = "Quitter le jeu"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LEGAL"] = "Mentions légales"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_EULA"] = "Contrat de licence utilisateur final"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_ERROR"] = "Erreur de mod"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_FRONT_END_POPUP"] = "Avis"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_MENU"] = "Mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_SINGLE_PLAYER"] = "Mods solo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_MULTIPLAYER"] = "Mods multijoueur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CONTENT_SWITCH"] = "Mise à jour des données du jeu"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_WAITING_PLAYERS"] = "En attente de joueurs"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_JOINING_ROOM"] = "Connexion au salon"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LOBBY"] = "Salon"
-- StagingRoom. Two tabs (Players / Game Options). SLOT_TYPE relabels the
-- per-slot SlotTypePulldown, whose label in the base UI is purely visual
-- positioning. Delta keys are spoken as remote players change state; each
-- leads with the player name so the distinguishing word comes first. HOST
-- is a tail tag appended to the host's slot summary; READY ditto.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_STAGING_ROOM"] = "Salon de préparation multijoueur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_PLAYERS_TAB"] = "Joueurs"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_OPTIONS_TAB"] = "Options de jeu"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SLOT_TYPE"] = "Type d'emplacement"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEAM"] = "Equipe"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CIVILIZATION"] = "Civilisation"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_READY"] = "prêt"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_HOST"] = "hôte"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_STATUS"] = "{1_Name}, {2_Status}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_CIV"] = "{1_Name}, {2_Civ}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_TEAM"] = "{1_Name}, {2_Team}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_HANDICAP"] = "{1_Name}, {2_Handicap}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_READY"] = "{1_Name} prêt"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_UNREADY"] = "{1_Name} pas prêt"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_MSG"] = "{1_Name} : {2_Text}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_HOST_MIGRATION"] = "{1_Name} est maintenant l'hôte"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DISCONNECT"] = "{1_Name} deconnecté"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_COUNTDOWN_START"] = "Lancement dans 10 secondes"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_COUNTDOWN_CANCEL"] = "Compte à rebours annulé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_COUNTDOWN_TICK"] = "{1_Seconds}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_PANEL"] = "Discussion"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_MESSAGES_TAB"] = "Messages"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_COMPOSE_TAB"] = "Rediger"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_COMPOSE"] = "Message"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_EMPTY"] = "Aucun message pour l'instant."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_HELP_OPEN"] = "Ouvrir la discussion"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_HELP_KEY_CLOSE"] = "Antislash ou Echap"
-- Lobby (PickerReader over the server listing). Row format reads as
-- "<server>, <members>, <map>" so the distinguishing server name comes
-- first; Members format speaks "X of Y" instead of the engine's "X/Y"
-- caption that screen readers mangle as "slash".
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_SERVERS_TAB"] = "Serveurs"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_DETAILS_TAB"] = "Details du serveur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_NO_SERVERS"] = "Aucun serveur trouvé."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_MEMBERS"] = "{1_Num} sur {2_Max}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_PICKER_ROW"] = "{1_Server}, {2_Members}, {3_Map}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_SORT_ASC"] = "croissant"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_SORT_DESC"] = "decroissant"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_NO_SELECTION"] =
    "Aucun serveur sélectionné. Passez à l'onglet Serveurs pour en choisir un."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_OPTIONS"] = "Options"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CREDITS"] = "Credits"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_GAME_SETUP"] = "Configuration de la partie"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MAP_TYPE"] = "Type de carte"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MAP_SIZE"] = "Taille de la carte"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_DIFFICULTY"] = "Difficulté"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_GAME_SPEED"] = "Vitesse de jeu"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CIVILIZATION"] = "Civilisation"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SET_CIV_NAMES"] = "Nommer la civilisation"
-- Mod / scenario / DLC browser screens (continuation of the same cluster).
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SCENARIOS"] = "Scénarios"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CUSTOM_MOD_GAME"] = "Partie personnalisée avec mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_TUTORIAL"] = "Tutoriel"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_BROWSER"] = "Parcourir les mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_PREMIUM_CONTENT"] = "DLC"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_WORLD_PICKER"] = "Taille du monde"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TUTORIAL_COMPLETED"] = "terminé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHOICE_SELECTED"] = "sélectionné"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHOICE_SELECTED_NAMED"] = "sélectionné, {1_Label}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_ABILITY"] = "Capacité unique"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_ABILITY_NAMED"] = "{1_Name}, capacité unique"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_UNIT"] = "Unité unique"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_BUILDING"] = "Bâtiment unique"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_IMPROVEMENT"] = "Amélioration unique"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LOADING"] = "Chargement de la partie"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLACES"] = "remplace {1_Name}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LABEL_STATE"] = "{1_Label}, {2_State}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LABEL_VALUE"] = "{1_Label} {2_Value}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LABELED_LIST"] = "{1_Label} {2_List}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHECK_ON"] = "activé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHECK_OFF"] = "désactivé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_EDIT"] = "modifier"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_BLANK"] = "vide"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_EDITING"] = "modification de {1_Label}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_RESTORED"] = "{1_Label} restauré"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPSCREEN_SMTP_FROM_EMAIL"] = "Adresse e-mail de l'expéditeur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPSCREEN_RESOLUTION_FS"] = "Résolution plein écran"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPSCREEN_RESOLUTION_W"] = "Résolution en fenêtre"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_FIELD_MAX_TURNS"] = "Nombre de tours"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_FIELD_TURN_TIMER"] = "Secondes du minuteur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPTIONS_COUNTDOWN_INTRO"] = "{1_Message}. Retour en arrière dans 20 secondes."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPTIONS_COUNTDOWN_EXPIRED"] = "Délai expiré, restauré."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MP_RECONNECTING"] = "Reconnexion en cours"
-- Advanced Setup + MP Setup (nested menus).
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_ADVANCED_SETUP"] = "Configuration avancée"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MP_GAME_SETUP"] = "Configuration de la partie multijoueur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_AI_SLOT"] = "IA {1_Num}, {2_Civ}, {3_Team}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HUMAN_SLOT"] = "Vous, {1_Civ}, {2_Team}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_PLAYERS"] = "Joueurs"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_AI_PLAYERS"] = "Joueurs IA"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_VICTORY_CONDITIONS"] = "Conditions de victoire"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_GAME_OPTIONS"] = "Options de jeu"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_DLC_ALLOWED"] = "DLC autorisé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNKNOWN_PLAYERS_STATUS"] =
    "Les joueurs IA ne peuvent pas être personnalisés lorsque la taille de carte aléatoire est sélectionnée. Choisissez une taille de carte spécifique pour modifier la liste des joueurs."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_FIELD_GAME_NAME"] = "Nom de la partie"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MAP_SIZE_ONLY"] = "{1_Size} uniquement"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MAP_SIZE_LIMITED"] = "tailles : {1_Sizes}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SEARCH_NO_MATCH"] = "aucune correspondance pour {1_Buffer}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SEARCH_CLEARED"] = "recherche effacée"
-- Help overlay (Shift+?). keyLabels use "or" (not slash) so screen readers
-- speak them cleanly; descriptions stay purpose-centric ("Navigate items"
-- not "Previous item" / "Next item"). Pairs must match across handlers or
-- the keyLabel dedupe in HandlerStack.collectHelpEntries won't collapse
-- equivalent entries. Mirrored in the InGame strings file because the
-- help overlay is reachable from every Context that routes through
-- InputRouter.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_HELP"] = "Aide"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_ENTRY"] = "{1_Key}, {2_Description}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_AZ09"] = "Lettres"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_UP_DOWN"] = "Haut ou bas"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_HOME_END"] = "Début ou fin"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ENTER_SPACE"] = "Entrée ou espace"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_LEFT_RIGHT"] = "Gauche ou droite"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_SHIFT_LEFT_RIGHT"] = "Maj plus gauche ou droite"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_CTRL_UP_DOWN"] = "Contrôle plus haut ou bas"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_TAB"] = "Tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_SHIFT_TAB"] = "Maj plus Tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_F1"] = "F1"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_BACKSLASH"] = "Antislash"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ESC"] = "Echap"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ENTER"] = "Entrée"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_QUESTION"] = "Point d'interrogation"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_SEARCH"] = "Saisir pour rechercher"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_NAV_ITEMS"] = "Naviguer entre les éléments"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_JUMP_FIRST_LAST"] = "Aller au premier ou au dernier"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ACTIVATE"] = "Activer"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ADJUST"] = "Ajuster la valeur ou entrer"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ADJUST_BIG"] = "Ajuster la valeur par grands pas"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_JUMP_GROUP"] = "Aller au groupe précédent ou suivant"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_NEXT_TAB"] = "Onglet suivant"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_PREV_TAB"] = "Onglet précédent"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_READ_HEADER"] = "Lire l'en-tête de l'écran"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CANCEL"] = "Annuler"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CLOSE"] = "Fermer"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CANCEL_EDIT"] = "Annuler la modification"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_COMMIT_EDIT"] = "Valider la modification"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_F12"] = "F12"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_CTRL_SHIFT_F12"] = "Contrôle plus Maj plus F12"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_OPEN_SETTINGS"] = "Ouvrir les paramètres"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CLOSE_SETTINGS"] = "Fermer les paramètres"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_TOGGLE_MUTE"] = "Mettre en pause ou reprendre le mod"
-- Settings overlay strings. Reachable from every Context that routes
-- through InputRouter, so duplicated in the InGame copy as well.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SETTINGS"] = "Paramètres"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_CUE_MODE"] = "Mode d'indices audio"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_SPEECH_ONLY"] = "Synthèse vocale uniquement"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_SPEECH_PLUS_CUES"] = "Synthèse vocale et indices audio"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_CUES_ONLY"] = "Indices audio uniquement"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_MASTER_VOLUME"] = "Volume principal"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_VOLUME_VALUE"] = "Volume principal, {1_Num} pourcent"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_SCANNER_AUTO_MOVE"] = "Déplacement automatique du curseur du scanner"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_FOLLOWS_SELECTION"] = "Curseur suit l'unité sélectionnée"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_MODE"] = "Coordonnées du curseur lors du déplacement"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_OFF"] = "Désactivé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_PREPEND"] = "Annoncer avant le déplacement"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_APPEND"] = "Annoncer après le déplacement"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_BORDER_ALWAYS_ANNOUNCE"] = "Toujours annoncer le territoire de la case"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_SCANNER_COORDS"] = "Le scanner affiche les coordonnées"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_READ_SUBTITLES"] = "Lire les sous-titres"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_REVEAL_ANNOUNCE"] =
    "Annoncer les changements de visibilité lors du déplacement"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AI_COMBAT_ANNOUNCE"] = "Annoncer la résolution des combats IA"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_FOREIGN_UNIT_WATCH_ANNOUNCE"] =
    "Annoncer les changements de visibilité en début de tour"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_SORT_BY"] = "Trier par"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_SAVES_TAB"] = "Sauvegardes"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_DETAILS_TAB"] = "Détails de la sauvegarde"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_NO_SAVES"] = "Aucune sauvegarde dans cette liste."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_DELETE_CONFIRM"] = "Supprimer {1_Name} ?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_DELETED"] = "Sauvegarde supprimée."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_MOD_VERSION"] = "{1_Name} version {2_Version}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LOAD_REPLAY"] = "Charger une reprise"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_LIST_TAB"] = "Reprises"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_DETAILS_TAB"] = "Détails de la reprise"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_DELETED"] = "Reprise supprimée."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_NO_SELECTION"] =
    "Aucune reprise sélectionnée. Passez à l'onglet Reprises pour en choisir une."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_REPLAY_VIEWER"] = "Reprise"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_PANEL_LABEL"] = "panneau"
-- Drillable label for a per-turn group of replay messages. Children inside
-- the group drop the turn prefix since the group label provides it.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_TURN_GROUP"] = "Tour {1_Turn}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PICKER_READER_EMPTY"] = "Aucun contenu pour cet élément."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PICKER_READER_NO_SELECTION"] =
    "Aucune sauvegarde sélectionnée. Passez à l'onglet Sauvegardes pour en choisir une."
-- InstalledPanel (PickerReader over the installed mods list, child of
-- ModsBrowser). Picker-row label templates carry the mod name then state;
-- confirmation formats take the display name and embed it in a question.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_INSTALLED_PANEL"] = "Mods installés"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_LIST_TAB"] = "Mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DETAILS_TAB"] = "Détails"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_NO_MODS"] = "Aucun mod installé."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_SORT_BY"] = "Trier par"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_APPLY_OPTIONS"] = "Appliquer"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_STATE"] = "Etat"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_STATE_ENABLED"] = "activé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_STATE_DISABLED"] = "désactivé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_ENABLE_BLOCKED"] = "Impossible d'activer : {1_Reason}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_PICKER_ROW"] = "{1_Name}, {2_State}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_PICKER_NEEDS_UPDATE"] = "{1_Name}, {2_State}, mise à jour requise"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_VERSION_RANGE"] = "{1_Name} version {2_MinVersion} à {3_MaxVersion}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_VERSION_SUFFIX"] = "{1_Name} version {2_Version}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DISABLE_CONFIRM"] = "Désactiver {1_Name} ?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DELETE_CONFIRM"] = "Supprimer {1_Name} ?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_UNSUBSCRIBE_CONFIRM"] = "Se désabonner de {1_Name} ?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DELETE_WITH_USER_DATA"] = "Supprimer avec les données utilisateur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DELETED"] = "Mod supprimé."
-- Spoken replacements for [ICON_*] markup. Registered into TextFilter by
-- CivVAccess_Icons.lua; the filter substitutes the bracket token inline
-- with the spoken text. Duplicated into the in-game strings file because
-- each Context has its own CivVAccess_Strings table (per-Context sandbox).
-- Keep the two in sync when adding / renaming icon keys.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GOLD"] = "or"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_FOOD"] = "nourriture"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_PRODUCTION"] = "production"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_CULTURE"] = "culture"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_SCIENCE"] = "science"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RESEARCH"] = "science"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_FAITH"] = "foi"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_TOURISM"] = "tourisme"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE"] = "grands personnages"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT"] = "grand personnage"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_STRENGTH"] = "puissance de combat"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RANGE_STRENGTH"] = "puissance de combat à distance"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_MOVEMENT"] = "déplacements"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_HAPPY"] = "bonheur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_HAPPY_ALT"] = "heureux"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_UNHAPPY"] = "malheur"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_UNHAPPY_ALT"] = "malheureux"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_ARROW_LEFT"] = "gauche"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_ARROW_RIGHT"] = "droite"
