-- OptionsMenu accessibility wiring. Five-tab form. The screen's own
-- OnCategory(which) toggles panel visibility and highlight boxes; we reuse
-- it directly rather than duplicate SetHide chains.
--
-- Items are ordered roughly top-to-bottom, left-to-right as they appear in
-- the shipped UI. Hidden-by-platform widgets (tablet-only sliders, LAN-
-- specific controls when multiplayer category is off) are still listed --
-- FormHandler's isNavigable skips them when IsHidden() returns true, so the
-- user never lands on something that would not accept input.

include("CivVAccess_FrontendCommon")
include("CivVAccess_SimpleListHandler")
include("CivVAccess_FormHandler")

local priorShowHide = ShowHideHandler
local priorInput    = InputHandler

local tabstrip = { kind = "tabstrip", textKey = "TXT_KEY_CIVVACCESS_TAB_STRIP" }

FormHandler.install(ContextPtr, {
    name          = "OptionsMenu",
    displayName   = Text.key("TXT_KEY_CIVVACCESS_SCREEN_OPTIONS"),
    priorShowHide = priorShowHide,
    priorInput    = priorInput,
    tabs = {
        {
            name      = "TXT_KEY_GAME_OPTIONS",
            showPanel = function() OnCategory(1) end,
            items     = {
                tabstrip,
                { kind = "slider",   controlName = "Tooltip1TimerSlider",
                  labelControlName = "Tooltip1TimerLength",
                  textKey = "TXT_KEY_OPSCREEN_TOOLTIP_1_TIMER_LENGTH" },
                { kind = "pulldown", controlName = "TutorialPull",
                  textKey = "TXT_KEY_OPSCREEN_TUTORIAL_LEVEL" },
                { kind = "button",   controlName = "ResetTutorialButton",
                  textKey = "TXT_KEY_OPSCREEN_RESET_TUTORIAL",
                  activate = function() OnResetTutorial() end },
                { kind = "checkbox", controlName = "SinglePlayerAutoEndTurnCheckBox",
                  textKey = "TXT_KEY_OPSCREEN_SPLAYER_AUTO_END_TURN" },
                { kind = "checkbox", controlName = "MultiplayerAutoEndTurnCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_MULTIPLAYER_AUTO_END_TURN" },
                { kind = "checkbox", controlName = "SPQuickCombatCheckBox",
                  textKey = "TXT_KEY_OPSCREEN_SPLAYER_QUICK_COMBAT" },
                { kind = "checkbox", controlName = "SPQuickMovementCheckBox",
                  textKey = "TXT_KEY_OPSCREEN_SPLAYER_QUICK_MOVEMENT" },
                { kind = "checkbox", controlName = "MPQuickCombatCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_MULTIPLAYER_QUICK_COMBAT" },
                { kind = "checkbox", controlName = "MPQuickMovementCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_MULTIPLAYER_QUICK_MOVEMENT" },
                { kind = "checkbox", controlName = "AutoWorkersDontReplaceCB",
                  textKey = "TXT_KEY_OPSCREEN_AUTO_WORKERS_DONT_REPLACE" },
                { kind = "checkbox", controlName = "AutoWorkersDontRemoveFeaturesCB",
                  textKey = "TXT_KEY_OPSCREEN_AUTO_WORKERS_DONT_REMOVE_FEATURES" },
                { kind = "checkbox", controlName = "NoRewardPopupsCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_NO_REWARD_POPUPS" },
                { kind = "checkbox", controlName = "NoTileRecommendationsCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_NO_TILE_RECOMMENDATIONS" },
                { kind = "checkbox", controlName = "CivilianYieldsCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_CIVILIAN_YIELDS" },
                { kind = "checkbox", controlName = "NoBasicHelpCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_NO_BASIC_HELP" },
                { kind = "checkbox", controlName = "QuickSelectionAdvCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_QUICK_SELECTION_ADVANCE" },
            },
        },
        {
            name      = "TXT_KEY_INTERFACE_OPTIONS",
            showPanel = function() OnCategory(2) end,
            items     = {
                tabstrip,
                { kind = "pulldown", controlName = "BindMousePull",
                  textKey = "TXT_KEY_BIND_MOUSE" },
                { kind = "checkbox", controlName = "ZoomCheck",
                  textKey = "TXT_KEY_OPSCREEN_DYNAMIC_CAMERA_ZOOM" },
                { kind = "checkbox", controlName = "PolicyInfo",
                  textKey = "TXT_KEY_OPSCREEN_SHOW_ALL_POLICY_INFO" },
                { kind = "checkbox", controlName = "AutoUnitCycleCheck",
                  textKey = "TXT_KEY_AUTO_UNIT_CYCLE" },
                { kind = "checkbox", controlName = "ScoreListCheck",
                  textKey = "TXT_KEY_OPSCREEN_SCORE_LIST" },
                { kind = "checkbox", controlName = "MPScoreListCheck",
                  textKey = "TXT_KEY_OPSCREEN_MP_SCORE_LIST" },
                { kind = "checkbox", controlName = "EnableMapInertiaCheck",
                  textKey = "TXT_KEY_OPSCREEN_ENABLE_MAP_INERTIA" },
                { kind = "checkbox", controlName = "SkipIntroVideoCheck",
                  textKey = "TXT_KEY_OPSCREEN_SKIP_INTRO_VIDEO" },
                { kind = "checkbox", controlName = "AutoUIAssetsCheck",
                  textKey = "TXT_KEY_OPSCREEN_AUTOSIZE_UI" },
                { kind = "checkbox", controlName = "SmallUIAssetsCheck",
                  textKey = "TXT_KEY_OPSCREEN_USE_SMALL_UI" },
                { kind = "pulldown", controlName = "LanguagePull",
                  textKey = "TXT_KEY_OPSCREEN_SELECT_LANG" },
                { kind = "pulldown", controlName = "SpokenLanguagePull",
                  textKey = "TXT_KEY_OPSCREEN_SELECT_SPOKEN_LANG" },
                { kind = "slider",   controlName = "DragSpeedSlider",
                  labelControlName = "DragSpeedValue",
                  textKey = "TXT_KEY_DRAG_SPEED" },
                { kind = "slider",   controlName = "PinchSpeedSlider",
                  labelControlName = "PinchSpeedValue",
                  textKey = "TXT_KEY_PINCH_SPEED" },
            },
        },
        {
            name      = "TXT_KEY_VIDEO_OPTIONS",
            showPanel = function() OnCategory(3) end,
            items     = {
                tabstrip,
                { kind = "pulldown", controlName = "FSResolutionPull",
                  textKey = "TXT_KEY_OPSCREEN_RESOLUTION" },
                { kind = "pulldown", controlName = "WResolutionPull",
                  textKey = "TXT_KEY_OPSCREEN_RESOLUTION" },
                { kind = "pulldown", controlName = "MSAAPull",
                  textKey = "TXT_KEY_OPSCREEN_MSAA" },
                { kind = "checkbox", controlName = "FullscreenCheck",
                  textKey = "TXT_KEY_OPSCREEN_FULLSCREEN" },
                { kind = "button",   controlName = "ApplyResButton",
                  textKey = "TXT_KEY_OPSCREEN_APPLY_RESOLUTION",
                  activate = function() OnApplyRes() end },
                { kind = "checkbox", controlName = "VSyncCheck",
                  textKey = "TXT_KEY_OPSCREEN_VSYNC" },
                { kind = "checkbox", controlName = "HDStratCheck",
                  textKey = "TXT_KEY_OPSCREEN_HIGH_DETAIL_STRAT_VIEW" },
                { kind = "checkbox", controlName = "GPUDecodeCheck",
                  textKey = "TXT_KEY_OPSCREEN_GPU_TEXTURE_DECODE" },
                { kind = "pulldown", controlName = "LeaderPull",
                  textKey = "TXT_KEY_OPSCREEN_LEADER_QUALITY" },
                { kind = "pulldown", controlName = "OverlayPull",
                  textKey = "TXT_KEY_OPSCREEN_OVERLAY_DETAIL" },
                { kind = "pulldown", controlName = "ShadowPull",
                  textKey = "TXT_KEY_OPSCREEN_SHADOW_QUALITY" },
                { kind = "pulldown", controlName = "FOWPull",
                  textKey = "TXT_KEY_OPSCREEN_FOW_QUALITY" },
                { kind = "pulldown", controlName = "TerrainDetailPull",
                  textKey = "TXT_KEY_OPSCREEN_TERRAIN_DETAIL_LEVEL" },
                { kind = "pulldown", controlName = "TerrainTessPull",
                  textKey = "TXT_KEY_OPSCREEN_TERRAIN_TESS_LEVEL" },
                { kind = "pulldown", controlName = "TerrainShadowPull",
                  textKey = "TXT_KEY_OPSCREEN_TERRAIN_SHADOW_QUALITY" },
                { kind = "pulldown", controlName = "WaterPull",
                  textKey = "TXT_KEY_OPSCREEN_WATER_QUALITY" },
                { kind = "pulldown", controlName = "TextureQualityPull",
                  textKey = "TXT_KEY_OPSCREEN_TEXTURE_QUALITY" },
            },
        },
        {
            name      = "TXT_KEY_AUDIO_OPTIONS",
            showPanel = function() OnCategory(4) end,
            items     = {
                tabstrip,
                { kind = "slider", controlName = "MusicVolumeSlider",
                  labelControlName = "MusicVolumeSliderValue",
                  textKey = "TXT_KEY_OPSCREEN_MUSIC_SLIDER" },
                { kind = "slider", controlName = "EffectsVolumeSlider",
                  labelControlName = "EffectsVolumeSliderValue",
                  textKey = "TXT_KEY_OPSCREEN_SF_SLIDER" },
                { kind = "slider", controlName = "AmbienceVolumeSlider",
                  labelControlName = "AmbienceVolumeSliderValue",
                  textKey = "TXT_KEY_OPSCREEN_AMBIANCE_SLIDER" },
                { kind = "slider", controlName = "SpeechVolumeSlider",
                  labelControlName = "SpeechVolumeSliderValue",
                  textKey = "TXT_KEY_OPSCREEN_SPEECH_SLIDER" },
            },
        },
        {
            name      = "TXT_KEY_MULTIPLAYER_OPTIONS",
            showPanel = function() OnCategory(5) end,
            items     = {
                tabstrip,
                { kind = "checkbox", controlName = "TurnNotifySteamInviteCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_TURN_NOTIFY_STEAM_INVITE" },
                { kind = "checkbox", controlName = "TurnNotifyEmailCheckbox",
                  textKey = "TXT_KEY_OPSCREEN_TURN_NOTIFY_EMAIL" },
                { kind = "checkbox", controlName = "TurnNotifySmtpTLS",
                  textKey = "TXT_KEY_OPSCREEN_TURN_NOTIFY_SMTP_TLS" },
            },
        },
    },
})
