-- Mod-authored strings, pt_BR overlay. Baseline in CivVAccess_FrontEndStrings_en_US.lua. (batch 1 of 3)
CivVAccess_Strings = CivVAccess_Strings or {}

CivVAccess_Strings["TXT_KEY_CIVVACCESS_BOOT_FRONTEND"] = "Mod de acessibilidade v{1_Version} pronto."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UPDATE_AVAILABLE"] = "Seu mod está desatualizado. Execute o instalador."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MUTE_PAUSED"] = "mod pausado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MUTE_RESUMED"] = "mod retomado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LEADERBOARD_PREV_PAGE"] = "Página anterior"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LEADERBOARD_NEXT_PAGE"] = "Próxima página"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_BUTTON_DISABLED"] = "desativado"

-- ===== Front-end screen names =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MAIN_MENU"] = "Menu principal"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_OTHER_MENU"] = "Outros"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SINGLE_PLAYER"] = "Um jogador"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MULTIPLAYER_SELECT"] = "Multijogador"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_EXIT_CONFIRM"] = "Sair do jogo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LEGAL"] = "Avisos legais"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_EULA"] = "Contrato de licença do usuário final"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_ERROR"] = "Erro de mod"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_FRONT_END_POPUP"] = "Aviso"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_MENU"] = "Mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_SINGLE_PLAYER"] = "Mods um jogador"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_MULTIPLAYER"] = "Mods multijogador"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CONTENT_SWITCH"] = "Atualizando dados do jogo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_WAITING_PLAYERS"] = "Aguardando jogadores"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_JOINING_ROOM"] = "Entrando na sala"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LOBBY"] = "Lobby"

-- ===== Staging room =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_STAGING_ROOM"] = "Sala de preparação multijogador"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_PLAYERS_TAB"] = "Jogadores"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_OPTIONS_TAB"] = "Opções de jogo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SLOT_TYPE"] = "Tipo de slot"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEAM"] = "Equipe"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CIVILIZATION"] = "Civilização"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_READY"] = "pronto"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_HOST"] = "anfitrião"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_STATUS"] = "{1_Name}, {2_Status}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_CIV"] = "{1_Name}, {2_Civ}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_TEAM"] = "{1_Name}, {2_Team}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_HANDICAP"] = "{1_Name}, {2_Handicap}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_READY"] = "{1_Name} pronto"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DELTA_UNREADY"] = "{1_Name} não pronto"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_MSG"] = "{1_Name}: {2_Text}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_HOST_MIGRATION"] = "{1_Name} agora é o anfitrião"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_DISCONNECT"] = "{1_Name} desconectou"

-- ===== Launch countdown =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_COUNTDOWN_START"] = "Iniciando em 10 segundos"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_COUNTDOWN_CANCEL"] = "Contagem regressiva cancelada"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_COUNTDOWN_TICK"] = "{1_Seconds}"

-- ===== Chat panel =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_PANEL"] = "Chat"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_MESSAGES_TAB"] = "Mensagens"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_COMPOSE_TAB"] = "Escrever"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_COMPOSE"] = "Mensagem"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_EMPTY"] = "Nenhuma mensagem ainda."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_HELP_OPEN"] = "Abrir chat"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_STAGING_CHAT_HELP_KEY_CLOSE"] = "Backslash ou Escape"

-- ===== Lobby =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_SERVERS_TAB"] = "Servidores"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_DETAILS_TAB"] = "Detalhes do servidor"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_NO_SERVERS"] = "Nenhum servidor encontrado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_MEMBERS"] = "{1_Num} de {2_Max}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_PICKER_ROW"] = "{1_Server}, {2_Members}, {3_Map}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_SORT_ASC"] = "crescente"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_SORT_DESC"] = "decrescente"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOBBY_NO_SELECTION"] =
    "Nenhum servidor selecionado. Mude para a aba de servidores para escolher um."

-- ===== More front-end screen names =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_OPTIONS"] = "Opções"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CREDITS"] = "Créditos"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_GAME_SETUP"] = "Configurar jogo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MAP_TYPE"] = "Tipo de mapa"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MAP_SIZE"] = "Tamanho do mapa"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_DIFFICULTY"] = "Dificuldade"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_GAME_SPEED"] = "Ritmo do jogo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CIVILIZATION"] = "Civilização"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SET_CIV_NAMES"] = "Nomear civilização"

-- ===== Mod / scenario / DLC browser =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SCENARIOS"] = "Cenários"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_CUSTOM_MOD_GAME"] = "Jogo de mod personalizado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_TUTORIAL"] = "Tutorial"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MODS_BROWSER"] = "Procurar mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_PREMIUM_CONTENT"] = "DLC"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_WORLD_PICKER"] = "Tamanho do mundo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TUTORIAL_COMPLETED"] = "concluído"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHOICE_SELECTED"] = "selecionado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHOICE_SELECTED_NAMED"] = "selecionado, {1_Label}"

-- ===== Civ-picker entry prefixes =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_ABILITY"] = "Característica única"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_ABILITY_NAMED"] = "{1_Name}, característica única"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_UNIT"] = "Unidade exclusiva"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_BUILDING"] = "Edifício exclusivo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNIQUE_IMPROVEMENT"] = "Melhoria exclusiva"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LOADING"] = "Carregando jogo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLACES"] = "substitui {1_Name}"

-- ===== Generic widget templates =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LABEL_STATE"] = "{1_Label}, {2_State}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LABEL_VALUE"] = "{1_Label} {2_Value}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LABELED_LIST"] = "{1_Label} {2_List}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHECK_ON"] = "ligado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_CHECK_OFF"] = "desligado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_EDIT"] = "editar"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_BLANK"] = "em branco"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_EDITING"] = "editando {1_Label}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_TEXTFIELD_RESTORED"] = "{1_Label} restaurado"

-- ===== Verbosity control-type tags =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_BUTTON"] = "botão"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_CHECKBOX"] = "alternador"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_SLIDER"] = "slider"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_PULLDOWN"] = "combo box"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_KIND_GROUP"] = "submenu"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_VERBOSE_POSITION"] = "{1_Num} de {2_Num}"

-- ===== Disambiguating option-screen labels =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPSCREEN_SMTP_FROM_EMAIL"] = "Endereço de e-mail do remetente"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPSCREEN_RESOLUTION_FS"] = "Resolução em tela cheia"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPSCREEN_RESOLUTION_W"] = "Resolução em janela"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_FIELD_MAX_TURNS"] = "Quantidade de turnos"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_FIELD_TURN_TIMER"] = "Segundos do temporizador"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPTIONS_COUNTDOWN_INTRO"] = "{1_Message}. Revertendo em 20 segundos."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_OPTIONS_COUNTDOWN_EXPIRED"] = "Tempo esgotado, revertido."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MP_RECONNECTING"] = "Reconectando"
-- Advanced Setup + MP Setup (nested menus).
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_ADVANCED_SETUP"] = "Configuração avançada"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_MP_GAME_SETUP"] = "Configuração de jogo multiplayer"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_AI_SLOT"] = "IA {1_Num}, {2_Civ}, {3_Team}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HUMAN_SLOT"] = "Você, {1_Civ}, {2_Team}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_PLAYERS"] = "Jogadores"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_AI_PLAYERS"] = "Jogadores de IA"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_VICTORY_CONDITIONS"] = "Condições de vitória"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_GAME_OPTIONS"] = "Opções de jogo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_GROUP_DLC_ALLOWED"] = "DLC permitido"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_UNKNOWN_PLAYERS_STATUS"] =
    "Os jogadores de IA não podem ser personalizados enquanto o tamanho aleatório do mapa está selecionado. Escolha um tamanho específico para editar a lista de jogadores."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_FIELD_GAME_NAME"] = "Nome do jogo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MAP_SIZE_ONLY"] = "somente {1_Size}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MAP_SIZE_LIMITED"] = "tamanhos: {1_Sizes}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SEARCH_NO_MATCH"] = "sem resultado para {1_Buffer}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SEARCH_CLEARED"] = "busca limpa"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_HELP"] = "Ajuda"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_ENTRY"] = "{1_Key}, {2_Description}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_AZ09"] = "Letras"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_UP_DOWN"] = "Cima ou baixo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_HOME_END"] = "Home ou End"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ENTER_SPACE"] = "Enter ou Space"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_LEFT_RIGHT"] = "Esquerda ou direita"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_SHIFT_LEFT_RIGHT"] = "Shift mais esquerda ou direita"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_CTRL_UP_DOWN"] = "Control mais cima ou baixo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_TAB"] = "Tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_SHIFT_TAB"] = "Shift mais Tab"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_F1"] = "F1"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_BACKSLASH"] = "Barra invertida"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ESC"] = "Escape"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_ENTER"] = "Enter"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_QUESTION"] = "Ponto de interrogação"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_SEARCH"] = "Digite para buscar"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_NAV_ITEMS"] = "Navegar itens"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_JUMP_FIRST_LAST"] = "Ir ao primeiro ou último"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ACTIVATE"] = "Ativar"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ADJUST"] = "Ajustar valor ou entrar"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_ADJUST_BIG"] = "Ajustar valor em passos maiores"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_JUMP_GROUP"] = "Ir ao grupo anterior ou próximo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_NEXT_TAB"] = "Próxima aba"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_PREV_TAB"] = "Aba anterior"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_READ_HEADER"] = "Ler cabeçalho da tela"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CANCEL"] = "Cancelar"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CLOSE"] = "Fechar"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CANCEL_EDIT"] = "Cancelar edição"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_COMMIT_EDIT"] = "Confirmar edição"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_F12"] = "F12"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_KEY_CTRL_SHIFT_F12"] = "Control mais Shift mais F12"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_OPEN_SETTINGS"] = "Abrir configurações"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_CLOSE_SETTINGS"] = "Fechar configurações"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_HELP_DESC_TOGGLE_MUTE"] = "Pausar ou retomar mod"
-- Settings overlay strings. Reachable from every Context that routes
-- through InputRouter, so duplicated in the InGame copy as well.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_SETTINGS"] = "Configurações"
-- Top-level drillable labels. The Settings menu groups individual prefs
-- into five buckets so the list isn't a flat wall of toggles.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_GROUP_UI"] = "Configurações de interface"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_GROUP_CURSOR"] = "Configurações do cursor"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_GROUP_BEACON"] = "Configurações da baliza"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_GROUP_SCANNER"] = "Configurações do scanner"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_GROUP_NOTIFICATIONS"] = "Notificações"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_CUE_MODE"] = "Sinais sonoros de terreno"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_SPEECH_ONLY"] = "Somente fala"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_SPEECH_PLUS_CUES"] = "Fala e sinais sonoros"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_VERBOSE_UI"] = "Interface detalhada"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AUDIO_CUES_ONLY"] = "Somente sinais sonoros"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_MASTER_VOLUME"] = "Volume dos sinais de terreno"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_VOLUME_VALUE"] = "Volume dos sinais de terreno, {1_Num} por cento"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_BEACON_VOLUME"] = "Volume da baliza"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_BEACON_VOLUME_VALUE"] = "Volume da baliza, {1_Num} por cento"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_BEACON_RANGE"] = "Distância audível da baliza"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_BEACON_RANGE_VALUE"] =
    "Distância audível da baliza, {1_Num} hexágonos"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_SCANNER_AUTO_MOVE"] = "Scanner move cursor automaticamente"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_FOLLOWS_SELECTION"] = "Cursor segue a unidade selecionada"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_MODE"] = "Coordenadas do cursor ao mover"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_OFF"] = "Desativado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_PREPEND"] = "Falar antes do anúncio de movimento"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_CURSOR_COORD_APPEND"] = "Falar após o anúncio de movimento"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_BORDER_ALWAYS_ANNOUNCE"] =
    "Sempre anunciar território na leitura do hexágono"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_SCANNER_COORDS"] = "Scanner exibe coordenadas"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_SCANNER_COMPASS_DIRECTION"] = "Scanner usa direção de bússola"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_SCANNER_DIRECTION_BEEP"] = "Scanner reproduz bipe direcional"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_READ_SUBTITLES"] = "Ler legendas"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_REVEAL_ANNOUNCE"] = "Anunciar mudanças de visibilidade ao mover"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_AI_COMBAT_ANNOUNCE"] = "Anunciar resultado de combate da IA"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_FOREIGN_UNIT_WATCH_ANNOUNCE"] =
    "Anunciar mudanças de visibilidade no início do turno"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_FOREIGN_CLEAR_ANNOUNCE"] =
    "Anunciar acampamentos e ruínas capturados por outros na área visível"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SETTINGS_TURN_START_SOUND"] = "Tocar som de início de turno em um jogador"
-- LoadMenu (PickerReader over the save picker). Saves-tab label, details-tab
-- label, empty-list placeholder, delete confirmation (format key takes the
-- save's display name), post-delete acknowledgement. The two PICKER_READER_
-- keys are duplicated from InGame/CivVAccess_InGameStrings_en_US.lua so the
-- Shared PickerReader resolves them from the front-end sandbox too (each
-- Context has its own CivVAccess_Strings table).
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_SORT_BY"] = "Ordenar por"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_SAVES_TAB"] = "Saves"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_DETAILS_TAB"] = "Detalhes do save"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_NO_SAVES"] = "Nenhum save nesta lista."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_DELETE_CONFIRM"] = "Excluir {1_Name}?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_DELETED"] = "Save excluído."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_LOAD_MOD_VERSION"] = "{1_Name} versão {2_Version}"
-- LoadReplayMenu (PickerReader over the replay picker). Engine's
-- TXT_KEY_NO_REPLAYS serves as the empty-list placeholder; delete confirm
-- reuses TXT_KEY_CIVVACCESS_LOAD_DELETE_CONFIRM. Replay-specific tab names
-- and post-delete acknowledgement below.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_LOAD_REPLAY"] = "Carregar replay"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_LIST_TAB"] = "Replays"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_DETAILS_TAB"] = "Detalhes do replay"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_DELETED"] = "Replay excluído."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_NO_SELECTION"] =
    "Nenhum replay selecionado. Vá para a aba de replays para escolher um."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_REPLAY_VIEWER"] = "Replay"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_PANEL_LABEL"] = "painel"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_REPLAY_TURN_GROUP"] = "Turno {1_Turn}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PICKER_READER_EMPTY"] = "Nenhum conteúdo para esta entrada."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_PICKER_READER_NO_SELECTION"] =
    "Nenhum save selecionado. Vá para a aba de saves para escolher um."
-- ===== InstalledPanel =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_SCREEN_INSTALLED_PANEL"] = "Mods instalados"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_LIST_TAB"] = "Mods"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DETAILS_TAB"] = "Detalhes"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_NO_MODS"] = "Nenhum mod instalado."
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_SORT_BY"] = "Ordenar por"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_APPLY_OPTIONS"] = "Aplicar"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_STATE"] = "Estado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_STATE_ENABLED"] = "ativado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_STATE_DISABLED"] = "desativado"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_ENABLE_BLOCKED"] = "Não é possível ativar: {1_Reason}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_PICKER_ROW"] = "{1_Name}, {2_State}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_PICKER_NEEDS_UPDATE"] = "{1_Name}, {2_State}, precisa de atualização"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_VERSION_RANGE"] = "{1_Name} versão {2_MinVersion} a {3_MaxVersion}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_VERSION_SUFFIX"] = "{1_Name} versão {2_Version}"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DISABLE_CONFIRM"] = "Desativar {1_Name}?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DELETE_CONFIRM"] = "Excluir {1_Name}?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_UNSUBSCRIBE_CONFIRM"] = "Cancelar assinatura de {1_Name}?"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DELETE_WITH_USER_DATA"] = "Excluir com dados do usuário"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_MODS_DELETED"] = "Mod removido."
-- ===== Icon spoken-text substitutions =====
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GOLD"] = "ouro"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_FOOD"] = "comida"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_PRODUCTION"] = "produção"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_CULTURE"] = "cultura"
-- Dedup alias copied from the game's localized text, not translated (see en_US). "" means the primary spoken form already collapses.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_CULTURE_ALT"] = "cultural"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_SCIENCE"] = "ciência"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RESEARCH"] = "ciência"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_FAITH"] = "fé"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_TOURISM"] = "turismo"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE"] = "grandes pessoas"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT"] = "grande pessoa"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT_ARTIST"] = "pontos grande artista"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT_ENGINEER"] = "pontos grande engenheiro"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT_MERCHANT"] = "pontos grande mercador"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_PEOPLE_ALT_SCIENTIST"] = "pontos grande cientista"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_GREAT_WORK"] = "grande obra"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_STRENGTH"] = "força de combate"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_STRENGTH_ALT"] = "força"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RANGE_STRENGTH"] = "força de combate a distância"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_RANGE_STRENGTH_ALT"] = "força de ataque"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_MOVEMENT"] = "movimentos"
-- Dedup alias copied from the game's localized text, not translated (see en_US). "" means the primary spoken form already collapses.
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_MOVEMENT_ALT"] = "movimento"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_HAPPY"] = "felicidade"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_HAPPY_ALT"] = "feliz"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_UNHAPPY"] = "infelicidade"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_UNHAPPY_ALT"] = "infeliz"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_ARROW_LEFT"] = "esquerda"
CivVAccess_Strings["TXT_KEY_CIVVACCESS_ICON_ARROW_RIGHT"] = "direita"
